In [75]:
import pandas as pd
import numpy as np

In [76]:
Boltrev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/BoltReviews.csv")

In [77]:
# EDA on the data
def display(x):
    """This function returns a 
    summary of the dataset"""
    
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(Boltrev)

Displays the rows and columns in the dataset
============================================
Rows: 260 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                                      Job Title  Job Ratings          time  \
0    Business development representative (bdr)          5.0   Nov 2, 2024
1                           Solutions engineer          2.0  Jun 26, 2025
2                     Senior software engineer          4.0   Feb 4, 2025
3                           Anonymous employee          4.0  Jan 16, 2025
4                   Revenue operations analyst          3.0  Nov 10, 2024
5                           Anonymous employee          2.0  Sep 17, 2024
6                                People leader          5.0  Jul 24, 2024
7                             Senior recruiter          5.0  Jul 23, 2024
8                           Anonymous employee          5.0  Jul 23, 2024
9                              Account manager          4.0   Nov 3, 2024
10                          Revenue operations          3.0  Aug 21, 2024
11                           Software engineer          1.0  Sep 18, 2024
12                                Risk analyst          2.0   Oct 1, 2024
13                           Software engineer          1.0  Nov 26, 2024
14                          Anonymous employee          2.0  Jan 18, 2024
15                          Anonymous employee          2.0  Jan 18, 2024
16                                 Ops manager          2.0   Oct 3, 2024
17                        Business development          5.0  Jul 23, 2024
18                                Partnerships          4.0  Jul 19, 2024
19                      Communications manager          5.0  Aug 19, 2024
20                          Revenue operations          3.0  Aug 21, 2024
21                           Software engineer          1.0  Sep 18, 2024
22                                Risk analyst          2.0   Oct 1, 2024
23                           Software engineer          1.0  Nov 26, 2024
24                          Anonymous employee          2.0  Jan 18, 2024
25                          Anonymous employee          2.0  Jan 18, 2024
26                                 Ops manager          2.0   Oct 3, 2024
27                        Business development          5.0  Jul 23, 2024
28                                Partnerships          4.0  Jul 19, 2024
29                      Communications manager          5.0  Aug 19, 2024
30                            Locked job title          5.0  Apr 25, 2025
31                            Locked job title          5.0  Apr 25, 2025
32                            Locked job title          5.0  Apr 25, 2025
33                            Locked job title          5.0  Apr 25, 2025
34                            Locked job title          5.0  Apr 25, 2025
35                            Locked job title          5.0  Apr 25, 2025
36                            Locked job title          5.0  Apr 25, 2025
37                            Locked job title          5.0  Apr 25, 2025
38                            Locked job title          5.0  Apr 25, 2025
39                            Locked job title          5.0  Apr 25, 2025
40                               People leader          5.0  Jul 23, 2024
41                          Anonymous employee          2.0  Feb 22, 2024
42              Director of corporate strategy          4.0  Jun 18, 2024
43                          Anonymous employee          1.0  Jan 18, 2024
44                          Senior gtm manager          2.0  Jun 21, 2024
45                Business development manager          1.0   Jun 6, 2024
46                          Anonymous employee          2.0  Jan 18, 2024
47                                        Tech          1.0  Jun 24, 2024
48                  Technical support engineer          3.0  Jan 18, 2024
49                      Individual contributor          1.0  Jan 23, 2023
50                               People leader          5.0  Jul 23, 2024
51                          Anonymous employee          2.0  Feb 22, 2024
52              Director of corporate strategy          4.0  Jun 18, 2024
53                          Anonymous employee          1.0  Jan 18, 2024
54                          Senior gtm manager          2.0  Jun 21, 2024
55                Business development manager          1.0   Jun 6, 2024
56                          Anonymous employee          2.0  Jan 18, 2024
57                                        Tech          1.0  Jun 24, 2024
58                  Technical support engineer          3.0  Jan 18, 2024
59                      Individual contributor          1.0  Jan 23, 2023
60                               People leader          5.0  Jul 23, 2024
61                          Anonymous employee          2.0  Feb 22, 2024
62              Director of corporate strategy          4.0  Jun 18, 2024
63                          Anonymous employee          1.0  Jan 18, 2024
64                          Senior gtm manager          2.0  Jun 21, 2024
65                Business development manager          1.0   Jun 6, 2024
66                          Anonymous employee          2.0  Jan 18, 2024
67                                        Tech          1.0  Jun 24, 2024
68                  Technical support engineer          3.0  Jan 18, 2024
69                      Individual contributor          1.0  Jan 23, 2023
70                               People leader          5.0  Jul 23, 2024
71                          Anonymous employee          2.0  Feb 22, 2024
72              Director of corporate strategy          4.0  Jun 18, 2024
73                          Anonymous employee          1.0  Jan 18, 2024
74                          Senior gtm manager          2.0  Jun 21, 2024
75                Business development manager          1.0   Jun 6, 2024
76                          Anonymous employee          2.0  Jan 18, 2024
77                                        Tech          1.0  Jun 24, 2024
78                  Technical support engineer          3.0  Jan 18, 2024
79                      Individual contributor          1.0  Jan 23, 2023
80                    Senior software engineer          4.0  Feb 28, 2024
81                              Data scientist          5.0  Mar 11, 2024
82                                 It engineer          3.0   Mar 5, 2024
83                         Software engineer i          4.0  Feb 22, 2024
84                           Software engineer          3.0   Mar 4, 2024
85                          Anonymous employee          4.0  Jan 18, 2024
86                           Software engineer          3.0  Jan 31, 2024
87                                       Sales          3.0  Jan 31, 2024
88                          Anonymous employee          5.0  Dec 11, 2023
89                                 Engineering          4.0   Nov 8, 2023
90                           Account executive          2.0  Oct 16, 2023
91                                         Gtm          2.0  Oct 24, 2023
92                           Account executive          2.0  Jul 17, 2023
93                           Software engineer          2.0   Nov 7, 2023
94                  Product operations manager          3.0   Nov 9, 2023
95                                Sre engineer          4.0  Oct 22, 2023
96                             Department lead          5.0  May 17, 2023
97                         Senior data analyst          5.0  Aug 23, 2023
98                   Machine learning engineer          1.0   Aug 1, 2023
99                           Software engineer          1.0  Nov 15, 2023
100                          Software engineer          3.0  Sep 11, 2023
101                         Operations manager          5.0   Jul 6, 2023
102                          Software engineer          1.0   Feb 3, 2023
103                         Anonymous employee          3.0  Nov 23, 2022
104                                  Associate          4.0  Jun 23, 2023
105                           Product designer          5.0  Nov 23, 2019
106                            Sales associate          5.0  Apr 10, 2023
107                          Account executive          5.0  Apr 27, 2023
108                   Senior software engineer          3.0   May 9, 2023
109              Director, employee experience          5.0  May 24, 2021
110                                    Manager          3.0  Apr 13, 2023
111                          Software engineer          3.0  Feb 28, 2023
112                          Software engineer          4.0  Feb 28, 2023
113                          Software engineer          5.0   Apr 9, 2020
114                          Software engineer          1.0  May 16, 2023
115                                     Talent          5.0   Aug 7, 2019
116                         Anonymous employee          2.0  Dec 16, 2019
117                            User researcher          3.0   Mar 7, 2023
118                          Account executive          3.0   Mar 6, 2023
119                          Software engineer          3.0   Dec 5, 2022
120                 Special projects associate          5.0  Aug 18, 2020
121                          Software engineer          3.0   Feb 1, 2023
122                          Software engineer          2.0  Feb 20, 2023
123                                  Recruiter          3.0  May 16, 2019
124                        Customer experience          5.0  Dec 26, 2019
125                    Senior android engineer          4.0  Nov 30, 2022
126                          Software engineer          3.0  Dec 21, 2022
127                    Director of engineering          2.0   Dec 2, 2022
128                                      Sales          5.0  Feb 24, 2020
129                           Customer success          5.0   Aug 2, 2019
130                        Technical recruiter          5.0  Aug 27, 2021
131                         Anonymous employee          5.0  Oct 24, 2018
132                         Anonymous employee          1.0  May 28, 2022
133                                 Operations          5.0  May 20, 2019
134                          Software engineer          5.0  Jan 18, 2018
135                          Account executive          3.0   Jun 2, 2022
136                          Software engineer          5.0   Apr 3, 2020
137                          Software engineer          5.0  Jun 16, 2020
138                                 Operations          5.0  Feb 23, 2021
139                         Anonymous employee          5.0   Oct 9, 2020
140                        Customer experience          5.0  Jul 13, 2020
141                         Anonymous employee          2.0  Mar 13, 2020
142                          Software engineer          5.0  Mar 18, 2021
143                                 Operations          5.0   Oct 2, 2020
144                          Software engineer          5.0  Jun 29, 2020
145                         Anonymous employee          2.0   Feb 5, 2020
146                         Anonymous employee          5.0  Jan 16, 2018
147                         Anonymous employee          2.0  Feb 21, 2020
148                                      Sales          3.0   Dec 5, 2019
149                                 Operations          5.0  Dec 27, 2019
150                          Product marketing          5.0  Sep 17, 2021
151                  Product marketing manager          2.0  Jun 13, 2022
152                                 Operations          5.0   Oct 2, 2020
153                          Software engineer          5.0  Sep 15, 2021
154                         Anonymous employee          5.0   Jul 5, 2018
155                                  Recruiter          5.0  Aug 27, 2021
156                            Support analyst          5.0  Feb 27, 2022
157                                 Operations          4.0   Oct 7, 2020
158                         Anonymous employee          2.0  May 31, 2022
159                                  Recruiter          5.0  Aug 30, 2021
160                 Vice president engineering          5.0   Sep 9, 2021
161                         Anonymous employee          2.0   Feb 3, 2020
162                               Risk analyst          5.0  Mar 24, 2020
163                                  Marketing          5.0  Sep 10, 2021
164                          Software engineer          3.0  Sep 17, 2020
165                         Anonymous employee          5.0  Jan 19, 2018
166                                      Sales          5.0   Apr 8, 2020
167                                      Sales          5.0  May 22, 2020
168                          People operations          4.0  Feb 10, 2020
169                          Software engineer          5.0  Jan 18, 2018
170                         Anonymous employee          5.0  Jan 17, 2018
171                                   Engineer          5.0  Jan 12, 2018
172                          Software engineer          5.0   Apr 4, 2020
173                                  Marketing          5.0   Apr 7, 2020
174                            Sales associate          5.0   Jun 4, 2020
175                          Software engineer          5.0   Oct 7, 2020
176                       Sales representative          1.0  Feb 21, 2020
177                   Salesforce administrator          5.0  Jan 23, 2020
178               Enterprise account executive          5.0  Jun 15, 2018
179                         Anonymous employee          5.0   Jun 8, 2018
180                                  Recruiter          5.0  Aug 19, 2021
181                               Risk analyst          5.0   Oct 9, 2018
182                        Customer experience          5.0  Aug 22, 2019
183                                      Sales          5.0   Mar 4, 2019
184                                  Recruiter          5.0   Nov 8, 2019
185                               Risk analyst          5.0  Feb 22, 2019
186                          Software engineer          4.0   Apr 7, 2020
187                        Technical recruiter          2.0  Jul 20, 2022
188                       Business development          5.0  Feb 12, 2019
189                           Senior recruiter          5.0  Aug 24, 2021
190                          Software engineer          4.0   Oct 7, 2020
191                                  Marketing          5.0   Oct 9, 2020
192                                      Sales          5.0  Jan 16, 2018
193                                     Talent          5.0  Jan 24, 2019
194                         Anonymous employee          5.0   Oct 1, 2018
195                          Software engineer          5.0  Apr 21, 2020
196                            Product manager          5.0  Sep 13, 2021
197                                      Sales          5.0   Aug 8, 2018
198                                   Director          5.0  Sep 10, 2021
199         Senior director revenue operations          5.0  Dec 29, 2021
200                          Strategic finance          5.0  May 13, 2020
201                         Anonymous employee          5.0  Sep 28, 2020
202                     Recruiting coordinator          5.0   Sep 1, 2021
203                           Customer success          5.0   Oct 9, 2020
204                       Sales representative          5.0  Oct 24, 2018
205                         Anonymous employee          5.0  Feb 12, 2019
206                         Anonymous employee          5.0  Aug 14, 2018
207     Sales development representative (sdr)          4.0  May 18, 2021
208                         Anonymous employee          1.0  Feb 27, 2022
209                         Anonymous employee          5.0   Jun 6, 2018
210                      It support specialist          5.0  Aug 31, 2021
211                          Account executive          4.0  Sep 23, 2019
212                          Software engineer          5.0  May 11, 2020
213                         Anonymous employee          4.0  Jun 30, 2020
214                          Software engineer          5.0  Jul 30, 2018
215                            Support analyst          5.0  Jul 22, 2019
216                         Anonymous employee          5.0  Jan 20, 2022
217                       Business development          5.0  Sep 16, 2019
218                                 Operations          2.0   Dec 4, 2019
219                          Software engineer          5.0  Sep 22, 2020
220                                      Sales          5.0  Dec 17, 2019
221                          Software engineer          3.0   Nov 2, 2022
222                         Anonymous employee          5.0   Oct 7, 2020
223                             Director sales          2.0  Jun 15, 2022
224                             Sales engineer          2.0  Jun 18, 2022
225               Director of enterprise sales          5.0  Oct 18, 2021
226                         Anonymous employee          5.0  Dec 28, 2021
227                         Anonymous employee          5.0  Sep 28, 2021
228                         Anonymous employee          5.0  Jan 12, 2018
229                            Product manager          4.0  May 31, 2022
230                         Anonymous employee          3.0   Jun 7, 2022
231                         Anonymous employee          5.0  Aug 19, 2015
232                               Risk analyst          5.0   Dec 7, 2018
233                         Anonymous employee          5.0  Aug 23, 2021
234                               Fp&a analyst          5.0  May 12, 2021
235                          Software engineer          3.0  Nov 17, 2022
236                         Anonymous employee          1.0  Mar 22, 2021
237                          Security engineer          4.0  May 28, 2022
238                          Software engineer          5.0   Oct 9, 2020
239                                    Manager          1.0  Jun 30, 2022
240                                   Designer          5.0   Jan 8, 2021
241                          Software engineer          5.0  Jun 24, 2021
242                         Anonymous employee          5.0   Jan 8, 2019
243                          Account executive          5.0  Jan 12, 2022
244                         Anonymous employee          5.0   Nov 5, 2018
245                          Software engineer          4.0   Jun 5, 2022
246                         Anonymous employee          3.0  Jul 16, 2022
247                          Software engineer          2.0   Jul 5, 2022
248                         Anonymous employee          1.0  Aug 16, 2022
249                   Senior account executive          1.0   Sep 1, 2022
250                         Anonymous employee          1.0  May 25, 2022
251                          Software engineer          5.0  Jun 30, 2025
252                         Anonymous employee          2.0  May 29, 2025
253                                      Sde-2          4.0  May 27, 2025
254                         Anonymous employee          2.0   Feb 3, 2024
255                       Integration engineer          2.0  Jul 17, 2024
256                          Software engineer          4.0   Jul 3, 2024
257            Social media support specialist          4.0  Jun 29, 2024
258                                 Operations          4.0  May 29, 2024
259                         Anonymous employee          4.0  Jan 18, 2024

                               JobStatus  \
0    Current employee, more than 3 years
1      Former employee, more than 1 year
2      Former employee, more than 1 year
3                       Current employee
4      Former employee, less than 1 year
5                        Former employee

In [78]:
# display the whole column content
pd.set_option("display.max_colwidth", None)

In [79]:
# The first 3 elements
print("Top 5 elements")
print("=============================")
print()
Boltrev.head()

Top 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Business development representative (bdr),5.0,"Nov 2, 2024","Current employee, more than 3 years","great team, great pay, great offices","Sales team goot toxic, bad management"
1,Solutions engineer,2.0,"Jun 26, 2025","Former employee, more than 1 year",New CEO might improve things,Lack of direction and too many managers who do nothing
2,Senior software engineer,4.0,"Feb 4, 2025","Former employee, more than 1 year",Decent place and great coworkers.,Leadership needs to do more.
3,Anonymous employee,4.0,"Jan 16, 2025",Current employee,Good work place and people,"Hard work, would do again"
4,Revenue operations analyst,3.0,"Nov 10, 2024","Former employee, less than 1 year",An incredible culture filled with amazing individuals who foster collaboration and creativity.,"The organization has experienced frequent changes in upper management, leading to a lack of stability and direction. This uncertainty is compounded by regular layoffs that create an atmosphere of tension and insecurity among employees."

In [80]:
# The last 3 elements
print("last 5 elements")
print("=============================")
print()
Boltrev.tail()

last 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
255,Integration engineer,2.0,"Jul 17, 2024","Former employee, less than 1 year","compensation, unlimited vacation, competitive salary",culture was not the best place to work
256,Software engineer,4.0,"Jul 3, 2024",Former employee,Good pay in Canada and good benifits,They have lost vision no one wants the service
257,Social media support specialist,4.0,"Jun 29, 2024",Current employee,Inclusion and innovation is largely encouraged.,BPO has taken over the support space.
258,Operations,4.0,"May 29, 2024",Current employee,Good opportunity to progress and develop,Periods of business as usual management
259,Anonymous employee,4.0,"Jan 18, 2024",Current employee,- Opportunity to make an impact right away and to work on a very cool product\n- Great work/life balance and a ton of autonomy \n- Managers and colleagues are among the best of the best,- Exec team has seen a lot of turnover and there is a need for more transparency from Execs but this been improving recently\n- It is a ride! Be prepared for a sometimes ambiguous environment.

In [81]:
# The random 3 elements
print("Random 5 elements")
print("=============================")
print()
Boltrev.sample(5)

Random 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
47,Tech,1.0,"Jun 24, 2024","Former employee, more than 3 years",Direct team members at the IC level are great,"Like other people have said, everything else - especially leadership."
7,Senior recruiter,5.0,"Jul 23, 2024","Current employee, less than 1 year","Interviewing with Bolt consisted of 4-5 conversations with leaders and stakeholders I'd be working alongside on a daily basis/supporting. Interviewers were engaging and it was a very positive experience overall. \n\nOnce hired, onboarding took about 1-2 weeks and was very organized. Had more than enough support in terms of both materials and colleagues to get up to speed on Bolt's product, culture, etc. \nPay and benefits are strong - company is remote-first, Pay is competitive (at/above industry average), and benefits are in alignment with other tech companies in the space. \n\nDespite previous re-structures and changes in the organization the last few years, leaders are/have been transparent about the changes, the reasons behind them, and the vision/plan for Bolt moving forward. \n\nProduct is interesting and a disrupter in the e-commerce space. You'll have the opportunity to work on/support the development of a product that supports well known brands everyone knows which is cool. \n\nThere have been changes in leadership recently, and as a new hire, it seems from both a company vision/GTM strategy, as well as an employee morale standpoint, they are for the better. Individual contributors and leaders alike are aligned on the vision for the company and the product moving forward and are making a concerted effort to create a culture of more communication, transparency, and openness within all aspects of the organization. \n\nDefinitely a startup culture where they prioritize hiring individuals who are able to/enjoy working autonomously, are strong culture builders, optimistic, and take ownership and accountability on the work they contribute. While there are more than enough systems/processes put in place, you also will have the opportunity to create processes from scratch or iterate on them. This may not be for everyone, but if you enjoy working in a high growth/scrappy startup environment, you will likely enjoy the type of work you get to do here.","Because of the multiple changes that have been made in the last 6-12 months, there may be some people that may not be aligned with the new vision/strategy of the company or new leadership moving forward. That being said, leadership has made a concerted effort to address this misalignment head on and have candid conversations about the future rather than not addressing people's apprehensions. From everything I've seen, department leaders and the executive team have taken a very humanistic approach to addressing people's concerns, and you can/will be heard and seen as a valued member of the Bolt organization."
203,Customer success,5.0,"Oct 9, 2020","Current employee, more than 3 years","Excellent team, great culture, opportunity to be part of something really remarkable. Incredible flexibility/sensitivity during the pandemic. Fair comp.",Start-up life means start-up benefits and they still leave a bit to be desired.
193,Talent,5.0,"Jan 24, 2019","Current employee, less than 1 year","From the product we support, the people that work here, and the kind of atmosphere thats created, Bolt not is not only an amazing place to work but an amazing place for personal development.","I 100% honesty, I can't say I have anything wrong with being at Bolt. I LOVE IT!"
94,Product operations manager,3.0,"Nov 9, 2023",Former employee,"Great team, lots of smart people","Leadership needs improvement, lots of cost-cutting and changes"

In [82]:
# loops over the whole column 1
for index,col in enumerate (Boltrev["Job Title"]):
    print(index, col)

0 Business development representative (bdr)
1 Solutions engineer
2 Senior software engineer
3 Anonymous employee
4 Revenue operations analyst
5 Anonymous employee
6 People leader
7 Senior recruiter
8 Anonymous employee
9 Account manager
10 Revenue operations
11 Software engineer
12 Risk analyst
13 Software engineer
14 Anonymous employee
15 Anonymous employee
16 Ops manager
17 Business development
18 Partnerships
19 Communications manager
20 Revenue operations
21 Software engineer
22 Risk analyst
23 Software engineer
24 Anonymous employee
25 Anonymous employee
26 Ops manager
27 Business development
28 Partnerships
29 Communications manager
30 Locked job title
31 Locked job title
32 Locked job title
33 Locked job title
34 Locked job title
35 Locked job title
36 Locked job title
37 Locked job title
38 Locked job title
39 Locked job title
40 People leader
41 Anonymous employee
42 Director of corporate strategy
43 Anonymous employee
44 Senior gtm manager
45 Business development manager
46 Anonymous employee
47 Tech
48 Technical support engineer
49 Individual contributor
50 People leader
51 Anonymous employee
52 Director of corporate strategy
53 Anonymous employee
54 Senior gtm manager
55 Business development manager
56 Anonymous employee
57 Tech
58 Technical support engineer
59 Individual contributor
60 People leader
61 Anonymous employee
62 Director of corporate strategy
63 Anonymous employee
64 Senior gtm manager
65 Business development manager
66 Anonymous employee
67 Tech
68 Technical support engineer
69 Individual contributor
70 People leader
71 Anonymous employee
72 Director of corporate strategy
73 Anonymous employee
74 Senior gtm manager
75 Business development manager
76 Anonymous employee
77 Tech
78 Technical support engineer
79 Individual contributor
80 Senior software engineer
81 Data scientist
82 It engineer
83 Software engineer i
84 Software engineer
85 Anonymous employee
86 Software engineer
87 Sales
88 Anonymous employee
89 Engineering
90 Account executive
91 Gtm
92 Account executive
93 Software engineer
94 Product operations manager
95 Sre engineer
96 Department lead
97 Senior data analyst
98 Machine learning engineer
99 Software engineer
100 Software engineer
101 Operations manager
102 Software engineer
103 Anonymous employee
104 Associate
105 Product designer
106 Sales associate
107 Account executive
108 Senior software engineer
109 Director, employee experience
110 Manager
111 Software engineer
112 Software engineer
113 Software engineer
114 Software engineer
115 Talent
116 Anonymous employee
117 User researcher
118 Account executive
119 Software engineer
120 Special projects associate
121 Software engineer
122 Software engineer
123 Recruiter
124 Customer experience
125 Senior android engineer
126 Software engineer
127 Director of engineering
128 Sales
129 Customer success
130 Technical recruiter
131 Anonymous employee
132 Anonymous employee
133 Operations
134 Software engineer
135 Account executive
136 Software engineer
137 Software engineer
138 Operations
139 Anonymous employee
140 Customer experience
141 Anonymous employee
142 Software engineer
143 Operations
144 Software engineer
145 Anonymous employee
146 Anonymous employee
147 Anonymous employee
148 Sales
149 Operations
150 Product marketing
151 Product marketing manager
152 Operations
153 Software engineer
154 Anonymous employee
155 Recruiter
156 Support analyst
157 Operations
158 Anonymous employee
159 Recruiter
160 Vice president engineering
161 Anonymous employee
162 Risk analyst
163 Marketing
164 Software engineer
165 Anonymous employee
166 Sales
167 Sales
168 People operations
169 Software engineer
170 Anonymous employee
171 Engineer
172 Software engineer
173 Marketing
174 Sales associate
175 Software engineer
176 Sales representative
177 Salesforce administrator
178 Enterprise account executive
179 Anonymous employee
180 Recruiter
181 Risk analyst
182 Customer experience
183 Sales
184 Recruiter
185 Risk analyst
186 Software engineer
187 Technical recruiter
188 Business development
189 Senior recruiter
190 Software engineer
191 Marketing
192 Sales
193 Talent
194 Anonymous employee
195 Software engineer
196 Product manager
197 Sales
198 Director
199 Senior director revenue operations
200 Strategic finance
201 Anonymous employee
202 Recruiting coordinator
203 Customer success
204 Sales representative
205 Anonymous employee
206 Anonymous employee
207 Sales development representative (sdr)
208 Anonymous employee
209 Anonymous employee
210 It support specialist
211 Account executive
212 Software engineer
213 Anonymous employee
214 Software engineer
215 Support analyst
216 Anonymous employee
217 Business development
218 Operations
219 Software engineer
220 Sales
221 Software engineer
222 Anonymous employee
223 Director sales
224 Sales engineer
225 Director of enterprise sales
226 Anonymous employee
227 Anonymous employee
228 Anonymous employee
229 Product manager
230 Anonymous employee
231 Anonymous employee
232 Risk analyst
233 Anonymous employee
234 Fp&a analyst
235 Software engineer
236 Anonymous employee
237 Security engineer
238 Software engineer
239 Manager
240 Designer
241 Software engineer
242 Anonymous employee
243 Account executive
244 Anonymous employee
245 Software engineer
246 Anonymous employee
247 Software engineer
248 Anonymous employee
249 Senior account executive
250 Anonymous employee
251 Software engineer
252 Anonymous employee
253 Sde-2
254 Anonymous employee
255 Integration engineer
256 Software engineer
257 Social media support specialist
258 Operations
259 Anonymous employee

In [83]:
Boltrev.iloc[30:39]

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
30,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
31,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
32,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
33,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
34,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
35,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
36,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
37,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
38,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN

In [84]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns 
    total null values on the dataset"""
    print(df.isna().sum())
null_values(Boltrev)

Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           10
dtype: int64

In [85]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the 
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(Boltrev)
# CisRev.dropna(inplace=True)

In [86]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(Boltrev)

In [87]:
# Rename the headers
Boltrev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [88]:
pd.reset_option("display.Max_rows", None)

In [89]:
Boltrev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Business development representative (bdr),5.0,2024-11-02,"Current employee, more than 3 years","great team, great pay, great offices","Sales team goot toxic, bad management"
1,Solutions engineer,2.0,2025-06-26,"Former employee, more than 1 year",New CEO might improve things,Lack of direction and too many managers who do nothing
2,Senior software engineer,4.0,2025-02-04,"Former employee, more than 1 year",Decent place and great coworkers.,Leadership needs to do more.
3,Anonymous employee,4.0,2025-01-16,Current employee,Good work place and people,"Hard work, would do again"
4,Revenue operations analyst,3.0,2024-11-10,"Former employee, less than 1 year",An incredible culture filled with amazing individuals who foster collaboration and creativity.,"The organization has experienced frequent changes in upper management, leading to a lack of stability and direction. This uncertainty is compounded by regular layoffs that create an atmosphere of tension and insecurity among employees."
...,...,...,...,...,...,...
255,Integration engineer,2.0,2024-07-17,"Former employee, less than 1 year","compensation, unlimited vacation, competitive salary",culture was not the best place to work
256,Software engineer,4.0,2024-07-03,Former employee,Good pay in Canada and good benifits,They have lost vision no one wants the service
257,Social media support specialist,4.0,2024-06-29,Current employee,Inclusion and innovation is largely encouraged.,BPO has taken over the support space.
258,Operations,4.0,2024-05-29,Current employee,Good opportunity to progress and develop,Periods of business as usual management
259,Anonymous employee,4.0,2024-01-18,Current employee,- Opportunity to make an impact right away and to work on a very cool product\n- Great work/life balance and a ton of autonomy \n- Managers and colleagues are among the best of the best,- Exec team has seen a lot of turnover and there is a need for more transparency from Execs but this been improving recently\n- It is a ride! Be prepared for a sometimes ambiguous environment.

In [90]:
Boltrev.info()

<class 'pandas.core.frame.DataFrame'>
Index: 250 entries, 0 to 259
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Job Title   250 non-null    object
 1   Job Rating  250 non-null    float64
 2   Time        250 non-null    datetime64[ns]
 3   Job Status  250 non-null    object
 4   Pros        250 non-null    object
 5   Cons        250 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 13.7+ KB

In [91]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(Boltrev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Business development representative (bdr),5.0,2024-11-02,"Current employee, more than 3 years","great team, great pay, great offices","Sales team goot toxic, bad management"
1,Solutions engineer,2.0,2025-06-26,"Former employee, more than 1 year",New CEO might improve things,Lack of direction and too many managers who do nothing
2,Senior software engineer,4.0,2025-02-04,"Former employee, more than 1 year",Decent place and great coworkers.,Leadership needs to do more.
3,Anonymous employee,4.0,2025-01-16,Current employee,Good work place and people,"Hard work, would do again"
4,Revenue operations analyst,3.0,2024-11-10,"Former employee, less than 1 year",An incredible culture filled with amazing individuals who foster collaboration and creativity.,"The organization has experienced frequent changes in upper management, leading to a lack of stability and direction. This uncertainty is compounded by regular layoffs that create an atmosphere of tension and insecurity among employees."
...,...,...,...,...,...,...
255,Integration engineer,2.0,2024-07-17,"Former employee, less than 1 year","compensation, unlimited vacation, competitive salary",culture was not the best place to work
256,Software engineer,4.0,2024-07-03,Former employee,Good pay in Canada and good benifits,They have lost vision no one wants the service
257,Social media support specialist,4.0,2024-06-29,Current employee,Inclusion and innovation is largely encouraged.,BPO has taken over the support space.
258,Operations,4.0,2024-05-29,Current employee,Good opportunity to progress and develop,Periods of business as usual management
259,Anonymous employee,4.0,2024-01-18,Current employee,Opportunity to make an impact right away and to work on a very cool product\n Great work/life balance and a ton of autonomy \n Managers and colleagues are among the best of the best,Exec team has seen a lot of turnover and there is a need for more transparency from Execs but this been improving recently\n It is a ride! Be prepared for a sometimes ambiguous environment.

In [92]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace("\n", "", regex=True))
    return df
remove_char(Boltrev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Business development representative (bdr),5.0,2024-11-02,"Current employee, more than 3 years","great team, great pay, great offices","Sales team goot toxic, bad management"
1,Solutions engineer,2.0,2025-06-26,"Former employee, more than 1 year",New CEO might improve things,Lack of direction and too many managers who do nothing
2,Senior software engineer,4.0,2025-02-04,"Former employee, more than 1 year",Decent place and great coworkers.,Leadership needs to do more.
3,Anonymous employee,4.0,2025-01-16,Current employee,Good work place and people,"Hard work, would do again"
4,Revenue operations analyst,3.0,2024-11-10,"Former employee, less than 1 year",An incredible culture filled with amazing individuals who foster collaboration and creativity.,"The organization has experienced frequent changes in upper management, leading to a lack of stability and direction. This uncertainty is compounded by regular layoffs that create an atmosphere of tension and insecurity among employees."
...,...,...,...,...,...,...
255,Integration engineer,2.0,2024-07-17,"Former employee, less than 1 year","compensation, unlimited vacation, competitive salary",culture was not the best place to work
256,Software engineer,4.0,2024-07-03,Former employee,Good pay in Canada and good benifits,They have lost vision no one wants the service
257,Social media support specialist,4.0,2024-06-29,Current employee,Inclusion and innovation is largely encouraged.,BPO has taken over the support space.
258,Operations,4.0,2024-05-29,Current employee,Good opportunity to progress and develop,Periods of business as usual management
259,Anonymous employee,4.0,2024-01-18,Current employee,Opportunity to make an impact right away and to work on a very cool product Great work/life balance and a ton of autonomy Managers and colleagues are among the best of the best,Exec team has seen a lot of turnover and there is a need for more transparency from Execs but this been improving recently It is a ride! Be prepared for a sometimes ambiguous environment.

In [93]:
hiphen = Boltrev[Boltrev["Cons"].str.startswith("-")]
hiphen

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [94]:
pd.set_option("display.max_rows",None)
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(Boltrev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Business development representative (bdr),5.0,2024-11-02,"Current employee, more than 3 years","great team, great pay, great offices","Sales team goot toxic, bad management"
1,Solutions engineer,2.0,2025-06-26,"Former employee, more than 1 year",New CEO might improve things,Lack of direction and too many managers who do nothing
2,Senior software engineer,4.0,2025-02-04,"Former employee, more than 1 year",Decent place and great coworkers.,Leadership needs to do more.
3,Anonymous employee,4.0,2025-01-16,Current employee,Good work place and people,"Hard work, would do again"
4,Revenue operations analyst,3.0,2024-11-10,"Former employee, less than 1 year",An incredible culture filled with amazing individuals who foster collaboration and creativity.,"The organization has experienced frequent changes in upper management, leading to a lack of stability and direction. This uncertainty is compounded by regular layoffs that create an atmosphere of tension and insecurity among employees."
5,Anonymous employee,2.0,2024-09-17,Former employee,"There were so many great employees at Bolt, it was a bummer that the product never could find it's market fit. The 4day work week was amazing.","There was poor communication between sales and eng teams that led us to take on merchants that needed a ton of new features that would be of no use to other merchants. It led to a lot of wasted time and energy, and ultimately money."
6,People leader,5.0,2024-07-24,"Current employee, more than 1 year","Bolt has a big vision, bringing frictionless shopping experiences to millions of shoppers worldwide by allowing shoppers to be recognized. The people at Bolt are highly motivated and exceptional to work with.","Bolt is still a startup, and pivots are frequent. We do a lot of experimentation and are aggressively trying to find our way to scale. If this sounds a little too uncomfortable, we may recognize it may not be the best environment for every personality."
7,Senior recruiter,5.0,2024-07-23,"Current employee, less than 1 year","Interviewing with Bolt consisted of 45 conversations with leaders and stakeholders I'd be working alongside on a daily basis/supporting. Interviewers were engaging and it was a very positive experience overall. Once hired, onboarding took about 12 weeks and was very organized. Had more than enough support in terms of both materials and colleagues to get up to speed on Bolt's product, culture, etc. Pay and benefits are strong company is remotefirst, Pay is competitive at/above industry average, and benefits are in alignment with other tech companies in the space. Despite previous restructures and changes in the organization the last few years, leaders are/have been transparent about the changes, the reasons behind them, and the vision/plan for Bolt moving forward. Product is interesting and a disrupter in the ecommerce space. You'll have the opportunity to work on/support the development of a product that supports well known brands everyone knows which is cool. There have been changes in leadership recently, and as a new hire, it seems from both a company vision/GTM strategy, as well as an employee morale standpoint, they are for the better. Individual contributors and leaders alike are aligned on the vision for the company and the product moving forward and are making a concerted effort to create a culture of more communication, transparency, and openness within all aspects of the organization. Definitely a startup culture where they prioritize hiring individuals who are able to/enjoy working autonomously, are strong culture builders, optimistic, and take ownership and accountability on the work they contribute. While there are more than enough systems/processes put in place, you also will have the opportunity to create processes from scratch or iterate on them. This may not be for everyone, but if you enjoy working in a high growth/scrappy startup environment, you will likely enjoy the type of work you get to do here.","Because of the multiple changes that have been made in the last 612 months, there may be some people that may not be aligned with the new vision/strategy of the company or new leadership moving forward. That being said, leadership has made a concerted effort to address this misalignment head on and have candid conversations about the future rather than not addressing people's apprehensions. From everything I've seen, department leaders and the executive team have taken a very humanistic approach to addressing people's concerns, and you can/will be heard and seen as a valued member of the Bolt organization."
8,Anonymous employee,5.0,2024-07-23,Current employee,"There is a lot of opportunity to roll up your sleeves and take on ownership that influence the strategic direction of the business. Bolt is going through a transformational shift and has great people in place across the board to help drive that. This is a great time to join if you like building, owning your domain, and innovating.","Bolt moves fast, there is no question about it. Often times, moving fast means things break. It's expected in a startup, but sometimes there are pieces to pick up and fix/solve when the company moves so quickly."
9,Account manager,4.0,2024-11-03,Current employee,Salary and work environment are great,Lots of overtime and not much vacations
10,Revenue operations,3.0,2024-08-21,"Former employee, more than 3 years",Great perks for both in office and remote employees Smart people with a passion to collaborate with one another,"Management was very secretive of process and what was happening. Also, leaders didn't always support their team. Layoffs several times a year."
11,Software engineer,1.0,2024-09-18,"Former employee, more than 1 year",Compensation is reasonable if you are not in Bay Area,"Not a week goes by without news of some drama about financing or a lawsuit by a customer. Most of the time, we hear about it from public news rather than being transparent internally. Very difficult to focus on work, keep good talent, or even attract customers."
12,Risk analyst,2.0,2024-10-01,"Current employee, more than 1 year",Flexible hours and decent pay,Upper leadership was unstable. There were may changes made to the team last minute and it can be stressful
13,Software engineer,1.0,2024-11-26,"Current employee, more than 1 year",Good domain and scale to work on.,No one knows what they are doing at Bolt.
14,Anonymous employee,2.0,2024-01-18,"Current employee, more than 1 year","San Francisco based pay no matter where you're located in the US or Canada. Bolt USED to have a 4day workweek but that's no longer the case starting in 2024, so I wouldn't be surprised if everyone starts abandoning ship. Huge upside IF everything works out, but it's a massive risk, so you've got to be OK with that.","Bolt has downsized considerably with multiple layoffs within the past two years, and with no more 4day workweeks, expect to be overworked and stretched very, very thin. Morale is abysmal. Seriously, STAY AWAY."
15,Anonymous employee,2.0,2024-01-18,Former employee,The managers were really good people.,"The executive leadership team could not be doing a better job at driving this company into the ground. 5 formal rounds of layoffs in 2 years. All female execs were “laid off” at the end of the year. The board is mostly the founders friends who are not experienced in the industry. The only perk, the four day work week, is no longer a benefit. If you asked most employees what the product is they wouldn’t have an answer. Pivoting, refocusing and changing plans occurred at least quarterly. Sales drives product. Sometimes the stores are the customer, sometimes the users are. The reason the company got as big as it did was because of shady user sign up practices. Leadership will not take any responsibility for any of the downturn they directly caused by their incompetence as business leaders. There is continuous news of litigation against the company. Shocked it’s still operating."
16,Ops manager,2.0,2024-10-03,Former employee,Salary is the only one,Everything besides salary is it
17,Business development,5.0,2024-07-23,"Current employee, less than 1 year",New CEO with a bold vision Great teamOpportunity to solve challenging problems and tremendous potential to differentiate and create value in the ecommerce space,Things can appear to be chaotic at timesMaking progress on focus and alignment
18,Partnerships,4.0,2024-07-19,"Current employee, less than 1 year",Ability to revolutionize commerce and drive strategy. Fast paced and strong group of people who are great to work with.,Frequent shifts in strategy to find product market fit
19,Communications manager,5.0,2024-08-19,"Current employee, more than 3 years","Good cash comp; finally some engaged, empathetic leadership","It's been a tough ride with lots of layoffs, executive changes, and challenges"
20,Revenue operations,3.0,2024-08-21,"Former employee, more than 3 years",Great perks for both in office and remote employees Smart people with a passion to collaborate with one another,"Management was very secretive of process and what was happening. Also, leaders didn't always support their team. Layoffs several times a year."
21,Software engineer,1.0,2024-09-18,"Former employee, more than 1 year",Compensation is reasonable if you are not in Bay Area,"Not a week goes by without news of some drama about financing or a lawsuit by a customer. Most of the time, we hear about it from public news rather than being transparent internally. Very difficult to focus on work, keep good talent, or even attract customers."
22,Risk analyst,2.0,2024-10-01,"Current employee, more than 1 year",Flexible hours and decent pay,Upper leadership was unstable. There were may changes made to the team last minute and it can be stressful
23,Software engineer,1.0,2024-11-26,"Current employee, more than 1 year",Good domain and scale to work on.,No one knows what they are doing at Bolt.
24,Anonymous employee,2.0,2024-01-18,"Current employee, more than 1 year","San Francisco based pay no matter where you're located in the US or Canada. Bolt USED to have a 4day workweek but that's no longer the case starting in 2024, so I wouldn't be surprised if everyone starts abandoning ship. Huge upside IF everything works out, but it's a massive risk, so you've got to be OK with that.","Bolt has downsized considerably with multiple layoffs within the past two years, and with no more 4day workweeks, expect to be overworked and stretched very, very thin. Morale is abysmal. Seriously, STAY AWAY."
25,Anonymous employee,2.0,2024-01-18,Former employee,The managers were really good people.,"The executive leadership team could not be doing a better job at driving this company into the ground. 5 formal rounds of layoffs in 2 years. All female execs were “laid off” at the end of the year. The board is mostly the founders friends who are not experienced in the industry. The only perk, the four day work week, is no longer a benefit. If you asked most employees what the product is they wouldn’t have an answer. Pivoting, refocusing and changing plans occurred at least quarterly. Sales drives product. Sometimes the stores are the customer, sometimes the users are. The reason the company got as big as it did was because of shady user sign up practices. Leadership will not take any responsibility for any of the downturn they directly caused by their incompetence as business leaders. There is continuous news of litigation against the company. Shocked it’s still operating."
26,Ops manager,2.0,2024-10-03,Former employee,Salary is the only one,Everything besides salary is it
27,Business development,5.0,2024-07-23,"Current employee, less than 1 year",New CEO with a bold vision Great teamOpportunity to solve challenging problems and tremendous potential to differentiate and create value in the ecommerce space,Things can appear to be chaotic at timesMaking progress on focus and alignment
28,Partnerships,4.0,2024-07-19,"Current employee, less than 1 year",Ability to revolutionize commerce and drive strategy. Fast paced and strong group of people who are great to work with.,Frequent shifts in strategy to find product market fit
29,Communications manager,5.0,2024-08-19,"Current employee, more than 3 years","Good cash comp; finally some engaged, empathetic leadership","It's been a tough ride with lots of layoffs, executive changes, and challenges"
40,People leader,5.0,2024-07-23,"Current employee, more than 1 year","Bolt is full of some of the smartest and most brilliant minds in the tech industry with tons of room for autonomy, really good work life balance",Being able to scale more effectively
41,Anonymous employee,2.0,2024-02-22,Current employee,There are a lot of really great people who are good at their jobs and genuinely nice. Flexibility of remote work,"Nepotism and lack of accountability from the top are creating a very toxic culture. The company is finally getting traction in the market, but inexperience and lack of substance in product leadership is impacting the entire company. No roadmap, no strategy, no leadership it's burning relationships with customers and burning out teams."
42,Director of corporate strategy,4.0,2024-06-18,"Former employee, more than 1 year","20192022 was amazing benefits, comp, upside. Since then....",four day weeks was not enough to do high impact work
43,Anonymous employee,1.0,2024-01-18,"Current employee, more than 3 years","If you're given a competitive salary, you'll probably get a decent severance when you're laid off and you'll get to keep your laptop. Remote first.Other ICs are great to work with.",Layoffs every couple of months for the last 2 years. Very little appreciation from managers and above. Everlowering valuation.The benefits are terrible. No 401k match.Equity is worthless.
44,Senior gtm manager,2.0,2024-06-21,Former employee,Salary align with market4 Day Week,"Every other aspect of the role, especially leadership."
45,Business development manager,1.0,2024-06-06,"Former employee, more than 3 years",They spend a lot of money on swag and retreats for leadership,This place is a mess. Poor leadership. Delusional goals. Focus on raising money instead of building a quality product.
46,Anonymous employee,2.0,2024-01-18,Current employee,"Autonomy, a vision that could change the industry, fullremote, interesting challenges","Leadership and communication: little transparency, disjoint communication channels, leadership doesn't care about IC career progression, ""boys club"" at the topCulture: no culture? no valuesBusiness: keep making same mistakes, true business performance hidden from rest of teamTech: lots of tech debt, old processes carried over from when company was larger"
47,Tech,1.0,2024-06-24,"Former employee, more than 3 years",Direct team members at the IC level are great,"Like other people have said, everything else especially leadership."
48,Technical support engineer,3.0,2024-01-18,Current employee,"Bolt really has been one of my favorite jobs, however, it is difficult to look past the issues with the product. The product works, and for the most part it works well, however there are so many players in this space it is hard to find product market fit.",Constantly shifting priorities leads to many rounds of layoffs. Sometimes it feels like you are just surviving the current round.
49,Individual contributor,1.0,2023-01-23,"Current employee, more than 3 years",Great team members lower level managers and team leads have been great on the teams I have been on 4 day work week,"The company is in the process of running out of money, so there are regular layoffs, departures, etc. Stock isn't worth anything, so comp isn't competitive. Moral is pretty low and most people are trying to leave or have already left. Some teams have lost too many people and are chronically understaffed relative to the workload. Leadership team is incredibly incompetent with only 1 or 2 exceptions like Shilpi on CE I would strongly recommend people not join at this point. While I don't regret joining this company and the time I spent here, I don't think it's a good idea to take a job at a startup that will have to sell or go out of business within the next year to 2 years. We're still probably 10x the headcount our revenue could actually support."
50,People leader,5.0,2024-07-23,"Current employee, more than 1 year","Bolt is full of some of the smartest and most brilliant minds in the tech industry with tons of room for autonomy, really good work life balance",Being able to scale more effectively
51,Anonymous employee,2.0,2024-02-22,Current employee,There are a lot of really great people who are good at their jobs and genuinely nice. Flexibility of remote work,"Nepotism and lack of accountability from the top are creating a very toxic culture. The company is finally getting traction in the market, but inexperience and lack of substance in product leadership is impacting the entire company. No roadmap, no strategy, no leadership it's burning relationships with customers and burning out teams."
52,Director of corporate strategy,4.0,2024-06-18,"Former employee, more than 1 year","20192022 was amazing benefits, comp, upside. Since then....",four day weeks was not enough to do high impact work
53,Anonymous employee,1.0,2024-01-18,"Current employee, more than 3 years","If you're given a competitive salary, you'll probably get a decent severance when you're laid off and you'll get to keep your laptop. Remote first.Other ICs are great to work with.",Layoffs every couple of months for the last 2 years. Very little appreciation from managers and above. Everlowering valuation.The benefits are terrible. No 401k match.Equity is worthless.
54,Senior gtm manager,2.0,2024-06-21,Former employee,Salary align with market4 Day Week,"Every other aspect of the role, especially leadership."
55,Business development manager,1.0,2024-06-06,"Former employee, more than 3 years",They spend a lot of money on swag and retreats for leadership,This place is a mess. Poor leadership. Delusional goals. Focus on raising money instead of building a quality product.
56,Anonymous employee,2.0,2024-01-18,Current employee,"Autonomy, a vision that could change the industry, fullremote, interesting challenges","Leadership and communication: little transparency, disjoint communication channels, leadership doesn't care about IC career progression, ""boys club"" at the topCulture: no culture? no valuesBusiness: keep making same mistakes, true business performance hidden from rest of teamTech: lots of tech debt, old processes carried over from when company was larger"
57,Tech,1.0,2024-06-24,"Former employee, more than 3 years",Direct team members at the IC level are great,"Like other people have said, everything else especially leadership."
58,Technical support engineer,3.0,2024-01-18,Current employee,"Bolt really has been one of my favorite jobs, however, it is difficult to look past the issues with the product. The product works, and for the most part it works well, however there are so many players in this space it is hard to find product market fit.",Constantly shifting priorities leads to many rounds of layoffs. Sometimes it feels like you are just surviving the current round.

In [95]:
# check duplicate sum
def checkDuplicateSum(df: pd.DataFrame) -> int:
    duplicate_count = df.duplicated().sum()
    return 'Sum of Duplicate_Values =', duplicate_count
checkDuplicateSum(Boltrev)

('Sum of Duplicate_Values =', 40)

In [96]:
Boltrev.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50      True
51      True
52      True
53      True
54      True
55      True
56      True
57      True
58      True
59      True
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70      True
71      True
72      True
73      True
74      True
75      True
76      True
77      True
78      True
79      True
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
dtype: bool

In [97]:
Boltrev.iloc[50:79]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
60,People leader,5.0,2024-07-23,"Current employee, more than 1 year","Bolt is full of some of the smartest and most brilliant minds in the tech industry with tons of room for autonomy, really good work life balance",Being able to scale more effectively
61,Anonymous employee,2.0,2024-02-22,Current employee,There are a lot of really great people who are good at their jobs and genuinely nice. Flexibility of remote work,"Nepotism and lack of accountability from the top are creating a very toxic culture. The company is finally getting traction in the market, but inexperience and lack of substance in product leadership is impacting the entire company. No roadmap, no strategy, no leadership it's burning relationships with customers and burning out teams."
62,Director of corporate strategy,4.0,2024-06-18,"Former employee, more than 1 year","20192022 was amazing benefits, comp, upside. Since then....",four day weeks was not enough to do high impact work
63,Anonymous employee,1.0,2024-01-18,"Current employee, more than 3 years","If you're given a competitive salary, you'll probably get a decent severance when you're laid off and you'll get to keep your laptop. Remote first.Other ICs are great to work with.",Layoffs every couple of months for the last 2 years. Very little appreciation from managers and above. Everlowering valuation.The benefits are terrible. No 401k match.Equity is worthless.
64,Senior gtm manager,2.0,2024-06-21,Former employee,Salary align with market4 Day Week,"Every other aspect of the role, especially leadership."
65,Business development manager,1.0,2024-06-06,"Former employee, more than 3 years",They spend a lot of money on swag and retreats for leadership,This place is a mess. Poor leadership. Delusional goals. Focus on raising money instead of building a quality product.
66,Anonymous employee,2.0,2024-01-18,Current employee,"Autonomy, a vision that could change the industry, fullremote, interesting challenges","Leadership and communication: little transparency, disjoint communication channels, leadership doesn't care about IC career progression, ""boys club"" at the topCulture: no culture? no valuesBusiness: keep making same mistakes, true business performance hidden from rest of teamTech: lots of tech debt, old processes carried over from when company was larger"
67,Tech,1.0,2024-06-24,"Former employee, more than 3 years",Direct team members at the IC level are great,"Like other people have said, everything else especially leadership."
68,Technical support engineer,3.0,2024-01-18,Current employee,"Bolt really has been one of my favorite jobs, however, it is difficult to look past the issues with the product. The product works, and for the most part it works well, however there are so many players in this space it is hard to find product market fit.",Constantly shifting priorities leads to many rounds of layoffs. Sometimes it feels like you are just surviving the current round.
69,Individual contributor,1.0,2023-01-23,"Current employee, more than 3 years",Great team members lower level managers and team leads have been great on the teams I have been on 4 day work week,"The company is in the process of running out of money, so there are regular layoffs, departures, etc. Stock isn't worth anything, so comp isn't competitive. Moral is pretty low and most people are trying to leave or have already left. Some teams have lost too many people and are chronically understaffed relative to the workload. Leadership team is incredibly incompetent with only 1 or 2 exceptions like Shilpi on CE I would strongly recommend people not join at this point. While I don't regret joining this company and the time I spent here, I don't think it's a good idea to take a job at a startup that will have to sell or go out of business within the next year to 2 years. We're still probably 10x the headcount our revenue could actually support."
70,People leader,5.0,2024-07-23,"Current employee, more than 1 year","Bolt is full of some of the smartest and most brilliant minds in the tech industry with tons of room for autonomy, really good work life balance",Being able to scale more effectively
71,Anonymous employee,2.0,2024-02-22,Current employee,There are a lot of really great people who are good at their jobs and genuinely nice. Flexibility of remote work,"Nepotism and lack of accountability from the top are creating a very toxic culture. The company is finally getting traction in the market, but inexperience and lack of substance in product leadership is impacting the entire company. No roadmap, no strategy, no leadership it's burning relationships with customers and burning out teams."
72,Director of corporate strategy,4.0,2024-06-18,"Former employee, more than 1 year","20192022 was amazing benefits, comp, upside. Since then....",four day weeks was not enough to do high impact work
73,Anonymous employee,1.0,2024-01-18,"Current employee, more than 3 years","If you're given a competitive salary, you'll probably get a decent severance when you're laid off and you'll get to keep your laptop. Remote first.Other ICs are great to work with.",Layoffs every couple of months for the last 2 years. Very little appreciation from managers and above. Everlowering valuation.The benefits are terrible. No 401k match.Equity is worthless.
74,Senior gtm manager,2.0,2024-06-21,Former employee,Salary align with market4 Day Week,"Every other aspect of the role, especially leadership."
75,Business development manager,1.0,2024-06-06,"Former employee, more than 3 years",They spend a lot of money on swag and retreats for leadership,This place is a mess. Poor leadership. Delusional goals. Focus on raising money instead of building a quality product.
76,Anonymous employee,2.0,2024-01-18,Current employee,"Autonomy, a vision that could change the industry, fullremote, interesting challenges","Leadership and communication: little transparency, disjoint communication channels, leadership doesn't care about IC career progression, ""boys club"" at the topCulture: no culture? no valuesBusiness: keep making same mistakes, true business performance hidden from rest of teamTech: lots of tech debt, old processes carried over from when company was larger"
77,Tech,1.0,2024-06-24,"Former employee, more than 3 years",Direct team members at the IC level are great,"Like other people have said, everything else especially leadership."
78,Technical support engineer,3.0,2024-01-18,Current employee,"Bolt really has been one of my favorite jobs, however, it is difficult to look past the issues with the product. The product works, and for the most part it works well, however there are so many players in this space it is hard to find product market fit.",Constantly shifting priorities leads to many rounds of layoffs. Sometimes it feels like you are just surviving the current round.
79,Individual contributor,1.0,2023-01-23,"Current employee, more than 3 years",Great team members lower level managers and team leads have been great on the teams I have been on 4 day work week,"The company is in the process of running out of money, so there are regular layoffs, departures, etc. Stock isn't worth anything, so comp isn't competitive. Moral is pretty low and most people are trying to leave or have already left. Some teams have lost too many people and are chronically understaffed relative to the workload. Leadership team is incredibly incompetent with only 1 or 2 exceptions like Shilpi on CE I would strongly recommend people not join at this point. While I don't regret joining this company and the time I spent here, I don't think it's a good idea to take a job at a startup that will have to sell or go out of business within the next year to 2 years. We're still probably 10x the headcount our revenue could actually support."
80,Senior software engineer,4.0,2024-02-28,"Current employee, more than 3 years",Overall the company is headed in the right direction to find product market fit.,Lots of upheaval in the last few years.
81,Data scientist,5.0,2024-03-11,Former employee,4 day work week was good,Move too fast and leadership was not good
82,It engineer,3.0,2024-03-05,"Former employee, more than 1 year",Good people took with. Good benefits.,Pivots every week on priorities. No stability
83,Software engineer i,4.0,2024-02-22,"Former employee, more than 1 year",coworkers work perks,leadership productmarket fit
84,Software engineer,3.0,2024-03-04,Current employee,smart people to work with4 day work week,need clearer product directionhigh turnover
85,Anonymous employee,4.0,2024-01-18,"Current employee, more than 1 year","remote first culture, high pay, room for career progression, great team",frequent lay offs and the stress that comes along with it
86,Software engineer,3.0,2024-01-31,Former employee,One of the smartest folks I got to work with.,Lots of poor management and lack of direction.
87,Sales,3.0,2024-01-31,Former employee,Very nice compensation structure at first,Poor leadership direction changed all the time
88,Anonymous employee,5.0,2023-12-11,"Current employee, more than 1 year",Leaders willing to make the hard decisions to turn the company around A ton of autonomyGood compensation,"A lot of change, which can be hard"

In [98]:
def drop_duplicate(df: pd.DataFrame) -> int:
    """This function drops the duplicated 
        values in the dataset
    Args = df for the dataset
    return = this function returns a dataframe 
        withiout the duplicate values"""
    drop_duplicates = df.drop_duplicates(subset = ["Job Title"], inplace=True)
    return drop_duplicates
drop_duplicate(Boltrev)

In [99]:
Rows, columns = Boltrev.shape
print(f"Rows = {Rows}, columns = {columns}")

Rows = 76, columns = 6

In [100]:
Boltrev.set_index("Job Title", inplace=True)
# Boltrev.drop("index", axis = 1, inplace=True)

In [101]:
Boltrev.reset_index(inplace=True)

In [102]:
Boltrev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Business development representative (bdr),5.0,2024-11-02,"Current employee, more than 3 years","great team, great pay, great offices","Sales team goot toxic, bad management"
1,Solutions engineer,2.0,2025-06-26,"Former employee, more than 1 year",New CEO might improve things,Lack of direction and too many managers who do nothing
2,Senior software engineer,4.0,2025-02-04,"Former employee, more than 1 year",Decent place and great coworkers.,Leadership needs to do more.
3,Anonymous employee,4.0,2025-01-16,Current employee,Good work place and people,"Hard work, would do again"
4,Revenue operations analyst,3.0,2024-11-10,"Former employee, less than 1 year",An incredible culture filled with amazing individuals who foster collaboration and creativity.,"The organization has experienced frequent changes in upper management, leading to a lack of stability and direction. This uncertainty is compounded by regular layoffs that create an atmosphere of tension and insecurity among employees."
5,People leader,5.0,2024-07-24,"Current employee, more than 1 year","Bolt has a big vision, bringing frictionless shopping experiences to millions of shoppers worldwide by allowing shoppers to be recognized. The people at Bolt are highly motivated and exceptional to work with.","Bolt is still a startup, and pivots are frequent. We do a lot of experimentation and are aggressively trying to find our way to scale. If this sounds a little too uncomfortable, we may recognize it may not be the best environment for every personality."
6,Senior recruiter,5.0,2024-07-23,"Current employee, less than 1 year","Interviewing with Bolt consisted of 45 conversations with leaders and stakeholders I'd be working alongside on a daily basis/supporting. Interviewers were engaging and it was a very positive experience overall. Once hired, onboarding took about 12 weeks and was very organized. Had more than enough support in terms of both materials and colleagues to get up to speed on Bolt's product, culture, etc. Pay and benefits are strong company is remotefirst, Pay is competitive at/above industry average, and benefits are in alignment with other tech companies in the space. Despite previous restructures and changes in the organization the last few years, leaders are/have been transparent about the changes, the reasons behind them, and the vision/plan for Bolt moving forward. Product is interesting and a disrupter in the ecommerce space. You'll have the opportunity to work on/support the development of a product that supports well known brands everyone knows which is cool. There have been changes in leadership recently, and as a new hire, it seems from both a company vision/GTM strategy, as well as an employee morale standpoint, they are for the better. Individual contributors and leaders alike are aligned on the vision for the company and the product moving forward and are making a concerted effort to create a culture of more communication, transparency, and openness within all aspects of the organization. Definitely a startup culture where they prioritize hiring individuals who are able to/enjoy working autonomously, are strong culture builders, optimistic, and take ownership and accountability on the work they contribute. While there are more than enough systems/processes put in place, you also will have the opportunity to create processes from scratch or iterate on them. This may not be for everyone, but if you enjoy working in a high growth/scrappy startup environment, you will likely enjoy the type of work you get to do here.","Because of the multiple changes that have been made in the last 612 months, there may be some people that may not be aligned with the new vision/strategy of the company or new leadership moving forward. That being said, leadership has made a concerted effort to address this misalignment head on and have candid conversations about the future rather than not addressing people's apprehensions. From everything I've seen, department leaders and the executive team have taken a very humanistic approach to addressing people's concerns, and you can/will be heard and seen as a valued member of the Bolt organization."
7,Account manager,4.0,2024-11-03,Current employee,Salary and work environment are great,Lots of overtime and not much vacations
8,Revenue operations,3.0,2024-08-21,"Former employee, more than 3 years",Great perks for both in office and remote employees Smart people with a passion to collaborate with one another,"Management was very secretive of process and what was happening. Also, leaders didn't always support their team. Layoffs several times a year."
9,Software engineer,1.0,2024-09-18,"Former employee, more than 1 year",Compensation is reasonable if you are not in Bay Area,"Not a week goes by without news of some drama about financing or a lawsuit by a customer. Most of the time, we hear about it from public news rather than being transparent internally. Very difficult to focus on work, keep good talent, or even attract customers."
10,Risk analyst,2.0,2024-10-01,"Current employee, more than 1 year",Flexible hours and decent pay,Upper leadership was unstable. There were may changes made to the team last minute and it can be stressful
11,Ops manager,2.0,2024-10-03,Former employee,Salary is the only one,Everything besides salary is it
12,Business development,5.0,2024-07-23,"Current employee, less than 1 year",New CEO with a bold vision Great teamOpportunity to solve challenging problems and tremendous potential to differentiate and create value in the ecommerce space,Things can appear to be chaotic at timesMaking progress on focus and alignment
13,Partnerships,4.0,2024-07-19,"Current employee, less than 1 year",Ability to revolutionize commerce and drive strategy. Fast paced and strong group of people who are great to work with.,Frequent shifts in strategy to find product market fit
14,Communications manager,5.0,2024-08-19,"Current employee, more than 3 years","Good cash comp; finally some engaged, empathetic leadership","It's been a tough ride with lots of layoffs, executive changes, and challenges"
15,Director of corporate strategy,4.0,2024-06-18,"Former employee, more than 1 year","20192022 was amazing benefits, comp, upside. Since then....",four day weeks was not enough to do high impact work
16,Senior gtm manager,2.0,2024-06-21,Former employee,Salary align with market4 Day Week,"Every other aspect of the role, especially leadership."
17,Business development manager,1.0,2024-06-06,"Former employee, more than 3 years",They spend a lot of money on swag and retreats for leadership,This place is a mess. Poor leadership. Delusional goals. Focus on raising money instead of building a quality product.
18,Tech,1.0,2024-06-24,"Former employee, more than 3 years",Direct team members at the IC level are great,"Like other people have said, everything else especially leadership."
19,Technical support engineer,3.0,2024-01-18,Current employee,"Bolt really has been one of my favorite jobs, however, it is difficult to look past the issues with the product. The product works, and for the most part it works well, however there are so many players in this space it is hard to find product market fit.",Constantly shifting priorities leads to many rounds of layoffs. Sometimes it feels like you are just surviving the current round.
20,Individual contributor,1.0,2023-01-23,"Current employee, more than 3 years",Great team members lower level managers and team leads have been great on the teams I have been on 4 day work week,"The company is in the process of running out of money, so there are regular layoffs, departures, etc. Stock isn't worth anything, so comp isn't competitive. Moral is pretty low and most people are trying to leave or have already left. Some teams have lost too many people and are chronically understaffed relative to the workload. Leadership team is incredibly incompetent with only 1 or 2 exceptions like Shilpi on CE I would strongly recommend people not join at this point. While I don't regret joining this company and the time I spent here, I don't think it's a good idea to take a job at a startup that will have to sell or go out of business within the next year to 2 years. We're still probably 10x the headcount our revenue could actually support."
21,Data scientist,5.0,2024-03-11,Former employee,4 day work week was good,Move too fast and leadership was not good
22,It engineer,3.0,2024-03-05,"Former employee, more than 1 year",Good people took with. Good benefits.,Pivots every week on priorities. No stability
23,Software engineer i,4.0,2024-02-22,"Former employee, more than 1 year",coworkers work perks,leadership productmarket fit
24,Sales,3.0,2024-01-31,Former employee,Very nice compensation structure at first,Poor leadership direction changed all the time
25,Engineering,4.0,2023-11-08,"Current employee, more than 1 year",You will get to build and iterate fast on super interesting concepts for the future of ecommerce.,One heck of a ride
26,Account executive,2.0,2023-10-16,"Former employee, more than 1 year",The pay was the best part about this job.,"There was no direction, no transparency from leadership, and no opportunities to grow."
27,Gtm,2.0,2023-10-24,"Current employee, more than 1 year","Interesting work. Able to work on a variety of products across the payments, fraud, and identity spaces.",Has struggled to find a product market fit or to learn from past mistakes.
28,Product operations manager,3.0,2023-11-09,Former employee,"Great team, lots of smart people","Leadership needs improvement, lots of costcutting and changes"
29,Sre engineer,4.0,2023-10-22,Former employee,Team unity was great at Bolt,"Often changing directions, and had to throw away many projects."
30,Department lead,5.0,2023-05-17,"Current employee, less than 1 year","4day work week Supportive manager Total autonomy in my role Smart, supportive team Founder mentality + the freedom to try new things","While the company had a rough 2022, Bolt has completely transformed in 2023. I think overall sentiment may vary across departments, but I have absolutely loved my experience so far! Only a few cons, but hopefully these will change soon: No 401k matching As the company hasn't gone public or been acquired, the RSUs aren't worth much"
31,Senior data analyst,5.0,2023-08-23,"Former employee, more than 1 year",Hiring great talents. Great work life Balance. Salary is competitive and 4 day work week is great.,"Due to economic environment, not very stable."
32,Machine learning engineer,1.0,2023-08-01,"Former employee, more than 3 years",4 day work week is nice. Some of the old timer people are very helpful but a lot of the recent additions are not,"Aggressively rude culture. Lots of backstabbing in infighting between groups as rev # are not that big, everyone wants a piece of something"
33,Operations manager,5.0,2023-07-06,"Former employee, more than 1 year","Flexibility, ownership, compensation, culture, benefits, career advancement, recognition of good work",Struggle to find product market fit
34,Associate,4.0,2023-06-23,Former employee,not bad and helpful and fair,need more training for both employees and managers
35,Product designer,5.0,2019-11-23,"Current employee, less than 1 year","I work with people who constantly make me feel energized to do the best I can. There are so many different personalities on the team but everyone is so driven and extremely competent. They are by far the brightest and funniest people I've ever worked with. Even though the company is full of very young and ambitious people, there really isn't a tech bro culture you would see at many other rising startups in the bay area. Extremely ownership and autonomy is highly encouraged here. Leadership is highly transparent and you can tell they make it a priority to keep their doors open for any feedback and thoughts. Very competitive comp package and benefits. But besides financial incentives, I truly feel taken care of by the company and everyone on the team on a day to day basis.","The level of autonomy people function with is not for everyone. If you're not a selfstarter and an independent thinker, I can imagine it'd feel challenging to get things done. Hiring is difficult because the combination of skills & a specific type of fire we look for in people is hard to come by. But that's also what makes the team so great."
36,Sales associate,5.0,2023-04-10,Current employee,Great perks dont have any cons,Can be tough to work at a fastgrowing startup but it can also be exciting.
37,"Director, employee experience",5.0,2021-05-24,"Current employee, less than 1 year","It's my first week here but already feel incredibly welcomed. I've been impressed and more quickly acclimated by a super robust onboarding and all the Culture Meetings too Firedsides, Affinity Group Events, etc.. Am learning about the benefits of Bolt's value of writing over talking. I've been at other startups and this is by far the most organized, the most accountable, the quickest and the most transparent. I, even from the interview process, feel like I can be myself here. Bolt encourages uniqueness and celebrating our team all parts of us, and I'm happy that there's less posturing that people don't seem fake/political/gameplaying at work and more genuine openness and realness. Bolt truly believes in the value of doing right by, and supporting, all the teammates. So far it seems like the company has prioritized various efforts, services and perks to help employees have a better work experience I'm obviously biased, but I think that's hugely important.","Bolt is still a startup, and feels like one for better but also for worse in some cases. I feel confident that the company will keep finetuning processes and policies, but everyone who joins will have to bring their proactiveness, creativity and a little patience to the table."
38,Manager,3.0,2023-04-13,Former employee,Nice and smart plus 4 day week,Chaos in decision making constantly
39,Talent,5.0,2019-08-07,"Current employee, less than 1 year","The product is unbeatable. Not only is it a needtohave, but there's also a mission driven component to stopping fraud and empowering merchants. It's a winwin for everyone. Our culture is genuine, and even though we have some of the smartest people in FinTech working here, there's no egos. People are just excited to drive the needle, which every person has the ability to do! Playbooks and processes are either already built out or are in the process of being built out. This makes scaling a startup way more efficient, and is a big reason we've been able to grow as fast as we have. Autonomy!! You are the CEO of your desk and are expected to deliver. The amount of trust we are given is motivating in itself. We live by our values, and have great values in place. Flexible hours to allow a work life balance. If you want to take a workout class midday, you can. On that note, we have the best benefits, including gym, commute, phone, lunch/afternoon coffee, and company happy hours to name a few.","Not really a con, but we have a self onboarding process. On one hand, self onboarding goes WAY faster because you can power through the tasks in a couple days. On the other hand, if you're a visual learner or if you prefer classroomstyle tutorials, it will take longer for the information to stick. Just something to keep in mind."
40,User researcher,3.0,2023-03-07,Former employee,4 day work week great people,fast paced unorganized seems that they are running out of runway
41,Special projects associate,5.0,2020-08-18,"Current employee, more than 1 year","I've been working at Bolt for over a year. I can't stress enough about how much I've learned during my time at Bolt. It's been quite the journey, and with each quarter, I continue to work on new projects, iterate, and drive success within Bolt. There are many pros to being here.I'd say the best thing about Bolt is the collaboration. I work across multiple teams and I love the personal connection and great work relationships I've built. I'd say most of the people I work with are great to work with and genuinely want what's best for Bolt.I am not one to take vacation or sick days, but my manager always asks about how I’m feeling and how things are going and always recommends time off and taking time for myself. Super appreciative of this and I have taken a few days off, and Bolt strongly recommends absolutely no work during these days which is great. You’re able to really unplug.Lastly, I’d say that Bolt is a great place to work. If you want to succeed and grow and learn, you are able to. There’s hard work wherever you look, but it’s all worth it. I enjoy my role and the impact of the projects I’m given. I look to continue to learn during my time here.","This is a tough one, I don't think I have explicit cons, especially with my team and role. Coronavirus is definitely a huge con here, as the worklife balance is less concrete."
42,Recruiter,3.0,2019-05-16,"Former employee, less than 1 year","startup fun, young atmospherecompany buys lunch every dayvery cool product, exciting value prop","elitist and judgmental The company is very young. The people are smart, but there's a huge lack of life and career experienceNot sure if they still do it, but when I was there they would post an announcement in slack every time a person was termed, to publicly announce why that person wasn't good enough and is no longer there, and to remind everyone of what they shouldn't do felt like bullying They emphasize hiring for culture, but fail to recognize that diversity exists beyond people looking differently or coming from a variety of demographics, but actually encompasses the ability to think differently too. They are at risk of hiring a bunch of people who all think the same way, which sadly kills diversity."
43,Customer experience,5.0,2019-12-26,"Current employee, more than 1 year","Smart, collaborative people and an excellent executive leadership team Great market opportunity and strong company growth potential Anybody at the company can have outsize impact Cultural norms and tooling allow for teams and individuals to easily provide feedback positive & constructive to one another, and feedback is nearly always given appropriate consideration regardless of who is giving the feedback to whom. Solid pay & benefits compared to companies of similar size and funding","Like many highgrowth startups, the environment is fastpaced, change is regular, everybody has a lot on their plate, and some parts of the organization are more mature in their processes and decisionmaking than others. To that end, being successful at Bolt requires you to: Be highly thoughtful about what is a priority and what can be accomplished over a specific time frame, and be comfortable saying ""no"" to projects or goals that are unrealistic or not yet a priority. Take time to build foundations, organizing information & data so that team members can make decisions quickly and then disseminate information about those decisions to key stakeholders with high efficiency.Currently, not every team or every individual makes the time to do the above on a regular basis, which can result in friction between teams and individuals. However, over the course of my time at the company, people have improved in these regards significantly and I have little doubt that we will only get better as time goes on."
44,Senior android engineer,4.0,2022-11-30,Current employee,4 hour work week is great,"Mobile is in a rough spot right now, not a lot to do or planned"
45,Director of engineering,2.0,2022-12-02,"Current employee, less than 1 year",smart people fast culture 4 day work week,no direction clueless leadership business outlook is not good

In [103]:
Boltrev.insert(6,"Company_Name", "Bolt")