In [4]:
import pandas as pd
import numpy as np

In [5]:
CisRev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/ciscoReviews.csv")

In [6]:
# EDA on the data
def display(x):
    """This function returns a 
    summary of the dataset"""
    
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(CisRev)

Displays the rows and columns in the dataset
============================================
Rows: 28092 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                               Job Title  Job Ratings          time  \
0             Manager, network services          4.0  Mar 13, 2015
1                      Systems engineer          3.0   Aug 5, 2025
2                   Strategy & planning          4.0   Jul 8, 2025
3                       Human resources          3.0  Aug 12, 2025
4                    Solutions engineer          4.0  Aug 10, 2025
...                                 ...          ...           ...
28087  Professional services management          1.0  Sep 26, 2021
28088                Anonymous employee          1.0  Feb 28, 2022
28089                Anonymous employee          1.0  Feb 24, 2018
28090  Professional services management          1.0  Sep 26, 2021
28091                Anonymous employee          1.0  Feb 28, 2022

                                 JobStatus  \
0       Former employee, more than 3 years
1       Former employee, more than 8 years
2                          Former employee
3      Current employee, more than 3 years
4      Current employee, more than 5 years
...                                    ...
28087                      Former employee
28088                     Current employee
28089    Former employee, more than 1 year
28090                      Former employee
28091                     Current employee

                                                    Pros  \
0      I decided to wait almost a year after leaving ...
1      Overall, Cisco is a good place to work. As a s...
2      Grow and learn with some genuinely smart and c...
3                People are collaborative. Nice culture.
4      Great culture for the most part. I know it mai...
...                                                  ...
28087                           lay back and stable role
28088                            No prod is offered here
28089                   Good working experience in cisco
28090                           lay back and stable role
28091                            No prod is offered here

                                                    Cons
0      Cisco can be a machine.  There isn't an overt ...
1      If you end up with a manager who manipulates s...
2      The 'old guard' of Cisco can be quite bureaucr...
3                Frequency of lay-offs are destabilizing
4      It sense like the powers that be don’t underst...
...                                                  ...
28087                  lack of innovation and disconnect
28088                        Everything is cons for sure
28089                                     no no no no no
28090                  lack of innovation and disconnect
28091                        Everything is cons for sure

[28092 rows x 6 columns]>

Returns the information in more details
============================================
        Job Ratings
count  28092.000000
mean       3.990104
std        1.009429
min        1.000000
25%        3.000000
50%        4.000000
75%        5.000000
max        5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           20
dtype: int64

In [7]:
# display the whole text
pd.set_option("display.max_colwidth", None)

In [8]:
# printing the first 20 elements on the dataset
print("first 5 elements")
print("=====================================================")
print()
CisRev.head(5)

first 5 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,"Manager, network services",4.0,"Mar 13, 2015","Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\r\n\r\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time (even the time outside of work) but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\r\n\r\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\r\n\r\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs."
1,Systems engineer,3.0,"Aug 5, 2025","Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of ground-level realities."
2,Strategy & planning,4.0,"Jul 8, 2025",Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company (~80K employees). Things can get lost."
3,Human resources,3.0,"Aug 12, 2025","Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of lay-offs are destabilizing
4,Solutions engineer,4.0,"Aug 10, 2025","Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment

In [9]:
# printing the last 20 elements on the dataset
print("Last 5 elements")
print("=====================================================")
print()
CisRev.tail(5)

Last 5 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
28087,Professional services management,1.0,"Sep 26, 2021",Former employee,lay back and stable role,lack of innovation and disconnect
28088,Anonymous employee,1.0,"Feb 28, 2022",Current employee,No prod is offered here,Everything is cons for sure
28089,Anonymous employee,1.0,"Feb 24, 2018","Former employee, more than 1 year",Good working experience in cisco,no no no no no
28090,Professional services management,1.0,"Sep 26, 2021",Former employee,lay back and stable role,lack of innovation and disconnect
28091,Anonymous employee,1.0,"Feb 28, 2022",Current employee,No prod is offered here,Everything is cons for sure

In [10]:
# printing the random sample of 20 elements
print("Random 5 elements")
print("=====================================================")
print()
CisRev.sample(5)

Random 5 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
5372,Software development engineer in test (sdet),5.0,"Aug 20, 2023",Current employee,everything is good about it,Nothing cons about it except for onsite opportunities
5853,Network operations engineer,4.0,"Mar 3, 2023","Former employee, less than 1 year",One of the best places to work ofcourse with excellent salary and benefits,But they do layoff in numbers with little or no notice periods for this type of role.
24396,Anonymous employee,4.0,"Feb 28, 2018",Current employee,"Great Company, enjoy the culture","Limited travel opportunities, limited growth for remote workers"
3944,Product manager,3.0,"Mar 5, 2024","Current employee, more than 3 years","benefits, work life balance, team members","pay, lack of growth opportunities, frequent restructuring"
8481,It engineer,3.0,"May 12, 2016","Current employee, more than 1 year",The compensation package and work style is the best part of the job. About 3 weeks off per year and the ability to work from home is great. Seemingly stable job with good benefits and relaxed work environment,"Depending where you get placed, the work may or may not match with your skill set or be of the most interest to you. Changing this can be difficult and must be fought for. Management changes can be frequent (3 in about 16 months) and political which can lead to a feeling of misdirection. Hard work can go unnoticed and so can slacking off"

In [11]:
# checking the first column details
col1 = CisRev["Job Title"]
col1

0               Manager, network services
1                        Systems engineer
2                     Strategy & planning
3                         Human resources
4                      Solutions engineer
                       ...
28087    Professional services management
28088                  Anonymous employee
28089                  Anonymous employee
28090    Professional services management
28091                  Anonymous employee
Name: Job Title, Length: 28092, dtype: object

In [12]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns 
    total null values on the dataset"""
    print(df.isna().sum())
null_values(CisRev)

Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           20
dtype: int64

In [13]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the 
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(CisRev)
# CisRev.dropna(inplace=True)

In [14]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(CisRev)

In [15]:
# Rename the headers
CisRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [16]:
pd.reset_option('Display.Max_rows')
pd.reset_option('Display.Max_columns')

In [17]:
CisRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,"Manager, network services",4.0,2015-03-13,"Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\r\n\r\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time (even the time outside of work) but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\r\n\r\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\r\n\r\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs."
1,Systems engineer,3.0,2025-08-05,"Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of ground-level realities."
2,Strategy & planning,4.0,2025-07-08,Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company (~80K employees). Things can get lost."
3,Human resources,3.0,2025-08-12,"Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of lay-offs are destabilizing
4,Solutions engineer,4.0,2025-08-10,"Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment
...,...,...,...,...,...,...
28087,Professional services management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28088,Anonymous employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure
28089,Anonymous employee,1.0,2018-02-24,"Former employee, more than 1 year",Good working experience in cisco,no no no no no
28090,Professional services management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28091,Anonymous employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure

In [18]:
# checking the unique values in the dataset
for job in CisRev["Job Title"].unique():
    print(job)

Manager, network services
Systems engineer
Strategy & planning
Human resources
Solutions engineer
Program manager
Software engineer
Operations manager
Data scientist
Sr. sales enablement manager
Regional sales manager
Softwater engineer
Business operations analyst
Technical consulting engineer
Project manager
Solution architect
Senior swe
Anonymous employee
Regional implementation coordinator
Senior product manager
Sr. software engineer
Software development engineer (sde)
Sales representative
Senior software engineer
Finance manager
Technical writer
Senior power bi developer
Customer project manager
Technical program manager
Team leader
Technical lead
Software engineer ii
Network engineer
Data engineer
India technical apprentice
Account executive
Desktop analyst
Solutions enginner
Receptionist
Senior account executive
Consulting engineer
Cyber security engineer
Account manager
Engineering program manager
Sales
Sales manager
Cse
Financial anlayst
Software engineer ii in test
Senior account manager
Sre trainee
Director
Network development engineer
Virtual partner account manager
Business analyst
Sdet3
Product manager intern
Product sales specialist
Product manager
Senior partner account manager
Technicsl support engineer
Engineering manager
Partner success manager
Executive assistant
Software engineering technical leader
Technical support engineer
Network security engineer
Marketing specialist
Graphic designer
Cloud engineer
Manager, software development & engineering
Ai/ml engineer
Partner account executive
Associate software engineer
Software engineering manager
Tce
Customer success specialist
Analyst
Software development engineer in test (sdet)
Sdet
Software engineer 4
Engineering product manager
Engineering leader
Sde1 entry
Ux designer
Customer delivery manager
Solutions architect
Tme engineer
Software developer
Senior product designer
Partner operations manager
Intern
Customer project specialist
Software architect
Sr. technical lead
Quality engineer
Finance
Middle ios developer
Global account manager
Software engineer iii
Territory account manager
Security engineer
Technical intern i
Customer success manager (csm)
Sr. product manager
Sales engineer
Business architect
Sales specialist
Vp- human resources
Sd-2
Nce - network consulting engineer
Partner account manager
Senior tce
Leader, customer delivery
Site relability engineer
Senior consultant
Commodity manager
Business operations manager
Talen acquisition partner
Swe intern
Tech lead
Sde-2
Data analyst
Lead engineer/technologist
It manager
Technical consulting engineer- customer delivery
Contract negotiator
Ui developer
Senior project manager
Technical consulting manager
Employee
Ux-ui designer
Artificial intelligence engineer
Bpmn developer
Tac engineer
Software engineer-1
Senior manager
Cx service lead
Solutions specialist
Recruiter
Technical undergraduate intern
Principal engineer
Network support engineer
Tde
Sr. business development executive
Software qa engineer
Senior technical lead
Sr. business development manager
Senior administrative assistant
Marketing manager
Project engineer
Hardware engineer
Senior solutions engineer manager
Engineer
Pre-sales consultant
Customer service engineer
Software engineer-iii
Senior product engineer
Technical architect
Demand planning manager
Renewals manager
Senior associate
Manager
Senior software qa engineer
Software tester
Developer
Sotfware engineer
Major incident manager
Senior technical program manager
Employee experience specialist
Software test engineer
Business ops analyst
Unpaid wagie
Strategic account executive - security services
Technical scrum master
Leaders in finance and technology (lift), financial analyst
Site reliability engineer
Se
Communications manager
Senior software engineer (sde3)
Head of ecommerce and digital marketing
Senior asic design verification engineer
System architect
Principal embedded software engineer
Senior consulting engineer
Finanace manager
Administrative
Finance leader
Network analyst
Sr. manager product management
Senior mechanical/design engineer
Sre/devops engineer
Manager, compliance
Business development manager
Software engineer(internship)
Virtual internship
Designer
Software development engineer (sde) 3
Ai researcher
Software engineer iv
Customer project/program manager
Internal auditor
Technical recruiter
Director, field marketing
Customer support engineer
Cybersecurity specialist
Consultant
Engineering leadership
Software engineer (swe ii)
Crm executive
Software developer intern
Architecture designer
Quality assurance
Sales leader
Internship
Software engineer trainee
Software engineer -2
Poject manager
Financial analyst
Technical apprentice
Human resources generalist
Swe 2
Sr financial analyst
Senior hardware engineer
Cyber security analyst
Senior test engineer
Change manager
Client operations analyst
Cisco tac engineer
Customer delivery leader
Technical specialist
Product designer
Director of systems engineering
Partner operations
Technical consultant
Technical solutions engineer
Sr. graphic designer
Bdm manager
Sr director product management
Partner business development manager
Software engineer - java developer
Bussiness operations manager
Demand generation manager
Business development representative (bdr)
Accounts assistant
Junior web developer
Associate software developer
Software enginner-iii
Senior web developer
Software engineering tech lead/manager
Senior tech leader
Systems architect
Senior qa manager
Associate java developer
Technical leader
Sales operations
Customer experience product manager
Customer program manager
Compliance specialist
Sourcing specialist
Product specialist
Customer success manager
Software enginner intern
Software engineer 3
Technical graduate
Full stack java developer
Change leader
Java developer
Technical security engineer
Systems administrator
Techincal support engineer
Manager, technical support
Senior director, product management
Customer support specialist
Partner marketing manager
Named account manager
Senior acountant
Software enginner ii
Forklift operator
Senior marketing manager
Apprentice
Software engineer i
Financial sales specialist
Principle technical program manager
Test engineer
Sales associate
Softwareengineer
Manager, business operations
Technical sales engineer
Partner development manager
Engineering project manager
Front end web developer
Sr asic engineer
Senior engineering manager
Consultor
High touch engineer
Customer experience
Cyber security account executive
Research software engineer
Engineering hardware lead
Regional manager
Finance analyst
Operation manager
Technical solutions architect
Business analysis manager
Marketing director
Business operations specialist
Software consulting engineer
Director, product marketing
Clerical assistant
L&d manager
Technical marketing engineer
Senior systems engineer
Senior data scientist
Data science intern
Data science manager
Devops engineer
Sre engineer
Customer success executive
Project coordinator ii
Business systems analyst
Technical engineer
Cloud infrastructure engineer
Technical support manager
Senior nework engineer
Senior manager, operations
Associate solutions engineer
Staff software engineer
Sales development representative (sdr)
Client operations delivery analyst
Consulting
Senior bd director
Regulatory compliance engineer
Professional services consultant
Salesforce business analyst
Cyber security consultant
Lawyer
Technical project manager
Creative
Senior infrastructure engineer
Tech leader
Data center engineer
Sales business development manager
Asset manager
Sales enablement manager
Consulatant
Systems engineering
Ux researcher
Security technical consulting engineer
Technical engagement manager
Software development engineer (sde) ii
Customer scrum lead
Machine learning engineer
Security guard
Select account manager
Software intern
Software consultant
Cloud and ai infrastructure specialist
Technical leader engineering
Hardware technical leader
Quote specialist
Compliance officer
Training specialist
Pss
Anonymous
Consulting software engineer
Software renewal specialist
Site reliability engineer - technical lead
Global business operations manager
Sales enablement specialist
Network consulting engineer
Senior executive assistant
Customer delivery architect
Sales acceleration manager
Technical comsultant
Returns specialist
Partner manager
Senior cx strategist
Product marketing
Security analyst
Sr. manager, operations
System engineer
Compliance auditor
Senior solutions engineer
Marketing manager iii
Strategic sourcing manager
Business capability manager
Sr software engineer in test
Asic engineer
Sales enablement associate
Strategy and planning manager
Office assistant
Head of sales
Enterprise account manager
Vlsi design engineer
Senior asic engineer
Head of technology
Virtual sales account manager
Software engineer 10
Senior softare engineer
Software dev engineer
Digital marketing specialist
Software development engineer
Sap analyst
G10
Senior architect
Senior ux researcher
Lead developer
Solutions architect tsa
Senior financial analyst
Individual contributor
Staff technical program manager
Marketing
Strategic partner manager
Senior partner marketing manager
Comms lead
Solutions integration architect
Manufacturing operations supply project manager
Service delivery manager
Senior analyst
Automation engineer
Css
Ux research manager
Qa engineer
Senior technical consulting engineer
It asset manager
Cloud senior consultant
Senior software developer
Talent acquisition specialist
Small business partner seller
Digital marketing manager
Parttime sales
Senior program manager
Senior manager, marketing
Distinguished engineer
Program manaer
Proofreader
Demand planner
Lead tech
Smb account executive
Commercial finance director
Product owner
Director engineering
Programme manager
Senior change manager
Sr site reliability engineer
Principal software engineer
Sales assistant
Senior network consulting engineer
Bdm
Ui\ux designer
Virtual sales engineer
Business development
Leader, customer experience
Senior finance analyst
Sde 3
Auditor
Client success manager
Consulting engineer trainee
Senior product marketing manager
Lead configuration engineer
It support specialist
Structure engineering
Content manager
Senior software consultant
Sales coordinator
Customer delivery director
Senior technical writer
Cloud security specialist
Associate creative director-art
Strategy and operations
Sw developer
Commercial finance analyst
Data architect
Sofwatre engineer
Sr pmm
Team lead product marketing
Visual designer
Technical consultant engineer
It engineer
Software engineer ii sde2
Channel manager
Service specialist
Controller
Prodcut manager
Spm
Cybersecurity internship
Senior user researcher
Solution engineer
Frontend technical lead
Financial analyst lift program
Marketing trainee
Services account executive
Senior sre
Sr leader, data science & ai solutions
Corporate strategy manager
Technical salesengineer
Technical systems engineer
Sr. network specialist
Software engineer level iv
Indian technical apprentice
Security consulting engineer
Business analayst
Leader software engineering
Engineering leadership development program
Software engineering
Senior ux designer
Senior incident response consultant
Sse- development
Software engineer swe iii
Staff engineer
Data manager
Account development representative
Strategy analyst
Strategy & planning manager
V&v engineer
Senior business analyst
Sales director uki
Director of sales
Ux research lead
Product desginer
Senior ai engineer
Senior technical leader
Client service executive
Customer success program manager
Opeartion analyst
Software engineer apprentice
Devops/sre engineer
Business manager
Projecty manager
Implementation engineer
Sr. director
Leader, talent acquisition
Icam inside channel account manager
Sales operations manager
Regional sales leader
Business development executive
Renewal specialist
Se manager
Videoproducer
Technical product owner
Key account manager (kam)
Deals desk analyst
Software engineer/technical leader
Chief of staff
Senior network engineer
Technical solution engineer
Software engineer intern
Security specialist
Custumer experience
Senior lead developer
Senior data analyst
Sofware engineer i
Siftware engineer
Physical design engineer
Content designer
Head of market development
Managing director
Professional services manager
S/w engg
High touch operations manager (htom)
Senior network support engineer
Cloud engineer 2
Vsam
Consultant engineer
Marketing program manager
Lobby ambassador
Senior director
Data analyst manager
Architect
Sales executive
Team leader - customer experience
Regional sales director
Product management
Team lead
Information security analyst
Category manager
Client delivery & operations
Technical support
Technical leader - software
Sr. supply chain manager
Virtual sales leader
Recruitment consultant
Qa software engineer
Customer success
Inside channel account manager
It service delivery leader
Business operation manager
Performance marketing manager
Sales strategy manager
Customer service representative
Sr operations manager
Business intelligence manager
Data science analyst
Community relations manager
Associate systems engineer
Data analysis manager
Senior sales manager
Team leader, customer success
Data engineering leader
Businessdevelopment
Senior buisness analyst
Software engineering director
Marketing leader
Vice president - technology
Css iii
Test automation engineer
Delivery leader
Sr manager channel sales
Programmer
Senior business systems analyst
It recruiter
Product designer lead
Senior director, communications
Sw engineer
Campaign manager
Client executive
Product marketing manager
Manager - strategy and planning
Engineering architect
Account ae
Cross-functional apprentice
Senior software engineer/tech lead
Database administrator (dba)
Reliability engineer
Component engineer
Technical solutions specialist
Senior director marketing
Operations director
Senior marketing operations manager
Enterprise architect
Cad engineer
Collaboration architect
Virtual account manager
Network consuling engineer
Electrical product engineer
Database administrator
Software engineer 2
Test development engineer
Softeware engineer
Mechanical design engineer
Senior learning partner
Client operations delivery manager
Tech support
Senior hardware design engineer
Business strategy manager
Talent acquisition
Back office
Vendor analyst
Services sales specialist
English teacher
Project specialist
Terrirory manager
Sde2 backend
Ux engineer
Senior business operations manager
Escalation engineer
Tecnhnical lead
Senior software development manager
Lead delivery consultant
It architect
Cybersecurity analyst
Partner marketing coordinator
Software test engineer trainee
Senior technical marketing engineer
Senior oracle ebs consultant
Finance controller
Bdr
Sangeeta gupta
Project manger
Account assistant
Data analyst, supply chain analytics
Technical product manager
Regional director
Cybersecurity sales specialist
Sales team leader
Global planning
Graduate apprentice trainee
Finance director
Security partner account manager
Channel solutions engineer
Creative director
Softwaere engineer
Sr program manager iii
Senior machine learning engineer
Rrs
Solutions consultant
Engineering
Mobility specialist
Senior customer experience manager
Sr. solution architect
Event manager
Cloud sales specialist
Legal counsel
Technology leader
Htts-customer support engineer at cisco
Client services support specialist
Inventory analyst
Technology analyst
Director, regional sales
Project coordinator
Technical leader i
Head of product marketing
Customer contract manager
User experience researcher
Electrical engineer (hardware systems)
Senior wireless engineer
Salesforce developer
Manager pmo
Senior security consulting engineer
Ux architect
Contnet writer
Assistant mnager
Sales and partnerships
Design verification engineer
Regional account manager
Associate director
Isr- inside sales representative
Seniors software engineer
Sotware engineer
Group leader
Supply chain manager
Business analyst manager
It business systems analyst
Sysyem engineer
Ux design intern
Business analyst intern
Principal consultant
Accounting manager
Sr. ux researcher
Technical account manager
Accounts manager
Cybersecurity partner specialist
Learning content developer
Senior manager, technical marketing
Technical sales intern
Marketer
Software development engineer (sde) -1
Hr analyst
Hr
Lead data scientist
Sr. product designer
Senior technical consultant
Senior analyst relations manager
Pre silicon verification engineer
Technician
Sr. marketing manager
Financial controller
.net developer
Success programs manager
Engineering technical leader
Director, operations
Human resources manager
Sem
Team leader - engineering
Sales enablement program manager
Communication manager
Hw engineer
Hr manager
Data center product sales specialist
Software engineer  3
Service delivery executive
Sr. tpm
Ccm
Product engineer
It senior project manager
Vice president
Am
Technical leader ii
Techincal leader
Public relations specialist
Ux leader
Senior systems engineering manager
High touch operations manager
Senior recruiter
Java software developer
Asm (area sales manager)
Senior corporate counsel
Software engineers
Principal solutions architect
Service selling manager
Principal solution engineer
Project manager/scrum master
Senior research analyst
Manager, customer success
Leader product management
Sde-2 backend
Qa manager
Senior grc consultant
Collaboration engineer
Client services manager
Full stack developer
Strategic sales engineer manager
Senior presales manager
Events director
Tss
Strategy manager
Sr sales development manager
Senior developer
Software developer - trainee
Premium services
Sr manager human resources
Consulting engineer - software
Account executive smb
Revenue operations manager
Sales bdm
Sde4
Virtual sales specialist
Senior people partner
Nde engineer
Vam - virtual account manager
Major account manager
Security sales specialist
Sr. sre engineer
Fw engineer
Employee engagement specialist
Cisco associate sales representative
Asic verification engineer
Sales, business development manager
Services sales executive
Senior technical recruiter
Optical network engineer
Software engineer l1
Senior accountant
Delivery manager
Lead ux designer
Optical design engineer
Associate sales representative
Senior technical support engineer
Principle software engineer
Product safety test engineer
Strategy planning
Sde-4
Technologist
Instructional designer
Business value consultant
Manager of technical operations
Mechanical engineer
Tme/qa/transcriptionist
Logistics project manager
Wireless software engineer
Bi analyst
Auxiliary police officer (enforcement)
Software eginner
Sales director
Sr bdm
Technical consultanting engineer
Senior finance manager
Senior sales engineer
Leader, strategy and planning
Trade compliance specialist
Collaboration sales specialist
Senior database administrator (dba)
Global leader
It engineering
Software engineering intern
Virtual associate sales representative
Data science
Product quality engineer
Sr. front end developer
Supply chain program manager
Senior sales director
Solutions architect senior tsa
Network solution architect
Director data and analytics
Director business operations
Director, strategy and planning
Systems architect iv
Graduate student
Learning consultant
Technical leader user experience/user interface
Benefits consultant
Ui/ux designer
Customer relationship manager - sinu
Threat researcher
Senior competitive intelligence analyst
Customer experience project manager
Civil enginerring
Senior business development manager
Vertrieb
Specialist
R&d
Senior asset manager
Install base analyst
Business systems analysis manager
Systems engineering manager
Software manager
General manager
Professional consulting engineer
Global commodity manager
Logic design engineer
Sales operations analyst
Sr. director, engineering
Field marketing manager
Compensation analyst

In [19]:
# capitalizing the dataset
def capital_letter(df, col="Job Title"):
    df[[col]] = df[[col]].apply(lambda c: c.str.title())
    return df
capital_letter(CisRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,"Manager, Network Services",4.0,2015-03-13,"Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\r\n\r\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time (even the time outside of work) but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\r\n\r\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\r\n\r\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs."
1,Systems Engineer,3.0,2025-08-05,"Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of ground-level realities."
2,Strategy & Planning,4.0,2025-07-08,Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company (~80K employees). Things can get lost."
3,Human Resources,3.0,2025-08-12,"Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of lay-offs are destabilizing
4,Solutions Engineer,4.0,2025-08-10,"Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment
...,...,...,...,...,...,...
28087,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28088,Anonymous Employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure
28089,Anonymous Employee,1.0,2018-02-24,"Former employee, more than 1 year",Good working experience in cisco,no no no no no
28090,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28091,Anonymous Employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure

In [20]:
# changing the datatype of the time column
def time_change(df, col="Time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(CisRev)

In [21]:
CisRev.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28072 entries, 0 to 28091
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Job Title   28072 non-null  object
 1   Job Rating  28072 non-null  float64
 2   Time        28072 non-null  datetime64[ns]
 3   Job Status  28072 non-null  object
 4   Pros        28072 non-null  object
 5   Cons        28072 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 1.5+ MB

In [22]:
# rename detail
CisRev["Job Title"] = CisRev["Job Title"].replace({
    "Tdr Trade Development Representative":"(Tdr) Trade Development Representative",
    "Qaengineer":"Qa Engineer","Çustomer Service Representative":"Customer Service Representative",
    "Sofatware Engineer":"Software Engineer","Softeware Enginee":"Software Engineer",
    "Ftth Engineer":"Ftth (Fiber to the Home) Engineer","Software qa engineer":"Software Qa Engineer",
    "Tdr":"Trade Development Representative","Itspecialist":"IT Specialist",
    "KEY NOT FOUND: jobLine.seasonal-current":"(Job) seasonal_current","I T Analyst":"IT Analyst",
    "It Specialist":"IT Specialist"
    })

In [23]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(CisRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,"Manager, Network Services",4.0,2015-03-13,"Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\n\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time even the time outside of work but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\n\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\n\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs."
1,Systems Engineer,3.0,2025-08-05,"Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of groundlevel realities."
2,Strategy & Planning,4.0,2025-07-08,Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company ~80K employees. Things can get lost."
3,Human Resources,3.0,2025-08-12,"Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of layoffs are destabilizing
4,Solutions Engineer,4.0,2025-08-10,"Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment
...,...,...,...,...,...,...
28087,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28088,Anonymous Employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure
28089,Anonymous Employee,1.0,2018-02-24,"Former employee, more than 1 year",Good working experience in cisco,no no no no no
28090,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28091,Anonymous Employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure

In [24]:
hiphen = CisRev[CisRev["Pros"].str.startswith("-")]
hiphen

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [25]:
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(CisRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,"Manager, Network Services",4.0,2015-03-13,"Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\n\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time even the time outside of work but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\n\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\n\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs."
1,Systems Engineer,3.0,2025-08-05,"Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of groundlevel realities."
2,Strategy & Planning,4.0,2025-07-08,Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company ~80K employees. Things can get lost."
3,Human Resources,3.0,2025-08-12,"Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of layoffs are destabilizing
4,Solutions Engineer,4.0,2025-08-10,"Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment
...,...,...,...,...,...,...
28087,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28088,Anonymous Employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure
28089,Anonymous Employee,1.0,2018-02-24,"Former employee, more than 1 year",Good working experience in cisco,no no no no no
28090,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect
28091,Anonymous Employee,1.0,2022-02-28,Current employee,No prod is offered here,Everything is cons for sure

In [31]:
# check duplicate sum
def checkDuplicateSum(df):
    Total = df.duplicated().sum()
    print(f"Sum of Duplicate_Values = {Total}")
checkDuplicateSum(CisRev)

Sum of Duplicate_Values = 0

In [27]:
# drop_duplicate
def DropDuplicate(df):
    df.drop_duplicates(subset=["Job Title"], inplace=True)
    return df
DropDuplicate(CisRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,"Manager, Network Services",4.0,2015-03-13,"Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\n\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time even the time outside of work but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\n\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\n\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs."
1,Systems Engineer,3.0,2025-08-05,"Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of groundlevel realities."
2,Strategy & Planning,4.0,2025-07-08,Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company ~80K employees. Things can get lost."
3,Human Resources,3.0,2025-08-12,"Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of layoffs are destabilizing
4,Solutions Engineer,4.0,2025-08-10,"Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment
...,...,...,...,...,...,...
28061,Devop Engineer,1.0,2022-02-24,Current employee,Teck stack is good,Management is bad and no clear communication
28063,Crs,1.0,2019-06-22,Former employee,Money good raises often bouns,Work hard nobody care no boss
28064,Hpc Engineer,1.0,2020-07-02,"Former employee, more than 1 year","Free drinks, free pizza, nice colleagues","Too much pressure, fast paced business"
28071,Loss Prevention,1.0,2021-09-07,Former employee,Idk not super good enough.,Idk what to say about this.
28081,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect

In [28]:
CisRev[CisRev["Cons"].str.contains("\r")]

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [29]:
CisRev.insert(6,"Company_Name", "Cisco")

In [ ]:
CisRev.set_index("Job Title", inplace=True)

In [34]:
CisRev.reset_index(inplace=True)

In [35]:
CisRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons,Company_Name
0,"Manager, Network Services",4.0,2015-03-13,"Former employee, more than 3 years","I decided to wait almost a year after leaving the company before posting a review. The primary reason being is that when you decide to leave an organization it is usually because there is something there that isn't aligning with you or what you want anymore however, the grass is not always greener someplace else. This has been my experience. In fact, the appreciation I have for the company has grown so much in my time away that I would really like to return.\n\nThe company truly believes on promoting within and as an employee you are encouraged to grow your career within the organization and learn new skills by taking different positions. Benefits are excellent. Cisco is the industry leader for networking and now cloud. It is sometimes easy to forget that on the daily grind but you are working for the company that everyone looks to for network and infrastructure standards. Culture within the business units managing product lines give you a lot of freedom to be innovative and creative in your approach to your role. In most cases you are given a fair amount of autonomy and control over how you do your job provided that it aligns with the strategic objectives. Benefits, 401k match, RSUs and ESPP are amazing. And while the salaries aren't the top of the industry, they are above market and pretty competitive.","Cisco can be a machine. There isn't an overt demand for all of your time even the time outside of work but more of a subtle, slight encouragement to always be on. If you are not careful, you will live, sleep and eat Cisco 24x7. Don't get me wrong, this is 100% a choice and if you are aware of this subtlety in the culture it is very easy to set appropriate boundaries that will be respected by the company and leadership team.\n\nIf you don't like where you are in Cisco or what you are working on, give it 6 months because you will be reorg'd. While it is sometimes necessary to realign the company to meet competitive threats or market demands, reorganizing the company once a year is excessive and tends to create a distrusting environment for the rank and file which makes being a leader in the organize challenging. There is a loss of momentum and motivation that occurs a few months before and a few months after reorgs so this leaves the company being effective at delivery and execution only about 70% of the time.\n\nWhile Cisco attracts some bright, motivated people the truth of the matter is you are either cut out for the company and its culture or you're not. If you aren't it will be painfully obvious to you and those around you. Sadly as a leader it is hard to cut dead weight from the team and the only really accepted way is via layoffs, which is why the company reorgs once a year despite the company line about the reorgs.",Cisco
1,Systems Engineer,3.0,2025-08-05,"Former employee, more than 8 years","Overall, Cisco is a good place to work. As a senior systems engineer, I had the opportunity to collaborate with many thoughtful, capable, and genuine people across teams—from engineering and test to compliance, product management, executives, manufacturing, and TAC. The company encourages technical excellence, and there are pockets of genuinely supportive leadership. That said, the experience can vary dramatically depending on your org and manager, and some managers operate with impunity despite repeated and serious concerns.","If you end up with a manager who manipulates systems and relationships—undermining direct reports, peers, and even superiors to secure promotion or survival—the only real option is to leave. Don’t expect HR, ER, or internal processes to intervene meaningfully, even when misconduct is extensively documented and corroborated by multiple witnesses. This toxic behavior often goes unpunished and actively rewarded—with visibility, advancement, incentives, and plenty of opportunities to retaliate against those who speak up.\n\nCisco has trimmed HR/ER and internal enforcement functions so much that the cultural messaging from the Cisco People Office feels performative and aspirational rather than reflective of groundlevel realities.",Cisco
2,Strategy & Planning,4.0,2025-07-08,Former employee,Grow and learn with some genuinely smart and capable folks\nPrestige of working for the market leader\nStays innovative through some great external acquisitions\nGood internal tools and work resources\nOverall a supportive company culture,"The 'old guard' of Cisco can be quite bureaucratic and political. You will discover that more innovative/more approachable/results driven leadership comes in from external acquisitions rather than long time senior employees.\n\nAfter a certain point, growth heavily hinges on somebody senior 'sponsoring' you. Ergo, high performance on its own will not open doors at the upper middle to senior manager level.\n\nIt's a big company ~80K employees. Things can get lost.",Cisco
3,Human Resources,3.0,2025-08-12,"Current employee, more than 3 years",People are collaborative. Nice culture.,Frequency of layoffs are destabilizing,Cisco
4,Solutions Engineer,4.0,2025-08-10,"Current employee, more than 5 years",Great culture for the most part. I know it mainly depends on your team but most leaders aren’t terrible.,It sense like the powers that be don’t understand advertising and public sentiment,Cisco
...,...,...,...,...,...,...,...
3414,Devop Engineer,1.0,2022-02-24,Current employee,Teck stack is good,Management is bad and no clear communication,Cisco
3415,Crs,1.0,2019-06-22,Former employee,Money good raises often bouns,Work hard nobody care no boss,Cisco
3416,Hpc Engineer,1.0,2020-07-02,"Former employee, more than 1 year","Free drinks, free pizza, nice colleagues","Too much pressure, fast paced business",Cisco
3417,Loss Prevention,1.0,2021-09-07,Former employee,Idk not super good enough.,Idk what to say about this.,Cisco
3418,Professional Services Management,1.0,2021-09-26,Former employee,lay back and stable role,lack of innovation and disconnect,Cisco

In [ ]:
Path = ""

In [ ]:
CisRev.to_csv(Path, in)