In [1]:
import pandas as pd
import numpy as np

In [3]:
Co_opRev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/Co-operative_bankReviews.csv")

In [4]:
# EDA on the data
def display(x):
    """This function returns a 
    summary of the dataset"""
    
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(Co_opRev)

Displays the rows and columns in the dataset
============================================
Rows: 320 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                                   Job Title  Job Ratings          time  \
0                        Anonymous employee          4.0  May 28, 2025
1    Business development executive manager          4.0  Feb 27, 2024
2                        Operations manager          4.0   Mar 5, 2024
3                        Anonymous employee          3.0   Feb 1, 2017
4                                   Support          3.0   Jul 9, 2017
..                                      ...          ...           ...
315                                     Ict          3.0  Jul 15, 2015
316                      Anonymous employee          3.0   Jan 2, 2017
317                    Relationship manager          4.0  Jan 25, 2021
318                      Anonymous employee          3.0  Apr 28, 2021
319                             Bank teller          4.0   Sep 2, 2022

                                JobStatus  \
0                        Current employee
1                        Current employee
2                        Current employee
3    Current employee, more than 10 years
4                         Former employee
..                                    ...
315                       Former employee
316                      Current employee
317                       Former employee
318     Former employee, more than 1 year
319                       Former employee

                                                  Pros  \
0    Comprehensive Medical Cover\nPension\nLoan fac...
1    Good salary, salary increment every year.\nDif...
2    Offers a challenging working environment for t...
3    They have good loan facilities for their staff...
4    Good pay,  on the job training , exposure to a...
..                                                 ...
315          Getting to interact with different people
316                          It was the bank of choice
317                            Good employer as at now
318                        Good environment to work in
319                   Great team spirit over prayerful

                                                  Cons
0    Some targets set are not smart\nLoan options n...
1       Long working hours with only few days of leave
2                         Slow growth and too engaging
3    Top management get most of the perks e.g their...
4    workload, low upward career  mobility, can hit...
..                                                 ...
315                      No transport for sales people
316                      Time consuming and pressure .
317                        Find out for yourself later
318  Limited opportunities for growth within the co...
319          Tribalism unclear growth and fear culture

[320 rows x 6 columns]>

Returns the information in more details
============================================
       Job Ratings
count   320.000000
mean      3.637500
std       1.044391
min       1.000000
25%       3.000000
50%       4.000000
75%       5.000000
max       5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           20
dtype: int64

In [5]:
# display the whole column content
pd.set_option("display.max_colwidth", None)

In [6]:
# The first 3 elements
print("Top 5 elements")
print("=============================")
print()
Co_opRev.head()

Top 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Anonymous employee,4.0,"May 28, 2025",Current employee,Comprehensive Medical Cover\nPension\nLoan facilities at a competitive rate,Some targets set are not smart\nLoan options not flexible
1,Business development executive manager,4.0,"Feb 27, 2024",Current employee,"Good salary, salary increment every year.\nDifferent types of loans available to staff.",Long working hours with only few days of leave
2,Operations manager,4.0,"Mar 5, 2024",Current employee,Offers a challenging working environment for those in operations,Slow growth and too engaging
3,Anonymous employee,3.0,"Feb 1, 2017","Current employee, more than 10 years",They have good loan facilities for their staff. Benefits such as and leave allowance are reasonable.,"Top management get most of the perks e.g their bonuses are not based on performance but on the Relation you have with the MD, Targets set for lower staff are shifted just before the year ends thus destabilizing your end-year performance appraisal, Target given are not smart and very unrealistic etc"
4,Support,3.0,"Jul 9, 2017",Former employee,"Good pay, on the job training , exposure to a variety of systems, leave days","workload, low upward career mobility, can hit the ceiling in pay raise after a reaching a certain level"

In [7]:
# The last 3 elements
print("last 5 elements")
print("=============================")
print()
Co_opRev.tail()

last 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
315,Ict,3.0,"Jul 15, 2015",Former employee,Getting to interact with different people,No transport for sales people
316,Anonymous employee,3.0,"Jan 2, 2017",Current employee,It was the bank of choice,Time consuming and pressure .
317,Relationship manager,4.0,"Jan 25, 2021",Former employee,Good employer as at now,Find out for yourself later
318,Anonymous employee,3.0,"Apr 28, 2021","Former employee, more than 1 year",Good environment to work in,Limited opportunities for growth within the company
319,Bank teller,4.0,"Sep 2, 2022",Former employee,Great team spirit over prayerful,Tribalism unclear growth and fear culture

In [8]:
# The random 3 elements
print("Random 5 elements")
print("=============================")
print()
Co_opRev.sample(5)

Random 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
231,Risk manager,5.0,"Feb 24, 2021","Former employee, more than 5 years",It a good organization and career growth,Some frequent change of job may be distructive
187,Sales associate,3.0,"Aug 19, 2021","Current employee, more than 1 year",good salary and one might get a bonus. STAFF LOANS ARE ALSO AVAILABLE AT GOOD RATES,takes alot of persnal time because you have to work\ninternal pressure but rewardings\ntranfers to differnt locations
149,Contact centre agent,3.0,"Dec 20, 2022","Former employee, more than 1 year",Good salary for entry level job,High targets too many working hours
239,Anonymous employee,4.0,"Jul 24, 2021","Former employee, more than 8 years",Great medical insurance. Some honest colleagues,"Discrimination, unnecessary rigidity. Bias in promotions"
67,Credit analyst,3.0,"Aug 10, 2024","Former employee, more than 3 years","Good bonus, medical and staff loans. Wonderful colleagues","No flexible hours or WFH, government like bureaucracy and no room for growth."

In [9]:
# loops over the whole column 1
for index,col in enumerate (Co_opRev["Job Title"]):
    print(index, col)

0 Anonymous employee
1 Business development executive manager
2 Operations manager
3 Anonymous employee
4 Support
5 Legal officer
6 Underwriter
7 Project manager
8 Small business banker
9 Business analyst/business development
10 Atm manager
11 Business analyst
12 Relationship banker
13 Contact center representative
14 Business banker
15 Finance manager
16 Ops manager
17 Client service representative
18 Data analyst
19 Customer service
20 Atm manager
21 Business analyst
22 Relationship banker
23 Contact center representative
24 Business banker
25 Finance manager
26 Ops manager
27 Client service representative
28 Data analyst
29 Customer service
30 Locked job title
31 Locked job title
32 Locked job title
33 Locked job title
34 Locked job title
35 Locked job title
36 Locked job title
37 Locked job title
38 Locked job title
39 Locked job title
40 Locked job title
41 Locked job title
42 Locked job title
43 Locked job title
44 Locked job title
45 Locked job title
46 Locked job title
47 Locked job title
48 Locked job title
49 Locked job title
50 Sourcing
51 Card and e-channels officer
52 Personal banker
53 Business intelligence developer
54 Customer relationship manager
55 Relationship manager
56 Relationship manager
57 It project manager
58 Cash officer
59 Finance business partner
60 Bank teller
61 Bank teller
62 Business banker
63 Relationship manager
64 Sales and service advisor
65 Relationship manager
66 Team assistant
67 Credit analyst
68 Anonymous employee
69 Sales executive
70 E-channels officer
71 Product manager
72 Asr (account service representative )
73 Personal banker
74 Customer experience executive
75 Enterprise support engineer
76 Relationship manager
77 Head trade finance services
78 Operations manager
79 Business development banker
80 Ssa clerk
81 Banker
82 Sales executive
83 Customer service representative
84 Customer service representative
85 It systems administrator
86 Reconciliation officer
87 Graduate clerk
88 Manager
89 Business banker
90 Personal banker
91 Relationship manager
92 Dealer
93 Sales and service advisor
94 Business development manager
95 Relationship manager
96 Agent
97 Deli clerk
98 Relationship manager
99 Software engineer
100 Intern
101 Business development manager
102 Credit officer
103 Relationship manager special assets
104 Personal banker
105 Internal auditor
106 Project manager
107 Ict manager
108 Contact center representative
109 Sales representative
110 Relationship banker
111 Bank teller
112 Business process analyst
113 Ict project manager
114 Credt analyst
115 Bank teller
116 Business process analyst
117 Business analyst (financial analyst)
118 Full stack developer
119 Telemarketer
120 Customer service manager
121 Business development manager
122 Customer service representative
123 Executive assistant
124 Operations manager
125 Consultant
126 Product manager
127 Executive customer experience officer
128 Relationship manager
129 Software developer
130 Relationships manager
131 Solutions architect
132 Sales and service advisor
133 Banker
134 Head of unit
135 Fixed income trader
136 Anonymous employee
137 Project manager
138 Branch manager
139 Officer
140 Product manager
141 Systems analyst
142 Bank teller
143 App security engineer
144 Relationship manager
145 Sales and service advisor
146 Operations manager
147 Project manager
148 Software engineer
149 Contact centre agent
150 Graduate clerk
151 Anonymous employee
152 Anonymous employee
153 It risk and control manager
154 Anonymous employee
155 Graduate clerk
156 Branch manager
157 Relationship manager
158 Sdo - service desk operator
159 Audit analyst
160 Business banker
161 Branch manager
162 Customerservice representative
163 Anonymous employee
164 Customer service representative
165 Product manager
166 Anonymous employee
167 Supervisor
168 Manager
169 Business banker
170 Anonymous employee
171 Software developer
172 Branch manager
173 Enterprise business analyst
174 Anonymous employee
175 Anonymous employee
176 It support specialist
177 Procurement manager
178 Bank teller
179 Anonymous employee
180 Graduate clerk
181 Business banker
182 Relationship manager
183 Personal banker
184 Treasurer
185 Audit manager
186 Anonymous employee
187 Sales associate
188 Graduate clerk
189 It support
190 Small business banker
191 Anonymous employee
192 Anonymous employee
193 Graduate clerk
194 Software engineer
195 Anonymous employee
196 Branch manager
197 Graduate clerk
198 Anonymous employee
199 Ict security analyst
200 Head of ict & cyber security
201 Anonymous employee
202 Branch manager
203 Credit officer
204 Anonymous employee
205 Customer care
206 Service desk officer
207 Relationship manager
208 Anonymous employee
209 Business development
210 Remedial relationship manager
211 Analyst
212 Sales representative
213 Client support specialist
214 Direct sales representative
215 Sales service advisor
216 Small/medium business account representative
217 Software engineer
218 Operations
219 Mobile expert
220 Anonymous employee
221 Manager
222 Anonymous employee
223 Anonymous employee
224 Business banker
225 Solution architect
226 Infrastructure specialist
227 Personal%2fbusiness banker
228 Sales executive/officer
229 Anonymous employee
230 Supervisor
231 Risk manager
232 Anonymous employee
233 Anonymous employee
234 Credit manager
235 Graduate clerk
236 Small business banker
237 Section head
238 Branch manager
239 Anonymous employee
240 Anonymous employee
241 Service desk officer
242 Manager, operations
243 Clerk/teller
244 Senior software developer
245 Sales and services advisor
246 Bancassurance officer
247 Software developer
248 Agent
249 Relationship manager
250 Internal auditor - it
251 Operations supervisor
252 Anonymous employee
253 Bank teller
254 Graduate clerk
255 Credit analyst
256 Relationship officer
257 Project manager
258 Anonymous employee
259 Anonymous employee
260 Software developer
261 Business banker
262 Bancassurance sales officer
263 Relationship manager
264 Bank teller
265 Data analytics
266 Financial accountant
267 Relationship officer
268 Quality and assurance analyst
269 Accounts service representative
270 Risk manager
271 Accountant
272 Head of assets
273 Bank teller
274 Personal banker
275 Accountant
276 Computer sales associate
277 Help desk officer
278 Business banker
279 Hr- consultant
280 Credit approver
281 Anonymous employee
282 Compliance analyst
283 Officer
284 Contact centre agent
285 Anonymous employee
286 Finance and administration assistant
287 Relationship manager
288 Anonymous employee
289 Backend developer
290 Sales executive
291 Bancassurance officer
292 Risk analyst
293 Customer service representative
294 Manager
295 Anonymous employee
296 Anonymous employee
297 Anonymous employee
298 Project manager
299 Anonymous employee
300 Project manager
301 Manager
302 Business development
303 Relationship manager
304 Anonymous employee
305 Anonymous employee
306 Anonymous employee
307 Ict service desk analyst
308 Senior manager
309 Bancassurance finance & support manager
310 Graduate clerk
311 Devops engineer
312 Sales and service advisor
313 Graduate clerk
314 Personal banker
315 Ict
316 Anonymous employee
317 Relationship manager
318 Anonymous employee
319 Bank teller

In [10]:
Co_opRev.iloc[30:49]

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
30,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
31,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
32,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
33,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
34,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
35,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
36,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
37,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
38,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
39,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
40,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
41,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
42,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
43,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
44,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
45,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
46,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
47,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
48,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN

In [11]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns 
    total null values on the dataset"""
    print(df.isna().sum())
null_values(Co_opRev)

Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           20
dtype: int64

In [13]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the 
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(Co_opRev)
# CisRev.dropna(inplace=True)

In [14]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(Co_opRev)

In [15]:
# Rename the headers
Co_opRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [18]:
# pd.set_option("display.Max_rows", None)
pd.reset_option("display.Max_rows", None)

In [19]:
Co_opRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Anonymous employee,4.0,2025-05-28,Current employee,Comprehensive Medical Cover\nPension\nLoan facilities at a competitive rate,Some targets set are not smart\nLoan options not flexible
1,Business development executive manager,4.0,2024-02-27,Current employee,"Good salary, salary increment every year.\nDifferent types of loans available to staff.",Long working hours with only few days of leave
2,Operations manager,4.0,2024-03-05,Current employee,Offers a challenging working environment for those in operations,Slow growth and too engaging
3,Anonymous employee,3.0,2017-02-01,"Current employee, more than 10 years",They have good loan facilities for their staff. Benefits such as and leave allowance are reasonable.,"Top management get most of the perks e.g their bonuses are not based on performance but on the Relation you have with the MD, Targets set for lower staff are shifted just before the year ends thus destabilizing your end-year performance appraisal, Target given are not smart and very unrealistic etc"
4,Support,3.0,2017-07-09,Former employee,"Good pay, on the job training , exposure to a variety of systems, leave days","workload, low upward career mobility, can hit the ceiling in pay raise after a reaching a certain level"
...,...,...,...,...,...,...
315,Ict,3.0,2015-07-15,Former employee,Getting to interact with different people,No transport for sales people
316,Anonymous employee,3.0,2017-01-02,Current employee,It was the bank of choice,Time consuming and pressure .
317,Relationship manager,4.0,2021-01-25,Former employee,Good employer as at now,Find out for yourself later
318,Anonymous employee,3.0,2021-04-28,"Former employee, more than 1 year",Good environment to work in,Limited opportunities for growth within the company
319,Bank teller,4.0,2022-09-02,Former employee,Great team spirit over prayerful,Tribalism unclear growth and fear culture

In [20]:
Co_opRev.info()

<class 'pandas.core.frame.DataFrame'>
Index: 300 entries, 0 to 319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Job Title   300 non-null    object
 1   Job Rating  300 non-null    float64
 2   Time        300 non-null    datetime64[ns]
 3   Job Status  300 non-null    object
 4   Pros        300 non-null    object
 5   Cons        300 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 16.4+ KB

In [21]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(Co_opRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Anonymous employee,4.0,2025-05-28,Current employee,Comprehensive Medical Cover\nPension\nLoan facilities at a competitive rate,Some targets set are not smart\nLoan options not flexible
1,Business development executive manager,4.0,2024-02-27,Current employee,"Good salary, salary increment every year.\nDifferent types of loans available to staff.",Long working hours with only few days of leave
2,Operations manager,4.0,2024-03-05,Current employee,Offers a challenging working environment for those in operations,Slow growth and too engaging
3,Anonymous employee,3.0,2017-02-01,"Current employee, more than 10 years",They have good loan facilities for their staff. Benefits such as and leave allowance are reasonable.,"Top management get most of the perks e.g their bonuses are not based on performance but on the Relation you have with the MD, Targets set for lower staff are shifted just before the year ends thus destabilizing your endyear performance appraisal, Target given are not smart and very unrealistic etc"
4,Support,3.0,2017-07-09,Former employee,"Good pay, on the job training , exposure to a variety of systems, leave days","workload, low upward career mobility, can hit the ceiling in pay raise after a reaching a certain level"
...,...,...,...,...,...,...
315,Ict,3.0,2015-07-15,Former employee,Getting to interact with different people,No transport for sales people
316,Anonymous employee,3.0,2017-01-02,Current employee,It was the bank of choice,Time consuming and pressure .
317,Relationship manager,4.0,2021-01-25,Former employee,Good employer as at now,Find out for yourself later
318,Anonymous employee,3.0,2021-04-28,"Former employee, more than 1 year",Good environment to work in,Limited opportunities for growth within the company
319,Bank teller,4.0,2022-09-02,Former employee,Great team spirit over prayerful,Tribalism unclear growth and fear culture

In [22]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace("\n", "", regex=True))
    return df
remove_char(Co_opRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Anonymous employee,4.0,2025-05-28,Current employee,Comprehensive Medical CoverPensionLoan facilities at a competitive rate,Some targets set are not smartLoan options not flexible
1,Business development executive manager,4.0,2024-02-27,Current employee,"Good salary, salary increment every year.Different types of loans available to staff.",Long working hours with only few days of leave
2,Operations manager,4.0,2024-03-05,Current employee,Offers a challenging working environment for those in operations,Slow growth and too engaging
3,Anonymous employee,3.0,2017-02-01,"Current employee, more than 10 years",They have good loan facilities for their staff. Benefits such as and leave allowance are reasonable.,"Top management get most of the perks e.g their bonuses are not based on performance but on the Relation you have with the MD, Targets set for lower staff are shifted just before the year ends thus destabilizing your endyear performance appraisal, Target given are not smart and very unrealistic etc"
4,Support,3.0,2017-07-09,Former employee,"Good pay, on the job training , exposure to a variety of systems, leave days","workload, low upward career mobility, can hit the ceiling in pay raise after a reaching a certain level"
...,...,...,...,...,...,...
315,Ict,3.0,2015-07-15,Former employee,Getting to interact with different people,No transport for sales people
316,Anonymous employee,3.0,2017-01-02,Current employee,It was the bank of choice,Time consuming and pressure .
317,Relationship manager,4.0,2021-01-25,Former employee,Good employer as at now,Find out for yourself later
318,Anonymous employee,3.0,2021-04-28,"Former employee, more than 1 year",Good environment to work in,Limited opportunities for growth within the company
319,Bank teller,4.0,2022-09-02,Former employee,Great team spirit over prayerful,Tribalism unclear growth and fear culture

In [23]:
hiphen = Co_opRev[Co_opRev["Cons"].str.startswith("-")]
hiphen

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [24]:
pd.set_option("display.max_rows",None)
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(Co_opRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Anonymous employee,4.0,2025-05-28,Current employee,Comprehensive Medical CoverPensionLoan facilities at a competitive rate,Some targets set are not smartLoan options not flexible
1,Business development executive manager,4.0,2024-02-27,Current employee,"Good salary, salary increment every year.Different types of loans available to staff.",Long working hours with only few days of leave
2,Operations manager,4.0,2024-03-05,Current employee,Offers a challenging working environment for those in operations,Slow growth and too engaging
3,Anonymous employee,3.0,2017-02-01,"Current employee, more than 10 years",They have good loan facilities for their staff. Benefits such as and leave allowance are reasonable.,"Top management get most of the perks e.g their bonuses are not based on performance but on the Relation you have with the MD, Targets set for lower staff are shifted just before the year ends thus destabilizing your endyear performance appraisal, Target given are not smart and very unrealistic etc"
4,Support,3.0,2017-07-09,Former employee,"Good pay, on the job training , exposure to a variety of systems, leave days","workload, low upward career mobility, can hit the ceiling in pay raise after a reaching a certain level"
5,Legal officer,3.0,2021-01-16,"Current employee, more than 1 year",Broad commercial legal experienceGood benefits like insurance and bonuses,"Fixed culture mindset, government like"
6,Underwriter,2.0,2025-08-10,"Former employee, more than 5 years",Feels like family in a lot of ways,Very challenging to grow at the company
7,Project manager,3.0,2025-08-07,"Current employee, more than 3 years",Excellent credit facilities for staff Numerous internal opportunities for lateral growth,Rigid in terms of adoption of solutions Challenging organizational culture
8,Small business banker,4.0,2025-07-24,"Former employee, more than 8 years",Offer good salary packages for borth entry grades and expert grades,Bonuses are not commensurate to companies earnings
9,Business analyst/business development,5.0,2025-06-06,"Former employee, more than 10 years","1. Open door policies, great management and worklife balance: depending on the department, 2.Great HR support including staff wellness programs, and opportunities for personal growth.3. Available opportunities for career growth.4. Benefits such as medical cover, insurance cover, annual bonuses based on performanceand grade, pensionable pay.5. The greatest CEO.","1. There are variations in management and leadership skills including communication, support and opportunities depending on the department.2. Annual salary reviews would be slow depending on staff grades."
10,Atm manager,4.0,2025-07-05,"Former employee, less than 1 year",Good communication among team members Efficient handling of tasksTeam building activities,Working under pressure since you are expected to meet your targets.
11,Business analyst,5.0,2025-04-21,"Current employee, more than 10 years",Very good at training its staff with requisite courses,The upskilling may not come witha salary increment
12,Relationship banker,5.0,2025-04-08,"Current employee, more than 1 year","Great employer, great learning curve and exposure to the financial sector.",No cons with the current structure.
13,Contact center representative,3.0,2025-04-11,"Current employee, more than 8 years","Flexible working hours , medical cover & yearly bonus",Nepotism and favoirism and unfair appraisals
14,Business banker,4.0,2025-03-10,"Former employee, more than 5 years",good employer with good salary,not seen any cons on employment
15,Finance manager,4.0,2025-02-20,"Former employee, more than 5 years","Secure, pays well and good package","Internal audit, leave over weekend will take 0.5 days"
16,Ops manager,5.0,2025-02-11,"Former employee, more than 1 year",Good benefits salary and job security,Clearly defined growth prospects for all levels.
17,Client service representative,3.0,2025-02-19,Current employee,The staff are well trained,Huge company not easy to grow
18,Data analyst,5.0,2025-02-12,"Former employee, more than 3 years",Great organization to work for,Management are like non touchables
19,Customer service,5.0,2025-01-07,"Current employee, more than 5 years",Good pay ease and bonuses,Non flexible work Hours .
20,Atm manager,4.0,2025-07-05,"Former employee, less than 1 year",Good communication among team members Efficient handling of tasksTeam building activities,Working under pressure since you are expected to meet your targets.
21,Business analyst,5.0,2025-04-21,"Current employee, more than 10 years",Very good at training its staff with requisite courses,The upskilling may not come witha salary increment
22,Relationship banker,5.0,2025-04-08,"Current employee, more than 1 year","Great employer, great learning curve and exposure to the financial sector.",No cons with the current structure.
23,Contact center representative,3.0,2025-04-11,"Current employee, more than 8 years","Flexible working hours , medical cover & yearly bonus",Nepotism and favoirism and unfair appraisals
24,Business banker,4.0,2025-03-10,"Former employee, more than 5 years",good employer with good salary,not seen any cons on employment
25,Finance manager,4.0,2025-02-20,"Former employee, more than 5 years","Secure, pays well and good package","Internal audit, leave over weekend will take 0.5 days"
26,Ops manager,5.0,2025-02-11,"Former employee, more than 1 year",Good benefits salary and job security,Clearly defined growth prospects for all levels.
27,Client service representative,3.0,2025-02-19,Current employee,The staff are well trained,Huge company not easy to grow
28,Data analyst,5.0,2025-02-12,"Former employee, more than 3 years",Great organization to work for,Management are like non touchables
29,Customer service,5.0,2025-01-07,"Current employee, more than 5 years",Good pay ease and bonuses,Non flexible work Hours .
50,Sourcing,5.0,2024-12-17,"Current employee, more than 1 year",Good working culture and experience.,Long working hours and targets
51,Card and e-channels officer,3.0,2024-11-27,"Former employee, more than 5 years","Challenging environment, skills on the job",Pressure for targetsEveryone is on the runcan get stuck in one position for long
52,Personal banker,3.0,2024-10-25,"Current employee, more than 3 years",Protocol is strictly adhered to.Fairly good salary scales,Limited growth opportunities especially when you don't boot lick.Toxic environment in most places brought on by toxic leadership.
53,Business intelligence developer,5.0,2024-12-06,"Current employee, more than 1 year","Well structured per role data engineer,data science,dm.qa",Missing big data in analytics
54,Customer relationship manager,4.0,2024-11-18,"Former employee, more than 1 year","Big company, Bonus, Job satisfaction, Good salary","High pressure, politics, bad managers, bad culture"
55,Relationship manager,5.0,2024-11-13,"Former employee, more than 8 years",Good employer who renumerates well based of performance,There's limited growth opportunity as promotions are hard to come by
56,Relationship manager,4.0,2024-11-20,"Former employee, more than 8 years","Good culture,growth,good insurance packages,friendly services,",Delayed promotion especially for internal hires.
57,It project manager,2.0,2024-10-30,Former employee,Salary increaments available based on performance,The company doesnot sponsor the staff for professional traininngs
58,Cash officer,3.0,2024-10-26,"Current employee, more than 5 years",Awesome employee benefits with bonus pay,You may stay in the same position for years
59,Finance business partner,2.0,2024-10-16,"Current employee, more than 10 years",Lots of staff benefits for employees,Unstructured promotions there is no guaranteed growth
60,Bank teller,2.0,2024-10-12,Current employee,Work dynamics changes continuously so you learn alot,Pressure which is constant and unnecessary
61,Bank teller,5.0,2024-10-04,"Current employee, more than 5 years",Opportunties for growth are immense.,Work life balance is limited
62,Business banker,3.0,2024-09-17,"Current employee, more than 1 year",Promotions are performance based and not based on who know who,There is a little bit on nepotism in the company
63,Relationship manager,4.0,2024-09-20,"Former employee, more than 8 years",Good working environment and good bonuses,Unfair and subjective appraisal system
64,Sales and service advisor,2.0,2024-10-03,"Former employee, more than 1 year",Fair payPension when confirmedMedical cover,Long hoursManagementSlow growth
65,Relationship manager,3.0,2024-09-25,"Former employee, more than 10 years",Integrity observed while working in the bank,No worklife balance in the work place
66,Team assistant,5.0,2024-09-16,"Current employee, more than 10 years",Medical. Bonus. Opportunities for growth.,"Overall, it is a good place to be"
67,Credit analyst,3.0,2024-08-10,"Former employee, more than 3 years","Good bonus, medical and staff loans. Wonderful colleagues","No flexible hours or WFH, government like bureaucracy and no room for growth."
68,Anonymous employee,4.0,2024-08-25,"Former employee, more than 3 years","Good pension and medical cover, great exposure to banking.",Strict bureaucratic culture that is engrained within those who have been there for long
69,Sales executive,3.0,2024-09-06,Former employee,Payment of salary on time,No much career growth progressively for men
70,E-channels officer,4.0,2024-09-03,Former employee,Company offers good compensation to employees,Micromanagement of employees is a downside.
71,Product manager,4.0,2024-08-21,Former employee,Benefits are great and the experience is diverse,Micro management which demotivates employees to do more and be more
72,Asr (account service representative ),3.0,2024-07-10,"Former employee, more than 3 years",Above average salary compared to similar banks,Long working hours and very limited breaks
73,Personal banker,4.0,2024-05-16,"Former employee, more than 5 years","Growth is performance based, the better you perform, the more chances you have to grow. Career growth is on a performance merit basis","Competition is very stiff across the board, both internally between staff and externally with other competitors"
74,Customer experience executive,3.0,2024-07-23,Former employee,Medical CoverAnnual BonusYearly IncrementTimely Salary Payment,Limited job rotation.Lack of an energetic corporate culture.Rigid working environment. Harsh on moms; more so single moms.
75,Enterprise support engineer,5.0,2024-07-23,"Former employee, more than 5 years",Pay bonusVery low interest rates for loan facilities as a staffGood pay,Official wear Suit and tie
76,Relationship manager,4.0,2024-07-29,Current employee,"Good pay, Medical Insurance, Networking",Regula meetings for KPI discussion
77,Head trade finance services,3.0,2024-06-04,"Former employee, more than 3 years",It has structures that make things work smoothly.,The religious aspects of the 'Kingdom' Bank can be very inhibitive and intoxicating to openminded and independentthinking staff.
78,Operations manager,4.0,2024-07-08,Former employee,Excellent experience through rigorous training,Heavy workload due to a big customer portfolio
79,Business development banker,5.0,2024-06-17,Former employee,Gained wide skills in sales and marketing.,Learned to work under pressure and multitasking.
80,Ssa clerk,5.0,2024-06-15,"Current employee, less than 1 year",Best lending rates and good working conditions,No negative traits so far
81,Banker,3.0,2024-05-27,Current employee,give me much needed jobstability,long working hours and perfomance pressure
82,Sales executive,4.0,2024-05-21,"Former employee, less than 1 year",High growth probability throught the ranks.,The pressure was too high for me.
83,Customer service representative,3.0,2024-05-05,"Current employee, more than 3 years",Good training and mentorshipGood salary to start,No work life balanceVery extended working hours
84,Customer service representative,5.0,2024-04-06,Former employee,i gained a wealth of experience and training towards the growth of my career,alot of pressure especially for a person with a young family
85,It systems administrator,4.0,2024-03-25,Former employee,Good place to nurture talent with vast exposure to a busy environment.,There are days you will have long working hours.
86,Reconciliation officer,3.0,2024-03-27,Current employee,Fairly stable job security and retirement plan,Unfair reward structures that are based more on expediency than experience and qualifications
87,Graduate clerk,3.0,2024-04-06,"Former employee, more than 1 year",Good pay and bonus when there's good profit,Lots of targets and little personal time
88,Manager,4.0,2024-04-14,"Former employee, more than 8 years",Best Hr practices and procedures,None so far but abit strict
89,Business banker,2.0,2023-12-29,"Current employee, more than 10 years","Loan benefits,Sacco membership for all staff",The management has one characteristic petty.Most mid level managers role is to make noise and they actually get higherpay and bonus that the person working.Implementation of policies is based on audit whose intention is to sack.Long working hours no work life balance
90,Personal banker,3.0,2024-03-10,Former employee,you can be employed on permanent terms,too many meetings especially online meetings
91,Relationship manager,2.0,2024-01-07,"Former employee, more than 8 years",Reasonable benefits although they have gotten worse over the years.,HR does very little for employeesCareer stagnation No/minimal Salary growthRigid management Top management enjoy most of the perks
92,Dealer,2.0,2024-02-08,Current employee,Bank so interdepartmental transfers are possible,"Bank, so compensation is limited"
93,Sales and service advisor,3.0,2024-01-10,"Former employee, more than 1 year","Good health benefit package that covers dental, optical.....",Long working hours and a lot of paper work
94,Business development manager,3.0,2023-12-04,Current employee,"Benefits, insurance, loans, sacco benefit and bonuses","Staff welfare, grapevine and an audit team that does not correct has an intention on always letting people go."
95,Relationship manager,3.0,2023-10-25,"Current employee, more than 5 years",Good starting point for new recruits,"Too much work pressure and workload No life ,work balance No equal pay on people under same role .Pay is according to whom you know and luck Moving upwards is slow"
96,Agent,4.0,2024-01-15,Current employee,Great nice and excellent employer,Nothing experienced was bad about it
97,Deli clerk,3.0,2024-01-09,Current employee,no worklife balance for junior staff,good remuneration packages for staff
98,Relationship manager,3.0,2024-01-06,Current employee,Good working environment for employees,Strict policies on their employees
99,Software engineer,3.0,2023-12-12,Current employee,thet offer mid salaries to their employees. good salaries if you do your research,long working hours especially for IT professionals
100,Intern,5.0,2023-12-14,"Former employee, less than 1 year",Great community of people and good management,Some intern work is quite repetitive
101,Business development manager,2.0,2023-11-19,"Former employee, more than 5 years",The company is stable financially. Not affected much by the market volatility.,Suffers from the big man syndrome. Senior manager do not articulate strategy and dictate tactics.
102,Credit officer,3.0,2023-11-24,"Former employee, more than 3 years",Good Medical BenefitsLow interest rate loans,Unattainable targets. Super long working hours
103,Relationship manager special assets,5.0,2023-11-11,Current employee,"Good package, flexible, stable, staff loans","High targets, not regional , lot of work, pip programs"
104,Personal banker,5.0,2023-11-20,"Current employee, more than 5 years",It's a good employer of choice,Not applicable not applicable not
105,Internal auditor,1.0,2023-12-03,"Former employee, more than 10 years",Deep experience acquired. Great team work experienced.,Heavy unachievable targets.Poor leadership that does not motivate staff.Inequality in pay structure.
106,Project manager,5.0,2023-10-22,"Current employee, more than 10 years",Great place to work learn a lot about the industry,I have not had a con
107,Ict manager,5.0,2023-10-17,Current employee,innovation agility transformation resilience teamwork,time hindrance's energy consuming politics stagnation
108,Contact center representative,4.0,2023-10-19,"Current employee, more than 8 years",Permanent job with good benefits,Work on weekends and public holidays
109,Sales representative,1.0,2023-12-08,"Former employee, less than 1 year",Great team and good working environment,Unrealistic targets that can never be achieved
110,Relationship banker,4.0,2023-09-04,"Former employee, more than 3 years",great working environment with friendly colleagues,working past normal working hours without compensation
111,Bank teller,5.0,2023-09-09,"Former employee, more than 8 years",One of the best employers in Kenya,Be ready to work hard
112,Business process analyst,4.0,2023-09-07,"Former employee, more than 5 years",Good benefits and opportunities for growth,Highly religious in office interaction
113,Ict project manager,4.0,2023-08-28,Current employee,"Dynamic, challenging and engaging work environment",Sometimes no clear responsibility mapping and proper planning with abstract goals.
114,Credt analyst,3.0,2023-08-17,Current employee,Great opportunities for personal development through free online courses.,Very rigid to change and too risk averse
115,Bank teller,4.0,2023-08-16,"Former employee, more than 1 year",Good salary Awesome benefits. Working hours,Too target oriented. Socially not conducive.
116,Business process analyst,3.0,2023-07-26,Former employee,Good benefits in terms of insurance and salary.,Unhealthy comptetition among departments in the bank.
117,Business analyst (financial analyst),5.0,2023-08-04,Current employee,Good with Human Capital and support to staff,Internal promotions not as frequent
118,Full stack developer,4.0,2023-07-27,Current employee,"Experience in multiple technologies, with specializations also welcomed",Late Hours and lots of meetings
119,Telemarketer,1.0,2023-10-02,Current employee,None.Honestly there is nothing to smile about.,Everything. Especially working on contract there is quite frustrating.
120,Customer service manager,3.0,2023-05-30,"Former employee, more than 8 years",They pay well with a clear defined duties.,They don't appraisal individual with actual performance. Is the manager to decide where to rate you when it comes to appraisals.
121,Business development manager,3.0,2023-07-14,Former employee,bonus at the end of the year,rigid work culture especially older staff
122,Customer service representative,5.0,2023-06-14,"Former employee, more than 5 years","Bonuses,medical, salary, pension and leave management","Pressure, CRM, staff management , and micro management"
123,Executive assistant,4.0,2023-07-06,"Current employee, more than 10 years",variety of loans at staff rate,nothing i can think of
124,Operations manager,5.0,2023-04-12,Former employee,"Provided staff with adequate room for growth and career progression. trainings for all staff on emerging trends on frauds, KYC and AML.",Overloading leading to staff burnouts
125,Consultant,3.0,2023-05-11,Current employee,Fully developed structures Clear performance expectations,No staff development program away from entry level roles Widespread career stagnation
126,Product manager,3.0,2023-05-29,"Current employee, more than 3 years","Great company, with a fantastic brand recognition.",Maneuvering the politics can be exhausting.
127,Executive customer experience officer,4.0,2023-06-08,Current employee,Salary is paid on time,It may take a while to get promoted especially at the branch level

In [25]:
# check duplicate sum
def checkDuplicateSum(df: pd.DataFrame) -> int:
    duplicate_count = df.duplicated().sum()
    return 'Sum of Duplicate_Values =', duplicate_count
checkDuplicateSum(Co_opRev)

('Sum of Duplicate_Values =', 10)

In [26]:
Co_opRev.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
dtype: bool

In [31]:
Co_opRev.iloc[10:29]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
10,Atm manager,4.0,2025-07-05,"Former employee, less than 1 year",Good communication among team members Efficient handling of tasksTeam building activities,Working under pressure since you are expected to meet your targets.
11,Business analyst,5.0,2025-04-21,"Current employee, more than 10 years",Very good at training its staff with requisite courses,The upskilling may not come witha salary increment
12,Relationship banker,5.0,2025-04-08,"Current employee, more than 1 year","Great employer, great learning curve and exposure to the financial sector.",No cons with the current structure.
13,Contact center representative,3.0,2025-04-11,"Current employee, more than 8 years","Flexible working hours , medical cover & yearly bonus",Nepotism and favoirism and unfair appraisals
14,Business banker,4.0,2025-03-10,"Former employee, more than 5 years",good employer with good salary,not seen any cons on employment
15,Finance manager,4.0,2025-02-20,"Former employee, more than 5 years","Secure, pays well and good package","Internal audit, leave over weekend will take 0.5 days"
16,Ops manager,5.0,2025-02-11,"Former employee, more than 1 year",Good benefits salary and job security,Clearly defined growth prospects for all levels.
17,Client service representative,3.0,2025-02-19,Current employee,The staff are well trained,Huge company not easy to grow
18,Data analyst,5.0,2025-02-12,"Former employee, more than 3 years",Great organization to work for,Management are like non touchables
19,Customer service,5.0,2025-01-07,"Current employee, more than 5 years",Good pay ease and bonuses,Non flexible work Hours .
20,Atm manager,4.0,2025-07-05,"Former employee, less than 1 year",Good communication among team members Efficient handling of tasksTeam building activities,Working under pressure since you are expected to meet your targets.
21,Business analyst,5.0,2025-04-21,"Current employee, more than 10 years",Very good at training its staff with requisite courses,The upskilling may not come witha salary increment
22,Relationship banker,5.0,2025-04-08,"Current employee, more than 1 year","Great employer, great learning curve and exposure to the financial sector.",No cons with the current structure.
23,Contact center representative,3.0,2025-04-11,"Current employee, more than 8 years","Flexible working hours , medical cover & yearly bonus",Nepotism and favoirism and unfair appraisals
24,Business banker,4.0,2025-03-10,"Former employee, more than 5 years",good employer with good salary,not seen any cons on employment
25,Finance manager,4.0,2025-02-20,"Former employee, more than 5 years","Secure, pays well and good package","Internal audit, leave over weekend will take 0.5 days"
26,Ops manager,5.0,2025-02-11,"Former employee, more than 1 year",Good benefits salary and job security,Clearly defined growth prospects for all levels.
27,Client service representative,3.0,2025-02-19,Current employee,The staff are well trained,Huge company not easy to grow
28,Data analyst,5.0,2025-02-12,"Former employee, more than 3 years",Great organization to work for,Management are like non touchables

In [32]:
def drop_duplicate(df: pd.DataFrame) -> int:
    """This function drops the duplicated 
        values in the dataset
    Args = df for the dataset
    return = this function returns a dataframe 
        withiout the duplicate values"""
    drop_duplicates = df.drop_duplicates(subset = ["Job Title"], inplace=True)
    return drop_duplicates
drop_duplicate(Co_opRev)

In [33]:
Rows, columns = Co_opRev.shape
print(f"Rows = {Rows}, columns = {columns}")

Rows = 138, columns = 6

In [38]:
Co_opRev.reset_index(inplace=True)
# Co_opRev.set_index("Job Title", inplace=True)
# Boltrev.drop("index", axis = 1, inplace=True)

In [39]:
Co_opRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Anonymous employee,4.0,2025-05-28,Current employee,Comprehensive Medical CoverPensionLoan facilities at a competitive rate,Some targets set are not smartLoan options not flexible
1,Business development executive manager,4.0,2024-02-27,Current employee,"Good salary, salary increment every year.Different types of loans available to staff.",Long working hours with only few days of leave
2,Operations manager,4.0,2024-03-05,Current employee,Offers a challenging working environment for those in operations,Slow growth and too engaging
3,Support,3.0,2017-07-09,Former employee,"Good pay, on the job training , exposure to a variety of systems, leave days","workload, low upward career mobility, can hit the ceiling in pay raise after a reaching a certain level"
4,Legal officer,3.0,2021-01-16,"Current employee, more than 1 year",Broad commercial legal experienceGood benefits like insurance and bonuses,"Fixed culture mindset, government like"
5,Underwriter,2.0,2025-08-10,"Former employee, more than 5 years",Feels like family in a lot of ways,Very challenging to grow at the company
6,Project manager,3.0,2025-08-07,"Current employee, more than 3 years",Excellent credit facilities for staff Numerous internal opportunities for lateral growth,Rigid in terms of adoption of solutions Challenging organizational culture
7,Small business banker,4.0,2025-07-24,"Former employee, more than 8 years",Offer good salary packages for borth entry grades and expert grades,Bonuses are not commensurate to companies earnings
8,Business analyst/business development,5.0,2025-06-06,"Former employee, more than 10 years","1. Open door policies, great management and worklife balance: depending on the department, 2.Great HR support including staff wellness programs, and opportunities for personal growth.3. Available opportunities for career growth.4. Benefits such as medical cover, insurance cover, annual bonuses based on performanceand grade, pensionable pay.5. The greatest CEO.","1. There are variations in management and leadership skills including communication, support and opportunities depending on the department.2. Annual salary reviews would be slow depending on staff grades."
9,Atm manager,4.0,2025-07-05,"Former employee, less than 1 year",Good communication among team members Efficient handling of tasksTeam building activities,Working under pressure since you are expected to meet your targets.
10,Business analyst,5.0,2025-04-21,"Current employee, more than 10 years",Very good at training its staff with requisite courses,The upskilling may not come witha salary increment
11,Relationship banker,5.0,2025-04-08,"Current employee, more than 1 year","Great employer, great learning curve and exposure to the financial sector.",No cons with the current structure.
12,Contact center representative,3.0,2025-04-11,"Current employee, more than 8 years","Flexible working hours , medical cover & yearly bonus",Nepotism and favoirism and unfair appraisals
13,Business banker,4.0,2025-03-10,"Former employee, more than 5 years",good employer with good salary,not seen any cons on employment
14,Finance manager,4.0,2025-02-20,"Former employee, more than 5 years","Secure, pays well and good package","Internal audit, leave over weekend will take 0.5 days"
15,Ops manager,5.0,2025-02-11,"Former employee, more than 1 year",Good benefits salary and job security,Clearly defined growth prospects for all levels.
16,Client service representative,3.0,2025-02-19,Current employee,The staff are well trained,Huge company not easy to grow
17,Data analyst,5.0,2025-02-12,"Former employee, more than 3 years",Great organization to work for,Management are like non touchables
18,Customer service,5.0,2025-01-07,"Current employee, more than 5 years",Good pay ease and bonuses,Non flexible work Hours .
19,Sourcing,5.0,2024-12-17,"Current employee, more than 1 year",Good working culture and experience.,Long working hours and targets
20,Card and e-channels officer,3.0,2024-11-27,"Former employee, more than 5 years","Challenging environment, skills on the job",Pressure for targetsEveryone is on the runcan get stuck in one position for long
21,Personal banker,3.0,2024-10-25,"Current employee, more than 3 years",Protocol is strictly adhered to.Fairly good salary scales,Limited growth opportunities especially when you don't boot lick.Toxic environment in most places brought on by toxic leadership.
22,Business intelligence developer,5.0,2024-12-06,"Current employee, more than 1 year","Well structured per role data engineer,data science,dm.qa",Missing big data in analytics
23,Customer relationship manager,4.0,2024-11-18,"Former employee, more than 1 year","Big company, Bonus, Job satisfaction, Good salary","High pressure, politics, bad managers, bad culture"
24,Relationship manager,5.0,2024-11-13,"Former employee, more than 8 years",Good employer who renumerates well based of performance,There's limited growth opportunity as promotions are hard to come by
25,It project manager,2.0,2024-10-30,Former employee,Salary increaments available based on performance,The company doesnot sponsor the staff for professional traininngs
26,Cash officer,3.0,2024-10-26,"Current employee, more than 5 years",Awesome employee benefits with bonus pay,You may stay in the same position for years
27,Finance business partner,2.0,2024-10-16,"Current employee, more than 10 years",Lots of staff benefits for employees,Unstructured promotions there is no guaranteed growth
28,Bank teller,2.0,2024-10-12,Current employee,Work dynamics changes continuously so you learn alot,Pressure which is constant and unnecessary
29,Sales and service advisor,2.0,2024-10-03,"Former employee, more than 1 year",Fair payPension when confirmedMedical cover,Long hoursManagementSlow growth
30,Team assistant,5.0,2024-09-16,"Current employee, more than 10 years",Medical. Bonus. Opportunities for growth.,"Overall, it is a good place to be"
31,Credit analyst,3.0,2024-08-10,"Former employee, more than 3 years","Good bonus, medical and staff loans. Wonderful colleagues","No flexible hours or WFH, government like bureaucracy and no room for growth."
32,Sales executive,3.0,2024-09-06,Former employee,Payment of salary on time,No much career growth progressively for men
33,E-channels officer,4.0,2024-09-03,Former employee,Company offers good compensation to employees,Micromanagement of employees is a downside.
34,Product manager,4.0,2024-08-21,Former employee,Benefits are great and the experience is diverse,Micro management which demotivates employees to do more and be more
35,Asr (account service representative ),3.0,2024-07-10,"Former employee, more than 3 years",Above average salary compared to similar banks,Long working hours and very limited breaks
36,Customer experience executive,3.0,2024-07-23,Former employee,Medical CoverAnnual BonusYearly IncrementTimely Salary Payment,Limited job rotation.Lack of an energetic corporate culture.Rigid working environment. Harsh on moms; more so single moms.
37,Enterprise support engineer,5.0,2024-07-23,"Former employee, more than 5 years",Pay bonusVery low interest rates for loan facilities as a staffGood pay,Official wear Suit and tie
38,Head trade finance services,3.0,2024-06-04,"Former employee, more than 3 years",It has structures that make things work smoothly.,The religious aspects of the 'Kingdom' Bank can be very inhibitive and intoxicating to openminded and independentthinking staff.
39,Business development banker,5.0,2024-06-17,Former employee,Gained wide skills in sales and marketing.,Learned to work under pressure and multitasking.
40,Ssa clerk,5.0,2024-06-15,"Current employee, less than 1 year",Best lending rates and good working conditions,No negative traits so far
41,Banker,3.0,2024-05-27,Current employee,give me much needed jobstability,long working hours and perfomance pressure
42,Customer service representative,3.0,2024-05-05,"Current employee, more than 3 years",Good training and mentorshipGood salary to start,No work life balanceVery extended working hours
43,It systems administrator,4.0,2024-03-25,Former employee,Good place to nurture talent with vast exposure to a busy environment.,There are days you will have long working hours.
44,Reconciliation officer,3.0,2024-03-27,Current employee,Fairly stable job security and retirement plan,Unfair reward structures that are based more on expediency than experience and qualifications
45,Graduate clerk,3.0,2024-04-06,"Former employee, more than 1 year",Good pay and bonus when there's good profit,Lots of targets and little personal time
46,Manager,4.0,2024-04-14,"Former employee, more than 8 years",Best Hr practices and procedures,None so far but abit strict
47,Dealer,2.0,2024-02-08,Current employee,Bank so interdepartmental transfers are possible,"Bank, so compensation is limited"
48,Business development manager,3.0,2023-12-04,Current employee,"Benefits, insurance, loans, sacco benefit and bonuses","Staff welfare, grapevine and an audit team that does not correct has an intention on always letting people go."
49,Agent,4.0,2024-01-15,Current employee,Great nice and excellent employer,Nothing experienced was bad about it
50,Deli clerk,3.0,2024-01-09,Current employee,no worklife balance for junior staff,good remuneration packages for staff
51,Software engineer,3.0,2023-12-12,Current employee,thet offer mid salaries to their employees. good salaries if you do your research,long working hours especially for IT professionals
52,Intern,5.0,2023-12-14,"Former employee, less than 1 year",Great community of people and good management,Some intern work is quite repetitive
53,Credit officer,3.0,2023-11-24,"Former employee, more than 3 years",Good Medical BenefitsLow interest rate loans,Unattainable targets. Super long working hours
54,Relationship manager special assets,5.0,2023-11-11,Current employee,"Good package, flexible, stable, staff loans","High targets, not regional , lot of work, pip programs"
55,Internal auditor,1.0,2023-12-03,"Former employee, more than 10 years",Deep experience acquired. Great team work experienced.,Heavy unachievable targets.Poor leadership that does not motivate staff.Inequality in pay structure.
56,Ict manager,5.0,2023-10-17,Current employee,innovation agility transformation resilience teamwork,time hindrance's energy consuming politics stagnation
57,Sales representative,1.0,2023-12-08,"Former employee, less than 1 year",Great team and good working environment,Unrealistic targets that can never be achieved
58,Business process analyst,4.0,2023-09-07,"Former employee, more than 5 years",Good benefits and opportunities for growth,Highly religious in office interaction
59,Ict project manager,4.0,2023-08-28,Current employee,"Dynamic, challenging and engaging work environment",Sometimes no clear responsibility mapping and proper planning with abstract goals.
60,Credt analyst,3.0,2023-08-17,Current employee,Great opportunities for personal development through free online courses.,Very rigid to change and too risk averse
61,Business analyst (financial analyst),5.0,2023-08-04,Current employee,Good with Human Capital and support to staff,Internal promotions not as frequent
62,Full stack developer,4.0,2023-07-27,Current employee,"Experience in multiple technologies, with specializations also welcomed",Late Hours and lots of meetings
63,Telemarketer,1.0,2023-10-02,Current employee,None.Honestly there is nothing to smile about.,Everything. Especially working on contract there is quite frustrating.
64,Customer service manager,3.0,2023-05-30,"Former employee, more than 8 years",They pay well with a clear defined duties.,They don't appraisal individual with actual performance. Is the manager to decide where to rate you when it comes to appraisals.
65,Executive assistant,4.0,2023-07-06,"Current employee, more than 10 years",variety of loans at staff rate,nothing i can think of
66,Consultant,3.0,2023-05-11,Current employee,Fully developed structures Clear performance expectations,No staff development program away from entry level roles Widespread career stagnation
67,Executive customer experience officer,4.0,2023-06-08,Current employee,Salary is paid on time,It may take a while to get promoted especially at the branch level
68,Software developer,2.0,2023-06-16,"Current employee, more than 3 years",good employee loans. Good medical.,No flexible hours. No option for remote.
69,Relationships manager,4.0,2023-05-13,Current employee,"Great renumeration, bonuses, training and career growth","Little opportunity for work life balance, crazy/ intense work pressure, archaic hr policies"
70,Solutions architect,5.0,2023-06-07,Former employee,Good working environment and exposure,No issue faced during my ternure
71,Head of unit,3.0,2023-05-09,"Former employee, more than 10 years",The company has excellent structures,The company has very poor company culture
72,Fixed income trader,5.0,2023-05-15,"Current employee, more than 1 year",Great benefits with good interest rates,None at the moment .
73,Branch manager,4.0,2023-05-19,Former employee,Great training ground Great team,Greatly conservative Salary disparity in same line
74,Officer,1.0,2023-03-11,"Former employee, less than 1 year",Pay is good Develop good work ethic,Unfriendly bosses bullish and disrespectful to their juniors Leaders lack empathy for their juniors Culture of blaming individuals for mistake and punitive punishments Unrealistic expectations on KPIs and working hours Leaders find themselves superior No worklife balance Petty processes and policies High turnover rates
75,Systems analyst,4.0,2023-02-02,"Current employee, more than 5 years",Good benefits Good terms of employment,Poor work culture Abit disorganized Irrelevant KPIs
76,App security engineer,4.0,2023-03-21,Former employee,"Great pay, great bonus, great employee benefits",organization politics take center stage
77,Contact centre agent,3.0,2022-12-20,"Former employee, more than 1 year",Good salary for entry level job,High targets too many working hours
78,It risk and control manager,4.0,2019-12-25,"Current employee, more than 3 years","The bank has invested heavily in staff training and talent development. If you are looking for a place where you will grow in training, this is the place to be. As a Kingdom bank, you will also feel homely with prayer meetings for all interested staff once every quarter. There is proffessionalism especially for low cadre jobs.","While the training is great, retaining talent is poor due to slow growth in remuneration. You'd better negotiate for a better salary while getting in coz you might be there for a while. Anyway, this seems to be the norm in many places lately."
79,Sdo - service desk operator,2.0,2022-05-12,"Current employee, more than 5 years",Great starting salary for a recent university graduate,No work life balance Unrealistic KPI expectations Cases one is expected to work on are loaded throughout the quarter making it hard to achieve One is expected to work on too many campaigns ongoing at the same time yet there is little time one can allocate to them Limited career growth as one is likely to stagnant in the same position for years
80,Audit analyst,4.0,2022-06-03,"Former employee, less than 1 year",Somehow good starting salary which gets a slight increase based on performance and your stay in the bank.,"Job description not coherent with the action partVery slow growth, no promotionsStray targets that are not related to the main job"
81,Customerservice representative,2.0,2022-09-28,"Current employee, more than 5 years",Good staff to work with,"Poor pay,high pay is for the who knows who,you could be on the same role with someone and they have better terms than you,no recognition you have to kill to be noticed,a lot of politics"
82,Supervisor,2.0,2021-04-13,"Current employee, more than 8 years",Good appreciable Bonus for the management despite th COVID 19 pandemic,"Depending on the manager you have, your growth is dependent on them"
83,Enterprise business analyst,3.0,2021-03-28,"Former employee, more than 1 year","If you are looking to gain good work experience and challenges, this is the place to be.Work life balance was also a plus",Company politics and unfavorable work environment. Career growth is also a challenge.
84,It support specialist,4.0,2022-05-29,Current employee,"Working in IT you develop some grit to help manouvere, as there is intense pressure to deliver at times",bureaucratic processes Can easily stagnate
85,Procurement manager,3.0,2019-07-24,"Current employee, more than 8 years",Access to loans at subsidized interest rates,"Growth is not assured despite years of service, exceptional performance or sensitivity of job"
86,Treasurer,3.0,2020-01-19,"Current employee, more than 5 years","Good benefits, Strong market presence, top 3 bank in Kenya","Inward looking culture, lower pay compared to other TEIR 1 peers"
87,Audit manager,4.0,2015-10-27,"Current employee, more than 1 year",Existence of effective internal control environment and culture,The organization is large hence it may be difficult to audit all the areas as the audit team is large.
88,Sales associate,3.0,2021-08-19,"Current employee, more than 1 year",good salary and one might get a bonus. STAFF LOANS ARE ALSO AVAILABLE AT GOOD RATES,takes alot of persnal time because you have to workinternal pressure but rewardingstranfers to differnt locations
89,It support,4.0,2022-07-28,"Former employee, more than 8 years",Good place to learn with exposure to different technologies.,There is crazy workload but on the positive side it helps build personal resilience and solid character.
90,Ict security analyst,5.0,2021-02-08,Current employee,1. Good work ethics2. Supportive Human Resource Partners. 3. Super learning environment,1. Quite a lot of work. Not for the faint of heart.
91,Head of ict & cyber security,4.0,2021-09-10,Former employee,Provide guidance for career growth and professional development opportunities,The culture can be a shocker to many. A little bit rigid to changes.
92,Customer care,3.0,2022-04-28,"Former employee, more than 8 years",It has the best medical cover.,The bank is only focusing on profit making and nothing about its staffs.
93,Service desk officer,4.0,2019-10-15,"Former employee, more than 10 years",growth opportunities are many when u work hard.,work life balance is a great challange for branch staff
94,Business development,2.0,2021-05-23,Current employee,Great IT systems for reporting purposes,Too much pressure and confusion as a result of too many instructions from different departments requiring action at the same time
95,Remedial relationship manager,3.0,2022-10-11,"Current employee, more than 10 years",Good entry salary's Good training,Cronyism very high Nepotism very high The bank lacks clear direction due to old leadership
96,Analyst,4.0,2019-10-16,Former employee,Fair remunerationGood exposure to industryGreat training opportunitiesRoom for career growth,Lots of bureaucracy in decision making
97,Client support specialist,2.0,2022-05-09,Current employee,The offer emplyment opportunities to graduates,The corporate needs qualified HR practitioner
98,Direct sales representative,4.0,2015-08-23,"Former employee, more than 1 year",it was a good company filled with great opportunities,they try to compete with upcoming banking companies
99,Sales service advisor,3.0,2020-03-02,"Former employee, more than 5 years",salary is goodbenefits are nice,discrimination and harassment of junior staff at branch level.Growth depends on who you know.
100,Small/medium business account representative,3.0,2021-05-18,"Current employee, more than 10 years",A lot of on job training available to staff,"Slow career growth,it can take over 10years to be promoted.Too much pressure."
101,Operations,5.0,2021-11-04,Former employee,Ability to grow and good bonuses.,Monotony at workplace and long working hours.

In [40]:
Co_opRev.insert(6,"Company_Name", "Co-Operative")