In [6]:
import pandas as pd
import numpy as np

In [7]:
EquityRev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/EquityReviews.csv")

In [8]:
# EDA on the data
def display(x):
    """This function returns a 
    summary of the dataset"""
    
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(EquityRev)

Displays the rows and columns in the dataset
============================================
Rows: 750 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                   Job Title  Job Ratings          time  \
0      Credit administrator          5.0  Jun 30, 2022
1          Sr. acct manager          1.0  Dec 20, 2024
2        Anonymous employee          4.0  Jul 28, 2023
3        Anonymous employee          4.0  Jan 26, 2016
4               Bank teller          2.0   Mar 1, 2021
..                      ...          ...           ...
745      Anonymous employee          1.0  Dec 27, 2015
746   Ban assurance officer          1.0  Oct 17, 2022
747          Credit officer          1.0  Sep 24, 2018
748    Relationship officer          1.0  Jun 17, 2022
749  Channel administrative          1.0   Oct 9, 2013

                               JobStatus  \
0     Former employee, more than 5 years
1     Former employee, more than 5 years
2                       Current employee
3                        Former employee
4      Former employee, more than 1 year
..                                   ...
745   Current employee, more than 1 year
746    Former employee, more than 1 year
747  Current employee, more than 3 years
748   Former employee, more than 5 years
749   Former employee, more than 5 years

                                                                                                                                                                                                                  Pros  \
0                                                                                                                                                                                Good culture environment and teamwork
1                                                                                                                                                                     Dont chose to work for this toddler ran company.
2                                                                                                                                                                     Big ambition to grow horizontally and leadership
3    The internship provides a great opportunity to be a college counselor and provide mentorship to young high school kids as they apply to universities abroad. Its one of the most fulfilling experiences I've had.
4                                                                                                                                                                                  Nice co-workers and good work hours
..                                                                                                                                                                                                                 ...
745                                                                                                                                                                        great exposure and experience,robust sytems
746                                                                                                                                                              Medical insurance cover. Low interest loans for staff
747                                                                                                                                                Robust systems, innovative, knowledgeable and energetic young staff
748                                                                                                                                                                                    Loans were subsidized for staff
749                                                                                                                                                                  exposure and experience good. growth too possible

                                                                                                                                                                  Cons
0                                                                                                                                      - Non applicable Non applicable
1                                                                                                                                      Low pay and long hours expected
2                                                                                                 Bureaucracy due to the age of the org and historical ways of working
3    Strict work culture (friendly staff through) which is subject to personal interpretation. I liked it since it was challenging and pushes one out of comfort zone.
4                                                                                           You can tell the upper management doesn't care about lower-level employees
..                                                                                                                                                                 ...
745                                                                                  poor pay, tribalism, less employee benefits, bureaucracy, officers are undermined
746                                                           Bad management Less than appropriate pay Extremely long work hours Extensive workload Toxic work culture
747                                                            Poor employee relations and welfare , poor pay, huge workload, long working hours, slow employee growth
748                                                                                                 Overworked and little pay, no work-life balance, basically no life
749                                                                                              work environment not good, need to improve a lot on HR related issues

[750 rows x 6 columns]>

Returns the information in more details
============================================
       Job Ratings
count   750.000000
mean      3.425333
std       1.138780
min       1.000000
25%       3.000000
50%       3.000000
75%       4.000000
max       5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           20
dtype: int64

In [9]:
# display the whole column content
pd.set_option("display.max_colwidth", None)

In [10]:
# The first 3 elements
print("Top 5 elements")
print("=============================")
print()
EquityRev.head()

Top 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Credit administrator,5.0,"Jun 30, 2022","Former employee, more than 5 years",Good culture environment and teamwork,- Non applicable Non applicable
1,Sr. acct manager,1.0,"Dec 20, 2024","Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected
2,Anonymous employee,4.0,"Jul 28, 2023",Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working
3,Anonymous employee,4.0,"Jan 26, 2016",Former employee,The internship provides a great opportunity to be a college counselor and provide mentorship to young high school kids as they apply to universities abroad. Its one of the most fulfilling experiences I've had.,Strict work culture (friendly staff through) which is subject to personal interpretation. I liked it since it was challenging and pushes one out of comfort zone.
4,Bank teller,2.0,"Mar 1, 2021","Former employee, more than 1 year",Nice co-workers and good work hours,You can tell the upper management doesn't care about lower-level employees

In [11]:
# The last 3 elements
print("last 5 elements")
print("=============================")
print()
EquityRev.tail()

last 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
745,Anonymous employee,1.0,"Dec 27, 2015","Current employee, more than 1 year","great exposure and experience,robust sytems","poor pay, tribalism, less employee benefits, bureaucracy, officers are undermined"
746,Ban assurance officer,1.0,"Oct 17, 2022","Former employee, more than 1 year",Medical insurance cover. Low interest loans for staff,Bad management Less than appropriate pay Extremely long work hours Extensive workload Toxic work culture
747,Credit officer,1.0,"Sep 24, 2018","Current employee, more than 3 years","Robust systems, innovative, knowledgeable and energetic young staff","Poor employee relations and welfare , poor pay, huge workload, long working hours, slow employee growth"
748,Relationship officer,1.0,"Jun 17, 2022","Former employee, more than 5 years",Loans were subsidized for staff,"Overworked and little pay, no work-life balance, basically no life"
749,Channel administrative,1.0,"Oct 9, 2013","Former employee, more than 5 years",exposure and experience good. growth too possible,"work environment not good, need to improve a lot on HR related issues"

In [12]:
# The random 3 elements
print("Random 5 elements")
print("=============================")
print()
EquityRev.sample(5)

Random 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
470,Senior communication and advertising officer,3.0,"Feb 4, 2022","Current employee, more than 3 years",Job security\r\nTier 1 Bank\r\nDiverse and high pressure environment,"Work politics \r\nBosses never leave, hence little to no growth in middle leadership levels"
318,Relationship manager,3.0,"Apr 4, 2023","Former employee, more than 8 years","Extensive exposure to the field of expertise-retail banking, Professional conduct by staff or customers Adheres to strict discipline and integrity values",long working hours- sometimes including weekends in need be
284,Relationship officer credit,3.0,"Sep 2, 2023","Former employee, more than 5 years",Low entry criteria (show some enthusiasm and passion),Performance Targets might be unreasonable if you are taken to a low performing branch.
175,Operations officer,3.0,"Aug 30, 2024","Current employee, more than 3 years","The company is gender balanced, everyone has an equal chance of up taking a role which is merit based",Staff on contractual terms are not confirmed on time
83,Security consultant,2.0,"Jul 9, 2025","Current employee, more than 8 years",A field to learn and have a experince,no work life balance\nNo salary increment \npoor pay comapred to the market rate

In [13]:
# loops over the whole column 1
for index,col in enumerate (EquityRev["Job Title"]):
    print(index, col)

0 Credit administrator
1 Sr. acct manager
2 Anonymous employee
3 Anonymous employee
4 Bank teller
5 Relationship officer
6 Anonymous employee
7 Mortgage banker
8 R/o
9 Manager
10 Anonymous employee
11 Anonymous employee
12 Associate director
13 Commercial loan assistant
14 Anonymous employee
15 Teller
16 Banker
17 Administrative assistant
18 Anonymous employee
19 Anonymous employee
20 Anonymous employee
21 Anonymous employee
22 Associate director
23 Commercial loan assistant
24 Anonymous employee
25 Teller
26 Banker
27 Administrative assistant
28 Anonymous employee
29 Anonymous employee
30 Locked job title
31 Locked job title
32 Locked job title
33 Locked job title
34 Locked job title
35 Locked job title
36 Locked job title
37 Locked job title
38 Locked job title
39 Locked job title
40 Locked job title
41 Locked job title
42 Locked job title
43 Locked job title
44 Locked job title
45 Locked job title
46 Locked job title
47 Locked job title
48 Locked job title
49 Locked job title
50 Anonymous employee
51 Recruiter
52 Anonymous employee
53 Credit analyst
54 Post doctoral fellow
55 Customer service manager (csm)
56 Manager
57 Relationship banker
58 System engineer
59 Noc engineer
60 Anonymous employee
61 Recruiter
62 Anonymous employee
63 Credit analyst
64 Post doctoral fellow
65 Customer service manager (csm)
66 Manager
67 Relationship banker
68 System engineer
69 Noc engineer
70 Senior software engineer
71 Credit officer
72 Relationship manager
73 Bank teller
74 Senior operations manager
75 Digital banking project manager
76 Finance assistant
77 Relationship officer
78 Relationship officer
79 Relationship supervisor
80 Bank teller
81 Senior officer
82 Senior payment officer/project coordinator/business analyst
83 Security consultant
84 Business relationship officer
85 Bank teller
86 Customer service representative
87 Loan officer
88 Accountant
89 Associate director
90 Relationship manager
91 Relationship manager
92 Customer service representative
93 Relationship officer
94 Product designer
95 Relationship officer
96 Relationship officer
97 Sales manager
98 Relationship officer
99 Software engineer
100 Relationship banker
101 Relationship officer
102 Hr operations
103 Supervisor
104 Account manager
105 Manager
106 Relationship officer
107 Bank teller
108 Data analyst
109 Data scientist
110 Cashier
111 Payments officer
112 Sales representative
113 Credit officer
114 Team lead
115 Customer relationship officer
116 Manager
117 Senior data analyst
118 Bank teller
119 Channel sales
120 Bank relationship officer
121 Legal officer
122 Senior test analyst
123 Assistant manager
124 Internal controls specialist
125 Bancassurance officer
126 Quality assurance analyst
127 E-channels officer
128 Relationship officer
129 Accountant
130 Customer relationship officer
131 Facilities engineer
132 Cashier
133 Customer service representative
134 Senior bancassurance sales executive
135 Credit officer
136 Senior erp support analyst
137 Cashier
138 Anonymous employee
139 Backend developer
140 Bank teller
141 Trade finance officer
142 Assistant manager
143 Bancassurance officer
144 Software engineer
145 Anonymous, head office
146 Payment officer
147 Treasury assistant
148 Software engineer
149 Software engineer
150 Senior software engineer
151 Analyst
152 Relationship officer
153 Credit officer
154 Aml analyst
155 Credit officer
156 Bank teller
157 Cashier/sales associate
158 Anonymous employee
159 Operations
160 Accountant
161 Sales associate
162 Bank teller
163 Technology analyst
164 Sales representative
165 Anonymous employee
166 Credit officer
167 Student equity leadership position
168 Business analyst
169 It project manager
170 Relationship manager
171 Relationship officer credit
172 Operations manager
173 Relationship officer
174 Talent acquisition manager
175 Operations officer
176 Bank teller
177 It officer
178 Bank teller
179 Anonymous employee
180 Procurement officer
181 Network engineer
182 Relationship officer
183 Relationship officer
184 Cash and liquidity management
185 Senior manager
186 Software engineer
187 Reltionship manager
188 Software engineer
189 Client relationship supervisor
190 Security analyst
191 Project management
192 Group head of business continuity
193 Marketing
194 Contact center representative
195 Senior analyst
196 Human rseources
197 Business analyst
198 Channels specialist
199 Relationship supervisor
200 Bank teller
201 Anonymous employee
202 Senior officer
203 Software engineer
204 Credit manager
205 Cashier
206 Senior officer
207 Cyber security specialist
208 Analytics manager
209 Relationships officer
210 Intern
211 Project manager
212 Program manager
213 Project manager
214 Operations manager
215 Senior regional manager
216 Relationship officer
217 Chief credit officer
218 Loan officer
219 Bank clearing officer
220 It officer
221 It senior business analyst
222 Intern
223 Relationship officer
224 Junior data scientist
225 Loan officer
226 Credit officer
227 Senior product manager
228 Relationship officer credit
229 Sales director
230 Software developer
231 Relationship officer
232 Senior officer
233 Accountant
234 Relationship officer
235 Customer service representative (csr)
236 Manager
237 Senior manager
238 Credit officer
239 Operations manager
240 Gender advisor
241 Business growth manager
242 Relationship officer credit
243 Payments supervisor
244 Information security auditor
245 Bank teller
246 Senior hr officer
247 Relationship officer
248 Front end developer
249 Analyst
250 Relationship officer
251 Engineer
252 Relationship banker
253 Data analyst
254 Driver
255 Bank clerk
256 Bank teller
257 Relationship officer
258 Head of strategy and business development
259 Assistant manager recovery
260 Customer service representative
261 Credit officer
262 Customer service representative (csr)
263 Entreprise development executive
264 It specialist
265 Academic content writer
266 Accountant
267 Relationship officer credit
268 Payments supervisor
269 Corporate relationship manager
270 Assistant manager
271 Anonymous employee
272 Regional supervisor
273 Accountant
274 Bancassurance specialist
275 Consumer credit officer
276 Relationship banker
277 Ict - senior software engineer
278 Software engineer
279 Customer relations
280 Relationship officer
281 Operations manager
282 Human resources business partner
283 Group head
284 Relationship officer credit
285 Senior treasury dealer
286 Relationship officer
287 Senior relationship officer-ii
288 Relationship manager
289 Bancassurance officer
290 Project manager
291 Relationship officer
292 Operations
293 Relationship manager
294 Credit controller
295 Sales representative
296 Sales representative
297 Head - it
298 Project management office (pmo)
299 It manager
300 Relationship officer
301 Risk analyst
302 Senior relationship officer cash
303 Relationship manager
304 Bank teller
305 Relationship manager
306 Manager
307 Credit officer
308 Relationship officer
309 Backend developer
310 Relationship officer
311 Graduate research assistant
312 Credit officer
313 Marketing
314 Accountant
315 Informaiton offficer
316 Relationship manager
317 Credit officer
318 Relationship manager
319 Software engineer
320 Officer
321 Anonymous employee
322 Relationship manager
323 Relationship officer
324 Apprentice
325 Credit manager
326 Aml analyst
327 Hr advisor
328 Senior software engineer
329 Relationship officer
330 It officer
331 Cashier
332 Bank teller
333 Cashier
334 Senior software engineer
335 Bank teller
336 Bank teller
337 Manager
338 Sales associate
339 Head of group digital products
340 Relationship banker
341 Payments manager
342 Credit officer
343 Project manager
344 Direct sales representative (dsr)
345 Credit analyst
346 Banking
347 Software engineer
348 Project manager
349 Bank teller
350 Front desk agent
351 It project manager
352 Senior officer
353 Relationship officer
354 Manager
355 Customer service
356 Relationship officer
357 Noc engineer
358 Legal assistant/paralegal
359 Relationship officer
360 Accountant
361 Accountant
362 Operations officer
363 Relationship manager
364 Noc engineer
365 Relationship officer
366 Relationship officer
367 General manager
368 Operations manager
369 Officer
370 It support
371 Sales representative
372 Salesperson
373 Anonymous employee
374 Macro research analyst
375 Customer relationship manager
376 Senior fraud analyst
377 Operational excellence change agent
378 Credit officer
379 Anonymous employee
380 Frontend developer
381 Relationship officer
382 Customer service
383 Cashier/teller
384 Assistant operations manager
385 Anonymous employee
386 Branch head of credit/administrator
387 Anonymous employee
388 Anonymous employee
389 Product development and innovations manager
390 Credit administrator
391 Relationship officer
392 Intern
393 Relationship manager
394 Fraud investigator
395 Operations supervisor
396 Relationhip officer
397 Anonymous employee
398 Software developer
399 Senior officer
400 Customer service representative
401 Anonymous employee
402 Business banker
403 Software developer
404 Senior analyst
405 Cashier
406 Senior relationship officer
407 Banker
408 Finance manager
409 Bank teller
410 Senior loan officer
411 Anonymous employee
412 Anonymous employee
413 Relationship officer
414 Credit officer
415 Anonymous employee
416 Internship
417 Anonymous employee
418 Anonymous employee
419 Communications specialist
420 Technical lead it
421 Senior software engineer
422 Anonymous employee
423 Relationship manager
424 Anonymous employee
425 Anonymous employee
426 Anonymous employee
427 Anonymous employee
428 Relationship banker
429 Senior relationship officer
430 Relationship manager
431 Senior program officer
432 Senior relationship officer
433 Anonymous employee
434 Relationship officer
435 Bank relationship officer
436 Anonymous employee
437 It auditor
438 Credit officer
439 Relationship officer
440 Relationship officer group lending
441 Hsnp officer
442 Credit officer
443 Anonymous employee
444 Bank teller
445 Transactional banker
446 Relationship banker
447 Anonymous employee
448 Fullstack developer
449 Relationship officer
450 Anonymous employee
451 Head-grc
452 Head office
453 Anonymous employee
454 Senior manager
455 Bank teller
456 Senior relationship manager
457 Relationship manager operations
458 Senior relationship banker
459 Customer service supervisor
460 Cashier
461 Software engineer
462 Anonymous employee
463 Manager
464 Relationship officer
465 Anonymous employee
466 Cash officer
467 Relationship banker
468 Assistant manager
469 Head of project management
470 Senior communication and advertising officer
471 It support officer
472 Relationship manager, agency banking
473 Relationship officer
474 Senior public relations manager
475 Relationship officer
476 Anonymous employee
477 Anonymous employee
478 Credit administrator
479 Business development manager
480 It project manager
481 Ict applications support
482 Equity trader
483 Banker
484 Senior human resources officer
485 Bank teller
486 Senior software developer
487 Junior engineer
488 Operations officer
489 Network engineer
490 Grc
491 Project manager
492 Cashier
493 Anonymous employee
494 Anonymous employee
495 It officer
496 Relationship banker
497 Project coordinator
498 Actuarial
499 Program intern
500 Anonymous employee
501 Relationship officer
502 It support
503 Relationship officer
504 Relationship officer
505 Anonymous employee
506 Senior data engineer
507 Operations associate
508 It support
509 Anonymous employee
510 Anonymous employee
511 Financial analyst
512 Customer service representative
513 Teller
514 Customer relationship officer
515 Accounts assistant
516 Sro
517 Relationship officer
518 Intern
519 Assistant manager
520 Senior accountant
521 Customer relations
522 Account manager
523 Anonymous employee
524 Operations associate
525 Debt collector
526 Anonymous employee
527 Anonymous employee
528 Assistant manager
529 Relationship officer
530 Business analyst
531 Senior relationship officer
532 Relationship officer
533 It project manager
534 Payments supervisor
535 Anonymous employee
536 Anonymous employee
537 Manager
538 Accountant
539 Anonymous employee
540 Relationship officer
541 Anonymous employee
542 Relationship officer
543 Internship
544 Finance analyst
545 Relationship manager
546 Programme analyst
547 Anonymous employee
548 Bank teller
549 Cyber security analyst
550 Anonymous employee
551 It security engineer
552 Ecommerce manager
553 Monitoring analyst
554 Anonymous employee
555 Senior credit analyst
556 Payables accountant
557 Anonymous employee
558 User experience designer
559 Agency banking manager
560 Middle level management
561 Accountant
562 Anonymous employee
563 Credit officer
564 Manual tester
565 Manager
566 Relationships officer
567 Relationship officer
568 Officer
569 Supervisor
570 Relationship officer
571 Senior project manager
572 Manager
573 Relationship officer
574 Anonymous employee
575 Senior android engineer
576 Associate director - it
577 Retail manager
578 Accountant
579 Anonymous employee
580 Relationship officer
581 Teller intern
582 Relationship officer
583 Relationship officer
584 Relationship officer
585 It project manager
586 Relationship officer
587 Civil engineer
588 Customer relationship officer
589 Relationship officer
590 Relationship officer
591 Relationship officer
592 Relationship manager
593 It officer
594 Relationship officer
595 Payments supervisor
596 Aml compliance analyst
597 Senior data engineer
598 Credit officer
599 Anonymous employee
600 Legal
601 Senior manager
602 Relationship officer
603 Manager
604 Relationship officer
605 Credit officer
606 Intern
607 Relationship officer
608 Relationship officer
609 Relationship officer
610 Senior internal auditor
611 Customer relationship officer
612 Software test engineer
613 Senior manager
614 Senior media buyer
615 Relationship banker
616 Merchant acquisition specialist
617 Relationship officer credit
618 Teller
619 Relationship banker
620 Noc engineer
621 Finance intern
622 Bank teller
623 Relationship banker
624 Intern
625 Software engineer
626 Big data engineer
627 Test engineer
628 Call center representative
629 Relationship officer
630 Anonymous employee
631 Finance intern
632 Account manager
633 Finance
634 Account manager
635 Kyc officer
636 Software engineer
637 Anonymous employee
638 Anonymous employee
639 Relationship officer
640 Officer
641 Market research intern
642 Relationship officer
643 Credit officer
644 Anonymous employee
645 Relationships officer
646 Relationship officer
647 Sales associate/cashier
648 Solutions architect
649 Universal banker
650 Associate
651 Credit officer
652 Client service executive
653 Credit officer
654 Bank teller
655 Relationship banker
656 Senior accountant
657 Bank teller
658 Credit manager
659 Relationship officer
660 Relationship officer
661 Executive assistant
662 Regional manager
663 Anonymous employee
664 Anonymous employee
665 Anonymous employee
666 Anonymous employee
667 Anonymous employee
668 Anonymous employee
669 Intern
670 Anonymous employee
671 Relationship officer
672 Relationship banker
673 Business support manager
674 Consumer loan officer
675 Intern
676 Bank teller
677 Cashier
678 Bank teller
679 Systems engineer
680 Teller
681 Accountant
682 Anonymous employee
683 Sales officer
684 Anonymous employee
685 Project & planning engineer
686 Relationship officer
687 It test engineer
688 Anonymous employee
689 Officer
690 Systems analyst
691 Supervisor
692 Bank teller
693 Relationship officer
694 R o
695 Anonymous employee
696 Anonymous employee
697 Officer
698 Anonymous employee
699 Relationship officer
700 Senior manager
701 Anonymous employee
702 Marketing specialist
703 Teller intern
704 Anonymous employee
705 Software engineer
706 Credit officer
707 Relationship officer
708 Micro credit officer
709 Project manager
710 Relationship banker
711 Cashier
712 Relationship officer
713 Bank teller
714 Human resources director
715 Anonymous employee
716 Relationship manager
717 Trade operations
718 Senior officer
719 Noc engineer
720 Relationship manager
721 Relationship officer
722 Payments officer
723 Anonymous employee
724 Educational program coordinator
725 Intern
726 Project manager
727 Finance analyst
728 Credit control and monitoring specialist
729 Risk manager
730 Relationship officer
731 Client relationship specialist
732 Personal banker ii
733 Planning officer
734 Accountant
735 Anonymous employee
736 Senior business analyst
737 Credit officer
738 Senior program manager
739 Officer
740 Credit administrator
741 Bank teller
742 Relationship officer
743 Teller
744 Internship
745 Anonymous employee
746 Ban assurance officer
747 Credit officer
748 Relationship officer
749 Channel administrative

In [14]:
EquityRev.iloc[30:49]

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
30,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
31,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
32,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
33,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
34,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
35,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
36,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
37,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
38,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
39,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
40,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
41,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
42,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
43,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
44,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
45,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
46,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
47,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
48,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN

In [15]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns 
    total null values on the dataset"""
    print(df.isna().sum())
null_values(EquityRev)

Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           20
dtype: int64

In [16]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the 
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(EquityRev)
# CisRev.dropna(inplace=True)

In [17]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(EquityRev)

In [18]:
# Rename the headers
EquityRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [19]:
# pd.set_option("display.Max_rows", None)
# pd.reset_option("display.Max_rows", None)

In [20]:
EquityRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Credit administrator,5.0,2022-06-30,"Former employee, more than 5 years",Good culture environment and teamwork,- Non applicable Non applicable
1,Sr. acct manager,1.0,2024-12-20,"Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected
2,Anonymous employee,4.0,2023-07-28,Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working
3,Anonymous employee,4.0,2016-01-26,Former employee,The internship provides a great opportunity to be a college counselor and provide mentorship to young high school kids as they apply to universities abroad. Its one of the most fulfilling experiences I've had.,Strict work culture (friendly staff through) which is subject to personal interpretation. I liked it since it was challenging and pushes one out of comfort zone.
4,Bank teller,2.0,2021-03-01,"Former employee, more than 1 year",Nice co-workers and good work hours,You can tell the upper management doesn't care about lower-level employees
...,...,...,...,...,...,...
745,Anonymous employee,1.0,2015-12-27,"Current employee, more than 1 year","great exposure and experience,robust sytems","poor pay, tribalism, less employee benefits, bureaucracy, officers are undermined"
746,Ban assurance officer,1.0,2022-10-17,"Former employee, more than 1 year",Medical insurance cover. Low interest loans for staff,Bad management Less than appropriate pay Extremely long work hours Extensive workload Toxic work culture
747,Credit officer,1.0,2018-09-24,"Current employee, more than 3 years","Robust systems, innovative, knowledgeable and energetic young staff","Poor employee relations and welfare , poor pay, huge workload, long working hours, slow employee growth"
748,Relationship officer,1.0,2022-06-17,"Former employee, more than 5 years",Loans were subsidized for staff,"Overworked and little pay, no work-life balance, basically no life"
749,Channel administrative,1.0,2013-10-09,"Former employee, more than 5 years",exposure and experience good. growth too possible,"work environment not good, need to improve a lot on HR related issues"

In [21]:
EquityRev.info()

<class 'pandas.core.frame.DataFrame'>
Index: 730 entries, 0 to 749
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Job Title   730 non-null    object
 1   Job Rating  730 non-null    float64
 2   Time        730 non-null    datetime64[ns]
 3   Job Status  730 non-null    object
 4   Pros        730 non-null    object
 5   Cons        730 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 39.9+ KB

In [22]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(EquityRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Credit administrator,5.0,2022-06-30,"Former employee, more than 5 years",Good culture environment and teamwork,Non applicable Non applicable
1,Sr. acct manager,1.0,2024-12-20,"Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected
2,Anonymous employee,4.0,2023-07-28,Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working
3,Anonymous employee,4.0,2016-01-26,Former employee,The internship provides a great opportunity to be a college counselor and provide mentorship to young high school kids as they apply to universities abroad. Its one of the most fulfilling experiences I've had.,Strict work culture friendly staff through which is subject to personal interpretation. I liked it since it was challenging and pushes one out of comfort zone.
4,Bank teller,2.0,2021-03-01,"Former employee, more than 1 year",Nice coworkers and good work hours,You can tell the upper management doesn't care about lowerlevel employees
...,...,...,...,...,...,...
745,Anonymous employee,1.0,2015-12-27,"Current employee, more than 1 year","great exposure and experience,robust sytems","poor pay, tribalism, less employee benefits, bureaucracy, officers are undermined"
746,Ban assurance officer,1.0,2022-10-17,"Former employee, more than 1 year",Medical insurance cover. Low interest loans for staff,Bad management Less than appropriate pay Extremely long work hours Extensive workload Toxic work culture
747,Credit officer,1.0,2018-09-24,"Current employee, more than 3 years","Robust systems, innovative, knowledgeable and energetic young staff","Poor employee relations and welfare , poor pay, huge workload, long working hours, slow employee growth"
748,Relationship officer,1.0,2022-06-17,"Former employee, more than 5 years",Loans were subsidized for staff,"Overworked and little pay, no worklife balance, basically no life"
749,Channel administrative,1.0,2013-10-09,"Former employee, more than 5 years",exposure and experience good. growth too possible,"work environment not good, need to improve a lot on HR related issues"

In [23]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace("\n", "", regex=True))
    return df
remove_char(EquityRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Credit administrator,5.0,2022-06-30,"Former employee, more than 5 years",Good culture environment and teamwork,Non applicable Non applicable
1,Sr. acct manager,1.0,2024-12-20,"Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected
2,Anonymous employee,4.0,2023-07-28,Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working
3,Anonymous employee,4.0,2016-01-26,Former employee,The internship provides a great opportunity to be a college counselor and provide mentorship to young high school kids as they apply to universities abroad. Its one of the most fulfilling experiences I've had.,Strict work culture friendly staff through which is subject to personal interpretation. I liked it since it was challenging and pushes one out of comfort zone.
4,Bank teller,2.0,2021-03-01,"Former employee, more than 1 year",Nice coworkers and good work hours,You can tell the upper management doesn't care about lowerlevel employees
...,...,...,...,...,...,...
745,Anonymous employee,1.0,2015-12-27,"Current employee, more than 1 year","great exposure and experience,robust sytems","poor pay, tribalism, less employee benefits, bureaucracy, officers are undermined"
746,Ban assurance officer,1.0,2022-10-17,"Former employee, more than 1 year",Medical insurance cover. Low interest loans for staff,Bad management Less than appropriate pay Extremely long work hours Extensive workload Toxic work culture
747,Credit officer,1.0,2018-09-24,"Current employee, more than 3 years","Robust systems, innovative, knowledgeable and energetic young staff","Poor employee relations and welfare , poor pay, huge workload, long working hours, slow employee growth"
748,Relationship officer,1.0,2022-06-17,"Former employee, more than 5 years",Loans were subsidized for staff,"Overworked and little pay, no worklife balance, basically no life"
749,Channel administrative,1.0,2013-10-09,"Former employee, more than 5 years",exposure and experience good. growth too possible,"work environment not good, need to improve a lot on HR related issues"

In [24]:
hiphen = EquityRev[EquityRev["Cons"].str.startswith("-")]
hiphen

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [25]:
pd.set_option("display.max_rows",None)
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(EquityRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Credit administrator,5.0,2022-06-30,"Former employee, more than 5 years",Good culture environment and teamwork,Non applicable Non applicable
1,Sr. acct manager,1.0,2024-12-20,"Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected
2,Anonymous employee,4.0,2023-07-28,Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working
3,Anonymous employee,4.0,2016-01-26,Former employee,The internship provides a great opportunity to be a college counselor and provide mentorship to young high school kids as they apply to universities abroad. Its one of the most fulfilling experiences I've had.,Strict work culture friendly staff through which is subject to personal interpretation. I liked it since it was challenging and pushes one out of comfort zone.
4,Bank teller,2.0,2021-03-01,"Former employee, more than 1 year",Nice coworkers and good work hours,You can tell the upper management doesn't care about lowerlevel employees
5,Relationship officer,4.0,2020-12-03,"Former employee, less than 1 year",Worked hand in hand with customers,"Other than client relations, tasks within the bank for this role were the same every day all day and not mindengaging."
6,Anonymous employee,5.0,2016-02-16,Former employee,Great learning experience and support from the management.,I liked my experience overall. I didn't find any big challenges.
7,Mortgage banker,4.0,2020-11-08,Current employee,Provides unsecured loans to small and medium suzed businessesExcrllent online banking platforms,Not a very good employer but pays well if you get the chance.
8,R/o,3.0,2013-06-21,"Former employee, less than 1 year",Good personal image among the clients,Long working hours that isnt reflected on the salary
9,Manager,5.0,2014-01-08,"Former employee, more than 1 year",Growing company that works with people,So much growth its hard to keep up
10,Anonymous employee,3.0,2021-10-21,"Former employee, less than 1 year",Fellow young professionals to form personal and professional relationships with,Misogynistic culture prioritizing male employees over female ones
11,Anonymous employee,3.0,2016-02-29,Former employee,Very friendly people and work has real impact,Low salaries for interns barely enough to support oneself
12,Associate director,4.0,2015-05-19,"Current employee, more than 3 years",The work is ok but want more,Need more to be completely fulfilling
13,Commercial loan assistant,4.0,2021-03-25,Current employee,"Great people, great customers. Plenty of growth opportunities.",Processes could use some improvement.
14,Anonymous employee,4.0,2021-12-13,Current employee,good balance of work hours and job independence,The pay can definitely be much better
15,Teller,3.0,2021-04-04,"Current employee, more than 1 year","Flexible and helpful, fun activites through the year","Customers, lack of staffing at times"
16,Banker,1.0,2019-10-14,"Former employee, more than 5 years",Free coffee and friendly coworkers in the beginning,There was a constant mergers and acquisitions mindset of executive management without regards to employees who actually had to do the work. Very hostile work environment.
17,Administrative assistant,4.0,2022-06-09,Current employee,Nice people and great place to work..,Pay is average..but not the worst
18,Anonymous employee,4.0,2015-02-09,Former employee,"Hours are great, with half day saturday.",Sometimes not clearly defined roles
19,Anonymous employee,3.0,2017-09-21,Former employee,Great company to work at,monotonous work because of repeating it
20,Anonymous employee,3.0,2021-10-21,"Former employee, less than 1 year",Fellow young professionals to form personal and professional relationships with,Misogynistic culture prioritizing male employees over female ones
21,Anonymous employee,3.0,2016-02-29,Former employee,Very friendly people and work has real impact,Low salaries for interns barely enough to support oneself
22,Associate director,4.0,2015-05-19,"Current employee, more than 3 years",The work is ok but want more,Need more to be completely fulfilling
23,Commercial loan assistant,4.0,2021-03-25,Current employee,"Great people, great customers. Plenty of growth opportunities.",Processes could use some improvement.
24,Anonymous employee,4.0,2021-12-13,Current employee,good balance of work hours and job independence,The pay can definitely be much better
25,Teller,3.0,2021-04-04,"Current employee, more than 1 year","Flexible and helpful, fun activites through the year","Customers, lack of staffing at times"
26,Banker,1.0,2019-10-14,"Former employee, more than 5 years",Free coffee and friendly coworkers in the beginning,There was a constant mergers and acquisitions mindset of executive management without regards to employees who actually had to do the work. Very hostile work environment.
27,Administrative assistant,4.0,2022-06-09,Current employee,Nice people and great place to work..,Pay is average..but not the worst
28,Anonymous employee,4.0,2015-02-09,Former employee,"Hours are great, with half day saturday.",Sometimes not clearly defined roles
29,Anonymous employee,3.0,2017-09-21,Former employee,Great company to work at,monotonous work because of repeating it
50,Anonymous employee,4.0,2017-11-02,Former employee,It is a good place to work,Can be a bit monotonous
51,Recruiter,3.0,2020-08-21,Current employee,Great place to work mostly,Some managers suck but others are great
52,Anonymous employee,4.0,2021-03-16,"Former employee, more than 1 year","Very busy atmosphere, great coworkers","Benefits, Pay, Some Mangement Issues"
53,Credit analyst,2.0,2022-04-25,Former employee,The experience gained is good,The growth trajectory is not clear.
54,Post doctoral fellow,5.0,2021-02-13,Former employee,Yes this was really good,Nothing specific to note here
55,Customer service manager (csm),1.0,2021-04-02,"Former employee, more than 3 years",None that I ever found.,Everything from Branch Mangers to Vice Presidents telling anything but the truth. Human Resources was an absolute joke.
56,Manager,1.0,2022-03-29,"Former employee, more than 5 years",Absoltely None horrible environment to work.,Everything too many executives not enough people to do hands o. Work.
57,Relationship banker,2.0,2025-08-19,"Former employee, more than 5 years",Most aspects were manageable but the hr strategies in place are questionable,"It was good working at the company for a while but things shifted so fast. Dismissals nowadays comes with no notice or warning, treating staff like assets or items that you'd dispose anyhow is their thing nowodays, no matter how loyal you are. Tell me why they would expire a contract for a committed employee who've been there for more than five years, then bring some new staff and even before probation ends , they're confirmed as permanent staff..these are guys who have not even mastered the basic roles..but for you, you got to wait for 5 years and more been on contract only for them to end the contract without at least issuing a notice prior, mind you the performance is good and no disciplinary cases whatsoever,"
58,System engineer,3.0,2025-08-14,Former employee,Good employer with good experience,Long and late working hours
59,Noc engineer,3.0,2025-08-08,"Former employee, more than 3 years",A very nice and conducive work environmentFriendly and helpful colleagues,"No salary growth not unless you move departmentsBonus allocation is the sole decision of the management, not guaranteed yearly"
60,Anonymous employee,4.0,2017-11-02,Former employee,It is a good place to work,Can be a bit monotonous
61,Recruiter,3.0,2020-08-21,Current employee,Great place to work mostly,Some managers suck but others are great
62,Anonymous employee,4.0,2021-03-16,"Former employee, more than 1 year","Very busy atmosphere, great coworkers","Benefits, Pay, Some Mangement Issues"
63,Credit analyst,2.0,2022-04-25,Former employee,The experience gained is good,The growth trajectory is not clear.
64,Post doctoral fellow,5.0,2021-02-13,Former employee,Yes this was really good,Nothing specific to note here
65,Customer service manager (csm),1.0,2021-04-02,"Former employee, more than 3 years",None that I ever found.,Everything from Branch Mangers to Vice Presidents telling anything but the truth. Human Resources was an absolute joke.
66,Manager,1.0,2022-03-29,"Former employee, more than 5 years",Absoltely None horrible environment to work.,Everything too many executives not enough people to do hands o. Work.
67,Relationship banker,2.0,2025-08-19,"Former employee, more than 5 years",Most aspects were manageable but the hr strategies in place are questionable,"It was good working at the company for a while but things shifted so fast. Dismissals nowadays comes with no notice or warning, treating staff like assets or items that you'd dispose anyhow is their thing nowodays, no matter how loyal you are. Tell me why they would expire a contract for a committed employee who've been there for more than five years, then bring some new staff and even before probation ends , they're confirmed as permanent staff..these are guys who have not even mastered the basic roles..but for you, you got to wait for 5 years and more been on contract only for them to end the contract without at least issuing a notice prior, mind you the performance is good and no disciplinary cases whatsoever,"
68,System engineer,3.0,2025-08-14,Former employee,Good employer with good experience,Long and late working hours
69,Noc engineer,3.0,2025-08-08,"Former employee, more than 3 years",A very nice and conducive work environmentFriendly and helpful colleagues,"No salary growth not unless you move departmentsBonus allocation is the sole decision of the management, not guaranteed yearly"
70,Senior software engineer,4.0,2025-08-04,"Current employee, less than 1 year",Friendly staff and good offices,Strict dress code is quite annoying
71,Credit officer,2.0,2025-08-05,"Current employee, more than 5 years",Opportunity to learn and grow,No work life balance. Too much pressure
72,Relationship manager,1.0,2025-08-12,"Current employee, more than 10 years",the institution is okay to client,Unable to handle HR issues
73,Bank teller,1.0,2025-08-13,"Current employee, more than 5 years",No pros Terrible place to work,"Bad salary, bad company culture"
74,Senior operations manager,3.0,2025-06-30,"Current employee, more than 8 years",Exposure to a variety of roles and tasks. Great for experience garnering in a short period of time.,"Slow and unclear growth path. Demand for many long hours, poor work life balance."
75,Digital banking project manager,5.0,2025-07-15,"Former employee, more than 1 year",opportunity to lead impactful projects across E.Africacompetitive compensation and benefits,long working hours during system upgrades and product launches
76,Finance assistant,5.0,2025-07-14,"Current employee, more than 1 year",Strong corporate social responsibility.Massive exposure to all areas of banking.Highly ambitious leadership.,Extremely highpressure work environment.Limited internal mobility.
77,Relationship officer,1.0,2025-07-29,"Former employee, less than 1 year",They are good at keeping time when paying salary,"Unrealistic expectations.If you are on contract and you do not meet the goals, you will be terminated."
78,Relationship officer,1.0,2025-08-01,"Former employee, more than 5 years",Good rates on loans interest,Huge work load Not best pay
79,Relationship supervisor,3.0,2025-07-17,"Current employee, more than 5 years",Pay on time each month,No bonusRare salary increment Easy to get stuck
80,Bank teller,4.0,2025-07-15,"Former employee, less than 1 year",Good working environment and friendly colleagues,Peak times of the month can get very busy
81,Senior officer,1.0,2025-07-30,"Former employee, more than 1 year",Limited personal growthLow morale,"Poor pay, work overload, poor remuneration"
82,Senior payment officer/project coordinator/business analyst,3.0,2025-07-03,"Former employee, more than 8 years",Well structured in terms of department. Good team spirit,"Bad salary, increase not common and less benefits"
83,Security consultant,2.0,2025-07-09,"Current employee, more than 8 years",A field to learn and have a experince,no work life balanceNo salary increment poor pay comapred to the market rate
84,Business relationship officer,1.0,2025-06-16,"Former employee, more than 10 years",Perfect on job trainings. Good in terms of job experience,"Low staff morale due to poor pay and long working hours.Excessive pressure Inadequate facilitation when going down field work.Nepotism in hiring and job promotion hence a major cause of fraud in the bank the ksh 1.5 billion that was lost.Lack of avenue to pass creative ideas , i.e it's Mwangi's kiosk , you are supposed to be seen and not to be heard"
85,Bank teller,4.0,2025-07-01,"Former employee, more than 1 year",Good trainingMedical Insurance is provided,The pay was not good compared to the industry
86,Customer service representative,3.0,2025-06-24,"Former employee, less than 1 year",Good exposure Good pay and benefits,Micro mgt sometimes Rude customers
87,Loan officer,3.0,2025-06-23,"Former employee, more than 5 years",Good career growth whe you are consistent,Low work/life balance and long working hours
88,Accountant,3.0,2025-06-10,Current employee,they ensure top professionalism in handling clients and workers,There are no cons according to my experience
89,Associate director,5.0,2025-06-13,Former employee,You will learn more in 1 year than 5 years elsewhere,"Hight pressure, high stakes environment"
90,Relationship manager,2.0,2025-06-12,"Current employee, more than 5 years",Chance for growth for all professions,No job security is not guaranteed
91,Relationship manager,5.0,2025-06-06,"Former employee, more than 3 years",Unique customer culture experience. Positive impact on livelihoods,"Little growth past branch manager, High pressure working environment,"
92,Customer service representative,3.0,2025-06-07,Former employee,It was good for the beginning of my career,None at the time I was there
93,Relationship officer,4.0,2025-06-04,"Former employee, less than 1 year","employed when very, very young",bullied by the relationship manager
94,Product designer,2.0,2025-05-29,"Current employee, more than 1 year",Stable income because its a financial institution,Toxic Top Management who dont care about the employees
95,Relationship officer,2.0,2025-05-21,Former employee,It is a nice place to begin for fresh graduates,"Depending on the management, sometimes the work environment may not be great."
96,Relationship officer,2.0,2025-05-06,"Current employee, more than 1 year",Some level of flexibility in shift allocation,Very unhealthy micromanagement practicesMinimal support from group management i.e. no financial motivation or team activities Infringing on legally allocated working hours i.e. meetings before or after shift extending office hours
97,Sales manager,2.0,2025-05-25,Current employee,Nothing good just vibing there,Nothing for far I can’t complain
98,Relationship officer,5.0,2025-05-11,"Current employee, more than 5 years",Good working environmentWell paying,Currently I can only recommend internal promotions
99,Software engineer,3.0,2025-05-08,"Current employee, more than 10 years",job security World class bank,overworking no bonus
100,Relationship banker,3.0,2025-05-01,Current employee,Good medical insurance cover for staff,Non for now but the work pressure can be much
101,Relationship officer,1.0,2025-05-06,"Former employee, more than 10 years",Treat your employees with love and respect,Nothing good working for this bank
102,Hr operations,2.0,2025-04-03,"Former employee, more than 1 year",Easy decision making within the country,No process No HR systemsWear only suits
103,Supervisor,3.0,2025-03-27,"Former employee, more than 10 years","Permanent and pensionable terms, good structures in place","Long working hours, low salary, too much pressure and micromanagement"
104,Account manager,4.0,2025-04-07,"Current employee, less than 1 year",Good learning opportunities for new beis,Have to Work on a Saturday
105,Manager,3.0,2025-03-18,"Former employee, more than 3 years",Fairly good if you have an understanding General Manager,Limited room for growth and pay raise
106,Relationship officer,4.0,2025-03-23,Former employee,Salary is paid on time,Tough working schedule. from 7am to 4.30pm
107,Bank teller,2.0,2025-02-20,"Former employee, more than 1 year","Good employer when starting careerThey motivate employees to improve performance, Through this one can gain Self development skills and self discipline","Toxic and hostile working environmentPoor payLong working hoursOverworked, underpaidZero worklife balance Bound to experience burnout"
108,Data analyst,3.0,2025-02-28,"Current employee, more than 3 years",There is massive data to work on,"Leadership loves meeting even for little things that can be passed through an email. When you are about to focus on work, disruptions."
109,Data scientist,3.0,2025-03-13,Current employee,N0t Applicable at the moment,Lower pay for beginners but with experience it improves
110,Cashier,2.0,2025-03-15,"Former employee, less than 1 year","good,,pay timely,free tea, growth, culture",over work bad pay bad culture g
111,Payments officer,3.0,2025-03-10,"Former employee, more than 1 year","Does not need lots of experience,",The work environment can be unfriendly at times
112,Sales representative,5.0,2025-03-01,Former employee,Good employer in terms of renumeration,"None, apart from some security concerns raised by customers"
113,Credit officer,3.0,2025-01-28,"Former employee, more than 5 years",An opportunity to develop networks with different people.,"Unrealistic working hours, no consideration for new mothers, a lot of after hours work and meetings, inconsiderate and inhumane managers."
114,Team lead,2.0,2024-11-19,"Current employee, more than 3 years","Salary, interesting projects, money is not a problem in Equity.","Managers are a disaster. They'll kill finished and running projects on a whim. But MANY projects. They'll start many others, and you'll never know if those will be killed at some point. Managers are more interested in promoting themselves than in manage anything.Also, it's not unusual for them to fail to pay contractors. I've seen people working without getting paid for six months."
115,Customer relationship officer,3.0,2025-02-13,Former employee,A stable income and access to loans,The work is monotonous and repetitive
116,Manager,3.0,2025-01-27,"Current employee, more than 10 years",Learning experience is greatgood for start up,Governance not firmCulture needs a lot of shiftingNo promises on people motivation
117,Senior data analyst,3.0,2025-02-18,"Current employee, more than 1 year",Well outlined structures for the wellorganized.,Poor reporting lines and changeovers
118,Bank teller,5.0,2025-01-31,Current employee,it is very enguaging being a teller,non so far. hoping for the best
119,Channel sales,4.0,2025-01-20,"Current employee, more than 10 years",Strong brandStability and strong culture,"Less pay,lack of growth,poor work life balance"
120,Bank relationship officer,5.0,2025-01-19,"Former employee, less than 1 year",Experience in financial industryMentorship and learning opportunities,Maybe the fact that you have to start your days really earlyMonotony of bank operations
121,Legal officer,3.0,2025-01-29,"Current employee, more than 1 year",There are flexible working hours. No weekends,Not that challenging and intellectually stimulating

In [26]:
# check duplicate sum
def checkDuplicateSum(df: pd.DataFrame) -> int:
    duplicate_count = df.duplicated().sum()
    return 'Sum of Duplicate_Values =', duplicate_count
checkDuplicateSum(EquityRev)

('Sum of Duplicate_Values =', 20)

In [27]:
EquityRev.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60      True
61      True
62      True
63      True
64      True
65      True
66      True
67      True
68      True
69      True
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
395    False
396    False
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437    False
438    False
439    False
440    False
441    False
442    False
443    False
444    False
445    False
446    False
447    False
448    False
449    False
450    False
451    False
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
473    False
474    False
475    False
476    False
477    False
478    False
479    False
480    False
481    False
482    False
483    False
484    False
485    False
486    False
487    False
488    False
489    False
490    False
491    False
492    False
493    False
494    False
495    False
496    False
497    False
498    False
499    False
500    False
501    False
502    False
503    False
504    False
505    False
506    False
507    False
508    False
509    False
510    False
511    False
512    False
513    False
514    False
515    False
516    False
517    False
518    False
519    False
520    False
521    False
522    False
523    False
524    False
525    False
526    False
527    False
528    False
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
559    False
560    False
561    False
562    False
563    False
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580    False
581    False
582    False
583    False
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600    False
601    False
602    False
603    False
604    False
605    False
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
614    False
615    False
616    False
617    False
618    False
619    False
620    False
621    False
622    False
623    False
624    False
625    False
626    False
627    False
628    False
629    False
630    False
631    False
632    False
633    False
634    False
635    False
636    False
637    False
638    False
639    False
640    False
641    False
642    False
643    False
644    False
645    False
646    False
647    False
648    False
649    False
650    False
651    False
652    False
653    False
654    False
655    False
656    False
657    False
658    False
659    False
660    False
661    False
662    False
663    False
664    False
665    False
666    False
667    False
668    False
669    False
670    False
671    False
672    False
673    False
674    False
675    False
676    False
677    False
678    False
679    False
680    False
681    False
682    False
683    False
684    False
685    False
686    False
687    False
688    False
689    False
690    False
691    False
692    False
693    False
694    False
695    False
696    False
697    False
698    False
699    False
700    False
701    False
702    False
703    False
704    False
705    False
706    False
707    False
708    False
709    False
710    False
711    False
712    False
713    False
714    False
715    False
716    False
717    False
718    False
719    False
720    False
721    False
722    False
723    False
724    False
725    False
726    False
727    False
728    False
729    False
730    False
731    False
732    False
733    False
734    False
735    False
736    False
737    False
738    False
739    False
740    False
741    False
742    False
743    False
744    False
745    False
746    False
747    False
748    False
749    False
dtype: bool

In [34]:
EquityRev.iloc[20:29]

,Job Title,Job Rating,Time,Job Status,Pros,Cons,Company_Name
70,Senior software engineer,4.0,2025-08-04,"Current employee, less than 1 year",Friendly staff and good offices,Strict dress code is quite annoying,Equity
71,Credit officer,2.0,2025-08-05,"Current employee, more than 5 years",Opportunity to learn and grow,No work life balance. Too much pressure,Equity
72,Relationship manager,1.0,2025-08-12,"Current employee, more than 10 years",the institution is okay to client,Unable to handle HR issues,Equity
74,Senior operations manager,3.0,2025-06-30,"Current employee, more than 8 years",Exposure to a variety of roles and tasks. Great for experience garnering in a short period of time.,"Slow and unclear growth path. Demand for many long hours, poor work life balance.",Equity
75,Digital banking project manager,5.0,2025-07-15,"Former employee, more than 1 year",opportunity to lead impactful projects across E.Africacompetitive compensation and benefits,long working hours during system upgrades and product launches,Equity
76,Finance assistant,5.0,2025-07-14,"Current employee, more than 1 year",Strong corporate social responsibility.Massive exposure to all areas of banking.Highly ambitious leadership.,Extremely highpressure work environment.Limited internal mobility.,Equity
79,Relationship supervisor,3.0,2025-07-17,"Current employee, more than 5 years",Pay on time each month,No bonusRare salary increment Easy to get stuck,Equity
81,Senior officer,1.0,2025-07-30,"Former employee, more than 1 year",Limited personal growthLow morale,"Poor pay, work overload, poor remuneration",Equity
82,Senior payment officer/project coordinator/business analyst,3.0,2025-07-03,"Former employee, more than 8 years",Well structured in terms of department. Good team spirit,"Bad salary, increase not common and less benefits",Equity

In [29]:
def drop_duplicate(df: pd.DataFrame) -> int:
    """This function drops the duplicated 
        values in the dataset
    Args = df for the dataset
    return = this function returns a dataframe 
        withiout the duplicate values"""
    drop_duplicates = df.drop_duplicates(subset = ["Job Title"], inplace=True)
    return drop_duplicates
drop_duplicate(EquityRev)

In [30]:
Rows, columns = EquityRev.shape
print(f"Rows = {Rows}, columns = {columns}")

Rows = 268, columns = 6

In [36]:
EquityRev.reset_index(inplace=True)
# EquityRev.set_index("Job Title", inplace=True)
# Boltrev.drop("index", axis = 1, inplace=True)

In [37]:
EquityRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons,Company_Name
0,Credit administrator,5.0,2022-06-30,"Former employee, more than 5 years",Good culture environment and teamwork,Non applicable Non applicable,Equity
1,Sr. acct manager,1.0,2024-12-20,"Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected,Equity
2,Anonymous employee,4.0,2023-07-28,Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working,Equity
3,Bank teller,2.0,2021-03-01,"Former employee, more than 1 year",Nice coworkers and good work hours,You can tell the upper management doesn't care about lowerlevel employees,Equity
4,Relationship officer,4.0,2020-12-03,"Former employee, less than 1 year",Worked hand in hand with customers,"Other than client relations, tasks within the bank for this role were the same every day all day and not mindengaging.",Equity
5,Mortgage banker,4.0,2020-11-08,Current employee,Provides unsecured loans to small and medium suzed businessesExcrllent online banking platforms,Not a very good employer but pays well if you get the chance.,Equity
6,R/o,3.0,2013-06-21,"Former employee, less than 1 year",Good personal image among the clients,Long working hours that isnt reflected on the salary,Equity
7,Manager,5.0,2014-01-08,"Former employee, more than 1 year",Growing company that works with people,So much growth its hard to keep up,Equity
8,Associate director,4.0,2015-05-19,"Current employee, more than 3 years",The work is ok but want more,Need more to be completely fulfilling,Equity
9,Commercial loan assistant,4.0,2021-03-25,Current employee,"Great people, great customers. Plenty of growth opportunities.",Processes could use some improvement.,Equity
10,Teller,3.0,2021-04-04,"Current employee, more than 1 year","Flexible and helpful, fun activites through the year","Customers, lack of staffing at times",Equity
11,Banker,1.0,2019-10-14,"Former employee, more than 5 years",Free coffee and friendly coworkers in the beginning,There was a constant mergers and acquisitions mindset of executive management without regards to employees who actually had to do the work. Very hostile work environment.,Equity
12,Administrative assistant,4.0,2022-06-09,Current employee,Nice people and great place to work..,Pay is average..but not the worst,Equity
13,Recruiter,3.0,2020-08-21,Current employee,Great place to work mostly,Some managers suck but others are great,Equity
14,Credit analyst,2.0,2022-04-25,Former employee,The experience gained is good,The growth trajectory is not clear.,Equity
15,Post doctoral fellow,5.0,2021-02-13,Former employee,Yes this was really good,Nothing specific to note here,Equity
16,Customer service manager (csm),1.0,2021-04-02,"Former employee, more than 3 years",None that I ever found.,Everything from Branch Mangers to Vice Presidents telling anything but the truth. Human Resources was an absolute joke.,Equity
17,Relationship banker,2.0,2025-08-19,"Former employee, more than 5 years",Most aspects were manageable but the hr strategies in place are questionable,"It was good working at the company for a while but things shifted so fast. Dismissals nowadays comes with no notice or warning, treating staff like assets or items that you'd dispose anyhow is their thing nowodays, no matter how loyal you are. Tell me why they would expire a contract for a committed employee who've been there for more than five years, then bring some new staff and even before probation ends , they're confirmed as permanent staff..these are guys who have not even mastered the basic roles..but for you, you got to wait for 5 years and more been on contract only for them to end the contract without at least issuing a notice prior, mind you the performance is good and no disciplinary cases whatsoever,",Equity
18,System engineer,3.0,2025-08-14,Former employee,Good employer with good experience,Long and late working hours,Equity
19,Noc engineer,3.0,2025-08-08,"Former employee, more than 3 years",A very nice and conducive work environmentFriendly and helpful colleagues,"No salary growth not unless you move departmentsBonus allocation is the sole decision of the management, not guaranteed yearly",Equity
20,Senior software engineer,4.0,2025-08-04,"Current employee, less than 1 year",Friendly staff and good offices,Strict dress code is quite annoying,Equity
21,Credit officer,2.0,2025-08-05,"Current employee, more than 5 years",Opportunity to learn and grow,No work life balance. Too much pressure,Equity
22,Relationship manager,1.0,2025-08-12,"Current employee, more than 10 years",the institution is okay to client,Unable to handle HR issues,Equity
23,Senior operations manager,3.0,2025-06-30,"Current employee, more than 8 years",Exposure to a variety of roles and tasks. Great for experience garnering in a short period of time.,"Slow and unclear growth path. Demand for many long hours, poor work life balance.",Equity
24,Digital banking project manager,5.0,2025-07-15,"Former employee, more than 1 year",opportunity to lead impactful projects across E.Africacompetitive compensation and benefits,long working hours during system upgrades and product launches,Equity
25,Finance assistant,5.0,2025-07-14,"Current employee, more than 1 year",Strong corporate social responsibility.Massive exposure to all areas of banking.Highly ambitious leadership.,Extremely highpressure work environment.Limited internal mobility.,Equity
26,Relationship supervisor,3.0,2025-07-17,"Current employee, more than 5 years",Pay on time each month,No bonusRare salary increment Easy to get stuck,Equity
27,Senior officer,1.0,2025-07-30,"Former employee, more than 1 year",Limited personal growthLow morale,"Poor pay, work overload, poor remuneration",Equity
28,Senior payment officer/project coordinator/business analyst,3.0,2025-07-03,"Former employee, more than 8 years",Well structured in terms of department. Good team spirit,"Bad salary, increase not common and less benefits",Equity
29,Security consultant,2.0,2025-07-09,"Current employee, more than 8 years",A field to learn and have a experince,no work life balanceNo salary increment poor pay comapred to the market rate,Equity
30,Business relationship officer,1.0,2025-06-16,"Former employee, more than 10 years",Perfect on job trainings. Good in terms of job experience,"Low staff morale due to poor pay and long working hours.Excessive pressure Inadequate facilitation when going down field work.Nepotism in hiring and job promotion hence a major cause of fraud in the bank the ksh 1.5 billion that was lost.Lack of avenue to pass creative ideas , i.e it's Mwangi's kiosk , you are supposed to be seen and not to be heard",Equity
31,Customer service representative,3.0,2025-06-24,"Former employee, less than 1 year",Good exposure Good pay and benefits,Micro mgt sometimes Rude customers,Equity
32,Loan officer,3.0,2025-06-23,"Former employee, more than 5 years",Good career growth whe you are consistent,Low work/life balance and long working hours,Equity
33,Accountant,3.0,2025-06-10,Current employee,they ensure top professionalism in handling clients and workers,There are no cons according to my experience,Equity
34,Product designer,2.0,2025-05-29,"Current employee, more than 1 year",Stable income because its a financial institution,Toxic Top Management who dont care about the employees,Equity
35,Sales manager,2.0,2025-05-25,Current employee,Nothing good just vibing there,Nothing for far I can’t complain,Equity
36,Software engineer,3.0,2025-05-08,"Current employee, more than 10 years",job security World class bank,overworking no bonus,Equity
37,Hr operations,2.0,2025-04-03,"Former employee, more than 1 year",Easy decision making within the country,No process No HR systemsWear only suits,Equity
38,Supervisor,3.0,2025-03-27,"Former employee, more than 10 years","Permanent and pensionable terms, good structures in place","Long working hours, low salary, too much pressure and micromanagement",Equity
39,Account manager,4.0,2025-04-07,"Current employee, less than 1 year",Good learning opportunities for new beis,Have to Work on a Saturday,Equity
40,Data analyst,3.0,2025-02-28,"Current employee, more than 3 years",There is massive data to work on,"Leadership loves meeting even for little things that can be passed through an email. When you are about to focus on work, disruptions.",Equity
41,Data scientist,3.0,2025-03-13,Current employee,N0t Applicable at the moment,Lower pay for beginners but with experience it improves,Equity
42,Cashier,2.0,2025-03-15,"Former employee, less than 1 year","good,,pay timely,free tea, growth, culture",over work bad pay bad culture g,Equity
43,Payments officer,3.0,2025-03-10,"Former employee, more than 1 year","Does not need lots of experience,",The work environment can be unfriendly at times,Equity
44,Sales representative,5.0,2025-03-01,Former employee,Good employer in terms of renumeration,"None, apart from some security concerns raised by customers",Equity
45,Team lead,2.0,2024-11-19,"Current employee, more than 3 years","Salary, interesting projects, money is not a problem in Equity.","Managers are a disaster. They'll kill finished and running projects on a whim. But MANY projects. They'll start many others, and you'll never know if those will be killed at some point. Managers are more interested in promoting themselves than in manage anything.Also, it's not unusual for them to fail to pay contractors. I've seen people working without getting paid for six months.",Equity
46,Customer relationship officer,3.0,2025-02-13,Former employee,A stable income and access to loans,The work is monotonous and repetitive,Equity
47,Senior data analyst,3.0,2025-02-18,"Current employee, more than 1 year",Well outlined structures for the wellorganized.,Poor reporting lines and changeovers,Equity
48,Channel sales,4.0,2025-01-20,"Current employee, more than 10 years",Strong brandStability and strong culture,"Less pay,lack of growth,poor work life balance",Equity
49,Bank relationship officer,5.0,2025-01-19,"Former employee, less than 1 year",Experience in financial industryMentorship and learning opportunities,Maybe the fact that you have to start your days really earlyMonotony of bank operations,Equity
50,Legal officer,3.0,2025-01-29,"Current employee, more than 1 year",There are flexible working hours. No weekends,Not that challenging and intellectually stimulating,Equity
51,Senior test analyst,2.0,2024-09-17,"Former employee, more than 3 years",Good support from other colleaguesSome good work on induction and onboarding,Lots of org politics you dont have a sayNot very conducive office environmentThe managers are oldfashioned expect lots of traditional work systemsWork burnout os crazy you have to work on saturdays and late hours on weekdaysDress code is a total bummer suits for men from mon to saturdays and offical dressing for women. No innovation you wont have a chance becaue of the traiditional setup. unpredictable contracts not sure when you'll be shown the door unnanounced.,Equity
52,Assistant manager,5.0,2025-01-24,Current employee,Benefits are really good. Team is good,Nothing as of now. Amazing exp,Equity
53,Internal controls specialist,3.0,2025-01-15,"Current employee, more than 8 years",Great place to learn. A bunch of different industries in one holding.,Worklife balance may not be achievable in some instances.,Equity
54,Bancassurance officer,1.0,2025-01-23,"Current employee, more than 3 years",Nothing special about equity bank. Work life balance is a story there.,Not worth it. Unrealistic targets. No proper channels for handling issues. A whole bank having communication breakdown. Even managers have no idea of what's happening in the bank? That's crazy,Equity
55,Quality assurance analyst,4.0,2025-01-15,"Former employee, more than 1 year",amazing health insurance and hazard pay,The strict apparel rules and long working hours,Equity
56,E-channels officer,3.0,2025-01-20,Current employee,You can gain useful experience,There are few growth opportunities,Equity
57,Facilities engineer,3.0,2025-01-01,"Former employee, more than 3 years",Very engaging and enjoyable. The role grows you,Too much work and less pay,Equity
58,Senior bancassurance sales executive,4.0,2025-01-03,"Current employee, more than 5 years",Great working here and experience is also great,Time consuming and lots of workload,Equity
59,Senior erp support analyst,3.0,2025-01-09,"Current employee, more than 10 years",Good medical insurancefree parking,no bonusessporadic salary review,Equity
60,Backend developer,4.0,2025-01-01,"Former employee, less than 1 year",Flexible work hoursFriendly work environment,Leave application procedure could be improved.,Equity
61,Trade finance officer,4.0,2024-09-24,"Former employee, more than 3 years",Great learning environment with diverse nature of transactions.Investment in employees learning and development,Deepstate kind of system in hiring and internal promotions leading to demoralization of hardworking employees.,Equity
62,"Anonymous, head office",3.0,2024-12-04,"Current employee, more than 1 year",Fast paced environment good for learningamazing talent,no recognition no salary increamentno work life balanceculture is outdatedpoor management,Equity
63,Payment officer,5.0,2024-11-07,Former employee,The company will properly train you for the job market. Would recommend as a first job especially if you’re looking to stay in banking,Worklife balance is almost non existent,Equity
64,Treasury assistant,4.0,2024-09-07,Current employee,Your job security is assured unless you find yourself with a fraud case.Targets are easily achieved due to huge number of customersFriendly workmatesLeaders are simple and ordinary,Your salary will rarely grow mostly after every 3 years but not assuredNo bonuses,Equity
65,Analyst,3.0,2024-11-24,Current employee,"Good employer thus far, no issues.","None, just work hard and keep your head down.",Equity
66,Aml analyst,3.0,2023-10-30,"Former employee, more than 8 years","The entity is awesome in terms of case studies, all kinds of typology can seen from their huge customer base. A great place to learn alot. Global Certification paid for by the company.","The salaries are way below market prices ,a certified aml specialist is paid less than Kshs 135,000 including assistant managers. Tribal issuesKikuyu Centered organization and ladies who are open to relationships with bosses tend to be elevated more because 90% of the managers are men. Alot of specialization hence cant create an all round officer to fit outside roles if you exit the organization. The medical cover is BS,you can only go to one hospital which is sponsored by the bank and full of quack doctors. No unsecured loans Reduced repayment period for some facilities compared to other banks. The CEO does increments and bonuses depending on his mood, you can stay for almost 3 years without anything yet the banks makes the highest profit in the region among banks. A lot of micro managing in the entity, multiple disparity in salaries between people doing same role . Employees have no say even when feeling oppressed.",Equity
67,Cashier/sales associate,4.0,2024-10-17,Former employee,Fastest growing bank in the region,Low salaries compared to other banks of similar size,Equity
68,Operations,2.0,2024-10-01,"Former employee, more than 5 years",You learn a lot and work soooo much. You can work anywhere after that,"No rest, if not careful you'll have no life outside work",Equity
69,Sales associate,3.0,2024-10-24,"Former employee, less than 1 year",Friendly staff.Acceptable work environment,Long hoursCompetitive6 days a week,Equity
70,Technology analyst,1.0,2024-11-21,Current employee,a lot to learn because its fast paced,toxic work environment and power with individuals,Equity
71,Student equity leadership position,5.0,2024-09-06,"Former employee, less than 1 year",It's a great company and offers satisfying solutions to all finance related problems.,So far so good. I have not seen any problem at Equity Bank Kenya.,Equity
72,Business analyst,2.0,2024-09-30,"Former employee, more than 3 years",Personal Growth in terms work and career,Renumeration is not comensurate to the role and rank,Equity
73,It project manager,4.0,2024-10-07,Current employee,Good experinece and diverse teams,Lots of workToo much pressure,Equity
74,Relationship officer credit,1.0,2024-10-09,"Former employee, more than 3 years",Salary paid on time between 24th_26th,Be prepared to be talked to rudely by the credit sector head like biashara banking and their regional manager,Equity
75,Operations manager,4.0,2024-09-24,"Current employee, more than 10 years",Quite a lot to learn,Requires patience when working as you learn,Equity
76,Talent acquisition manager,2.0,2024-09-01,"Current employee, less than 1 year","Career Mobility, competitive, professional growth","Irregular bonus, concerning culture, bureaucratic, no compensation review",Equity
77,Operations officer,3.0,2024-08-30,"Current employee, more than 3 years","The company is gender balanced, everyone has an equal chance of up taking a role which is merit based",Staff on contractual terms are not confirmed on time,Equity
78,It officer,3.0,2024-07-27,"Former employee, more than 1 year","Fast paced environment, great for learning.",Salary and bonus reviews are not standardized. Managers in most depts have free reign. Organization culture doesn't change with the times.,Equity
79,Procurement officer,5.0,2024-08-29,"Current employee, more than 3 years",Good work environmentExtra educational plans and webinarsRewarded well,Actually there is not even a single con,Equity
80,Network engineer,4.0,2024-08-20,"Former employee, more than 1 year",very nice place to grow in terms of technical knowledge,not good environment in terms of job promotion,Equity
81,Cash and liquidity management,1.0,2024-10-07,"Former employee, more than 10 years",Good loans at cheap rates,No bonus. No salary increment.,Equity
82,Senior manager,3.0,2024-07-18,"Current employee, more than 10 years",Visionary with a huge impact on the society,Unclear policies Unclear structure and organisational roles and responsibilities Unstructured performance management,Equity
83,Reltionship manager,2.0,2024-08-15,"Former employee, more than 3 years",Accessibility to loan facilities and insurance,Unprofessional and untrained supervisors and managers,Equity
84,Client relationship supervisor,3.0,2024-07-15,Former employee,Staff benefits are good and there is access to the best medical facilities.,None I can think of at the moment,Equity
85,Security analyst,1.0,2024-10-01,Former employee,Low pay and not consistent,Late pay and unfair and bure,Equity
86,Project management,3.0,2024-08-07,"Current employee, less than 1 year",amazing onboarding and outreach for incoming staff,Tedious process for exiting employees,Equity
87,Group head of business continuity,4.0,2024-07-27,"Current employee, more than 3 years",Great Place to get experience,The Work is a lot in comparison to the Compensation,Equity
88,Marketing,4.0,2024-06-27,Former employee,"Very selling brand,proper branding, proper working condition",Streachy targets that maximizes full potential. I feel motivated having those targets,Equity
89,Contact center representative,3.0,2024-07-15,"Current employee, more than 3 years",Very professionalGood working environment,Slow career growth/shufflingincreament in salary yearly,Equity
90,Senior analyst,3.0,2024-06-08,"Former employee, more than 3 years","The best place to start out ones career, the scale of operations and the lack of distinct specializations makes you interact with a lot of things. You learn alot","Growth, both career progression and salary, is very slow",Equity
91,Human rseources,5.0,2024-07-18,"Current employee, less than 1 year",Work life balanceGreat r enumeration,None at the moment noted,Equity

In [33]:
EquityRev.insert(6,"Company_Name", "Equity")

In [44]:
path = "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CleanCompanyRev/Equity.csv"

In [45]:
EquityRev.to_csv(path, index=False)

In [46]:
df = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CleanCompanyRev/Equity.csv")
df

,Job Title,Job Rating,Time,Job Status,Pros,Cons,Company_Name
0,Credit administrator,5.0,2022-06-30,"Former employee, more than 5 years",Good culture environment and teamwork,Non applicable Non applicable,Equity
1,Sr. acct manager,1.0,2024-12-20,"Former employee, more than 5 years",Dont chose to work for this toddler ran company.,Low pay and long hours expected,Equity
2,Anonymous employee,4.0,2023-07-28,Current employee,Big ambition to grow horizontally and leadership,Bureaucracy due to the age of the org and historical ways of working,Equity
3,Bank teller,2.0,2021-03-01,"Former employee, more than 1 year",Nice coworkers and good work hours,You can tell the upper management doesn't care about lowerlevel employees,Equity
4,Relationship officer,4.0,2020-12-03,"Former employee, less than 1 year",Worked hand in hand with customers,"Other than client relations, tasks within the bank for this role were the same every day all day and not mindengaging.",Equity
5,Mortgage banker,4.0,2020-11-08,Current employee,Provides unsecured loans to small and medium suzed businessesExcrllent online banking platforms,Not a very good employer but pays well if you get the chance.,Equity
6,R/o,3.0,2013-06-21,"Former employee, less than 1 year",Good personal image among the clients,Long working hours that isnt reflected on the salary,Equity
7,Manager,5.0,2014-01-08,"Former employee, more than 1 year",Growing company that works with people,So much growth its hard to keep up,Equity
8,Associate director,4.0,2015-05-19,"Current employee, more than 3 years",The work is ok but want more,Need more to be completely fulfilling,Equity
9,Commercial loan assistant,4.0,2021-03-25,Current employee,"Great people, great customers. Plenty of growth opportunities.",Processes could use some improvement.,Equity
10,Teller,3.0,2021-04-04,"Current employee, more than 1 year","Flexible and helpful, fun activites through the year","Customers, lack of staffing at times",Equity
11,Banker,1.0,2019-10-14,"Former employee, more than 5 years",Free coffee and friendly coworkers in the beginning,There was a constant mergers and acquisitions mindset of executive management without regards to employees who actually had to do the work. Very hostile work environment.,Equity
12,Administrative assistant,4.0,2022-06-09,Current employee,Nice people and great place to work..,Pay is average..but not the worst,Equity
13,Recruiter,3.0,2020-08-21,Current employee,Great place to work mostly,Some managers suck but others are great,Equity
14,Credit analyst,2.0,2022-04-25,Former employee,The experience gained is good,The growth trajectory is not clear.,Equity
15,Post doctoral fellow,5.0,2021-02-13,Former employee,Yes this was really good,Nothing specific to note here,Equity
16,Customer service manager (csm),1.0,2021-04-02,"Former employee, more than 3 years",None that I ever found.,Everything from Branch Mangers to Vice Presidents telling anything but the truth. Human Resources was an absolute joke.,Equity
17,Relationship banker,2.0,2025-08-19,"Former employee, more than 5 years",Most aspects were manageable but the hr strategies in place are questionable,"It was good working at the company for a while but things shifted so fast. Dismissals nowadays comes with no notice or warning, treating staff like assets or items that you'd dispose anyhow is their thing nowodays, no matter how loyal you are. Tell me why they would expire a contract for a committed employee who've been there for more than five years, then bring some new staff and even before probation ends , they're confirmed as permanent staff..these are guys who have not even mastered the basic roles..but for you, you got to wait for 5 years and more been on contract only for them to end the contract without at least issuing a notice prior, mind you the performance is good and no disciplinary cases whatsoever,",Equity
18,System engineer,3.0,2025-08-14,Former employee,Good employer with good experience,Long and late working hours,Equity
19,Noc engineer,3.0,2025-08-08,"Former employee, more than 3 years",A very nice and conducive work environmentFriendly and helpful colleagues,"No salary growth not unless you move departmentsBonus allocation is the sole decision of the management, not guaranteed yearly",Equity
20,Senior software engineer,4.0,2025-08-04,"Current employee, less than 1 year",Friendly staff and good offices,Strict dress code is quite annoying,Equity
21,Credit officer,2.0,2025-08-05,"Current employee, more than 5 years",Opportunity to learn and grow,No work life balance. Too much pressure,Equity
22,Relationship manager,1.0,2025-08-12,"Current employee, more than 10 years",the institution is okay to client,Unable to handle HR issues,Equity
23,Senior operations manager,3.0,2025-06-30,"Current employee, more than 8 years",Exposure to a variety of roles and tasks. Great for experience garnering in a short period of time.,"Slow and unclear growth path. Demand for many long hours, poor work life balance.",Equity
24,Digital banking project manager,5.0,2025-07-15,"Former employee, more than 1 year",opportunity to lead impactful projects across E.Africacompetitive compensation and benefits,long working hours during system upgrades and product launches,Equity
25,Finance assistant,5.0,2025-07-14,"Current employee, more than 1 year",Strong corporate social responsibility.Massive exposure to all areas of banking.Highly ambitious leadership.,Extremely highpressure work environment.Limited internal mobility.,Equity
26,Relationship supervisor,3.0,2025-07-17,"Current employee, more than 5 years",Pay on time each month,No bonusRare salary increment Easy to get stuck,Equity
27,Senior officer,1.0,2025-07-30,"Former employee, more than 1 year",Limited personal growthLow morale,"Poor pay, work overload, poor remuneration",Equity
28,Senior payment officer/project coordinator/business analyst,3.0,2025-07-03,"Former employee, more than 8 years",Well structured in terms of department. Good team spirit,"Bad salary, increase not common and less benefits",Equity
29,Security consultant,2.0,2025-07-09,"Current employee, more than 8 years",A field to learn and have a experince,no work life balanceNo salary increment poor pay comapred to the market rate,Equity
30,Business relationship officer,1.0,2025-06-16,"Former employee, more than 10 years",Perfect on job trainings. Good in terms of job experience,"Low staff morale due to poor pay and long working hours.Excessive pressure Inadequate facilitation when going down field work.Nepotism in hiring and job promotion hence a major cause of fraud in the bank the ksh 1.5 billion that was lost.Lack of avenue to pass creative ideas , i.e it's Mwangi's kiosk , you are supposed to be seen and not to be heard",Equity
31,Customer service representative,3.0,2025-06-24,"Former employee, less than 1 year",Good exposure Good pay and benefits,Micro mgt sometimes Rude customers,Equity
32,Loan officer,3.0,2025-06-23,"Former employee, more than 5 years",Good career growth whe you are consistent,Low work/life balance and long working hours,Equity
33,Accountant,3.0,2025-06-10,Current employee,they ensure top professionalism in handling clients and workers,There are no cons according to my experience,Equity
34,Product designer,2.0,2025-05-29,"Current employee, more than 1 year",Stable income because its a financial institution,Toxic Top Management who dont care about the employees,Equity
35,Sales manager,2.0,2025-05-25,Current employee,Nothing good just vibing there,Nothing for far I can’t complain,Equity
36,Software engineer,3.0,2025-05-08,"Current employee, more than 10 years",job security World class bank,overworking no bonus,Equity
37,Hr operations,2.0,2025-04-03,"Former employee, more than 1 year",Easy decision making within the country,No process No HR systemsWear only suits,Equity
38,Supervisor,3.0,2025-03-27,"Former employee, more than 10 years","Permanent and pensionable terms, good structures in place","Long working hours, low salary, too much pressure and micromanagement",Equity
39,Account manager,4.0,2025-04-07,"Current employee, less than 1 year",Good learning opportunities for new beis,Have to Work on a Saturday,Equity
40,Data analyst,3.0,2025-02-28,"Current employee, more than 3 years",There is massive data to work on,"Leadership loves meeting even for little things that can be passed through an email. When you are about to focus on work, disruptions.",Equity
41,Data scientist,3.0,2025-03-13,Current employee,N0t Applicable at the moment,Lower pay for beginners but with experience it improves,Equity
42,Cashier,2.0,2025-03-15,"Former employee, less than 1 year","good,,pay timely,free tea, growth, culture",over work bad pay bad culture g,Equity
43,Payments officer,3.0,2025-03-10,"Former employee, more than 1 year","Does not need lots of experience,",The work environment can be unfriendly at times,Equity
44,Sales representative,5.0,2025-03-01,Former employee,Good employer in terms of renumeration,"None, apart from some security concerns raised by customers",Equity
45,Team lead,2.0,2024-11-19,"Current employee, more than 3 years","Salary, interesting projects, money is not a problem in Equity.","Managers are a disaster. They'll kill finished and running projects on a whim. But MANY projects. They'll start many others, and you'll never know if those will be killed at some point. Managers are more interested in promoting themselves than in manage anything.Also, it's not unusual for them to fail to pay contractors. I've seen people working without getting paid for six months.",Equity
46,Customer relationship officer,3.0,2025-02-13,Former employee,A stable income and access to loans,The work is monotonous and repetitive,Equity
47,Senior data analyst,3.0,2025-02-18,"Current employee, more than 1 year",Well outlined structures for the wellorganized.,Poor reporting lines and changeovers,Equity
48,Channel sales,4.0,2025-01-20,"Current employee, more than 10 years",Strong brandStability and strong culture,"Less pay,lack of growth,poor work life balance",Equity
49,Bank relationship officer,5.0,2025-01-19,"Former employee, less than 1 year",Experience in financial industryMentorship and learning opportunities,Maybe the fact that you have to start your days really earlyMonotony of bank operations,Equity
50,Legal officer,3.0,2025-01-29,"Current employee, more than 1 year",There are flexible working hours. No weekends,Not that challenging and intellectually stimulating,Equity
51,Senior test analyst,2.0,2024-09-17,"Former employee, more than 3 years",Good support from other colleaguesSome good work on induction and onboarding,Lots of org politics you dont have a sayNot very conducive office environmentThe managers are oldfashioned expect lots of traditional work systemsWork burnout os crazy you have to work on saturdays and late hours on weekdaysDress code is a total bummer suits for men from mon to saturdays and offical dressing for women. No innovation you wont have a chance becaue of the traiditional setup. unpredictable contracts not sure when you'll be shown the door unnanounced.,Equity
52,Assistant manager,5.0,2025-01-24,Current employee,Benefits are really good. Team is good,Nothing as of now. Amazing exp,Equity
53,Internal controls specialist,3.0,2025-01-15,"Current employee, more than 8 years",Great place to learn. A bunch of different industries in one holding.,Worklife balance may not be achievable in some instances.,Equity
54,Bancassurance officer,1.0,2025-01-23,"Current employee, more than 3 years",Nothing special about equity bank. Work life balance is a story there.,Not worth it. Unrealistic targets. No proper channels for handling issues. A whole bank having communication breakdown. Even managers have no idea of what's happening in the bank? That's crazy,Equity
55,Quality assurance analyst,4.0,2025-01-15,"Former employee, more than 1 year",amazing health insurance and hazard pay,The strict apparel rules and long working hours,Equity
56,E-channels officer,3.0,2025-01-20,Current employee,You can gain useful experience,There are few growth opportunities,Equity
57,Facilities engineer,3.0,2025-01-01,"Former employee, more than 3 years",Very engaging and enjoyable. The role grows you,Too much work and less pay,Equity
58,Senior bancassurance sales executive,4.0,2025-01-03,"Current employee, more than 5 years",Great working here and experience is also great,Time consuming and lots of workload,Equity
59,Senior erp support analyst,3.0,2025-01-09,"Current employee, more than 10 years",Good medical insurancefree parking,no bonusessporadic salary review,Equity
60,Backend developer,4.0,2025-01-01,"Former employee, less than 1 year",Flexible work hoursFriendly work environment,Leave application procedure could be improved.,Equity
61,Trade finance officer,4.0,2024-09-24,"Former employee, more than 3 years",Great learning environment with diverse nature of transactions.Investment in employees learning and development,Deepstate kind of system in hiring and internal promotions leading to demoralization of hardworking employees.,Equity
62,"Anonymous, head office",3.0,2024-12-04,"Current employee, more than 1 year",Fast paced environment good for learningamazing talent,no recognition no salary increamentno work life balanceculture is outdatedpoor management,Equity
63,Payment officer,5.0,2024-11-07,Former employee,The company will properly train you for the job market. Would recommend as a first job especially if you’re looking to stay in banking,Worklife balance is almost non existent,Equity
64,Treasury assistant,4.0,2024-09-07,Current employee,Your job security is assured unless you find yourself with a fraud case.Targets are easily achieved due to huge number of customersFriendly workmatesLeaders are simple and ordinary,Your salary will rarely grow mostly after every 3 years but not assuredNo bonuses,Equity
65,Analyst,3.0,2024-11-24,Current employee,"Good employer thus far, no issues.","None, just work hard and keep your head down.",Equity
66,Aml analyst,3.0,2023-10-30,"Former employee, more than 8 years","The entity is awesome in terms of case studies, all kinds of typology can seen from their huge customer base. A great place to learn alot. Global Certification paid for by the company.","The salaries are way below market prices ,a certified aml specialist is paid less than Kshs 135,000 including assistant managers. Tribal issuesKikuyu Centered organization and ladies who are open to relationships with bosses tend to be elevated more because 90% of the managers are men. Alot of specialization hence cant create an all round officer to fit outside roles if you exit the organization. The medical cover is BS,you can only go to one hospital which is sponsored by the bank and full of quack doctors. No unsecured loans Reduced repayment period for some facilities compared to other banks. The CEO does increments and bonuses depending on his mood, you can stay for almost 3 years without anything yet the banks makes the highest profit in the region among banks. A lot of micro managing in the entity, multiple disparity in salaries between people doing same role . Employees have no say even when feeling oppressed.",Equity
67,Cashier/sales associate,4.0,2024-10-17,Former employee,Fastest growing bank in the region,Low salaries compared to other banks of similar size,Equity
68,Operations,2.0,2024-10-01,"Former employee, more than 5 years",You learn a lot and work soooo much. You can work anywhere after that,"No rest, if not careful you'll have no life outside work",Equity
69,Sales associate,3.0,2024-10-24,"Former employee, less than 1 year",Friendly staff.Acceptable work environment,Long hoursCompetitive6 days a week,Equity
70,Technology analyst,1.0,2024-11-21,Current employee,a lot to learn because its fast paced,toxic work environment and power with individuals,Equity
71,Student equity leadership position,5.0,2024-09-06,"Former employee, less than 1 year",It's a great company and offers satisfying solutions to all finance related problems.,So far so good. I have not seen any problem at Equity Bank Kenya.,Equity
72,Business analyst,2.0,2024-09-30,"Former employee, more than 3 years",Personal Growth in terms work and career,Renumeration is not comensurate to the role and rank,Equity
73,It project manager,4.0,2024-10-07,Current employee,Good experinece and diverse teams,Lots of workToo much pressure,Equity
74,Relationship officer credit,1.0,2024-10-09,"Former employee, more than 3 years",Salary paid on time between 24th_26th,Be prepared to be talked to rudely by the credit sector head like biashara banking and their regional manager,Equity
75,Operations manager,4.0,2024-09-24,"Current employee, more than 10 years",Quite a lot to learn,Requires patience when working as you learn,Equity
76,Talent acquisition manager,2.0,2024-09-01,"Current employee, less than 1 year","Career Mobility, competitive, professional growth","Irregular bonus, concerning culture, bureaucratic, no compensation review",Equity
77,Operations officer,3.0,2024-08-30,"Current employee, more than 3 years","The company is gender balanced, everyone has an equal chance of up taking a role which is merit based",Staff on contractual terms are not confirmed on time,Equity
78,It officer,3.0,2024-07-27,"Former employee, more than 1 year","Fast paced environment, great for learning.",Salary and bonus reviews are not standardized. Managers in most depts have free reign. Organization culture doesn't change with the times.,Equity
79,Procurement officer,5.0,2024-08-29,"Current employee, more than 3 years",Good work environmentExtra educational plans and webinarsRewarded well,Actually there is not even a single con,Equity
80,Network engineer,4.0,2024-08-20,"Former employee, more than 1 year",very nice place to grow in terms of technical knowledge,not good environment in terms of job promotion,Equity
81,Cash and liquidity management,1.0,2024-10-07,"Former employee, more than 10 years",Good loans at cheap rates,No bonus. No salary increment.,Equity
82,Senior manager,3.0,2024-07-18,"Current employee, more than 10 years",Visionary with a huge impact on the society,Unclear policies Unclear structure and organisational roles and responsibilities Unstructured performance management,Equity
83,Reltionship manager,2.0,2024-08-15,"Former employee, more than 3 years",Accessibility to loan facilities and insurance,Unprofessional and untrained supervisors and managers,Equity
84,Client relationship supervisor,3.0,2024-07-15,Former employee,Staff benefits are good and there is access to the best medical facilities.,None I can think of at the moment,Equity
85,Security analyst,1.0,2024-10-01,Former employee,Low pay and not consistent,Late pay and unfair and bure,Equity
86,Project management,3.0,2024-08-07,"Current employee, less than 1 year",amazing onboarding and outreach for incoming staff,Tedious process for exiting employees,Equity
87,Group head of business continuity,4.0,2024-07-27,"Current employee, more than 3 years",Great Place to get experience,The Work is a lot in comparison to the Compensation,Equity
88,Marketing,4.0,2024-06-27,Former employee,"Very selling brand,proper branding, proper working condition",Streachy targets that maximizes full potential. I feel motivated having those targets,Equity
89,Contact center representative,3.0,2024-07-15,"Current employee, more than 3 years",Very professionalGood working environment,Slow career growth/shufflingincreament in salary yearly,Equity
90,Senior analyst,3.0,2024-06-08,"Former employee, more than 3 years","The best place to start out ones career, the scale of operations and the lack of distinct specializations makes you interact with a lot of things. You learn alot","Growth, both career progression and salary, is very slow",Equity
91,Human rseources,5.0,2024-07-18,"Current employee, less than 1 year",Work life balanceGreat r enumeration,None at the moment noted,Equity