<a href="https://colab.research.google.com/github/Brian342/JupyterAI-Clean/blob/main/GoogleReviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
import numpy as np

In [82]:
# from google.colab import files
# uploaded = files.upload()

In [83]:
GoogleRev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/googleReviews.csv")

In [84]:
# EDA on the data
def display(x):
    """This function returns a
    summary of the dataset"""

    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(GoogleRev)

Displays the rows and columns in the dataset
============================================
Rows: 42430 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                                  Job Title  Job Ratings          time  \
0                          Program manager          4.0  Jun 21, 2013
1                    Software engineer iii          5.0  May 10, 2014
2                       Anonymous employee          5.0   Feb 8, 2015
3                          Program manager          4.0   Aug 5, 2025
4      Software development engineer (sde)          4.0  Jul 28, 2025
...                                    ...          ...           ...
42425                   Anonymous employee          5.0  Sep 27, 2022
42426                      Sales associate          5.0  Sep 28, 2022
42427                        Web developer          5.0  Sep 28, 2022
42428                            Marketing          4.0  Sep 28, 2022
42429                 Sales representative          4.0  Sep 28, 2022

                                 JobStatus  \
0       Former employee, more than 8 years
1       Current employee, more than 1 year
2                         Current employee
3      Current employee, more than 3 years
4                          Former employee
...                                    ...
42425                     Current employee
42426                     Current employee
42427   Current employee, more than 1 year
42428    Former employee, more than 1 year
42429                     Current employee

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Pros  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1) Food, food, food.  15+ cafes on main campus (MTV) alone.  Mini-kitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day.\r\n\r\n2) Benefits/perks.  Free 24:7 gym access (on MTV campus).  Free (self service) laundry (washer/dryer) available.  Bowling alley.  Volley ball pit.  Custom-built and exclusive employee use only outdoor sport park (MTV).  Free health/fitness assessments.  Dog-friendly.  Etc. etc. etc.\r\n\r\n3) Compensation.  In ~2010 or 2011, Google updated its compensation packages so that they were more competitive.  \r\n\r\n4) For the size of the organization (30K+), it has remained relatively innovative, nimble, and fast-paced and open with communication but, that is definitely changing (for the worse).\r\n\r\n5) With so many departments, focus areas, and products, *in theory*, you should have plenty of opportunity to grow your career (horizontally or vertically).  In practice, not true.  \r\n\r\n6)  You get to work with some of the brightest, most innovative and hard-working/diligent minds in the industry.  There's a "con" to that, too (see below).
1      * If you're a software engineer, you're among the kings of the hill at Google. It's an engineer-driven company without a doubt (that *is* changing, but it's still very engineer-focused).\r\n* The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties (at Waldorf Astoria, NY Public Library, MoMA, etc.); overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially.\r\n* Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants.\r\n* There a huge diversity of work ranging from defending independent journalism worldwide (Google Project Shield) to crisis response during disasters (see Maps during Hurricane Sandy or Tsunamis), to the best machine learning experts and projects in the world, to more mundane revenue-driving projects in advertising, there's really something for everybody.\r\n* It's easy to move around within the company as long as you're in good standing (the vast majority of engineers are).\r\n* The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive.\r\n* No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible.\r\n\r\nNeither pro nor con, but general information on work-life balance, promotions, and advancement.\r\n* Work life balance can be what you want it to be on most teams. (Some teams are in more competitive sectors and require more crazy hours all the time - but very few of them). If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hyper-motived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still - and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand.\r\n* If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance "even at Google" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google -- smarter than average, but just average compared to other Googlers -- you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer (it's the minimum requirement), but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        You can't find a more well-regarded company that actually deserves the hype it gets.\r\n\r\nYou'll work on cutting edge projects / solve important issues that impact your community and the world\r\n\r\nYou'll meet interesting people who are your colleagues, managers, and senior management.\r\n\r\nYou'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing\r\n\r\nYou'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. \r\n\r\nThere are 22 cafes (more or less), the food is excellent, and it's free.\r\n\r\nYour pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved.\r\n\r\nGoogle cares about how it treats its employees.\r\n\r\nThe campus is like an academic campus in many ways.\r\n\r\nThere are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out - but you'll need to make sure to carve out time to do these things.\r\n\r\nYou'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google.\r\n\r\nIf and when you leave, you'll never regret having that company on your resume. It opens doors. \r\n\r\nThe company is flexible - if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work - but don't get me wrong - you'll work a LOT. But you don't have to do all of it chained to your desk.

In [85]:
# display the whole text
pd.set_option("display.max_colwidth", None)

In [86]:
# printing the first 20 elements on the dataset
print("first 5 elements")
print("=====================================================")
print()
GoogleRev.head(5)

first 5 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Program manager,4.0,"Jun 21, 2013","Former employee, more than 8 years","1) Food, food, food. 15+ cafes on main campus (MTV) alone. Mini-kitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day.\r\n\r\n2) Benefits/perks. Free 24:7 gym access (on MTV campus). Free (self service) laundry (washer/dryer) available. Bowling alley. Volley ball pit. Custom-built and exclusive employee use only outdoor sport park (MTV). Free health/fitness assessments. Dog-friendly. Etc. etc. etc.\r\n\r\n3) Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. \r\n\r\n4) For the size of the organization (30K+), it has remained relatively innovative, nimble, and fast-paced and open with communication but, that is definitely changing (for the worse).\r\n\r\n5) With so many departments, focus areas, and products, *in theory*, you should have plenty of opportunity to grow your career (horizontally or vertically). In practice, not true. \r\n\r\n6) You get to work with some of the brightest, most innovative and hard-working/diligent minds in the industry. There's a ""con"" to that, too (see below).","1) Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so - and it inevitably trickles down. I don't know if Google inadvertently hires the work-a-holics or if they create work-a-holics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change.\r\n\r\n2) Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems - and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions - not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously.\r\n\r\n3) Jerks. Sure, there are a lot of brilliant people - but, sadly, there are also a lot of jerks (and, many times, they are one and the same). Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straight-up cussing out their employees and intimidating/scaring their employees into compliance.\r\n\r\n4) It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :("
1,Software engineer iii,5.0,"May 10, 2014","Current employee, more than 1 year","* If you're a software engineer, you're among the kings of the hill at Google. It's an engineer-driven company without a doubt (that *is* changing, but it's still very engineer-focused).\r\n* The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties (at Waldorf Astoria, NY Public Library, MoMA, etc.); overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially.\r\n* Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants.\r\n* There a huge diversity of work ranging from defending independent journalism worldwide (Google Project Shield) to crisis response during disasters (see Maps during Hurricane Sandy or Tsunamis), to the best machine learning experts and projects in the world, to more mundane revenue-driving projects in advertising, there's really something for everybody.\r\n* It's easy to move around within the company as long as you're in good standing (the vast majority of engineers are).\r\n* The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive.\r\n* No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible.\r\n\r\nNeither pro nor con, but general information on work-life balance, promotions, and advancement.\r\n* Work life balance can be what you want it to be on most teams. (Some teams are in more competitive sectors and require more crazy hours all the time - but very few of them). If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hyper-motived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still - and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand.\r\n* If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google -- smarter than average, but just average compared to other Googlers -- you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer (it's the minimum requirement), but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","* It *is* becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, cross-divisional tension (though nothing remotely approaching that of Microsoft's internal tension).\r\n* The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse.\r\n* Also with growth means more internal-confidential data leaks (again, because of the raw numbers of people) -- product announcements being ruined, etc. That means the company has to be tighter-lipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture."
2,Anonymous employee,5.0,"Feb 8, 2015",Current employee,"You can't find a more well-regarded company that actually deserves the hype it gets.\r\n\r\nYou'll work on cutting edge projects / solve important issues that impact your community and the world\r\n\r\nYou'll meet interesting people who are your colleagues, managers, and senior management.\r\n\r\nYou'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing\r\n\r\nYou'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. \r\n\r\nThere are 22 cafes (more or less), the food is excellent, and it's free.\r\n\r\nYour pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved.\r\n\r\nGoogle cares about how it treats its employees.\r\n\r\nThe campus is like an academic campus in many ways.\r\n\r\nThere are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out - but you'll need to make sure to carve out time to do these things.\r\n\r\nYou'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google.\r\n\r\nIf and when you leave, you'll never regret having that company on your resume. It opens doors. \r\n\r\nThe company is flexible - if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work - but don't get me wrong - you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle - sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 3-4 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal.\r\n\r\nYour first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things.\r\n\r\nYou'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing - which is kind of hard.\r\n\r\nAfter two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. \r\n\r\nIt's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30-something idealism on top which can fool you into thinking that people are easygoing - they're not. They're driven. If you're not driven, you're not going to fit in.\r\n\r\nWhen you start at Google, it seems like peer reviews are super important - they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc.\r\n\r\nIt's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out."
3,Program manager,4.0,"Aug 5, 2025","Current employee, more than 3 years","Good pay, intelligent and down to earth people (for the most part), and despite there being a lot disgruntled employees about the continued layoffs and mixed feelings about Sundar, Google still really is an exciting place to work with a lot of potential opportunity given the AI movement.","The truth is you could get laid off at any point... and this is coming from someone who was given the highest performance rating possible in 2024. Even if you're hired in August of this year, by Feb of next year there's a real chance leadership has made some top down decision to slash roles in your org or to prioritize a different location for your org. The environment at Google has been increasingly tense and stressful the last 3 years. Managers and those around you are more and more panicked, so it's only naturally that you'll feel the consequences of this in your day to day (bottom line, it's becoming a more stressful place to work and expectations are increasing each month),"
4,Software development engineer (sde),4.0,"Jul 28, 2025",Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include:\n1. **High Expectations**: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly.\n\n2. **Intense Workload**: The fast-paced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees.\n3. **Internal Competition**: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful.\n4. **Work-Life Balance**: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life.\n5. **Bureaucracy and Hierarchy**: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decision-making or innovation for some teams.\nOf course, these experiences can vary widely depending on the team, role, and individual preferences."

In [87]:
# printing the last 5 elements on the dataset
print("first 5 elements")
print("=====================================================")
print()
GoogleRev.tail(5)

first 5 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
42425,Anonymous employee,5.0,"Sep 27, 2022",Current employee,Great company to work for,Nothing to share for this company
42426,Sales associate,5.0,"Sep 28, 2022",Current employee,benefits benefits benefits benefits benefits,salary salary salary salary salary
42427,Web developer,5.0,"Sep 28, 2022","Current employee, more than 1 year",very good company to work in,good good good good good
42428,Marketing,4.0,"Sep 28, 2022","Former employee, more than 1 year",Amazing people and culture to work in.,Not much scope of growth
42429,Sales representative,4.0,"Sep 28, 2022",Current employee,Cool environment. Good pay. Talented people,Make work remote. Office work sucks

In [88]:
# printing the random 5 elements on the dataset
print("Random 5 elements")
print("=====================================================")
print()
GoogleRev.sample(5)

Random 5 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
25692,Senior account manager,5.0,"Mar 17, 2022","Current employee, more than 8 years","Great work/life balance, great people, solid pay","Work is pretty run of the mill, no remote work after April 5."
20300,Associate account strategist,2.0,"Oct 21, 2016","Former employee, more than 1 year","- Amazing office space, free food and drinks, benefits, very nice work environment\r\n- You will make some great friends just based on the sheer amount of people you will meet\r\n- Good salary for a first job (not so much later on)\r\n- Targets are easy to achieve and you can have a great WLB if you know what you are doing\r\n- Easy to hide in such a big company, no problem to run off for a few hours and go for a nap or play PlayStation (as long as you are performing well no one cares)\r\n- Very interesting product with many layers of complexity. You can learn relevant product knowledge if you want to bootstrap something later on.","- Promotions solely based on something they like to call VISIBILITY. Useless projects get started all the time just to be cc'd on emails to Director-level and above. Those projects in most cases lead to nothing and don't produce ANY results at all, it is solely done for the purpose of being able to mention one's ""great"" initiative in the next performance review cycle. Another factor they promote on are several ""soft attributes"" which is a way for management to promote on subjectivity.\r\n- You are always told the company is a meritocracy eventho it is clearly not. This incongruent messaging compared to reality is extremely frustrating. It does not matter at all if you reach 100% of your target or 200%, what matters in the end is the above mentioned visibility. Another proof is that I heard managers say ""Oh, he has been here already for 2.5 years, we have to promote him now"" which is a joke and demotivating for high performing folks.\r\n- The metrics you are measured on in an Account Management role are only indirectly linked to revenue and are manipulated by the vast majority of reps once they have been on the job for a quarter and know the drill. Management knows this but does not care since they look good in front of their own bosses if the numbers look good. The best of the manipulators do not have to work at all to reach their targets.\r\n- Many of the middle managers are incompetent and have been stuck in their role for sometimes nearly a decade. There is no real willingness to achieve something great and make progress, but those people are just happy where they are in their career and spend their whole day wasting everyone's time in meetings or sending out useless emails. Very limited learning opportunity if you have a manager like this and very demotivating because no one wants to end up like them. However, there is the rare exception of a great manager.\r\n- Leadership cult, people of levels of director and above are worshipped through the entire organization and are treated like god's gift to everything. Some of them are admittedly great, some of them aren't.\r\n- Learning curve will be non-existent at the latest after 6 months and you will be doing the same day in day out. You can learn by yourself some new stuff with the great online training database, but the main thing you are doing gets old quite soon.\r\n- A lot of people drink the kool aid. There are quite a few critical people like myself in the organization, but a majority of people think they are on top of the world because they work in one of the least respected role of a prestigious company. People are not ""super smart"" everywhere, they hire basically everyone and it is just luck getting through the interview process. 90%+ of hires come from personal referrals since their CVs wouldn't go through the official channel. Level of entitled and incompetent people can be extremely high in certain teams."
6290,Software engineer,5.0,"Aug 24, 2024","Current employee, less than 1 year",1- competitive package\n2-can collaborate with great minds,1-To competitive for a begineer
34048,Program manager,4.0,"Jul 28, 2022","Current employee, more than 10 years","Salary, perks, medical insurance, Travel","Long hours, sometimes a lot of internal politics"
1352,Senior manager,5.0,"May 22, 2025",Current employee,Lots of great challenges that are intellectually stimulating. Great pay and lots of flexibility,Getting bigger and more political

In [89]:
# checking the first column details
col1 = GoogleRev["Job Title"]
col1

0                            Program manager
1                      Software engineer iii
2                         Anonymous employee
3                            Program manager
4        Software development engineer (sde)
                        ...
42425                     Anonymous employee
42426                        Sales associate
42427                          Web developer
42428                              Marketing
42429                   Sales representative
Name: Job Title, Length: 42430, dtype: object

In [90]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns
    total null values on the dataset"""
    print(df.isna().sum())
null_values(GoogleRev)

Job Title      1
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [91]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(GoogleRev)
# CisRev.dropna(inplace=True)

In [92]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(GoogleRev)

In [93]:
# Rename the headers
GoogleRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [94]:
# checking the unique values in the dataset
for job in GoogleRev["Job Title"].unique():
    print(job)

Program manager
Software engineer iii
Anonymous employee
Software development engineer (sde)
Account manager
Software engineer
Staff engineer
Product manager
Senior program manager
Administrative
Trading
Engineer
Software engineering manager
People consultant
Software engineer swe iii
Applications engineer
Software engineer apprentice
Datacenter technician
Software engineer (swe ii)
Technical solutions engineer
Senior software engineer
Software developer
Cloud engineer
Dfm engineer
Sde1 entry
User experience designer
Software engineer ii
Technical recruiter
Janitor
Solutions engineer
Ai cloud engineer
Scaled operations manager
Business analyst
Senior manager
Silicon design engineer
Sofwatre engineer
Data analyst
Kak
Senior ai engineer
Software engineer l4
Data scientist
Sofware engineer ii
Senior account strategist
Senior creative lead
Customer service representative (csr)
Graphic designer
Business development senior manager
Recruiter
It support specialist
Product marketing manager
Software engineering manager ii
Project manager
Senior account manager
S s e(senior software engineer)
Account strategist
Staff software engineer
Marketing product manager (pmm)
Data coordinator
Qa engineer
Silicon physical design engineer
Vp of sales
Translator
Dhruv
Ux researcher
Ad specialist
Account executive
Account planner
Sales representative
Solutions consultant
Ml engineer
Apprentice
Machine learning engineer
Junior analyst
Cook
Sales associate
Software development engineer (sde1)
Media account specialist
Content reviewer
Human resource consultant
Recruiter (l4)
Software development engineer (sde) intern
Site reliability engineer
Analyst
Software enginner
Sales
Software qa engineer
Software development engineer in test (sdet)
Frontend developer
Administrative assistant
Assistant manager
Janitor/cleaner
People operations
Farm worker
Engineering analyst
Swe-ml
Account associate
Hr manager
Technical solutions consultant
Contect writer
Technical lead
Sr financial analyst
Key account manager
Systems engineer
Front end developer
Manager
Products manager
Strategy & operations manager
Software developer intern
Event manager
Customer service representative
Sr. software engineer
Full stack web developer
Retail sales associate
Analista sênior
Data engineer
Senior deal desk analyst
Production manager
Executive assistant
Go to market - regional product lead
Web developer
Content writer
Digital strategist
Marketing
Senior mechanical engineer
Electrical engineer
Business analysis sr analyst
Research scientist
Product designer
Supply chain manager
Test engineer
Senior software engineer in test
Finance manager
Backend developer
Structural engineering technologist
Senior business systems analyst
Senior digital design engineer
Internship
Junior data analyst
Lead product manager
Software engineer - android
Senior software enginner
Media specialist iii
Technology analyst
Accountant
Product/project manager
Mts1 software engineer
Senior tpm
Operations analyst
Marketing manager
Fraud and risk analyst
L3
Digital marketing strategist
Learning experience designer
Head of sales
Consultant
Software engineer l3
Senior programmer analyst
Talent development specialist
Marketing coordinator
Full stack developer
Software development engineer
Iam
Google ads specialist
Pmts
Human resources manager
Industry manager
Financial analyst
Isv partner manager
Research assistant
Clinical specialist
Senior electrical engineer
Intern
Ux designer
Software engineer 2
Senior consultant
User experience dedigner
Sa360 specialist
Cyber security engineer
Swe new grad
Hardware engineer
Social media specialist
Business intelligence analyst
Sales executive
Task assistant
Software solutions architect
Graduate student
Policy specialist
Swe intern
Customer growth associate - gcs
Senior design engineer
Senior financial analyst
Ux
Step intern
Computer developer
Supply & demand manager
Strategist
Operations expert
Qa
Silicon engineer
Field sales representative
Sre2/3
Android developer
Grad student researcher
Carpenter
Owner
Territory sales manager (tsm)
Tse i
Growth manager
Receptionist
Staff accountant
Community manager
Senior site reliability engineer
Venture capital analyst
Hr recruiter
Sr member of technical staff
Head of engineering
Marketing assistant
Smooth and interesting process
Finance
Data entry specialist
Full stack software engineer
Senior engineer
Brand specialist
Security engineer
Junior software engineer
Business development manager
Google ads quality rater
Seinor software engineer
Professional googler
Project management apprentice
Technical support engineer
Pom
Subject matter expert (sme)
Software enigneer
Lead technical program manager
Senior recruiter
Sdr manager, emea
Customer service advisor
Engineering
System engineer
Trust and safety analyst
Customer service associate
Cyber security analyst
Threat researcher
Sr  developer
Senior technical program manager
Research engineer
Associate
Student researcher
Senior ux designer
Google ads account strategist
Coffee shop manager
Chief executive officer (ceo)
Engineering manager
Ai developer
Senior datacenter technician
Ai engineer
Senior associate
Network engineer
Mail carrier
Senior java developer
Scrum master
Freezer/cooler/deli
Ai/ml engineer
Regional sales manager
Staff network engineer
Computer programmer
Java engineer
Marketer
Prodcut manager
Quality assurance specialist
Senior talent acquisition specialist
Sales specialist
Technical program manager
Global product lead
Software test engineer
Pt grocery associate
Senior swe
Director
Technician
Associate account strategist
Senior hardware engineer
Policy analyst
Sales head
Help desk technician
User experience researcher
Deputy cyber lead
Policy manager
Measurement lead
Copywriter
Export manager
Global partnerships manager
Web designer
Youtuber
Strategic partnerships manager
Senior account executive
Cloud technical residency
Senior product manager
Administrative business partner
Chef kok/chef restaurant/chef inkoop(bottelier)/catering manager
Senior product manager (l6)
Swe l3
Customer service
Software engineer(internship)
Senior staff software engineer
Lead recruiter
Sde-intern
Software engineer-iii
Active candidate specialist
Sowtware engineer
Ceo-founder
Coder
Private disability care attendant
Media manager
It support
Sineor software engineer
Tech support
Head of product
Video editor
Tech analyst (idk it changes so often)
Hype man
Sales director
Territory sales manager
Strategic partner manager
Google reviews
Google software engineering
Quality engineer
Firmware engineer
Programmer
Mkt manager
Soc analyst
Company secretary
It support technician
Programmer/analyst
Research intern
General manager
Intenrship
Head of partnerships
Softwater engineer
Estagiária administrativa
Customer helper
Finance manger
Working student
Research & insights manager
Managing director
Ui\ux designer
Senior data scientist
Marketing executive
Softwarwe engineer
Software tester
Associate financial analyst
User experience
Virtual assistant
Ta
Support worker
Chief googler
Associate product manager
Software development engineer (sde) ii
People analyst
Software engineer (site reliability)
Senior designer
Badminton coach
Sales manager
Pgm manager
Softeware developer
Finance analyst
Tpm ii
Sofrwareengineer
Se
Senior sofware engineer
Account manager %7c large customer sales
Softwar engineer
Senior incident reponse consultant
Software engineer swe 4
Inside sales acount manager
Legal specialist
Df
Head of insights
Asic design engineer
Sales bdm
Ux manager
L7 senior manager
Legal counsel
Ae
Advertising sales
Flutter developer
Associate software engineer
Desingner
Truck driver
Csr associate
Great service representative (gsr)
Ux writer/content designer
Noc engineer
Head of business development
Sde
Registered nurse
Tax associate
Ai software engineer
Sales strategy and operations
Buyer
Fake
Head of industry
Enterprise account executive
Swe
Editor
Senior staffing operations associate
Software develooer
Strategy manager
Sales enginner
Sr. technical program manager
Summer work experience
Researcher
Senior softare engineer
Project management apprenticeship
Psm
Employee relations partner
Reviewer
Executive business partner
Software engineer manager
Partnership manager
Designer
Director of research
Senior strategist
Head of new business
Social media
Sr. staff data scientist
Sre
Senior systems design engineer
Server/bartender
Architect
Staff ux researcher
Senior solutions consultant
Senior developer
Head of finance
Apple genius
Phd student researcher
Fullstack developer
Sdr
Data center technician
L5 engineer
Tpm manager
Swe 3
Artist
Senior sales manager
Great opportunity to improve employee future
Quality analyst
Vendedora free lancer
Motion graphics designer
Mechanical design engineer
Senior it consultant
Recruiting manager
Software development engineer (sde) 3
Critical situation  manager
Customer engineer
Operations manager
Maintenance supervisor
Content strategist
Dsa
Senior finance analyst
Software eginner
Lead ux designer
Software development engineer in test (sdet) ii
Marketing specialist
Director, marketing
Senior product specialist
Data science
Senior software engineer ii
Gtm
Seo specialist
Senior staff engineer
Analytical lead
It administrator
Data science intern
Senior ux/ui designer
Human resources
Account relationship manager
Senior engineering manager
Executive
Senior web developer
Accounting manager
Software engineer, level 6
Did not disclose
Business strategy manager
Marketing lead
Cloud sales manager
Strategy and operations lead
Technical specialist
Corp development
Product owner
Technical support
Software develeper
Dara analyst
Sales lead
Software developer engineer intern
Lawyer
Data center operations manager
Software engineer 4
Business development associate
Member of technical staff
Data entry
Technical consultant
Sr. manager engineering
Swe 1
Employment specialist
Customer support
Global program manager
Qa automation engineer
Associate engineer
Snr. software engineer
Account director
Cloud solution architect
Sr. engineer
Eningeering
Ml swe
Kitchen staff
Maintenance technician
Chief technology officer (cto)
Tse ii
Business development representative
Conserje nocturno
Senior staff asic engineer
Digital marketing manager
Head - dcm, director - dcm
Strategic account manager
Devops engineer
Digital strategy lead
Data & ia engineer
Executive search expert
Softeware engineer
Software engineering
Principal analytical consultant
Senior ux researcher
Business systems analyst
Senior product data scientist
Senior member of technical staff
Account mananger
Swe internship
Ux director
Client engagement specialist
Sre engineer
Front end react developer
Strategy analyst
Strategy and operations manager
Sr staff technical program manager
Senior sae
Business development consultant
Sales rep
President &ceo
Customer care representative
Software engineering intern
Digital marketing specialist
Portfolio manager
Therapist
Mother
Sourcing specialist
Team leader
Solution consultant
Business data scientist
Motion graphics freelancer
User support specialist
Software engiener co-op
Cleaner
Senior ux engineer
Strategic cloud engineer
Securityengineer
Strategy and operations associate
Network operations
Industry head
Software intern
Customer operations specialist
Sr. ai engineer
Support operations manager
Still unemployed
Sde-2 backend
Sofware developer
Mobile developer
Senior software engineer (sde3)
Senior ux writer
Fitbit health coach
Program lead
Digital marketing associate
Sde-2
Software engineer -2
Summer mba intern
Lead programmer
Financial accountant
Product lead
Senior projext manager
It senior manager
Google maps review rating
Senior specialist, search, discovery and lifecycle
Backend engineer
Software engineer 3
Human resources business partner hrbp
Senior accountant
Sales ops manager
Freelancer
Bussiness development executive
Java developer
Ux engineer
Manager, hris
Strategic business development manager
Young professional user experience researcher
Em
Best buy mobile sales associate
Senior product manager/senior product owner
Service delivery manager
Sr. director, engineering
Solutions architect
Emea regional manager
Developer
Systems analyst
Cloud technical solution engineer
Communications manager
Human resources specialist (hr specialist)
Resident service associate
Creative director
Strategy & operations
Ux desinger
Research analyst
Soft eng
Software engineer (swe iii)
Compliance lead
Junior developer
Partner solutions engineer
Human resources assistant
Senior interaction designer
Data center engineer
Sr staff engineer
Human resources coordinator
Financial service representative (fsr)
Assistant project manager
Hwe
Associate account manager
Data center technician ii
Business intelligence engineer
Senior program manager lead
Quality assurance engineer
Regional security specialist
Trust & safety analyst
Product leader
Graduate student researcher
Customer success manager (csm)
Growth consultant
Electrician
Web solutions engineer
.net engineer
Academic counsellor
Labour's and packaging
Workplace program manager
Direct sales representative
Chief marketing officer (cmo)
Sr. director
Digital marketing intern
Head of incubation
Junior accountant
Talent acquisition partner
Young apprentice
Technical team lead
Title clerk
Content creator
One of the best company in my careers
Senior risk associate
Sales strategy and operations manager
Product analyst
Red team manager
Machine operator
Cybersecurity pentester
Social media manager
Anonymous
Tech recruiter
Guvna
Program manager, supply chain
Sde-1(backend)
Infrastructure engineer
Product specialist
Risk manager
Warehouse associate
Software engineer se3
Fnjbv
Sandwich maker
Partner
Staff product manager
Partner engineer
Junior it administrator
Product operations manager
Analytical consultant
Product design engineer
Corporate operations engineer
Big guy
Sf
Software engineer trainee
Product manager 2
Communications specialist
Paid media specialist
Senior apllication support
Advisor
Sse- development
New business development
Human resources generalist
Marketing analyst
Senior analyst
Structural engineer
Product operations director
It specialist
Smm manager
Global cloud availability and service continuity manager
Junior devops engineer
Educator
Construction manager
Vp
Junior consultant
Head of production
Superintendent
Softwere engineer
Lead genius
Administrator
Staff partner engineer
Office manager
Psychologist
Nursery practitioner
Risk analyst
Principal software engineer
Compliance officer
Partnerships
Outside sales representative
Data analst
Sr. engineering manager
Technical porgram manager
Digital ads specialist
Hr director
Cloud ai engineer
Senior marketing manger
Adsense associate
Software engineer new grad
Software egnineer
Support engineer
Senior software engineer (l5)
Sales engineer
Mobile apps consultant, online partnerships group
Business development representative (bdr)
Digital content producer
Senior director
Exe
Broker
Associate product manager (apm)
Daya analyst
Privacy engineer
Senior user experience designer
Real estate executive
Paid search specialist
Sales advisor
Merchandiser
Associate consultant
Csa - customer service associate
Mechanical engineer
Chief engineer
Inbound customer solutions consultant
Digital technology lead
Product marketing manager/senior pmm
Sr. product manager
Senior devops engineer
User support manager
Advertising solutions architect
Employee
Algorithm engineer
Solution engineer
Senior test engineer
Intern - hourly
Cash manager
Head of marketing
Google map reviewer and survey
Career specialist
Postdoctoral researcher
Sr program manager
Global communications
Data sienctist
Part time cleaning lady
Assitant manager
Supervisor
Sr software engineer
Senior software engineer-l3
Policy officer
Softweare engineer i
Associate finance analyst
Technical program manager ii
Senior network engineer
Senior technical program manager - privacy
Apigee developer
Customer onboarding strategist
Technical sales consultant
Senior systems engineer
Investemenbanker
L3 engineer
Vendor manager
Sr. hardware design engineer
Ceo
Warehouse worker
Software engineers
Ai resident
Senior data analyst
Linguist
Bob
Industrial designer
Manager, website operations
Google map reviewer
Senior sales operations manager
Ai specialist
Senior laser safety officer
Data center facilities technician
Senor software engineer
Sales intern
Adtech consultant
Partner sales manager
Senior pgm
Ai researcher
Transportation planner
Sr development engineer
Security officer
Sales management trainee
Associate sofware engineer
Sales enablement lead
Sr. thermal engineer
Growth marketing manager
Sofatware engineer
Recruiting lead
Remote health coach
Front end web deceloper
Systems administrator
Bd manager
Senior software developer
Senior marketer
Software engineer-1
Solution architect
International sales manager
Sr policy analyst
Hr coordinator
Police officer
Junior cloud engineer
Partner manager
Technology lead
Ads review agent
Sr. manager, operations
Accelerated growth consultant
Sales account manager
Security analyst
Physical design engineer
E4
Operations
Infrastructure technician
Sales strategy manager
Technical sourcer
Software development engineer (sde) -1
Content marketer
Group financial controller
Junior web developer
Global process owner
Cloud program manager
It progect manager
Software developer iii
Programme analyst
Senior software engineering manager
Cloud architect
Cloud technical support engineer
Regional product lead
Gff key client coordinator
Specialist
Data lead
International growth consultant
Billing specialist
Accelerate growth consultant
Python developer
Class a cdl driver
Ratings analyst
Senior design manager
Group marketing manager
Shop assistant
Admin
Markting manager
Recruitment manager
Sr test engineer
Embedded firmware engineer
Software engineer iv
Non it recruiter
Content moderator
Interaction designer
Thermal design engineer
Principal account executive
Senior finance manager
Performance analyst
User experience tester
Sdeii/sde1
Senior it engineer
Rating analyst
International account executive
Be developer
Fitness instructor
Senior technical consultant
Senior sre engineer
Go to market
Adwords strategist
Google map
Principal account management
Senior staff research scientist
Frontend engineer
Human resources business partner
It engineer
Hub manager
Market research
Fp&a analyst
Advertising
Engeneering coordinator
Technical writer
Project engineer
Application security engineer
Ux writer
Sales enablement specialist
Offensive coordinator
Swe-sre
Floor staff
Director, program management
Software enginerring analyst
Softwareengineer
Business & finance manager
Senior marketing-manager
Coe specialist
Leveraged finance analyst
Legal assistant
Tech recuiter
Custodial worker
Team lead
Uxr researcher
Associate professor
Operations engineer
Software engineer, site reliability engineering
Director global gtm
Strategic partnership manager
Digital marketer
Consultancy
Janator
E.i.t.
Senior technical program manager lead
Sre/devops engineer
Staff data scientist
Partnerships marketing
Lead ux researcher
Marketing agent
Retail leader
Lab tehnician
Filestore engineer
Software developer associate
Ai content writer
Android engineer
Global supplier manager
Program coordinator
Contractor
Cs operations manager
Reviews specialist
Junior java software engineer
Softwre engineer
Market research manager
Ux design manager
Cloud security engineer
Senior product marketing manager
Marketing director
Hr business partner
Speech-language pathologist
Analista júnior
Rrl lab assistant ii
Asic design verification engineer
Information security program manager
None given to me
Planner
Assistant project manager (apm)
Student worker
Prod/ops
Engagement manager
Line cook
Senior android developer
Checkout operator
Industry manager - sales
Change manager
Sr engineering manager
Technical marketing engineer
Senior cloud architect
Electrical assistant
Senior ux design lead
Brand manager
Market lead
Partnerships manager

In [95]:
# capitalizing the dataset
def capital_letter(df, col="Job Title"):
    df[[col]] = df[[col]].apply(lambda c: c.str.title())
    return df
capital_letter(GoogleRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Program Manager,4.0,2013-06-21,"Former employee, more than 8 years","1) Food, food, food. 15+ cafes on main campus (MTV) alone. Mini-kitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day.\r\n\r\n2) Benefits/perks. Free 24:7 gym access (on MTV campus). Free (self service) laundry (washer/dryer) available. Bowling alley. Volley ball pit. Custom-built and exclusive employee use only outdoor sport park (MTV). Free health/fitness assessments. Dog-friendly. Etc. etc. etc.\r\n\r\n3) Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. \r\n\r\n4) For the size of the organization (30K+), it has remained relatively innovative, nimble, and fast-paced and open with communication but, that is definitely changing (for the worse).\r\n\r\n5) With so many departments, focus areas, and products, *in theory*, you should have plenty of opportunity to grow your career (horizontally or vertically). In practice, not true. \r\n\r\n6) You get to work with some of the brightest, most innovative and hard-working/diligent minds in the industry. There's a ""con"" to that, too (see below).","1) Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so - and it inevitably trickles down. I don't know if Google inadvertently hires the work-a-holics or if they create work-a-holics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change.\r\n\r\n2) Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems - and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions - not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously.\r\n\r\n3) Jerks. Sure, there are a lot of brilliant people - but, sadly, there are also a lot of jerks (and, many times, they are one and the same). Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straight-up cussing out their employees and intimidating/scaring their employees into compliance.\r\n\r\n4) It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :("
1,Software Engineer Iii,5.0,2014-05-10,"Current employee, more than 1 year","* If you're a software engineer, you're among the kings of the hill at Google. It's an engineer-driven company without a doubt (that *is* changing, but it's still very engineer-focused).\r\n* The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties (at Waldorf Astoria, NY Public Library, MoMA, etc.); overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially.\r\n* Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants.\r\n* There a huge diversity of work ranging from defending independent journalism worldwide (Google Project Shield) to crisis response during disasters (see Maps during Hurricane Sandy or Tsunamis), to the best machine learning experts and projects in the world, to more mundane revenue-driving projects in advertising, there's really something for everybody.\r\n* It's easy to move around within the company as long as you're in good standing (the vast majority of engineers are).\r\n* The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive.\r\n* No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible.\r\n\r\nNeither pro nor con, but general information on work-life balance, promotions, and advancement.\r\n* Work life balance can be what you want it to be on most teams. (Some teams are in more competitive sectors and require more crazy hours all the time - but very few of them). If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hyper-motived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still - and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand.\r\n* If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google -- smarter than average, but just average compared to other Googlers -- you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer (it's the minimum requirement), but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","* It *is* becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, cross-divisional tension (though nothing remotely approaching that of Microsoft's internal tension).\r\n* The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse.\r\n* Also with growth means more internal-confidential data leaks (again, because of the raw numbers of people) -- product announcements being ruined, etc. That means the company has to be tighter-lipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture."
2,Anonymous Employee,5.0,2015-02-08,Current employee,"You can't find a more well-regarded company that actually deserves the hype it gets.\r\n\r\nYou'll work on cutting edge projects / solve important issues that impact your community and the world\r\n\r\nYou'll meet interesting people who are your colleagues, managers, and senior management.\r\n\r\nYou'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing\r\n\r\nYou'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. \r\n\r\nThere are 22 cafes (more or less), the food is excellent, and it's free.\r\n\r\nYour pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved.\r\n\r\nGoogle cares about how it treats its employees.\r\n\r\nThe campus is like an academic campus in many ways.\r\n\r\nThere are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out - but you'll need to make sure to carve out time to do these things.\r\n\r\nYou'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google.\r\n\r\nIf and when you leave, you'll never regret having that company on your resume. It opens doors. \r\n\r\nThe company is flexible - if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work - but don't get me wrong - you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle - sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 3-4 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal.\r\n\r\nYour first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things.\r\n\r\nYou'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing - which is kind of hard.\r\n\r\nAfter two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. \r\n\r\nIt's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30-something idealism on top which can fool you into thinking that people are easygoing - they're not. They're driven. If you're not driven, you're not going to fit in.\r\n\r\nWhen you start at Google, it seems like peer reviews are super important - they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc.\r\n\r\nIt's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out."
3,Program Manager,4.0,2025-08-05,"Current employee, more than 3 years","Good pay, intelligent and down to earth people (for the most part), and despite there being a lot disgruntled employees about the continued layoffs and mixed feelings about Sundar, Google still really is an exciting place to work with a lot of potential opportunity given the AI movement.","The truth is you could get laid off at any point... and this is coming from someone who was given the highest performance rating possible in 2024. Even if you're hired in August of this year, by Feb of next year there's a real chance leadership has made some top down decision to slash roles in your org or to prioritize a different location for your org. The environment at Google has been increasingly tense and stressful the last 3 years. Managers and those around you are more and more panicked, so it's only naturally that you'll feel the consequences of this in your day to day (bottom line, it's becoming a more stressful place to work and expectations are increasing each month),"
4,Software Development Engineer (Sde),4.0,2025-07-28,Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include:\n1. **High Expectations**: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly.\n\n2. **Intense Workload**: The fast-paced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees.\n3. **Internal Competition**: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful.\n4. **Work-Life Balance**: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life.\n5. **Bureaucracy and Hierarchy**: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decision-making or innovation for some teams.\nOf course, these experiences can vary widely depending on the team, role, and individual preferences."
...,...,...,...,...,...,...
42425,Anonymous Employee,5.0,2022-09-27,Current employee,Great company to work for,Nothing to share for this company
42426,Sales Associate,5.0,2022-09-28,Current employee,benefits benefits benefits benefits benefits,salary salary salary salary salary
42427,Web Developer,5.0,2022-09-28,"Current employee, more than 1 year",very good company to work in,good good good good good
42428,Marketing,4.0,2022-09-28,"Former employee, more than 1 year",Amazing people and culture to work in.,Not much scope of growth
42429,Sales Representative,4.0,2022-09-28,Current employee,Cool environment. Good pay. Talented people,Make work remote. Office work sucks

In [96]:
GoogleRev.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42429 entries, 0 to 42429
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Job Title   42429 non-null  object
 1   Job Rating  42429 non-null  float64
 2   Time        42429 non-null  datetime64[ns]
 3   Job Status  42429 non-null  object
 4   Pros        42429 non-null  object
 5   Cons        42429 non-null  object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 2.3+ MB

In [97]:
# rename detail
GoogleRev["Job Title"] = GoogleRev["Job Title"].replace({
    "Tdr Trade Development Representative":"(Tdr) Trade Development Representative",
    "Qaengineer":"Qa Engineer","Çustomer Service Representative":"Customer Service Representative",
    "Sofatware Engineer":"Software Engineer","Softeware Enginee":"Software Engineer",
    "Ftth Engineer":"Ftth (Fiber to the Home) Engineer","Software qa engineer":"Software Qa Engineer",
    "Tdr":"Trade Development Representative","Itspecialist":"IT Specialist",
    "KEY NOT FOUND: jobLine.seasonal-current":"(Job) seasonal_current","I T Analyst":"IT Analyst",
    "It Specialist":"IT Specialist"
    })

In [98]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(GoogleRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Program Manager,4.0,2013-06-21,"Former employee, more than 8 years","1 Food, food, food. 15+ cafes on main campus MTV alone. Minikitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day.\n\n2 Benefits/perks. Free 24:7 gym access on MTV campus. Free self service laundry washer/dryer available. Bowling alley. Volley ball pit. Custombuilt and exclusive employee use only outdoor sport park MTV. Free health/fitness assessments. Dogfriendly. Etc. etc. etc.\n\n3 Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. \n\n4 For the size of the organization 30K+, it has remained relatively innovative, nimble, and fastpaced and open with communication but, that is definitely changing for the worse.\n\n5 With so many departments, focus areas, and products, in theory, you should have plenty of opportunity to grow your career horizontally or vertically. In practice, not true. \n\n6 You get to work with some of the brightest, most innovative and hardworking/diligent minds in the industry. There's a ""con"" to that, too see below.","1 Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so and it inevitably trickles down. I don't know if Google inadvertently hires the workaholics or if they create workaholics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change.\n\n2 Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously.\n\n3 Jerks. Sure, there are a lot of brilliant people but, sadly, there are also a lot of jerks and, many times, they are one and the same. Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straightup cussing out their employees and intimidating/scaring their employees into compliance.\n\n4 It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :"
1,Software Engineer Iii,5.0,2014-05-10,"Current employee, more than 1 year","If you're a software engineer, you're among the kings of the hill at Google. It's an engineerdriven company without a doubt that is changing, but it's still very engineerfocused.\n The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties at Waldorf Astoria, NY Public Library, MoMA, etc.; overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially.\n Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants.\n There a huge diversity of work ranging from defending independent journalism worldwide Google Project Shield to crisis response during disasters see Maps during Hurricane Sandy or Tsunamis, to the best machine learning experts and projects in the world, to more mundane revenuedriving projects in advertising, there's really something for everybody.\n It's easy to move around within the company as long as you're in good standing the vast majority of engineers are.\n The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive.\n No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible.\n\nNeither pro nor con, but general information on worklife balance, promotions, and advancement.\n Work life balance can be what you want it to be on most teams. Some teams are in more competitive sectors and require more crazy hours all the time but very few of them. If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hypermotived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand.\n If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google smarter than average, but just average compared to other Googlers you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer it's the minimum requirement, but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","It is becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, crossdivisional tension though nothing remotely approaching that of Microsoft's internal tension.\n The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse.\n Also with growth means more internalconfidential data leaks again, because of the raw numbers of people product announcements being ruined, etc. That means the company has to be tighterlipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture."
2,Anonymous Employee,5.0,2015-02-08,Current employee,"You can't find a more wellregarded company that actually deserves the hype it gets.\n\nYou'll work on cutting edge projects / solve important issues that impact your community and the world\n\nYou'll meet interesting people who are your colleagues, managers, and senior management.\n\nYou'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing\n\nYou'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. \n\nThere are 22 cafes more or less, the food is excellent, and it's free.\n\nYour pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved.\n\nGoogle cares about how it treats its employees.\n\nThe campus is like an academic campus in many ways.\n\nThere are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out but you'll need to make sure to carve out time to do these things.\n\nYou'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google.\n\nIf and when you leave, you'll never regret having that company on your resume. It opens doors. \n\nThe company is flexible if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work but don't get me wrong you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 34 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal.\n\nYour first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things.\n\nYou'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing which is kind of hard.\n\nAfter two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. \n\nIt's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30something idealism on top which can fool you into thinking that people are easygoing they're not. They're driven. If you're not driven, you're not going to fit in.\n\nWhen you start at Google, it seems like peer reviews are super important they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc.\n\nIt's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out."
3,Program Manager,4.0,2025-08-05,"Current employee, more than 3 years","Good pay, intelligent and down to earth people for the most part, and despite there being a lot disgruntled employees about the continued layoffs and mixed feelings about Sundar, Google still really is an exciting place to work with a lot of potential opportunity given the AI movement.","The truth is you could get laid off at any point... and this is coming from someone who was given the highest performance rating possible in 2024. Even if you're hired in August of this year, by Feb of next year there's a real chance leadership has made some top down decision to slash roles in your org or to prioritize a different location for your org. The environment at Google has been increasingly tense and stressful the last 3 years. Managers and those around you are more and more panicked, so it's only naturally that you'll feel the consequences of this in your day to day bottom line, it's becoming a more stressful place to work and expectations are increasing each month,"
4,Software Development Engineer (Sde),4.0,2025-07-28,Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include:\n1. High Expectations: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly.\n\n2. Intense Workload: The fastpaced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees.\n3. Internal Competition: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful.\n4. WorkLife Balance: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life.\n5. Bureaucracy and Hierarchy: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decisionmaking or innovation for some teams.\nOf course, these experiences can vary widely depending on the team, role, and individual preferences."
...,...,...,...,...,...,...
42425,Anonymous Employee,5.0,2022-09-27,Current employee,Great company to work for,Nothing to share for this company
42426,Sales Associate,5.0,2022-09-28,Current employee,benefits benefits benefits benefits benefits,salary salary salary salary salary
42427,Web Developer,5.0,2022-09-28,"Current employee, more than 1 year",very good company to work in,good good good good good
42428,Marketing,4.0,2022-09-28,"Former employee, more than 1 year",Amazing people and culture to work in.,Not much scope of growth
42429,Sales Representative,4.0,2022-09-28,Current employee,Cool environment. Good pay. Talented people,Make work remote. Office work sucks

In [99]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    df[[col, col2]] = df[[col, col2]].apply(
        lambda s: s.str.replace("\n", " ", regex=False))
    return df
remove_char(GoogleRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Program Manager,4.0,2013-06-21,"Former employee, more than 8 years","1 Food, food, food. 15+ cafes on main campus MTV alone. Minikitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day. 2 Benefits/perks. Free 24:7 gym access on MTV campus. Free self service laundry washer/dryer available. Bowling alley. Volley ball pit. Custombuilt and exclusive employee use only outdoor sport park MTV. Free health/fitness assessments. Dogfriendly. Etc. etc. etc. 3 Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. 4 For the size of the organization 30K+, it has remained relatively innovative, nimble, and fastpaced and open with communication but, that is definitely changing for the worse. 5 With so many departments, focus areas, and products, in theory, you should have plenty of opportunity to grow your career horizontally or vertically. In practice, not true. 6 You get to work with some of the brightest, most innovative and hardworking/diligent minds in the industry. There's a ""con"" to that, too see below.","1 Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so and it inevitably trickles down. I don't know if Google inadvertently hires the workaholics or if they create workaholics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change. 2 Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously. 3 Jerks. Sure, there are a lot of brilliant people but, sadly, there are also a lot of jerks and, many times, they are one and the same. Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straightup cussing out their employees and intimidating/scaring their employees into compliance. 4 It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :"
1,Software Engineer Iii,5.0,2014-05-10,"Current employee, more than 1 year","If you're a software engineer, you're among the kings of the hill at Google. It's an engineerdriven company without a doubt that is changing, but it's still very engineerfocused. The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties at Waldorf Astoria, NY Public Library, MoMA, etc.; overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially. Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants. There a huge diversity of work ranging from defending independent journalism worldwide Google Project Shield to crisis response during disasters see Maps during Hurricane Sandy or Tsunamis, to the best machine learning experts and projects in the world, to more mundane revenuedriving projects in advertising, there's really something for everybody. It's easy to move around within the company as long as you're in good standing the vast majority of engineers are. The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive. No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible. Neither pro nor con, but general information on worklife balance, promotions, and advancement. Work life balance can be what you want it to be on most teams. Some teams are in more competitive sectors and require more crazy hours all the time but very few of them. If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hypermotived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand. If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google smarter than average, but just average compared to other Googlers you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer it's the minimum requirement, but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","It is becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, crossdivisional tension though nothing remotely approaching that of Microsoft's internal tension. The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse. Also with growth means more internalconfidential data leaks again, because of the raw numbers of people product announcements being ruined, etc. That means the company has to be tighterlipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture."
2,Anonymous Employee,5.0,2015-02-08,Current employee,"You can't find a more wellregarded company that actually deserves the hype it gets. You'll work on cutting edge projects / solve important issues that impact your community and the world You'll meet interesting people who are your colleagues, managers, and senior management. You'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing You'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. There are 22 cafes more or less, the food is excellent, and it's free. Your pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved. Google cares about how it treats its employees. The campus is like an academic campus in many ways. There are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out but you'll need to make sure to carve out time to do these things. You'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google. If and when you leave, you'll never regret having that company on your resume. It opens doors. The company is flexible if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work but don't get me wrong you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 34 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal. Your first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things. You'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing which is kind of hard. After two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. It's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30something idealism on top which can fool you into thinking that people are easygoing they're not. They're driven. If you're not driven, you're not going to fit in. When you start at Google, it seems like peer reviews are super important they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc. It's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out."
3,Program Manager,4.0,2025-08-05,"Current employee, more than 3 years","Good pay, intelligent and down to earth people for the most part, and despite there being a lot disgruntled employees about the continued layoffs and mixed feelings about Sundar, Google still really is an exciting place to work with a lot of potential opportunity given the AI movement.","The truth is you could get laid off at any point... and this is coming from someone who was given the highest performance rating possible in 2024. Even if you're hired in August of this year, by Feb of next year there's a real chance leadership has made some top down decision to slash roles in your org or to prioritize a different location for your org. The environment at Google has been increasingly tense and stressful the last 3 years. Managers and those around you are more and more panicked, so it's only naturally that you'll feel the consequences of this in your day to day bottom line, it's becoming a more stressful place to work and expectations are increasing each month,"
4,Software Development Engineer (Sde),4.0,2025-07-28,Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include: 1. High Expectations: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly. 2. Intense Workload: The fastpaced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees. 3. Internal Competition: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful. 4. WorkLife Balance: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life. 5. Bureaucracy and Hierarchy: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decisionmaking or innovation for some teams. Of course, these experiences can vary widely depending on the team, role, and individual preferences."
...,...,...,...,...,...,...
42425,Anonymous Employee,5.0,2022-09-27,Current employee,Great company to work for,Nothing to share for this company
42426,Sales Associate,5.0,2022-09-28,Current employee,benefits benefits benefits benefits benefits,salary salary salary salary salary
42427,Web Developer,5.0,2022-09-28,"Current employee, more than 1 year",very good company to work in,good good good good good
42428,Marketing,4.0,2022-09-28,"Former employee, more than 1 year",Amazing people and culture to work in.,Not much scope of growth
42429,Sales Representative,4.0,2022-09-28,Current employee,Cool environment. Good pay. Talented people,Make work remote. Office work sucks

In [100]:
hiphen = GoogleRev[GoogleRev["Pros"].str.startswith("-")]
hiphen

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [101]:
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(GoogleRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Program Manager,4.0,2013-06-21,"Former employee, more than 8 years","1 Food, food, food. 15+ cafes on main campus MTV alone. Minikitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day. 2 Benefits/perks. Free 24:7 gym access on MTV campus. Free self service laundry washer/dryer available. Bowling alley. Volley ball pit. Custombuilt and exclusive employee use only outdoor sport park MTV. Free health/fitness assessments. Dogfriendly. Etc. etc. etc. 3 Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. 4 For the size of the organization 30K+, it has remained relatively innovative, nimble, and fastpaced and open with communication but, that is definitely changing for the worse. 5 With so many departments, focus areas, and products, in theory, you should have plenty of opportunity to grow your career horizontally or vertically. In practice, not true. 6 You get to work with some of the brightest, most innovative and hardworking/diligent minds in the industry. There's a ""con"" to that, too see below.","1 Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so and it inevitably trickles down. I don't know if Google inadvertently hires the workaholics or if they create workaholics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change. 2 Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously. 3 Jerks. Sure, there are a lot of brilliant people but, sadly, there are also a lot of jerks and, many times, they are one and the same. Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straightup cussing out their employees and intimidating/scaring their employees into compliance. 4 It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :"
1,Software Engineer Iii,5.0,2014-05-10,"Current employee, more than 1 year","If you're a software engineer, you're among the kings of the hill at Google. It's an engineerdriven company without a doubt that is changing, but it's still very engineerfocused. The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties at Waldorf Astoria, NY Public Library, MoMA, etc.; overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially. Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants. There a huge diversity of work ranging from defending independent journalism worldwide Google Project Shield to crisis response during disasters see Maps during Hurricane Sandy or Tsunamis, to the best machine learning experts and projects in the world, to more mundane revenuedriving projects in advertising, there's really something for everybody. It's easy to move around within the company as long as you're in good standing the vast majority of engineers are. The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive. No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible. Neither pro nor con, but general information on worklife balance, promotions, and advancement. Work life balance can be what you want it to be on most teams. Some teams are in more competitive sectors and require more crazy hours all the time but very few of them. If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hypermotived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand. If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google smarter than average, but just average compared to other Googlers you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer it's the minimum requirement, but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","It is becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, crossdivisional tension though nothing remotely approaching that of Microsoft's internal tension. The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse. Also with growth means more internalconfidential data leaks again, because of the raw numbers of people product announcements being ruined, etc. That means the company has to be tighterlipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture."
2,Anonymous Employee,5.0,2015-02-08,Current employee,"You can't find a more wellregarded company that actually deserves the hype it gets. You'll work on cutting edge projects / solve important issues that impact your community and the world You'll meet interesting people who are your colleagues, managers, and senior management. You'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing You'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. There are 22 cafes more or less, the food is excellent, and it's free. Your pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved. Google cares about how it treats its employees. The campus is like an academic campus in many ways. There are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out but you'll need to make sure to carve out time to do these things. You'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google. If and when you leave, you'll never regret having that company on your resume. It opens doors. The company is flexible if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work but don't get me wrong you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 34 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal. Your first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things. You'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing which is kind of hard. After two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. It's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30something idealism on top which can fool you into thinking that people are easygoing they're not. They're driven. If you're not driven, you're not going to fit in. When you start at Google, it seems like peer reviews are super important they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc. It's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out."
3,Program Manager,4.0,2025-08-05,"Current employee, more than 3 years","Good pay, intelligent and down to earth people for the most part, and despite there being a lot disgruntled employees about the continued layoffs and mixed feelings about Sundar, Google still really is an exciting place to work with a lot of potential opportunity given the AI movement.","The truth is you could get laid off at any point... and this is coming from someone who was given the highest performance rating possible in 2024. Even if you're hired in August of this year, by Feb of next year there's a real chance leadership has made some top down decision to slash roles in your org or to prioritize a different location for your org. The environment at Google has been increasingly tense and stressful the last 3 years. Managers and those around you are more and more panicked, so it's only naturally that you'll feel the consequences of this in your day to day bottom line, it's becoming a more stressful place to work and expectations are increasing each month,"
4,Software Development Engineer (Sde),4.0,2025-07-28,Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include: 1. High Expectations: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly. 2. Intense Workload: The fastpaced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees. 3. Internal Competition: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful. 4. WorkLife Balance: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life. 5. Bureaucracy and Hierarchy: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decisionmaking or innovation for some teams. Of course, these experiences can vary widely depending on the team, role, and individual preferences."
...,...,...,...,...,...,...
42425,Anonymous Employee,5.0,2022-09-27,Current employee,Great company to work for,Nothing to share for this company
42426,Sales Associate,5.0,2022-09-28,Current employee,benefits benefits benefits benefits benefits,salary salary salary salary salary
42427,Web Developer,5.0,2022-09-28,"Current employee, more than 1 year",very good company to work in,good good good good good
42428,Marketing,4.0,2022-09-28,"Former employee, more than 1 year",Amazing people and culture to work in.,Not much scope of growth
42429,Sales Representative,4.0,2022-09-28,Current employee,Cool environment. Good pay. Talented people,Make work remote. Office work sucks

In [102]:
# check duplicate sum
def checkDuplicateSum(df):
    Total = df.duplicated().sum()
    print(f"Sum of Duplicate_Values = {Total}")
checkDuplicateSum(GoogleRev)

Sum of Duplicate_Values = 81

In [103]:
# drop_duplicate
def DropDuplicate(df):
    df.drop_duplicates(subset=["Job Title"], inplace=True)
    return df
DropDuplicate(GoogleRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Program Manager,4.0,2013-06-21,"Former employee, more than 8 years","1 Food, food, food. 15+ cafes on main campus MTV alone. Minikitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day. 2 Benefits/perks. Free 24:7 gym access on MTV campus. Free self service laundry washer/dryer available. Bowling alley. Volley ball pit. Custombuilt and exclusive employee use only outdoor sport park MTV. Free health/fitness assessments. Dogfriendly. Etc. etc. etc. 3 Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. 4 For the size of the organization 30K+, it has remained relatively innovative, nimble, and fastpaced and open with communication but, that is definitely changing for the worse. 5 With so many departments, focus areas, and products, in theory, you should have plenty of opportunity to grow your career horizontally or vertically. In practice, not true. 6 You get to work with some of the brightest, most innovative and hardworking/diligent minds in the industry. There's a ""con"" to that, too see below.","1 Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so and it inevitably trickles down. I don't know if Google inadvertently hires the workaholics or if they create workaholics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change. 2 Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously. 3 Jerks. Sure, there are a lot of brilliant people but, sadly, there are also a lot of jerks and, many times, they are one and the same. Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straightup cussing out their employees and intimidating/scaring their employees into compliance. 4 It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :"
1,Software Engineer Iii,5.0,2014-05-10,"Current employee, more than 1 year","If you're a software engineer, you're among the kings of the hill at Google. It's an engineerdriven company without a doubt that is changing, but it's still very engineerfocused. The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties at Waldorf Astoria, NY Public Library, MoMA, etc.; overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially. Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants. There a huge diversity of work ranging from defending independent journalism worldwide Google Project Shield to crisis response during disasters see Maps during Hurricane Sandy or Tsunamis, to the best machine learning experts and projects in the world, to more mundane revenuedriving projects in advertising, there's really something for everybody. It's easy to move around within the company as long as you're in good standing the vast majority of engineers are. The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive. No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible. Neither pro nor con, but general information on worklife balance, promotions, and advancement. Work life balance can be what you want it to be on most teams. Some teams are in more competitive sectors and require more crazy hours all the time but very few of them. If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hypermotived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand. If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google smarter than average, but just average compared to other Googlers you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer it's the minimum requirement, but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","It is becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, crossdivisional tension though nothing remotely approaching that of Microsoft's internal tension. The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse. Also with growth means more internalconfidential data leaks again, because of the raw numbers of people product announcements being ruined, etc. That means the company has to be tighterlipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture."
2,Anonymous Employee,5.0,2015-02-08,Current employee,"You can't find a more wellregarded company that actually deserves the hype it gets. You'll work on cutting edge projects / solve important issues that impact your community and the world You'll meet interesting people who are your colleagues, managers, and senior management. You'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing You'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. There are 22 cafes more or less, the food is excellent, and it's free. Your pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved. Google cares about how it treats its employees. The campus is like an academic campus in many ways. There are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out but you'll need to make sure to carve out time to do these things. You'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google. If and when you leave, you'll never regret having that company on your resume. It opens doors. The company is flexible if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work but don't get me wrong you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 34 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal. Your first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things. You'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing which is kind of hard. After two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. It's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30something idealism on top which can fool you into thinking that people are easygoing they're not. They're driven. If you're not driven, you're not going to fit in. When you start at Google, it seems like peer reviews are super important they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc. It's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out."
4,Software Development Engineer (Sde),4.0,2025-07-28,Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include: 1. High Expectations: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly. 2. Intense Workload: The fastpaced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees. 3. Internal Competition: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful. 4. WorkLife Balance: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life. 5. Bureaucracy and Hierarchy: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decisionmaking or innovation for some teams. Of course, these experiences can vary widely depending on the team, role, and individual preferences."
5,Account Manager,1.0,2025-07-08,"Former employee, more than 1 year","Benefits, Colleagues, Pay, Dog friendly and free food. Overall its a great environment with plenty of perks, amazing people and opportunities to move and learn.","Everything here depends on your direct manager. You will either get a genuine leader who invests in your growth and success or a someone who pretends but is only there to make themselves look good and will actively make your life hell to push you out. Holier than thou attitudes of middle managers make it very a very toxic and twofaced environment. If you don't follow blindly you will be pushed out of the company under the facade of ""support"". Expectations seem to be different for people in the same role depending on if a manager likes you or not. Untrustworthy people in influential positions who play the politics game instead of actually serving customers. HR dont take reports of bullying and discrimination seriously enough. They don't actually care about customers and doing things the right way, its a fake customer first mindset while you're forced to shove products down businesses throats even though it could ruin their business. Overall be very cautious of the people around you, because behind the smiles, fake ""we're a team and support each other"" talk and ""Googliness"", there are some who want you to fail."
...,...,...,...,...,...,...
42335,Boat Mechanic,5.0,2022-08-17,Former employee,Great great great great job,No cons no cons no cons
42365,Cvg Marketing,4.0,2022-09-02,Current employee,Great pay for new hire,Work a lot on the holidays
42379,Actuary,5.0,2022-09-08,"Current employee, less than 1 year",because its a good administration,there agree work jest fjfjfjf jf
42384,Senior Information Developer,5.0,2022-09-11,Current employee,Good to work and good,Ehh not much here to write
42402,Corporate Tax Intern,4.0,2022-09-19,Current employee,Nothing to say about it,Only good things to say about it

In [104]:
GoogleRev[GoogleRev["Cons"].str.contains("\r")]

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [105]:
GoogleRev.insert(6,"Company_Name", "Google")

In [106]:
GoogleRev.set_index("Job Title", inplace=True)

In [107]:
GoogleRev.reset_index(inplace=True)

In [108]:
GoogleRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons,Company_Name
0,Program Manager,4.0,2013-06-21,"Former employee, more than 8 years","1 Food, food, food. 15+ cafes on main campus MTV alone. Minikitchens, snacks, drinks, free breakfast/lunch/dinner, all day, errr'day. 2 Benefits/perks. Free 24:7 gym access on MTV campus. Free self service laundry washer/dryer available. Bowling alley. Volley ball pit. Custombuilt and exclusive employee use only outdoor sport park MTV. Free health/fitness assessments. Dogfriendly. Etc. etc. etc. 3 Compensation. In ~2010 or 2011, Google updated its compensation packages so that they were more competitive. 4 For the size of the organization 30K+, it has remained relatively innovative, nimble, and fastpaced and open with communication but, that is definitely changing for the worse. 5 With so many departments, focus areas, and products, in theory, you should have plenty of opportunity to grow your career horizontally or vertically. In practice, not true. 6 You get to work with some of the brightest, most innovative and hardworking/diligent minds in the industry. There's a ""con"" to that, too see below.","1 Work/life balance. What balance? All those perks and benefits are an illusion. They keep you at work and they help you to be more productive. I've never met anybody at Google who actually time off on weekends or on vacations. You may not hear management say, ""You have to work on weekends/vacations"" but, they set the culture by doing so and it inevitably trickles down. I don't know if Google inadvertently hires the workaholics or if they create workaholics in us. Regardless, I have seen way too many of the following: marriages fall apart, colleagues choosing work and projects over family, colleagues getting physically sick and ill because of stress, colleagues crying while at work because of the stress, colleagues shooting out emails at midnight, 1am, 2am, 3am. It is absolutely ridiculous and something needs to change. 2 Poor management. I think the issue is that, a majority of people love Google because they get to work on interesting technical problems and these are the people that see little value in learning how to develop emotional intelligence. Perhaps they enjoy technical problems because people are too ""difficult."" People are promoted into management positions not because they actually know how to lead/manage, but because they happen to be smart or because there is no other path to grow into. So there is a layer of intelligent individuals who are horrible managers and leaders. Yet, there is no value system to actually do anything about that because ""emotional intelligence"" or ""adaptive leadership"" are not taken seriously. 3 Jerks. Sure, there are a lot of brilliant people but, sadly, there are also a lot of jerks and, many times, they are one and the same. Years ago, that wasn't the case. I don't know if the pool of candidates is getting smaller, or maybe all the folks with great personalities cashed out and left, or maybe people are getting burned out and it's wearing on their personality and patience. I've heard stories of managers straightup cussing out their employees and intimidating/scaring their employees into compliance. 4 It's a giant company now and, inevitably, it has become slower moving and is now layered with process and bureaucracy. So many political battles, empire building, territory grabbing. Google says, ""Don't be evil."" But, that practice doesn't seem to be put into place when it comes to internal practices. :",Google
1,Software Engineer Iii,5.0,2014-05-10,"Current employee, more than 1 year","If you're a software engineer, you're among the kings of the hill at Google. It's an engineerdriven company without a doubt that is changing, but it's still very engineerfocused. The perks are amazing. Yes, free breakfast, lunch, an dinner every weekday. Aaaaaamazing holiday parties at Waldorf Astoria, NY Public Library, MoMA, etc.; overnight ski trips to Vermont; overnight nature trips to the Poconos in the summer; summer picnics at Chelsea piers; and on and on and on. I don't see this going away unless the company starts hurting financially. Speaking of which, the company is doing quite well, which reflects in bonuses and equity grants. There a huge diversity of work ranging from defending independent journalism worldwide Google Project Shield to crisis response during disasters see Maps during Hurricane Sandy or Tsunamis, to the best machine learning experts and projects in the world, to more mundane revenuedriving projects in advertising, there's really something for everybody. It's easy to move around within the company as long as you're in good standing the vast majority of engineers are. The company is amazingly open: every week Larry Page and Sergey Brin host what's called TGIF where food, beer, wine, etc. is served, a new project is presented, and afterward there's an open forum to ask the executives anything you want. It's truly fair game to ask anything, no matter how controversial, and frequently the executives will be responsive. No, nobody cares if you use an iPhone, Facebook, shop with Amazon, stream using Spotify, or refuse to use Google+. The company is amazingly open and flexible. Neither pro nor con, but general information on worklife balance, promotions, and advancement. Work life balance can be what you want it to be on most teams. Some teams are in more competitive sectors and require more crazy hours all the time but very few of them. If you do what's expected, you'll be fine at least for a handful of years. Working a roughly 40 hour work week is possible, and many people do it. There are also people who are hypermotived and work like crazy just because they love it, or because they're competitive, or they want to get a promotion. If you work 40 hour weeks without putting in anything extra, you'll fall behind them as they advance and you stand still and maybe that doesn't matter, so it works out for everybody. But at least know where you would realistically stand. If you excel and work your butt off, you'll be compensated and promoted. If you let yourself be a code monkey, and just sit coding with your head down all day, you'll be fine but won't advance. A big complaint from some Googlers is about not being able to advance ""even at Google"" with pure coding. Sure, if you're the uber genius who created MapReduce and Bigtable, you're going to advance like a rocket without having to do anything but coding; but if you're like most engineers at Google smarter than average, but just average compared to other Googlers you're just a good coder and not revolutionary. Code monkeys are important to actually get stuff done, and to be sure you absolutely need to be a good coder as a software engineer it's the minimum requirement, but code monkeys won't advance because they're not leaders and they're easy to replace. To get promoted you need to lead and do more than just code. There are plenty of ways to lead other than being an official tech lead, so this isn't actually _that_ hard, so the real point is just that you can't just sit there coding what other people tell you to code all day and expect to advance.","It is becoming larger, and with it comes growing pains: bureaucracy, slow to respond to market threats, bloated teams, crossdivisional tension though nothing remotely approaching that of Microsoft's internal tension. The quality of the engineers is possibly dropping, but possibly not. It's hard to get real metrics, because as the absolute number of people grows, naturally the number of bad apples grows; as a percentage it's supposedly the same as it ever was, but with larger numbers of poorer quality engineers it just _feels_ like things might be changing for the worse. Also with growth means more internalconfidential data leaks again, because of the raw numbers of people product announcements being ruined, etc. That means the company has to be tighterlipped internally to avoid leaks, which makes things less open. It's still an amazingly open place, but less so than it was even a couple years ago. The good thing is they recognize it and actively look to improve things because they know how important it is to keep the good culture.",Google
2,Anonymous Employee,5.0,2015-02-08,Current employee,"You can't find a more wellregarded company that actually deserves the hype it gets. You'll work on cutting edge projects / solve important issues that impact your community and the world You'll meet interesting people who are your colleagues, managers, and senior management. You'll open the paper and see your company in the news almost every day, and read about projects you're working on, which is a cool thing You'll see Larry and Sergey at TGIF and you'll admire how they lead the company. They are brilliant, goofy, low key but intense, and likeable. There are 22 cafes more or less, the food is excellent, and it's free. Your pay will typically be competitive, though it needs to be tweaked up a bit since the economy has improved. Google cares about how it treats its employees. The campus is like an academic campus in many ways. There are tons of activities on campus, like authors speaking about their books, films after work, and gyms where you can work out but you'll need to make sure to carve out time to do these things. You'll get plenty of external validation from people who suddenly think you're smart and rich because you work there, even if you're not rich and you're as smart when you didn't work at Google. If and when you leave, you'll never regret having that company on your resume. It opens doors. The company is flexible if you're lucky, you won't have a micromanager boss and you can be somewhat flexible in how you work but don't get me wrong you'll work a LOT. But you don't have to do all of it chained to your desk.","I live in SF so the commute can take between 1.5 hours to 1.75 hours each way on the shuttle sometimes 2 hours each way on a busy day or rainy day. That means being on the bus for 34 hours PER DAY. It's a wired bus though which means you can work on the way to Mountain View. But it can feel brutal. Your first year or two are really important in terms of your career at Google and they affect how you're viewed, and your ability to be promoted. You should always ask to work on high profile projects. If you don't get them, don't expect to get high ratings or get promoted. Always volunteer for cross functional group work for maximum exposure, and then work hard at those things. You'll likely work on something that no one will explain to you and it will take you at least a year to be comfortable doing what you're working on, even if you're super quick at learning. No one has time to train you or teach you what you're doing which is kind of hard. After two or three years, people you started out with at Google start to get promoted. If you're not one of them, you'll wonder why and how it happened, and that process is somewhat political and not always clear. It's a big company now. And super political. So don't be naive. Expect some people to be catty, some people to be territorial, and be prepared to be mentally tough. Don't let people see your vulnerableness. It's a Darwinistic culture with a huge dose of 30something idealism on top which can fool you into thinking that people are easygoing they're not. They're driven. If you're not driven, you're not going to fit in. When you start at Google, it seems like peer reviews are super important they are, but they are the sprinkles on the fro yo. The important thing is that your direct manager knows your work, likes your work and likes you, and then you can get promoted. If your boss doesn't like you, all the positive peer reviews in the world won't help you. Make sure you know what your boss wants, and give it to them. You will have weekly one on ones, and make sure you are addressing your performance at each one, asking if they have questions, how you can improve, can you work on cross functional projects, etc. It's really hard to find work life balance at Google. The workload is huge. I hardly have time to work out. The commute is brutal. My family sometimes needs more from me and I can't give it. I'm still trying to find the balance. I think I need more down time than most people so I have a hard time being structured every day to fit all the things I want into my day, so a lot of things slip, like working out.",Google
3,Software Development Engineer (Sde),4.0,2025-07-28,Former employee,"Google is also known for offering generous benefits, a flexible work environment, and a focus on personal development and learning. The diversity of projects and the impact their work can have globally is another big draw for those who work there. Would you like to know more about specific aspects of Google's work culture","While many employees enjoy working at Google, some challenges have been reported by others. These can include: 1. High Expectations: Google has a reputation for hiring top talent, which means there's often pressure to meet high expectations and deliver results quickly. 2. Intense Workload: The fastpaced, constantly evolving nature of the tech industry can result in long hours or a sense of burnout for some employees. 3. Internal Competition: With such a large pool of talented people, some individuals might feel a competitive atmosphere that can be stressful. 4. WorkLife Balance: While Google offers flexible work options, the sheer volume of work and the company's fast pace may make it challenging for some employees to maintain a balance between work and personal life. 5. Bureaucracy and Hierarchy: Despite its reputation for innovation, the company is still large and can have bureaucratic layers that may slow decisionmaking or innovation for some teams. Of course, these experiences can vary widely depending on the team, role, and individual preferences.",Google
4,Account Manager,1.0,2025-07-08,"Former employee, more than 1 year","Benefits, Colleagues, Pay, Dog friendly and free food. Overall its a great environment with plenty of perks, amazing people and opportunities to move and learn.","Everything here depends on your direct manager. You will either get a genuine leader who invests in your growth and success or a someone who pretends but is only there to make themselves look good and will actively make your life hell to push you out. Holier than thou attitudes of middle managers make it very a very toxic and twofaced environment. If you don't follow blindly you will be pushed out of the company under the facade of ""support"". Expectations seem to be different for people in the same role depending on if a manager likes you or not. Untrustworthy people in influential positions who play the politics game instead of actually serving customers. HR dont take reports of bullying and discrimination seriously enough. They don't actually care about customers and doing things the right way, its a fake customer first mindset while you're forced to shove products down businesses throats even though it could ruin their business. Overall be very cautious of the people around you, because behind the smiles, fake ""we're a team and support each other"" talk and ""Googliness"", there are some who want you to fail.",Google
...,...,...,...,...,...,...,...
4909,Boat Mechanic,5.0,2022-08-17,Former employee,Great great great great job,No cons no cons no cons,Google
4910,Cvg Marketing,4.0,2022-09-02,Current employee,Great pay for new hire,Work a lot on the holidays,Google
4911,Actuary,5.0,2022-09-08,"Current employee, less than 1 year",because its a good administration,there agree work jest fjfjfjf jf,Google
4912,Senior Information Developer,5.0,2022-09-11,Current employee,Good to work and good,Ehh not much here to write,Google
4913,Corporate Tax Intern,4.0,2022-09-19,Current employee,Nothing to say about it,Only good things to say about it,Google

In [109]:
Path  = "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CleanCompanyRev/Google.csv"

In [110]:
GoogleRev.to_csv(Path, index=False)