In [9]:
# importing packages
import pandas as pd
import numpy as np

In [10]:
kcbRev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/KCBReviews.csv")

In [11]:
# EDA on the data
def display(x):
    """This function returns a 
    summary of the dataset"""
    
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(kcbRev)

Displays the rows and columns in the dataset
============================================
Rows: 210 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                              Job Title  Job Ratings          time  \
0      Certified nursing assistant cna          1.0  Mar 12, 2024
1               Cyber security analyst          5.0  Jul 23, 2025
2                         Bank officer          5.0  Jul 28, 2025
3                     Finacial analyst          5.0  Jul 14, 2025
4                    Finance executive          5.0  Jul 16, 2025
..                                 ...          ...           ...
205                   Business analyst          4.0  Apr 17, 2024
206                 Clerical assistant          4.0  Apr 16, 2024
207  Direct sales representative (dsr)          2.0  Mar 21, 2024
208                 Management trainee          5.0  Mar 14, 2024
209           Customer success manager          4.0  Mar 19, 2024

                               JobStatus  \
0                       Current employee
1     Current employee, more than 1 year
2    Current employee, more than 3 years
3     Current employee, more than 1 year
4      Former employee, less than 1 year
..                                   ...
205  Current employee, more than 3 years
206                     Current employee
207    Former employee, less than 1 year
208  Current employee, more than 3 years
209  Current employee, more than 5 years

                                                  Pros  \
0                            No home life no insurance
1    good work life balance and good insurance , ho...
2            Nice renumeration\nOpportunity for growth
3    Strong leadership and corporate culture.\nMult...
4    remote work option\nadvance system\ntransparen...
..                                                 ...
205  Good working environment and opportunities for...
206             Extensive medical cover\nGood employer
207  Enables one to learn a lot in the banking indu...
208  good medical scheme and employee retirement sc...
209  Flexibility, training and development and care...

                                                  Cons
0        Bad management mandatory overtime every shift
1               few commissions which come once a year
2                         Long working hours\nMean mgt
3    Heavy workload in some departments.\nCommunica...
4    long working hours\nhigh work load\npoor work ...
..                                                 ...
205                 It is a results driven environment
206                     None I have experienced so far
207         Too much pressure to meet the target sales
208  role stagnation can extende up to more than a ...
209             Long working hours pressure to deliver

[210 rows x 6 columns]>

Returns the information in more details
============================================
       Job Ratings
count   210.000000
mean      4.361905
std       0.876310
min       1.000000
25%       4.000000
50%       5.000000
75%       5.000000
max       5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           50
dtype: int64

In [12]:
# display the whole column content
pd.set_option("display.max_colwidth", None)

In [13]:
# The first 3 elements
print("Top 5 elements")
print("=============================")
print()
kcbRev.head()

Top 5 elements
=============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Certified nursing assistant cna,1.0,"Mar 12, 2024",Current employee,No home life no insurance,Bad management mandatory overtime every shift
1,Cyber security analyst,5.0,"Jul 23, 2025","Current employee, more than 1 year","good work life balance and good insurance , holiday and mortgage bonuses",few commissions which come once a year
2,Bank officer,5.0,"Jul 28, 2025","Current employee, more than 3 years",Nice renumeration\nOpportunity for growth,Long working hours\nMean mgt
3,Finacial analyst,5.0,"Jul 14, 2025","Current employee, more than 1 year",Strong leadership and corporate culture.\nMultiple learning and growth opportunities.\nInclusive and innovative mindset.,Heavy workload in some departments.\nCommunication gaps between branches and HQ.
4,Finance executive,5.0,"Jul 16, 2025","Former employee, less than 1 year",remote work option\nadvance system\ntransparent communication from leadership\nencouragement of innovation and ideas,long working hours\nhigh work load\npoor work life balance

In [14]:
# last 5 elements
print("last 5 elements")
print("============================")
print()
kcbRev.tail()

last 5 elements
============================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
205,Business analyst,4.0,"Apr 17, 2024","Current employee, more than 3 years",Good working environment and opportunities for growth,It is a results driven environment
206,Clerical assistant,4.0,"Apr 16, 2024",Current employee,Extensive medical cover\nGood employer,None I have experienced so far
207,Direct sales representative (dsr),2.0,"Mar 21, 2024","Former employee, less than 1 year",Enables one to learn a lot in the banking industry,Too much pressure to meet the target sales
208,Management trainee,5.0,"Mar 14, 2024","Current employee, more than 3 years",good medical scheme and employee retirement scheme,role stagnation can extende up to more than a year
209,Customer success manager,4.0,"Mar 19, 2024","Current employee, more than 5 years","Flexibility, training and development and career growth opportunities",Long working hours pressure to deliver

In [15]:
# random 5 elements
print("Random 5 elements")
print("=========================")
print()
kcbRev.sample(5)

Random 5 elements
=========================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
53,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
136,Marketing,3.0,"Oct 2, 2024","Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
9,Bancassurance officer,4.0,"May 12, 2025","Former employee, more than 3 years",Guaranteed bonuses annually\nGuaranteed salary increment annually,Growth opportunities are limited hence one bein stagnant
190,Branch manager,4.0,"Aug 28, 2024",Current employee,Very nice work environment. Welcoming and easy to be productive,Lack of accountability by higher level staff
95,Direct sales representative,3.0,"Oct 17, 2024",Former employee,Good colleagues and working conditions,No leave days for contractors

In [16]:
# loops over the whole column 1
for index,col in enumerate (kcbRev["Job Title"]):
    print(index, col)

0 Certified nursing assistant cna
1 Cyber security analyst
2 Bank officer
3 Finacial analyst
4 Finance executive
5 Senior risk management analyst
6 Bancassurance officer
7 Anonymous employee
8 Direct sales representative
9 Bancassurance officer
10 Transition specialist
11 Application security specialist
12 Intern
13 Direct sales representative (dsr)
14 Data analyst
15 Bank teller
16 Ict administrator
17 Direct sales representative (dsr)
18 Direst sales representative
19 Marketing director
20 Transition specialist
21 Application security specialist
22 Intern
23 Direct sales representative (dsr)
24 Data analyst
25 Bank teller
26 Ict administrator
27 Direct sales representative (dsr)
28 Direst sales representative
29 Marketing director
30 Locked job title
31 Locked job title
32 Locked job title
33 Locked job title
34 Locked job title
35 Locked job title
36 Locked job title
37 Locked job title
38 Locked job title
39 Locked job title
40 Locked job title
41 Locked job title
42 Locked job title
43 Locked job title
44 Locked job title
45 Locked job title
46 Locked job title
47 Locked job title
48 Locked job title
49 Locked job title
50 Locked job title
51 Locked job title
52 Locked job title
53 Locked job title
54 Locked job title
55 Locked job title
56 Locked job title
57 Locked job title
58 Locked job title
59 Locked job title
60 Locked job title
61 Locked job title
62 Locked job title
63 Locked job title
64 Locked job title
65 Locked job title
66 Locked job title
67 Locked job title
68 Locked job title
69 Locked job title
70 Locked job title
71 Locked job title
72 Locked job title
73 Locked job title
74 Locked job title
75 Locked job title
76 Locked job title
77 Locked job title
78 Locked job title
79 Locked job title
80 Accountant
81 Direct sales representative (dsr)
82 Solutions architect
83 Banker
84 Bank teller
85 Direct sales representative
86 Marketing
87 Banker
88 It support technician
89 Customer service representative
90 Accountant
91 Direct sales representative (dsr)
92 Solutions architect
93 Banker
94 Bank teller
95 Direct sales representative
96 Marketing
97 Banker
98 It support technician
99 Customer service representative
100 Accountant
101 Direct sales representative (dsr)
102 Solutions architect
103 Banker
104 Bank teller
105 Direct sales representative
106 Marketing
107 Banker
108 It support technician
109 Customer service representative
110 Accountant
111 Direct sales representative (dsr)
112 Solutions architect
113 Banker
114 Bank teller
115 Direct sales representative
116 Marketing
117 Banker
118 It support technician
119 Customer service representative
120 Accountant
121 Direct sales representative (dsr)
122 Solutions architect
123 Banker
124 Bank teller
125 Direct sales representative
126 Marketing
127 Banker
128 It support technician
129 Customer service representative
130 Accountant
131 Direct sales representative (dsr)
132 Solutions architect
133 Banker
134 Bank teller
135 Direct sales representative
136 Marketing
137 Banker
138 It support technician
139 Customer service representative
140 Accountant
141 Direct sales representative (dsr)
142 Solutions architect
143 Banker
144 Bank teller
145 Direct sales representative
146 Marketing
147 Banker
148 It support technician
149 Customer service representative
150 Accountant
151 Direct sales representative (dsr)
152 Solutions architect
153 Banker
154 Bank teller
155 Direct sales representative
156 Marketing
157 Banker
158 It support technician
159 Customer service representative
160 Accountant
161 Direct sales representative (dsr)
162 Solutions architect
163 Banker
164 Bank teller
165 Direct sales representative
166 Marketing
167 Banker
168 It support technician
169 Customer service representative
170 Accountant
171 Direct sales representative (dsr)
172 Solutions architect
173 Banker
174 Bank teller
175 Direct sales representative
176 Marketing
177 Banker
178 It support technician
179 Customer service representative
180 Accountant
181 Direct sales representative (dsr)
182 Solutions architect
183 Banker
184 Bank teller
185 Direct sales representative
186 Marketing
187 Banker
188 It support technician
189 Customer service representative
190 Branch manager
191 Anonymous employee
192 Direct sales representative
193 It technical support specialist
194 Branch manager
195 Direct sales representative
196 App developer
197 Sales representative
198 Analyst
199 Applications developer
200 Data entry clerk
201 Card operations officer
202 Teller
203 Direct sales representative (dsr)
204 Applications developer
205 Business analyst
206 Clerical assistant
207 Direct sales representative (dsr)
208 Management trainee
209 Customer success manager

In [17]:
kcbRev.iloc[30:79]

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
30,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
31,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
32,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
33,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
34,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
35,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
36,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
37,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
38,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
39,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
40,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
41,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
42,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
43,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
44,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
45,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
46,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
47,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
48,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
49,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
50,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
51,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
52,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
53,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
54,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
55,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
56,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
57,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
58,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
59,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
60,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
61,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
62,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
63,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
64,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
65,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
66,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
67,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
68,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
69,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
70,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
71,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
72,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
73,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
74,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
75,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
76,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
77,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN
78,Locked job title,5.0,"Apr 25, 2025","Former employee, more than 1 year","This review is locked, to see it please log in",NaN

In [18]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns 
    total null values on the dataset"""
    print(df.isna().sum())
null_values(kcbRev)

Job Title       0
Job Ratings     0
time            0
JobStatus       0
Pros            0
Cons           50
dtype: int64

In [19]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the 
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(kcbRev)
# CisRev.dropna(inplace=True)

In [20]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(kcbRev)

In [21]:
# Rename the headers
kcbRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [22]:
# pd.set_option("display.max_rows",None)
pd.reset_option("display.max_rows",None)

In [23]:
kcbRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Certified nursing assistant cna,1.0,2024-03-12,Current employee,No home life no insurance,Bad management mandatory overtime every shift
1,Cyber security analyst,5.0,2025-07-23,"Current employee, more than 1 year","good work life balance and good insurance , holiday and mortgage bonuses",few commissions which come once a year
2,Bank officer,5.0,2025-07-28,"Current employee, more than 3 years",Nice renumeration\nOpportunity for growth,Long working hours\nMean mgt
3,Finacial analyst,5.0,2025-07-14,"Current employee, more than 1 year",Strong leadership and corporate culture.\nMultiple learning and growth opportunities.\nInclusive and innovative mindset.,Heavy workload in some departments.\nCommunication gaps between branches and HQ.
4,Finance executive,5.0,2025-07-16,"Former employee, less than 1 year",remote work option\nadvance system\ntransparent communication from leadership\nencouragement of innovation and ideas,long working hours\nhigh work load\npoor work life balance
...,...,...,...,...,...,...
205,Business analyst,4.0,2024-04-17,"Current employee, more than 3 years",Good working environment and opportunities for growth,It is a results driven environment
206,Clerical assistant,4.0,2024-04-16,Current employee,Extensive medical cover\nGood employer,None I have experienced so far
207,Direct sales representative (dsr),2.0,2024-03-21,"Former employee, less than 1 year",Enables one to learn a lot in the banking industry,Too much pressure to meet the target sales
208,Management trainee,5.0,2024-03-14,"Current employee, more than 3 years",good medical scheme and employee retirement scheme,role stagnation can extende up to more than a year
209,Customer success manager,4.0,2024-03-19,"Current employee, more than 5 years","Flexibility, training and development and career growth opportunities",Long working hours pressure to deliver

In [24]:
kcbRev.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160 entries, 0 to 209
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Job Title   160 non-null    object
 1   Job Rating  160 non-null    float64
 2   Time        160 non-null    datetime64[ns]
 3   Job Status  160 non-null    object
 4   Pros        160 non-null    object
 5   Cons        160 non-null    object
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 8.8+ KB

In [25]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(kcbRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Certified nursing assistant cna,1.0,2024-03-12,Current employee,No home life no insurance,Bad management mandatory overtime every shift
1,Cyber security analyst,5.0,2025-07-23,"Current employee, more than 1 year","good work life balance and good insurance , holiday and mortgage bonuses",few commissions which come once a year
2,Bank officer,5.0,2025-07-28,"Current employee, more than 3 years",Nice renumeration\nOpportunity for growth,Long working hours\nMean mgt
3,Finacial analyst,5.0,2025-07-14,"Current employee, more than 1 year",Strong leadership and corporate culture.\nMultiple learning and growth opportunities.\nInclusive and innovative mindset.,Heavy workload in some departments.\nCommunication gaps between branches and HQ.
4,Finance executive,5.0,2025-07-16,"Former employee, less than 1 year",remote work option\nadvance system\ntransparent communication from leadership\nencouragement of innovation and ideas,long working hours\nhigh work load\npoor work life balance
...,...,...,...,...,...,...
205,Business analyst,4.0,2024-04-17,"Current employee, more than 3 years",Good working environment and opportunities for growth,It is a results driven environment
206,Clerical assistant,4.0,2024-04-16,Current employee,Extensive medical cover\nGood employer,None I have experienced so far
207,Direct sales representative (dsr),2.0,2024-03-21,"Former employee, less than 1 year",Enables one to learn a lot in the banking industry,Too much pressure to meet the target sales
208,Management trainee,5.0,2024-03-14,"Current employee, more than 3 years",good medical scheme and employee retirement scheme,role stagnation can extende up to more than a year
209,Customer success manager,4.0,2024-03-19,"Current employee, more than 5 years","Flexibility, training and development and career growth opportunities",Long working hours pressure to deliver

In [26]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace("\n", "", regex=True))
    return df
remove_char(kcbRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Certified nursing assistant cna,1.0,2024-03-12,Current employee,No home life no insurance,Bad management mandatory overtime every shift
1,Cyber security analyst,5.0,2025-07-23,"Current employee, more than 1 year","good work life balance and good insurance , holiday and mortgage bonuses",few commissions which come once a year
2,Bank officer,5.0,2025-07-28,"Current employee, more than 3 years",Nice renumerationOpportunity for growth,Long working hoursMean mgt
3,Finacial analyst,5.0,2025-07-14,"Current employee, more than 1 year",Strong leadership and corporate culture.Multiple learning and growth opportunities.Inclusive and innovative mindset.,Heavy workload in some departments.Communication gaps between branches and HQ.
4,Finance executive,5.0,2025-07-16,"Former employee, less than 1 year",remote work optionadvance systemtransparent communication from leadershipencouragement of innovation and ideas,long working hourshigh work loadpoor work life balance
...,...,...,...,...,...,...
205,Business analyst,4.0,2024-04-17,"Current employee, more than 3 years",Good working environment and opportunities for growth,It is a results driven environment
206,Clerical assistant,4.0,2024-04-16,Current employee,Extensive medical coverGood employer,None I have experienced so far
207,Direct sales representative (dsr),2.0,2024-03-21,"Former employee, less than 1 year",Enables one to learn a lot in the banking industry,Too much pressure to meet the target sales
208,Management trainee,5.0,2024-03-14,"Current employee, more than 3 years",good medical scheme and employee retirement scheme,role stagnation can extende up to more than a year
209,Customer success manager,4.0,2024-03-19,"Current employee, more than 5 years","Flexibility, training and development and career growth opportunities",Long working hours pressure to deliver

In [27]:
hiphen = kcbRev[kcbRev["Cons"].str.startswith("-")]
hiphen

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [28]:
pd.set_option("display.max_rows",None)
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(kcbRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Certified nursing assistant cna,1.0,2024-03-12,Current employee,No home life no insurance,Bad management mandatory overtime every shift
1,Cyber security analyst,5.0,2025-07-23,"Current employee, more than 1 year","good work life balance and good insurance , holiday and mortgage bonuses",few commissions which come once a year
2,Bank officer,5.0,2025-07-28,"Current employee, more than 3 years",Nice renumerationOpportunity for growth,Long working hoursMean mgt
3,Finacial analyst,5.0,2025-07-14,"Current employee, more than 1 year",Strong leadership and corporate culture.Multiple learning and growth opportunities.Inclusive and innovative mindset.,Heavy workload in some departments.Communication gaps between branches and HQ.
4,Finance executive,5.0,2025-07-16,"Former employee, less than 1 year",remote work optionadvance systemtransparent communication from leadershipencouragement of innovation and ideas,long working hourshigh work loadpoor work life balance
5,Senior risk management analyst,5.0,2025-07-13,"Current employee, more than 3 years",Good bonusesMedicalVery open staff,Prayers before meetings. Very strange for non Christians.
6,Bancassurance officer,5.0,2025-06-23,"Former employee, more than 3 years",Great working environment and teamwork,Culture change from management and teamwork
7,Anonymous employee,4.0,2025-06-01,"Former employee, less than 1 year",Inclusive of employees Good payFriendly environment,Intense environment in terms of deadlines and assigned roles
8,Direct sales representative,4.0,2025-05-20,"Former employee, less than 1 year",get paid for your effort,purely commission based no retainer
9,Bancassurance officer,4.0,2025-05-12,"Former employee, more than 3 years",Guaranteed bonuses annuallyGuaranteed salary increment annually,Growth opportunities are limited hence one bein stagnant
10,Transition specialist,3.0,2025-05-08,Former employee,Great for learning as junior,Limited growth career path in IT
11,Application security specialist,4.0,2025-01-20,"Current employee, more than 3 years","Tightknit team that works well together for the most part. Senior managers are cool, very down to earth and ready to assist even if you don't directly report to them. If you want stability with a governmentbacked institution, KCB is your goto choice. Loans are awesomely priced at low interest for employees.","Procurement could use some speed in terms of how long it takes to get tools, services, etc onboarded. Pay is ok. Benefits are ok as well."
12,Intern,3.0,2025-02-25,"Former employee, less than 1 year",Learn the intricacies of the banking industry,"Sometimes I felt underemployed, and the department I was interning at had peak seasons and low seasons"
13,Direct sales representative (dsr),3.0,2025-03-18,"Former employee, more than 1 year","Friendly colleagues, good benefits overall","Unreasonable sales target, too much pressure"
14,Data analyst,5.0,2025-01-25,"Current employee, more than 1 year",Friendly work Environment from management to colleagues,"Long working hours, requires proper time management."
15,Bank teller,5.0,2025-01-26,"Former employee, more than 1 year",Conducive environment for both workers and customers,Sometimes you work till late
16,Ict administrator,5.0,2025-01-22,"Former employee, more than 1 year",Good Salary paid every month,bureaucracy at top management level
17,Direct sales representative (dsr),4.0,2025-01-06,Current employee,Good working environmentSmooth interview process,More of field work than stationary work
18,Direst sales representative,4.0,2024-11-12,"Former employee, more than 3 years",I want to able to build the brand image of Kenya Commercial Bank,Not being that competitive with other banking industries
19,Marketing director,4.0,2024-11-15,"Current employee, more than 1 year",Enthusiastic team to work with good targets,Targets can at times be quite high
20,Transition specialist,3.0,2025-05-08,Former employee,Great for learning as junior,Limited growth career path in IT
21,Application security specialist,4.0,2025-01-20,"Current employee, more than 3 years","Tightknit team that works well together for the most part. Senior managers are cool, very down to earth and ready to assist even if you don't directly report to them. If you want stability with a governmentbacked institution, KCB is your goto choice. Loans are awesomely priced at low interest for employees.","Procurement could use some speed in terms of how long it takes to get tools, services, etc onboarded. Pay is ok. Benefits are ok as well."
22,Intern,3.0,2025-02-25,"Former employee, less than 1 year",Learn the intricacies of the banking industry,"Sometimes I felt underemployed, and the department I was interning at had peak seasons and low seasons"
23,Direct sales representative (dsr),3.0,2025-03-18,"Former employee, more than 1 year","Friendly colleagues, good benefits overall","Unreasonable sales target, too much pressure"
24,Data analyst,5.0,2025-01-25,"Current employee, more than 1 year",Friendly work Environment from management to colleagues,"Long working hours, requires proper time management."
25,Bank teller,5.0,2025-01-26,"Former employee, more than 1 year",Conducive environment for both workers and customers,Sometimes you work till late
26,Ict administrator,5.0,2025-01-22,"Former employee, more than 1 year",Good Salary paid every month,bureaucracy at top management level
27,Direct sales representative (dsr),4.0,2025-01-06,Current employee,Good working environmentSmooth interview process,More of field work than stationary work
28,Direst sales representative,4.0,2024-11-12,"Former employee, more than 3 years",I want to able to build the brand image of Kenya Commercial Bank,Not being that competitive with other banking industries
29,Marketing director,4.0,2024-11-15,"Current employee, more than 1 year",Enthusiastic team to work with good targets,Targets can at times be quite high
80,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
81,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
82,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
83,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
84,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
85,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
86,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
87,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
88,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
89,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
90,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
91,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
92,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
93,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
94,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
95,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
96,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
97,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
98,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
99,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
100,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
101,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
102,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
103,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
104,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
105,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
106,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
107,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
108,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
109,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
110,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
111,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
112,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
113,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
114,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
115,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
116,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
117,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
118,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
119,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
120,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
121,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
122,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
123,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
124,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
125,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
126,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
127,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
128,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
129,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
130,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
131,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
132,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
133,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
134,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
135,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
136,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
137,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
138,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
139,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
140,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
141,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
142,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
143,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
144,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
145,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
146,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
147,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
148,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
149,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
150,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
151,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
152,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
153,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
154,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
155,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
156,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
157,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
158,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
159,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
160,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
161,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
162,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
163,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
164,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
165,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
166,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new

In [29]:
# check duplicate sum
def checkDuplicateSum(df: pd.DataFrame) -> int:
    duplicate_count = df.duplicated().sum()
    return 'Sum of Duplicate_Values =', duplicate_count
checkDuplicateSum(kcbRev)

('Sum of Duplicate_Values =', 110)

In [30]:
kcbRev.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90      True
91      True
92      True
93      True
94      True
95      True
96      True
97      True
98      True
99      True
100     True
101     True
102     True
103     True
104     True
105     True
106     True
107     True
108     True
109     True
110     True
111     True
112     True
113     True
114     True
115     True
116     True
117     True
118     True
119     True
120     True
121     True
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147     True
148     True
149     True
150     True
151     True
152     True
153     True
154     True
155     True
156     True
157     True
158     True
159     True
160     True
161     True
162     True
163     True
164     True
165     True
166     True
167     True
168     True
169     True
170     True
171     True
172     True
173     True
174     True
175     True
176     True
177     True
178     True
179     True
180     True
181     True
182     True
183     True
184     True
185     True
186     True
187     True
188     True
189     True
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
dtype: bool

In [31]:
kcbRev.iloc[90:189]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
140,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
141,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
142,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
143,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
144,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
145,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
146,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
147,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
148,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
149,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
150,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
151,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
152,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
153,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
154,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
155,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
156,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
157,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
158,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
159,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
160,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
161,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
162,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
163,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
164,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
165,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
166,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
167,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
168,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
169,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
170,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
171,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
172,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
173,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
174,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
175,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
176,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
177,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
178,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
179,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
180,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines
181,Direct sales representative (dsr),5.0,2024-11-15,"Former employee, more than 1 year","Favorable working environment, no toxicity.",Bearable pressure. Still the best employer.
182,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects
183,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work
184,Bank teller,3.0,2024-10-22,"Former employee, less than 1 year",It's a nice placeCustomer care service good Time management,Over timeSystem problemOver working
185,Direct sales representative,3.0,2024-10-17,Former employee,Good colleagues and working conditions,No leave days for contractors
186,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new
187,Banker,5.0,2024-09-28,Current employee,The company offer Competitive salary,"Long working hours, no time for personal development"
188,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment
189,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift
190,Branch manager,4.0,2024-08-28,Current employee,Very nice work environment. Welcoming and easy to be productive,Lack of accountability by higher level staff
191,Anonymous employee,4.0,2024-08-27,"Former employee, more than 1 year",Competitive remunerationGrowth opportunitiesLow interest staff loans,Some senior managers have been there for long and have developed rigidity
192,Direct sales representative,1.0,2024-10-03,Former employee,They offer good retainer if you meet 100%targets,There's too much pressure and no guarantee to renew
193,It technical support specialist,5.0,2024-08-11,Former employee,Great working office environment for staff,none that i can think of
194,Branch manager,5.0,2024-07-18,Former employee,work balance is well catered for,too much micro management may be prohibitive
195,Direct sales representative,5.0,2024-07-29,"Former employee, more than 1 year",Career growth and developmentWork life balanceMedical cover,Pressure increasingHostile marketGround
196,App developer,4.0,2024-07-19,"Former employee, more than 5 years",Enjoyed my time there. Good employer,If you don't like corporate politics then ain't a good place for you.
197,Sales representative,3.0,2024-06-22,"Former employee, less than 1 year",It is the most transparent employer,some targets are not easy to attain
198,Analyst,3.0,2024-07-01,Current employee,good bonuses are paid every year,the internal process of being hired internally is hard
199,Applications developer,4.0,2024-05-14,"Current employee, more than 1 year",You get an opportunity to work on different kinds of projects which can in return grow your skills,Projects take a lot of time to finish due to unnecessary delays.
200,Data entry clerk,5.0,2024-05-22,"Current employee, more than 1 year",Leading bank in East and Central africa,You will handsomely paid well according to your experience
201,Card operations officer,5.0,2024-05-22,"Former employee, less than 1 year",Good work environment in the office,The leave days are a little
202,Teller,4.0,2024-05-20,"Current employee, more than 3 years",Good EmployerGood annual salary increment,Nothing to share for now
203,Direct sales representative (dsr),5.0,2024-05-15,"Former employee, more than 1 year",Possibility for career growth and skills cultivation,I haven't had any downside
204,Applications developer,5.0,2024-04-25,"Former employee, more than 1 year","Great place to work at, good culture, friendly workmates","Only annual salary increments, no mid year salary review"
205,Business analyst,4.0,2024-04-17,"Current employee, more than 3 years",Good working environment and opportunities for growth,It is a results driven environment
206,Clerical assistant,4.0,2024-04-16,Current employee,Extensive medical coverGood employer,None I have experienced so far
207,Direct sales representative (dsr),2.0,2024-03-21,"Former employee, less than 1 year",Enables one to learn a lot in the banking industry,Too much pressure to meet the target sales
208,Management trainee,5.0,2024-03-14,"Current employee, more than 3 years",good medical scheme and employee retirement scheme,role stagnation can extende up to more than a year
209,Customer success manager,4.0,2024-03-19,"Current employee, more than 5 years","Flexibility, training and development and career growth opportunities",Long working hours pressure to deliver

In [32]:
def drop_duplicate(df: pd.DataFrame) -> int:
    """This function drops the duplicated 
        values in the dataset
    Args = df for the dataset
    return = this function returns a dataframe 
        withiout the duplicate values"""
    drop_duplicates = df.drop_duplicates(subset = ["Job Title"], inplace=True)
    return drop_duplicates
drop_duplicate(kcbRev)

In [38]:
kcbRev.set_index("Job Title", inplace=True)
# kcbRev.drop("index", axis = 1, inplace=True)

In [39]:
kcbRev.reset_index(inplace=True)

,Job Title,Job Rating,Time,Job Status,Pros,Cons,Company_Name
0,Certified nursing assistant cna,1.0,2024-03-12,Current employee,No home life no insurance,Bad management mandatory overtime every shift,KCB
1,Cyber security analyst,5.0,2025-07-23,"Current employee, more than 1 year","good work life balance and good insurance , holiday and mortgage bonuses",few commissions which come once a year,KCB
2,Bank officer,5.0,2025-07-28,"Current employee, more than 3 years",Nice renumerationOpportunity for growth,Long working hoursMean mgt,KCB
3,Finacial analyst,5.0,2025-07-14,"Current employee, more than 1 year",Strong leadership and corporate culture.Multiple learning and growth opportunities.Inclusive and innovative mindset.,Heavy workload in some departments.Communication gaps between branches and HQ.,KCB
4,Finance executive,5.0,2025-07-16,"Former employee, less than 1 year",remote work optionadvance systemtransparent communication from leadershipencouragement of innovation and ideas,long working hourshigh work loadpoor work life balance,KCB
5,Senior risk management analyst,5.0,2025-07-13,"Current employee, more than 3 years",Good bonusesMedicalVery open staff,Prayers before meetings. Very strange for non Christians.,KCB
6,Bancassurance officer,5.0,2025-06-23,"Former employee, more than 3 years",Great working environment and teamwork,Culture change from management and teamwork,KCB
7,Anonymous employee,4.0,2025-06-01,"Former employee, less than 1 year",Inclusive of employees Good payFriendly environment,Intense environment in terms of deadlines and assigned roles,KCB
8,Direct sales representative,4.0,2025-05-20,"Former employee, less than 1 year",get paid for your effort,purely commission based no retainer,KCB
9,Transition specialist,3.0,2025-05-08,Former employee,Great for learning as junior,Limited growth career path in IT,KCB
10,Application security specialist,4.0,2025-01-20,"Current employee, more than 3 years","Tightknit team that works well together for the most part. Senior managers are cool, very down to earth and ready to assist even if you don't directly report to them. If you want stability with a governmentbacked institution, KCB is your goto choice. Loans are awesomely priced at low interest for employees.","Procurement could use some speed in terms of how long it takes to get tools, services, etc onboarded. Pay is ok. Benefits are ok as well.",KCB
11,Intern,3.0,2025-02-25,"Former employee, less than 1 year",Learn the intricacies of the banking industry,"Sometimes I felt underemployed, and the department I was interning at had peak seasons and low seasons",KCB
12,Direct sales representative (dsr),3.0,2025-03-18,"Former employee, more than 1 year","Friendly colleagues, good benefits overall","Unreasonable sales target, too much pressure",KCB
13,Data analyst,5.0,2025-01-25,"Current employee, more than 1 year",Friendly work Environment from management to colleagues,"Long working hours, requires proper time management.",KCB
14,Bank teller,5.0,2025-01-26,"Former employee, more than 1 year",Conducive environment for both workers and customers,Sometimes you work till late,KCB
15,Ict administrator,5.0,2025-01-22,"Former employee, more than 1 year",Good Salary paid every month,bureaucracy at top management level,KCB
16,Direst sales representative,4.0,2024-11-12,"Former employee, more than 3 years",I want to able to build the brand image of Kenya Commercial Bank,Not being that competitive with other banking industries,KCB
17,Marketing director,4.0,2024-11-15,"Current employee, more than 1 year",Enthusiastic team to work with good targets,Targets can at times be quite high,KCB
18,Accountant,5.0,2024-11-21,"Former employee, more than 1 year",Favorable working environmentInteractions at workplace,Misunderstandings with junior staffTight deadlines,KCB
19,Solutions architect,5.0,2024-11-01,"Former employee, more than 1 year",great work life balance and culture,too many formalities in projects,KCB
20,Banker,5.0,2024-10-03,"Current employee, more than 3 years","Best employer in Kenya, with best insurance covers and employee relationsCareer growth is guaranteed",Generally in banking you 'll never have enough time to concentrate on much outside work,KCB
21,Marketing,3.0,2024-10-02,"Current employee, more than 1 year",Good work environment and lovely,None at the moment. Just new,KCB
22,It support technician,4.0,2024-09-30,"Current employee, more than 1 year",The workplace has great cultureComparable compensation,No cons at the moment,KCB
23,Customer service representative,4.0,2024-09-23,Former employee,"good work environment, location wise",long working hours on a shift,KCB
24,Branch manager,4.0,2024-08-28,Current employee,Very nice work environment. Welcoming and easy to be productive,Lack of accountability by higher level staff,KCB
25,It technical support specialist,5.0,2024-08-11,Former employee,Great working office environment for staff,none that i can think of,KCB
26,App developer,4.0,2024-07-19,"Former employee, more than 5 years",Enjoyed my time there. Good employer,If you don't like corporate politics then ain't a good place for you.,KCB
27,Sales representative,3.0,2024-06-22,"Former employee, less than 1 year",It is the most transparent employer,some targets are not easy to attain,KCB
28,Analyst,3.0,2024-07-01,Current employee,good bonuses are paid every year,the internal process of being hired internally is hard,KCB
29,Applications developer,4.0,2024-05-14,"Current employee, more than 1 year",You get an opportunity to work on different kinds of projects which can in return grow your skills,Projects take a lot of time to finish due to unnecessary delays.,KCB
30,Data entry clerk,5.0,2024-05-22,"Current employee, more than 1 year",Leading bank in East and Central africa,You will handsomely paid well according to your experience,KCB
31,Card operations officer,5.0,2024-05-22,"Former employee, less than 1 year",Good work environment in the office,The leave days are a little,KCB
32,Teller,4.0,2024-05-20,"Current employee, more than 3 years",Good EmployerGood annual salary increment,Nothing to share for now,KCB
33,Business analyst,4.0,2024-04-17,"Current employee, more than 3 years",Good working environment and opportunities for growth,It is a results driven environment,KCB
34,Clerical assistant,4.0,2024-04-16,Current employee,Extensive medical coverGood employer,None I have experienced so far,KCB
35,Management trainee,5.0,2024-03-14,"Current employee, more than 3 years",good medical scheme and employee retirement scheme,role stagnation can extende up to more than a year,KCB
36,Customer success manager,4.0,2024-03-19,"Current employee, more than 5 years","Flexibility, training and development and career growth opportunities",Long working hours pressure to deliver,KCB

In [35]:
kcbRev

In [ ]:
kcbRev.insert(6,"Company_Name", "KCB")

In [ ]:
kcbRev

In [ ]:
Path  = "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CleanCompanyRev/KCB.csv"