In [54]:
import pandas as pd
import numpy as np

In [55]:
SafRev = pd.read_csv(
    "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CompanyReviewCsvData/SafaricomReviews.csv")

In [56]:
# EDA on the data
def display(x):
    """This function returns a 
    summary of the dataset"""
    
    print("Displays the rows and columns in the dataset")
    print("============================================")
    Rows, col = x.shape
    print(f"Rows: {Rows} Columns: {col}")
    print()
    print("Displays data columns")
    print("============================================")
    print(x.columns)
    print()
    print("Returns the data information")
    print("============================================")
    print(x.info)
    print()
    print("Returns the information in more details")
    print("============================================")
    print(x.describe())
    print()
    print("The data type")
    print("============================================")
    print(x.dtypes)
    print()
    print("The number of null values in the dataset")
    print("============================================")
    print(x.isna().sum())
display(SafRev)

Displays the rows and columns in the dataset
============================================
Rows: 1410 Columns: 6

Displays data columns
============================================
Index(['Job Title', 'Job Ratings', 'time', 'JobStatus', 'Pros', 'Cons'], dtype='object')

Returns the data information
============================================
<bound method DataFrame.info of                     Job Title  Job Ratings          time  \
0            Brand ambassador          5.0   Aug 8, 2025
1     Senior mobile developer          4.0  Jul 28, 2025
2             Project manager          4.0  Jul 15, 2025
3              Ict technician          5.0  Jul 18, 2025
4                      Intern          5.0  Jul 15, 2025
...                       ...          ...           ...
1405       Anonymous employee          3.0   Mar 7, 2022
1406                   Intern          4.0   Apr 8, 2022
1407               Internship          5.0  Jun 13, 2022
1408       Senior ux designer          2.0  Jun 20, 2022
1409                   Intern          5.0  Aug 16, 2022

                                 JobStatus  \
0        Former employee, more than 1 year
1     Current contractor, more than 1 year
2       Former employee, more than 3 years
3                          Former employee
4          Former intern, less than 1 year
...                                    ...
1405    Current employee, more than 1 year
1406       Former intern, less than 1 year
1407                        Current intern
1408                       Former employee
1409                        Current intern

                                                                                                                                                                     Pros  \
0                                                                            Flexible hours, supportive team, good training, fun work environment, opportunity to travel.
1                                                                                                     Great for gaining experience on large scale enterprise applications
2     Strong support for professional growth through training\nExposure to large-scale, impactful projects across Kenya\nCompetitive salary and performance-based bonuses
3                                                                                                                                         the working experience was good
4                                                                                                                                Great work environment. Regular bonuses.
...                                                                                                                                                                   ...
1405                                                                                                                                                 A good place to work
1406                                                                                                                                  Good Benefits and Minimal Workload.
1407                                                                                                                                 Good experience working at safaricom
1408                                                                                                                                     Good work place to work in Kenya
1409                                                                                                                                            Good Salary for an intern

                                                                                                                                        Cons
0     Inconsistent hours, limited career growth, commission structure can be unclear, standing for long hours, sometimes slow communication.
1                                                                                                               A lot of shifting priorities
2                                            Occasional tight deadlines and high-pressure timelines\nBureaucracy can delay project sign-offs
3                                                                                              there are no major drawbacks i can talk about
4                                                                                                                        None I can think of
...                                                                                                                                      ...
1405                                                                                                Being overworked and under high pressure
1406                                                                                                Poor structure for internship programme.
1407                                                                                                        Could pay interns better atleast
1408                                                                                                                   No cons here in kenya
1409                                                                                                                 none that I came across

[1410 rows x 6 columns]>

Returns the information in more details
============================================
       Job Ratings
count  1410.000000
mean      4.238298
std       0.861581
min       1.000000
25%       4.000000
50%       4.000000
75%       5.000000
max       5.000000

The data type
============================================
Job Title       object
Job Ratings    float64
time            object
JobStatus       object
Pros            object
Cons            object
dtype: object

The number of null values in the dataset
============================================
Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [57]:
# printing the first 20 elements on the dataset
print("first 20 elements")
print("=====================================================")
print()
SafRev.head(10)

first 20 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
0,Brand ambassador,5.0,"Aug 8, 2025","Former employee, more than 1 year","Flexible hours, supportive team, good training, fun work environment, opportunity to travel.","Inconsistent hours, limited career growth, commission structure can be unclear, standing for long hours, sometimes slow communication."
1,Senior mobile developer,4.0,"Jul 28, 2025","Current contractor, more than 1 year",Great for gaining experience on large scale enterprise applications,A lot of shifting priorities
2,Project manager,4.0,"Jul 15, 2025","Former employee, more than 3 years","Strong support for professional growth through training\nExposure to large-scale, impactful projects across Kenya\nCompetitive salary and performance-based bonuses",Occasional tight deadlines and high-pressure timelines\nBureaucracy can delay project sign-offs
3,Ict technician,5.0,"Jul 18, 2025",Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,"Jul 15, 2025","Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
5,Site reliability engineer,4.0,"Jul 14, 2025","Current contractor, more than 1 year",RTO policy 3 days in the office,Workload may be too much sometime
6,Software qa engineer,3.0,"Jul 13, 2025","Former contractor, more than 3 years",Opportunities for growth\nGood company \nGreat work policy,Tough management \nExtreme work conditions (pressure)\nNepotism
7,Customer service,4.0,"Jul 8, 2025","Former intern, less than 1 year",Good place to work and grow career-wise,Is place that offers carrier growth
8,Customer service representative,3.0,"Jul 3, 2025",Current employee,Job security\nBonus is available,No growth\nCompensation for customer care is not worth it
9,Ran engineer,4.0,"Jul 6, 2025",Former employee,Conducive work environment for employees growth,Have to meet strict deadlines

In [58]:
# printing the last 20 elements on the dataset
print("Last 20 elements")
print("=====================================================")
print()
SafRev.tail(20)

Last 20 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
1390,Customer experience executive,5.0,"Oct 20, 2019","Current employee, more than 8 years",Safaricom PLC is a great employer,Career growth is limited
1391,Software engineer,3.0,"Feb 25, 2020","Former contractor, more than 3 years","Average Pay, Nice Projects, Highly engaging","Excess Work hours, Tight Deadlines"
1392,Product manager,5.0,"Oct 30, 2020","Former employee, more than 3 years","Good employer, great environment. Good","Pressure , though performance based"
1393,Engineer,4.0,"Dec 9, 2020","Current employee, more than 1 year",Great team to work with.,High pressure to meet deadlines
1394,Full stack developer,3.0,"Dec 15, 2020",Former employee,nice working with safaricom man,lots of mistakes from them ni wezi
1395,Software engineer,4.0,"Dec 26, 2020","Current employee, more than 3 years",Wonderful place to work as usual,No comment on the issue
1396,Network optimization engineer,5.0,"Feb 3, 2021",Current employee,Very good terms of employment,Slow career growth in technology
1397,Customer experience executive,5.0,"Feb 22, 2021","Former employee, more than 5 years",Good compensation. Diversity and Inclusion,Limited growth within 5 years
1398,Customer experience representative,2.0,"Mar 11, 2021",Former contractor,Company name is the only big thing,"No exposure,to contracted stuff controlling boss"
1399,Information technology,3.0,"Apr 14, 2021",Former temporary employee,efficient in communication sector in Kenya,luring customers to buy their bundles
1400,Legal officer,3.0,"May 13, 2021","Current employee, more than 5 years","Good salary, environment, benefits, offices are good","Bad bosses, no career advancement"
1401,Telecommunications engineering specialist,4.0,"Jun 13, 2021","Current contractor, more than 8 years",Excellent company to be in,A lot tasks are in place
1402,Customer care representative,2.0,"Jun 19, 2021",KEY NOT FOUND: jobLine.seasonal-former,good company very efficient and fast,poor wadges and late payment rates
1403,Sales representative,5.0,"Oct 4, 2021",Current contractor,Effective communication\r\nTeam work\r\nCoaching is good,Growth opportunities are not clear
1404,Account manager,4.0,"Jan 26, 2022",Current employee,Safaricom has good medical benefits,Safaricom Hr processes are very bureacratic
1405,Anonymous employee,3.0,"Mar 7, 2022","Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,"Apr 8, 2022","Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,"Jun 13, 2022",Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior ux designer,2.0,"Jun 20, 2022",Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,"Aug 16, 2022",Current intern,Good Salary for an intern,none that I came across

In [59]:
# printing the random sample of 20 elements
print("Random 20 elements")
print("=====================================================")
print()
SafRev.sample(20)

Random 20 elements
=====================================================

,Job Title,Job Ratings,time,JobStatus,Pros,Cons
84,Sales associate,3.0,"Apr 7, 2025","Former temporary employee, less than 1 year",Competitive salary and good work environment.,Working under pressure on projects
228,Software engineer,5.0,"Sep 9, 2024","Current employee, more than 1 year",best in the world you know,Salaries come early thAn expeCted'|
910,Territory account manager,5.0,"Dec 5, 2021","Current employee, more than 5 years","Great work environment, culture and employee welfare.","High pressure environment, you got to keep up with ever changing trends in telecommunications"
208,Engineering manager,4.0,"Jun 30, 2024","Current employee, more than 5 years","You have freedom to design solutions. Compared to other companies in the region, the Total reward is good especially medical cover for you and your family, annual bonus, and car allowance.","Just like any other mature company, a little politics is expected and it can be annoying, but nothing big to frustrate you. Sometimes work can be intense, with unrealistic timelines but this is not the norm. Things often balance themselves out."
1254,Content marketer,3.0,"Mar 1, 2021",Former employee,i felt good being there,good place and nice to be
59,Data analyst,4.0,"May 17, 2025",Current employee,Great packs and flexible schedule,Work tends to be a lot
194,Data scientist,3.0,"Oct 9, 2024","Former employee, more than 5 years",It is a place that values diversity.,Opportunities for advancement are few and far between.
569,Software engineer,3.0,"Jun 12, 2023",Former employee,"fast paced environment, good experience to grow",no work life balance even lunch time is work time
861,Regional sales manager,3.0,"Oct 31, 2018","Former employee, more than 5 years",It is a big brand,Lots of corporate politics and employee insecurity
393,Product designer,4.0,"Feb 16, 2024",Former employee,It was a great company,"Like any other, you can't be all great"
980,Customer service representative,3.0,"Apr 21, 2022",Former employee,You get extra money when you work on public holidays\nBest medical cover ever,Too tedious yet pay is less\nHard to get promoted\nNo life balance
415,Cloud support engineer,4.0,"Jan 22, 2024","Former employee, more than 1 year",Employee career advancement and support,Strict on bonus to be paid
240,Customer care specialist,5.0,"Aug 27, 2024","Current employee, more than 10 years","Shift based, flexible and has work from home opportunities",slow salary increment/ could do better
1069,It support,5.0,"Apr 10, 2020",Former employee,Great company.. continous learning and growth,no cons at all.. Favourite company
838,Telecommunications (oss) engineer,5.0,"Mar 27, 2021","Former intern, less than 1 year",There is great exposure to the industry. You choose an area of interest after orientation which is amazing because you get to choose what you want to get good at.,No negative experience. The place is overall great
1112,It incident management analyst,5.0,"Apr 12, 2021","Current employee, more than 8 years",Best Medical Cover\r\nWorking from Home,Too Hierachical.\r\nLots of ideas are throlttled by middle level mgmt
700,Legal intern,5.0,"Jan 20, 2023","Current employee, less than 1 year",The community is adaptable to work with,None workable attitude is not allowed
1157,Anonymous employee,3.0,"Jan 30, 2018","Current employee, less than 1 year",Good and working excellent experience,Internal processes long and slow
1060,Business development manager,4.0,"Jul 15, 2013","Current employee, more than 1 year",lots of experience and exposure,lot of pressure to deliver
777,Enterprise infrastructure,5.0,"May 12, 2019","Current employee, more than 5 years","This role has alot of learning opportunities .. Especially if you are planning to do your IE certification on the network side. It also has alot on emphasis of Systems that provide Enterprise services; All scoped on planning, implementation and support",Overworked but there is compensation on overtime.\r\nStrict deadlines that are dependent on other teams for delivery.

# Data cleaning.

In [60]:
column1 = SafRev["Job Title"]
column1

0              Brand ambassador
1       Senior mobile developer
2               Project manager
3                Ict technician
4                        Intern
                 ...
1405         Anonymous employee
1406                     Intern
1407                 Internship
1408         Senior ux designer
1409                     Intern
Name: Job Title, Length: 1410, dtype: object

In [61]:
# calculating total null values on the dataset
def null_values(df):
    """This function returns 
    total null values on the dataset"""
    print(df.isna().sum())
    
null_values(SafRev)

Job Title      0
Job Ratings    0
time           0
JobStatus      0
Pros           0
Cons           0
dtype: int64

In [62]:
# dropping dublicate values
def duplicate_values(df):
    """This function drops all the 
    duplicate values on the dataset"""
    df.dropna(inplace=True)
duplicate_values(SafRev)
# SafRev.dropna(inplace=True)

In [63]:
# changing the datatype of the time column
def time_change(df, col="time"):
    df[col] = pd.to_datetime(df[col], format='%b %d, %Y', errors="coerce")
    return df
Rev = time_change(SafRev)

In [64]:
# Rename the headers
SafRev.rename(columns={"Job Title":"Job Title", "Job Ratings":"Job Rating", "time":"Time", "JobStatus":"Job Status",
                      "Pros":"Pros","Cons":"Cons"},inplace=True)

In [65]:
SafRev["Job Title"].unique()

array(['Brand ambassador', 'Senior mobile developer', 'Project manager',
       'Ict technician', 'Intern', 'Site reliability engineer',
       'Software qa engineer', 'Customer service',
       'Customer service representative', 'Ran engineer',
       'Territory development representative (tdr)', 'Telesales agent',
       'Junior software developer', 'Sr. manager it',
       'Software developer', 'Internship', 'Senior software engineer',
       'Software engineer', 'Frontend developer', 'Brand manager',
       'Data analyst', 'Field engineer', 'Territory manager',
       'Customer experience representative', 'Finance intern',
       'Office administrator', 'Consultant', 'Software engineer i',
       'Call center agent', 'Driver', 'Sales associate',
       'Customer service representative (csr)',
       'Consumer business intern', 'Systems engineer',
       'Sales representative', 'Global management trainee (gmt)',
       'Cybersecurity internship', 'Manager', 'Analyst',
       'Administrative assistant', 'Assistant project manager',
       'Data entry clerk', 'Network engineer', 'Cyber security analyst',
       'Audit associate', 'Specialist', 'It specialist',
       'Program manager', 'Backend engineer', 'Finance',
       'Data analyst intern', 'Integration engineer', 'Sales assistant',
       'Solutions architect', 'Legal intern', 'Sre/devops engineer',
       'Contractor', 'Agribusiness manager', 'Ux designer',
       'Data analytics partner', 'Trade development representative',
       'It contractor', 'Software developer intern',
       'Senior assurance officer', 'Graduate trainee', 'Web developer',
       'Customercare executive', 'Admin intern', 'Account executive',
       'Business analyst', 'Customer care representative', 'Qa engineer',
       'Data analyst/junior data scientist', 'Treasury analyst',
       'Customer success manager', 'Engineer', 'It manager',
       'Devops engineer', 'Senior data analyst', 'Team leader',
       'Ml engineer', 'Sofatware engineer', 'Manager, financial services',
       'Sales executive', 'Human resources assistant',
       'Customer experience executive', 'Customer service agent',
       'Data associate', 'Quality engineer', 'Category manager',
       'Computer science/engineering', 'Front end developer',
       'Technology intern', 'Finance manager', 'Data scientist',
       'Senior service reliability engineer', 'Business development',
       'Structural engineer', 'Administrative', 'Management trainee',
       'Site reliability engineer intern', 'Cybersecurity analyst',
       'Backend developer', 'Software engineer(internship)',
       'Engineering manager', 'Database administrator', 'Accountant',
       'Agile coach', 'Marketing coordinator', 'Cybersecurity',
       'Vas engineer', 'Ran capacity planning engineer',
       'Accounts payable', 'Principal auditor', 'Commercial manager',
       'Field agent', 'Customer care specialist',
       'Senior executive assistant', 'Finance team lead',
       'Senior integration engineer',
       'Software development engineer in test (sdet)', 'Sales',
       'Android developer', 'Graphic designer', 'Account manager',
       'Customer support specialist', 'Ip support engineer',
       'Full stack engineer', 'Data engineer',
       'Çustomer service representative', 'Senior solutions architect',
       'Front desk agent', 'Telecom engineer', 'Data entry',
       'Call center representative', 'Technical lead',
       'Lead android developer', 'Senior cse', 'Telesales representative',
       'Ftth engineer', 'Customer service account associate',
       'Anonymous contractor', 'Human resources manager',
       'Senior network engineer', 'Solutions engineer',
       'Casual team member', 'Technician', 'Bi developer',
       'Network administrator', 'Senior data analytics engineer',
       'It intern', 'Middle ios developer',
       'Client relationship executive', 'Accounts assistant',
       'Systems administrator', 'Radio access network engineer',
       'It assistant', 'Software engineer intenship', 'Marketing intern',
       'Product manager', 'Senior software developer', 'It technician',
       'Chef', 'Direct sales representative',
       'It technical support specialist', 'Business development manager',
       'Marketing', 'Tdr trade development representative',
       'Anonymous employee', 'Band h', 'Program director',
       'Enterprise risk management', 'Digital marketing',
       'Accounts receivable', 'Microservices developer',
       'Product designer', 'Financial services intern', 'Human resources',
       'Human resources specialist (hr specialist)',
       'Machine learning engineer', 'Cloud support engineer',
       'Quality assurance', 'Junior data analyst',
       'Senior manager international business', 'Janitor/cleaner',
       'Software engineer intern', 'Technical support engineer',
       'Chief technology officer (cto)', 'Principal',
       'Graduate engineer trainee', 'Support analyst',
       'Market researcher', 'Qaengineer', 'Enterprise support engineer',
       'Online chat agent', 'Sales officer', 'Chat moderator',
       'Principal engineer', 'Software development engineer (sde)',
       'Scrum master/agile coach', 'Merchant support', 'Intern engineer',
       'Chief executive officer (ceo)', 'Product owner',
       'Big data engineer', 'Analysts', 'Is intern', 'Ict officer',
       'Customer care executive', 'Sales manager', 'Security guard',
       'Pricing analyst', 'Accounts clerk', 'Senior graphic designer',
       'Sales represenative', 'Fixed support central dispatch engineer',
       'Sales agent', 'Cloud engineer', 'Software engineer ii',
       'Solution architect', 'Computer programmer', 'Soc engineer',
       'Customer experience specialist', 'Customer sevice specialist',
       'Sales intern', 'Analytics manager', 'Financial controller',
       'End user support', 'Communications',
       'Financial services representative', 'Saler support',
       'Frontend web developer', 'Category sourcing manager',
       'Head of technical', 'Sweeper', 'Treasury intern',
       'Dealer relationship manager', 'Tech leader', 'Hod',
       'Fullstack developer', 'Network intern', 'Integrations engineer',
       'Paid ads specialist', 'Database administrator (dba)',
       'Social media manager', 'Tech support engineer',
       'Asm (area sales manager)', 'Junior software engineer',
       'Communications manager', 'Ict manager',
       'Field sales representative', 'It business analyst',
       'Customer care', 'Direct sales agent', 'Marketing specialist',
       'It support', 'Ui-ux designer & graphics designer',
       'Vas support engineer', 'Supervisor', 'Data base administrator',
       'Graduate management engineer', 'Software engineering',
       'Senior engineer', 'Business data analyst',
       'Discover-graduate program', 'Financial analyst',
       'Head of research', 'Data manager', 'Accounts intern',
       'Senior manager enterprise service delivery',
       'Principal radio planning engineer', 'Retail analyst',
       'Mid level manager', 'Human resources officer',
       'Security controller', 'Senior manager - retail transformation',
       'Ipcc engineer', 'Senior management', 'Corporate ressponsibility',
       'Procurement intern', 'Training coordinator',
       'Consulting hardware engineer', 'Sales executives',
       'Technology academy', 'Project deployment',
       'Telecommunications engineer', 'Management engineer',
       'Core network engineer', 'Hrbp', 'Retail cee',
       'Technical project manager', 'Territory account executive',
       'Enterprise infrastructure', 'Quality analyst',
       'Social media analyst', 'Customer experience manager',
       'Senior manager', 'Sector manager', 'Government affairs manager',
       'Support lead', 'Retail customer experience executive',
       'Anonymous intern', 'Computer science student',
       'Data science intern', 'Information security analyst',
       'Senior manager innovation', 'Technology analyst',
       'Senior officer', 'Route salesman', 'Junior data scientist',
       'Manager, operations', 'Human resources consultant',
       'Bi management', 'Integration support analyst',
       'Acting inbound logistics manager',
       'Telecommunications (oss) engineer', 'Product marketer',
       'Enterprise provisioning', 'Principal operations officer',
       'Retail assistant - customer services', 'Women in technology',
       'Sales and marketing', 'Engineering internship',
       'Senior devops engineer',
       'Principal human resource business partner (hrbp) officer',
       'Regional sales manager', 'Segments manager', 'Office assistant',
       'Platinum support manager', 'Business development associate',
       'Principal internal auditor', 'Dealer manager',
       'Softeware engineer', 'Quality assurance analyst', 'Hr-intern',
       'Corporate sales', 'Logistics quality assurance',
       'It support analyst', 'Bi analyst', 'Relationship manager',
       'Call centre team leader', 'Territory account manager',
       'Senior manager operations engineering', 'Systems analyst',
       'Principal analyst', 'Call center customer service representative',
       'Customer service associate', 'Finance professional',
       'Senior officer, supplier qualification and contracts management',
       'Products development engineer', 'Supply chain',
       'User experience designer', 'Chief executive officer',
       'Ip planning engineer', 'Software development intern',
       'Intraoperative neuromonitoring tech', 'Tdr', 'Stock controller',
       'Coder', 'Configuration and support engineer',
       'Inventory controller', 'Nairobi', 'Customer executive officer',
       'Graduate electrical engineer', 'Projects officer',
       'Cloud solutions engineer', 'Senior iot engineer',
       'Personal assistant', 'Digital customer experience manager',
       'Qa governance & operations', 'Applications support engineer',
       'Intern - hourly', 'Kenya – republic of kenya',
       'Technical consultant', 'Digital product manager',
       'Provisioning engineer', 'Assistant store manager',
       'Software engineer - android', 'Tdr - sales', 'Fibre technician',
       'Senior scrum master', 'Ass treasurer', 'Compliance manager',
       'Senior customer service representative',
       'Talent acquisition specialist',
       'Capital projects business partner', 'Operations team leader',
       'Network officer', 'Procurement analyst', 'Networking engineer',
       'Business executive', 'Secretary', 'Radio planning engineer',
       'Financial advisor', 'Ran', 'Product development',
       'National account manager', 'Computer systems engineer',
       'Senior human resources officer', 'Retention manager',
       'Programme analyst', 'Senior principal developer',
       'Procurement officer', 'Operations engineer', 'Staff accountant',
       'Senior product manager', 'Enterprise service desk engineer',
       'Retail quality analyst', 'Remote support engineer',
       'Customer service specialist', 'Talent acquisition intern',
       'Assistant commercial manager', 'It incident management analyst',
       'Data analyst/data scientist', 'Senior tech lead',
       'Student intern', 'Junior graphic designer',
       'Ran optimization and planning engineer',
       'Commercial sales consultant', 'Senior accountant',
       'Service assurance engineer', 'Digital experience executive',
       'Cyber security consultant', 'Call centre agent',
       'Devops/full-stack developer', 'Marketer', 'Ip engineer',
       'Advertising sales or data entry', 'Technical enterprise services',
       'Senior sourcing engineer', 'Ict', 'Anonymous temporary employee',
       'Contact center team leader', 'Digital media executive',
       'Technology', 'Risk management', 'Project management intern',
       'Social worker', 'Customer support', 'Site administrator',
       'Qa intern', 'Software quality assurance engineer',
       'Sales manager cee', 'Writer', 'Territory sales representative',
       'Network planning engineer', 'Business engagement manager',
       'Lead engineer', 'Senior communications manager',
       'Enterprise quality assurance analyst', 'Typing',
       'Resource planning analyst', 'Content marketer', 'Cyber security',
       'It solutions architect', 'Stock control',
       'Computer scientist (1550)', 'Field service engineer',
       'Manager - new business development', 'Cleaning',
       'Django developer', 'Executive assistant', 'Inventory accountant',
       'Finance/accounting', 'Delear sales associate',
       'Systems developer', 'Noc engineer', 'Product development manager',
       'Research associate', 'Online data entry', 'Brand promotion',
       'Actuarial analyst', 'Legal assistant', 'Designer',
       'Stocks controller', 'Core network support',
       'Intern for financial services', 'Customer service executive',
       'I t analyst', 'Senior software engineer/tech lead',
       'Mobile developer', 'Internal auditor',
       'Financial service operator', 'Senior financial services officer',
       'Customer support representative',
       'Regional business development manager',
       'Sales, marketing and communications professional', 'Mpesa',
       'Senior lawyer', 'Operations manager', 'Relationship officer',
       'Retail centre team leader', 'Executive', 'Itspecialist',
       'Brand experience activations manager', 'Full stack developer',
       'Network optimization engineer', 'Information technology',
       'Legal officer', 'Telecommunications engineering specialist',
       'Senior ux designer'], dtype=object)

In [66]:
# rename detail
SafRev["Job Title"] = SafRev["Job Title"].replace({
    "Tdr Trade Development Representative":"(Tdr) Trade Development Representative",
    "Qaengineer":"Qa Engineer","Çustomer Service Representative":"Customer Service Representative",
    "Sofatware Engineer":"Software Engineer","Softeware Enginee":"Software Engineer",
    "Ftth Engineer":"Ftth (Fiber to the Home) Engineer","Software qa engineer":"Software Qa Engineer",
    "Tdr":"Trade Development Representative","Itspecialist":"IT Specialist",
    "KEY NOT FOUND: jobLine.seasonal-current":"(Job) seasonal_current","I T Analyst":"IT Analyst",
    "It Specialist":"IT Specialist"
    })

In [67]:
# locating value on the dataset
SafRev[SafRev["Job Title"]=="IT Analyst"]

Empty DataFrame
Columns: [Job Title, Job Rating, Time, Job Status, Pros, Cons]
Index: []

In [68]:
# changing the headers on the file into headers
SafRev["Job Title"] = SafRev["Job Title"].str.title()

In [69]:
# locating specific data
SafRev.query('`Job Title`=="Anonymous Contractor"')

,Job Title,Job Rating,Time,Job Status,Pros,Cons
291,Anonymous Contractor,4.0,2024-05-29,"Former contractor, more than 3 years",Diversity and inclusion\nGood salary and compensation benefits\nWork-life balance\nEmployee development,Too much sales pressure to meet monthly sales targets
340,Anonymous Contractor,5.0,2024-04-12,"Current contractor, less than 1 year",comradarie and collaboration. also exposure.,working hours. not enough pay.
377,Anonymous Contractor,2.0,2024-03-13,"Current contractor, more than 5 years",-can be remote\n-Good benefits,-Bad team leaders\n-Bad for mental health\n-Bad life/work balance
875,Anonymous Contractor,5.0,2019-02-17,"Current contractor, more than 3 years",Its a place one can admire to work at,It always values work life balance thus being the best company ever
951,Anonymous Contractor,4.0,2022-06-07,"Former contractor, less than 1 year",Great & flexible work environment,Some work activities can be lengthy due to policies.
1063,Anonymous Contractor,4.0,2017-10-24,"Former contractor, more than 1 year",Great opportunity & blue chip firm to learn,High pressure work that deserves full commitment even on weekends
1184,Anonymous Contractor,3.0,2021-09-07,Current contractor,best place to work in kenya,lower salary compared to what is expected
1212,Anonymous Contractor,4.0,2019-08-14,"Current contractor, more than 1 year",Annual bonus and competitive salary,None so far but could do better
1278,Anonymous Contractor,5.0,2022-09-02,"Current contractor, less than 1 year",Many career opportunities\nConducive environment,Hired through agency so you get less salary

In [70]:
SafRev['Job Status'].unique()

array(['Former employee, more than 1 year',
       'Current contractor, more than 1 year',
       'Former employee, more than 3 years', 'Former employee',
       'Former intern, less than 1 year',
       'Former contractor, more than 3 years', 'Current employee',
       'Current employee, more than 1 year',
       'Former contractor, more than 1 year',
       'Current contractor, more than 3 years',
       'Current employee, less than 1 year', 'Former intern',
       'Current contractor', 'Current employee, more than 3 years',
       'Former employee, more than 10 years', 'Former contractor',
       'Current employee, more than 5 years',
       'Current employee, more than 10 years',
       'Current temporary employee', 'Former employee, more than 8 years',
       'Current intern, more than 1 year',
       'Former employee, less than 1 year',
       'Former employee, more than 5 years',
       'Former freelancer, less than 1 year', 'Current intern',
       'Former temporary employee, less than 1 year',
       'Current intern, less than 1 year', 'Former temporary employee',
       'Current employee, more than 8 years',
       'Former contractor, less than 1 year',
       'Current contractor, more than 8 years',
       'Current contractor, less than 1 year', 'Current freelancer',
       'Current contractor, more than 5 years',
       'Former intern, more than 1 year',
       'Former freelancer, more than 1 year',
       'Current freelancer, more than 1 year',
       'Former contractor, more than 5 years', 'Formerly self-employed',
       'Former intern, more than 3 years',
       'Former temporary employee, more than 3 years',
       'Current freelancer, less than 1 year',
       'Former contractor, more than 8 years', 'Currently self-employed',
       'Current temporary employee, more than 3 years',
       'Former freelancer', 'KEY NOT FOUND: jobLine.seasonal-current',
       'KEY NOT FOUND: jobLine.seasonal-former'], dtype=object)

In [71]:
SafRev[SafRev['Job Status']=="Former freelancer"]

,Job Title,Job Rating,Time,Job Status,Pros,Cons
1262,Computer Scientist (1550),3.0,2021-12-17,Former freelancer,paid relatively well compared to other companies,jobs did not come oftenly
1366,"Sales, Marketing And Communications Professional",4.0,2020-11-19,Former freelancer,Good and well structured organization,Takes time to absorb its employees

In [72]:
# pd.set_option('Display.Max_rows',None)
# pd.set_option('Display.Max_columns',None)
SafRev[["Pros"]]

                                                                                                                                                                     Pros
0                                                                            Flexible hours, supportive team, good training, fun work environment, opportunity to travel.
1                                                                                                     Great for gaining experience on large scale enterprise applications
2     Strong support for professional growth through training\nExposure to large-scale, impactful projects across Kenya\nCompetitive salary and performance-based bonuses
3                                                                                                                                         the working experience was good
4                                                                                                                                Great work environment. Regular bonuses.
...                                                                                                                                                                   ...
1405                                                                                                                                                 A good place to work
1406                                                                                                                                  Good Benefits and Minimal Workload.
1407                                                                                                                                 Good experience working at safaricom
1408                                                                                                                                     Good work place to work in Kenya
1409                                                                                                                                            Good Salary for an intern

[1410 rows x 1 columns]

In [73]:
SafRev.loc[0]

Job Title                                                                                                                           Brand Ambassador
Job Rating                                                                                                                                       5.0
Time                                                                                                                             2025-08-08 00:00:00
Job Status                                                                                                         Former employee, more than 1 year
Pros                                                    Flexible hours, supportive team, good training, fun work environment, opportunity to travel.
Cons          Inconsistent hours, limited career growth, commission structure can be unclear, standing for long hours, sometimes slow communication.
Name: 0, dtype: object

In [74]:
# pd.set_option('Display.Max_rows',None)
SafRev[["Pros", "Cons"]]

,Pros,Cons
0,"Flexible hours, supportive team, good training, fun work environment, opportunity to travel.","Inconsistent hours, limited career growth, commission structure can be unclear, standing for long hours, sometimes slow communication."
1,Great for gaining experience on large scale enterprise applications,A lot of shifting priorities
2,"Strong support for professional growth through training\nExposure to large-scale, impactful projects across Kenya\nCompetitive salary and performance-based bonuses",Occasional tight deadlines and high-pressure timelines\nBureaucracy can delay project sign-offs
3,the working experience was good,there are no major drawbacks i can talk about
4,Great work environment. Regular bonuses.,None I can think of
...,...,...
1405,A good place to work,Being overworked and under high pressure
1406,Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Good experience working at safaricom,Could pay interns better atleast
1408,Good work place to work in Kenya,No cons here in kenya
1409,Good Salary for an intern,none that I came across

In [75]:
SafRev

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible hours, supportive team, good training, fun work environment, opportunity to travel.","Inconsistent hours, limited career growth, commission structure can be unclear, standing for long hours, sometimes slow communication."
1,Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great for gaining experience on large scale enterprise applications,A lot of shifting priorities
2,Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong support for professional growth through training\nExposure to large-scale, impactful projects across Kenya\nCompetitive salary and performance-based bonuses",Occasional tight deadlines and high-pressure timelines\nBureaucracy can delay project sign-offs
3,Ict Technician,5.0,2025-07-18,Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
...,...,...,...,...,...,...
1405,Anonymous Employee,3.0,2022-03-07,"Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,2022-04-08,"Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,2022-06-13,Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior Ux Designer,2.0,2022-06-20,Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,2022-08-16,Current intern,Good Salary for an intern,none that I came across

In [76]:
# Replacing the \n on the Cons column
# SafRev["Pros"]=SafRev["Pros"].str.replace("\n", ",", regex=False)
def replace_str(df, col1="Cons", col2 ="Pros"):
    df[[col1, col2]] = df[[col1, col2]].apply(lambda s: s.str.replace("\n", " ", regex=False))
    return df
replace_str(SafRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible hours, supportive team, good training, fun work environment, opportunity to travel.","Inconsistent hours, limited career growth, commission structure can be unclear, standing for long hours, sometimes slow communication."
1,Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great for gaining experience on large scale enterprise applications,A lot of shifting priorities
2,Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong support for professional growth through training Exposure to large-scale, impactful projects across Kenya Competitive salary and performance-based bonuses",Occasional tight deadlines and high-pressure timelines Bureaucracy can delay project sign-offs
3,Ict Technician,5.0,2025-07-18,Former employee,the working experience was good,there are no major drawbacks i can talk about
4,Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great work environment. Regular bonuses.,None I can think of
...,...,...,...,...,...,...
1405,Anonymous Employee,3.0,2022-03-07,"Current employee, more than 1 year",A good place to work,Being overworked and under high pressure
1406,Intern,4.0,2022-04-08,"Former intern, less than 1 year",Good Benefits and Minimal Workload.,Poor structure for internship programme.
1407,Internship,5.0,2022-06-13,Current intern,Good experience working at safaricom,Could pay interns better atleast
1408,Senior Ux Designer,2.0,2022-06-20,Former employee,Good work place to work in Kenya,No cons here in kenya
1409,Intern,5.0,2022-08-16,Current intern,Good Salary for an intern,none that I came across

In [77]:
# capitalize the dataset
def capital_letter(df, col="Pros", col2="Cons"):
    df[[col, col2]] = df[[col, col2]].apply(lambda s: s.str.title()) 
    return df
capital_letter(SafRev)
# SafRev['Cons'].str.title()

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
1,Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
2,Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To Large-Scale, Impactful Projects Across Kenya Competitive Salary And Performance-Based Bonuses",Occasional Tight Deadlines And High-Pressure Timelines Bureaucracy Can Delay Project Sign-Offs
3,Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
4,Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...,...
1405,Anonymous Employee,3.0,2022-03-07,"Current employee, more than 1 year",A Good Place To Work,Being Overworked And Under High Pressure
1406,Intern,4.0,2022-04-08,"Former intern, less than 1 year",Good Benefits And Minimal Workload.,Poor Structure For Internship Programme.
1407,Internship,5.0,2022-06-13,Current intern,Good Experience Working At Safaricom,Could Pay Interns Better Atleast
1408,Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya
1409,Intern,5.0,2022-08-16,Current intern,Good Salary For An Intern,None That I Came Across

In [78]:
# display the whole text
pd.set_option("display.max_colwidth", None)

In [79]:
SafRev[["Job Title","Pros"]]

,Job Title,Pros
0,Brand Ambassador,"Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel."
1,Senior Mobile Developer,Great For Gaining Experience On Large Scale Enterprise Applications
2,Project Manager,"Strong Support For Professional Growth Through Training Exposure To Large-Scale, Impactful Projects Across Kenya Competitive Salary And Performance-Based Bonuses"
3,Ict Technician,The Working Experience Was Good
4,Intern,Great Work Environment. Regular Bonuses.
...,...,...
1405,Anonymous Employee,A Good Place To Work
1406,Intern,Good Benefits And Minimal Workload.
1407,Internship,Good Experience Working At Safaricom
1408,Senior Ux Designer,Good Work Place To Work In Kenya
1409,Intern,Good Salary For An Intern

In [80]:
# check duplicate
def checkDuplicate(df):
    df.duplicated()
    return df
checkDuplicate(SafRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
1,Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
2,Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To Large-Scale, Impactful Projects Across Kenya Competitive Salary And Performance-Based Bonuses",Occasional Tight Deadlines And High-Pressure Timelines Bureaucracy Can Delay Project Sign-Offs
3,Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
4,Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...,...
1405,Anonymous Employee,3.0,2022-03-07,"Current employee, more than 1 year",A Good Place To Work,Being Overworked And Under High Pressure
1406,Intern,4.0,2022-04-08,"Former intern, less than 1 year",Good Benefits And Minimal Workload.,Poor Structure For Internship Programme.
1407,Internship,5.0,2022-06-13,Current intern,Good Experience Working At Safaricom,Could Pay Interns Better Atleast
1408,Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya
1409,Intern,5.0,2022-08-16,Current intern,Good Salary For An Intern,None That I Came Across

In [81]:
# check duplicate sum
def checkDuplicateSum(df):
    Total = df.duplicated().sum()
    print(f"Sum of Duplicate_Values = {Total}")
checkDuplicateSum(SafRev)

Sum of Duplicate_Values = 20

In [82]:
# drop_duplicate
def DropDuplicate(df):
    df.drop_duplicates(subset=["Job Title"], inplace=True)
    return df
DropDuplicate(SafRev)

,Job Title,Job Rating,Time,Job Status,Pros,Cons
0,Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
1,Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
2,Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To Large-Scale, Impactful Projects Across Kenya Competitive Salary And Performance-Based Bonuses",Occasional Tight Deadlines And High-Pressure Timelines Bureaucracy Can Delay Project Sign-Offs
3,Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
4,Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...,...
1396,Network Optimization Engineer,5.0,2021-02-03,Current employee,Very Good Terms Of Employment,Slow Career Growth In Technology
1399,Information Technology,3.0,2021-04-14,Former temporary employee,Efficient In Communication Sector In Kenya,Luring Customers To Buy Their Bundles
1400,Legal Officer,3.0,2021-05-13,"Current employee, more than 5 years","Good Salary, Environment, Benefits, Offices Are Good","Bad Bosses, No Career Advancement"
1401,Telecommunications Engineering Specialist,4.0,2021-06-13,"Current contractor, more than 8 years",Excellent Company To Be In,A Lot Tasks Are In Place
1408,Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya

In [83]:
SafRev.set_index("Job Title", inplace=True)

In [94]:
SafRev.reset_index(inplace=True)

In [85]:
# SafRev.drop("index", axis=1, inplace=True)

In [86]:
SafRev

,Job Rating,Time,Job Status,Pros,Cons
Job Title,,,,,
Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To Large-Scale, Impactful Projects Across Kenya Competitive Salary And Performance-Based Bonuses",Occasional Tight Deadlines And High-Pressure Timelines Bureaucracy Can Delay Project Sign-Offs
Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...
Network Optimization Engineer,5.0,2021-02-03,Current employee,Very Good Terms Of Employment,Slow Career Growth In Technology
Information Technology,3.0,2021-04-14,Former temporary employee,Efficient In Communication Sector In Kenya,Luring Customers To Buy Their Bundles
Legal Officer,3.0,2021-05-13,"Current employee, more than 5 years","Good Salary, Environment, Benefits, Offices Are Good","Bad Bosses, No Career Advancement"
Telecommunications Engineering Specialist,4.0,2021-06-13,"Current contractor, more than 8 years",Excellent Company To Be In,A Lot Tasks Are In Place
Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya

In [87]:
hiphen = SafRev[SafRev["Pros"].str.startswith("-")]
hiphen

,Job Rating,Time,Job Status,Pros,Cons
Job Title,,,,,
Frontend Developer,4.0,2025-05-22,"Current employee, more than 3 years",- Very Friendly And Easy To Work With Colleagues. - The Engineering Lead For Web Is One Of The Best Person I'Ve Ever Met.,"- Too Much Focus On Short Term Goals - Work Overload, Easy To Find Only One Engineer Working On A Huge Project Alone"
Senior Integration Engineer,5.0,2024-05-12,"Current employee, more than 5 years","- Decent Compensation And Benefits Including Airtime Allowance, Car Allowance(Dependent On Job Group), Good Medical Cover. - Access To Low Interest Unsecured Bank Loan For Full Time Staff. - Depending On The Role, Hybrid Or Purely Working From Home Is Possible","- Depending On The Team And Role, It Might Be Hard To Strike A Worknlife Balance. - In Some Teams, It Can Be Difficult To Be Promoted Within The Company If You Are Not Outspoken."
Principal Engineer,4.0,2023-10-13,"Current employee, more than 8 years",- Great Culture - Hybrid Working Model -Career Growth,- Fast Paced Environment - Room For Improvement On Compensation
Big Data Engineer,4.0,2023-07-21,"Former employee, more than 3 years",- State Of The Art Architecture And Tech - Interesting Products That Impact Alot Of People - Skilled Colleagues,- Micro Management - Slow Rate Of Adoption On Proper Dev Practices - All About The Bonus Baby!
Human Resources Officer,2.0,2011-01-07,Current employee,"- Policies And Procedures Are Clear. This Protects The Employees\r - Great Benefits (Medical, Esop, Training)\r - Great Opportunities To Learn. Having Worked At Safaricom, One Can Work In Any Environment And Comfortably Handle The Pressure","- Often Overworked And Sometimes The Pay Is Not Adequate\r - Bad Leadership. Managers Operate Like They Have Little Kingdoms\r - Tribalism In Appointments And Promotions Especially Hr, Finance, Retail And Risk Departments\r - Culture Of Blame Game"
Security Controller,2.0,2019-10-05,"Current contractor, more than 3 years","-Free Calling While At Work.\r -Possible To Do Long-Distance Learning During Night Shifts\r -No Defined Job Valuation Requirement [Yet], E.G. Kpis, Spis, Like Permanent Staff\r -Fair Pay [Though Meagre]\r -Autonomous Working/Valued Opinion, I.E. Controller'S Deduction On Op Issues Is Occasionally/Often Valued & Actioned Upon By Mgt.",-Long Working Hours At Low Pay .\r -Lack Of Growth Opportunities\r -Lack Of Motivation From Leadership\r -Lack Of Allowances\r -Controlled Wifi Access\r -No Special Training Facility Before One Deploys.\r -Lack Of Adequate Support From Leadership
Procurement Intern,5.0,2012-10-28,"Former intern, less than 1 year",-Great Positive Energy Amongst The Staff\r -Team Work And Group Support Highly Valued\r -Respect For People\r -Fun Activities That Facilitate Bonding Like The Tgif'S And Staff Competitions\r -Free Airtime!,"Unless One Creates The Cons, I Believe The Environment There Is Good Enough For One To Srive In Their Career"
Telecommunications Engineer,4.0,2010-02-24,Former employee,-Good Benefits\r -Good Career Development Prospects\r -Good Work-Home Balance\r -Flexibility In Work Schedules In Some Departments\r -Good Corporate Service Responibility Practices,"-Politics In Management\r -Politics In Promotions\r -Some Employees Overwork, Some Underwork And Earn Same Salaries\r -Tribalism Is Practiced In Many Departments"
Territory Account Executive,4.0,2020-10-21,"Current contractor, more than 5 years","- Good Working Environment, That Is, The Company Care About Employee Welfare, Health, Appreciate Current Trends Technology Revolution, And The Involvement In Sdgs Implementation.",So Far Everything Is Amazing About Working At Safaricom.
Sector Manager,4.0,2015-09-28,"Current employee, more than 5 years","-Fast Paced Environment, Exciting And Always Changing. \r -Great People And Culture Of Super Achievers All Round. -\r -Spacious Open Offices And Open Door Policies. \r -Transparency And Awards On Merit. \r -Quick To Respond To Feedback And Adopt To The Changing Market Environment",- Flat Organisation Structure Making Little Room For Vertical Growth\r -
Support Lead,5.0,2022-09-25,"Current employee, more than 8 years","- Good Non Cash Benefits, Medical Cover, Pension Scheme, Gym Facilities Within The Office - Csr Projects Participation - Good Bonuses Based On Performance - Hybrid Working -",- There Is Too Much Pressure To Deliver. - Working Long Hours Is Common. -Salaries Not Aligned To The Market Rates For Similar Roles Elsewhere
Stock Controller,3.0,2021-05-15,"Current employee, more than 8 years",-Nice Working Environment\r -8Hrs Shift\r -Medical Cover\r -Commissions,Low Pay For The Lower Band Starting Salary Is $600
National Account Manager,4.0,2020-04-23,"Current contractor, more than 1 year",- Very Good Benefits\r - Recognize Hard Work,- Takes Long To Grow\r - Management Needs To Appreciate Their Teams More
Digital Experience Executive,5.0,2021-04-08,Current employee,- Good Perks\r - Better Exposure,- Growth Space Is Minimal
Ip Engineer,3.0,2017-06-18,"Current employee, more than 5 years","- Good Company, Hard Working Employees, Good Teamwork!","No Career Growth, Esp. For Engineers, A Lot Stagnation..."
Contact Center Team Leader,4.0,2021-03-06,"Former employee, more than 8 years",- Employee Empowerment\r - Daycare\r - Fast Pace,- It'S Challenging To Have A Work-Life Balance

In [88]:
# SafRev["Pros"] = SafRev["Pros"].str.replace("\r", "", regex=False)
def remove_char(df, col="Pros", col2="Cons"):
    pattern = r"[\r\*\-\(\)]"
    df[["Pros", "Cons"]] = df[["Pros", "Cons"]].apply(
        lambda s: s.str.replace(pattern, "", regex=True))
    return df
remove_char(SafRev)

,Job Rating,Time,Job Status,Pros,Cons
Job Title,,,,,
Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To LargeScale, Impactful Projects Across Kenya Competitive Salary And PerformanceBased Bonuses",Occasional Tight Deadlines And HighPressure Timelines Bureaucracy Can Delay Project SignOffs
Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...
Network Optimization Engineer,5.0,2021-02-03,Current employee,Very Good Terms Of Employment,Slow Career Growth In Technology
Information Technology,3.0,2021-04-14,Former temporary employee,Efficient In Communication Sector In Kenya,Luring Customers To Buy Their Bundles
Legal Officer,3.0,2021-05-13,"Current employee, more than 5 years","Good Salary, Environment, Benefits, Offices Are Good","Bad Bosses, No Career Advancement"
Telecommunications Engineering Specialist,4.0,2021-06-13,"Current contractor, more than 8 years",Excellent Company To Be In,A Lot Tasks Are In Place
Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya

In [89]:
# 
SafRev["Pros"] = SafRev["Pros"].str.lstrip("-")

In [90]:
SafRev[SafRev["Pros"].str.contains("()")]

/var/folders/6w/_1xx55992tqfg37yz_8bt5v80000gn/T/ipykernel_12600/907015425.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  SafRev[SafRev["Pros"].str.contains("()")]

,Job Rating,Time,Job Status,Pros,Cons
Job Title,,,,,
Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To LargeScale, Impactful Projects Across Kenya Competitive Salary And PerformanceBased Bonuses",Occasional Tight Deadlines And HighPressure Timelines Bureaucracy Can Delay Project SignOffs
Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...
Network Optimization Engineer,5.0,2021-02-03,Current employee,Very Good Terms Of Employment,Slow Career Growth In Technology
Information Technology,3.0,2021-04-14,Former temporary employee,Efficient In Communication Sector In Kenya,Luring Customers To Buy Their Bundles
Legal Officer,3.0,2021-05-13,"Current employee, more than 5 years","Good Salary, Environment, Benefits, Offices Are Good","Bad Bosses, No Career Advancement"
Telecommunications Engineering Specialist,4.0,2021-06-13,"Current contractor, more than 8 years",Excellent Company To Be In,A Lot Tasks Are In Place
Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya

In [91]:
SafRev["Pros"] = SafRev["Pros"].str.strip("\r")

In [92]:
SafRev.insert(6, "Company_Name", "Safaricom")

IndexError: index 6 is out of bounds for axis 0 with size 5

In [93]:
SafRev

,Job Rating,Time,Job Status,Pros,Cons
Job Title,,,,,
Brand Ambassador,5.0,2025-08-08,"Former employee, more than 1 year","Flexible Hours, Supportive Team, Good Training, Fun Work Environment, Opportunity To Travel.","Inconsistent Hours, Limited Career Growth, Commission Structure Can Be Unclear, Standing For Long Hours, Sometimes Slow Communication."
Senior Mobile Developer,4.0,2025-07-28,"Current contractor, more than 1 year",Great For Gaining Experience On Large Scale Enterprise Applications,A Lot Of Shifting Priorities
Project Manager,4.0,2025-07-15,"Former employee, more than 3 years","Strong Support For Professional Growth Through Training Exposure To LargeScale, Impactful Projects Across Kenya Competitive Salary And PerformanceBased Bonuses",Occasional Tight Deadlines And HighPressure Timelines Bureaucracy Can Delay Project SignOffs
Ict Technician,5.0,2025-07-18,Former employee,The Working Experience Was Good,There Are No Major Drawbacks I Can Talk About
Intern,5.0,2025-07-15,"Former intern, less than 1 year",Great Work Environment. Regular Bonuses.,None I Can Think Of
...,...,...,...,...,...
Network Optimization Engineer,5.0,2021-02-03,Current employee,Very Good Terms Of Employment,Slow Career Growth In Technology
Information Technology,3.0,2021-04-14,Former temporary employee,Efficient In Communication Sector In Kenya,Luring Customers To Buy Their Bundles
Legal Officer,3.0,2021-05-13,"Current employee, more than 5 years","Good Salary, Environment, Benefits, Offices Are Good","Bad Bosses, No Career Advancement"
Telecommunications Engineering Specialist,4.0,2021-06-13,"Current contractor, more than 8 years",Excellent Company To Be In,A Lot Tasks Are In Place
Senior Ux Designer,2.0,2022-06-20,Former employee,Good Work Place To Work In Kenya,No Cons Here In Kenya

In [ ]:
Path  = "/Users/briankimanzi/Documents/programmingLanguages/PythonProgramming/ReviewsProject/CleanCompanyRev/Safaricom.csv"

In [ ]:
SafRev.to_csv(Path, index=False)