In [1]:
file.create("Hello.R")

[1] TRUE

In [2]:
print("Hello, World")

[1] "Hello, World"

In [11]:
# getting user input
name <- readline("What's your name: ")
greeting <- paste("Hello, ", name, sep="")
print(paste0(greeting)

What's your name:  paul

[1] "Hello, paul"

In [14]:
# getting user input
name <- readline("What's your name: ")
greeting <- paste0("Hello, ", name) # does not include the sep function
print(greeting)

What's your name:  paul

[1] "Hello, paul"

In [13]:
# getting user input
name <- readline("What's your name: ")
print(paste("Hello, ", name, sep=""))

What's your name:  james

[1] "Hello, james"

In [ ]:
?paste

# COUNT
file.create("filename.extension")

In [4]:
# # file.create("count.R")
# mario <- readline("Enter votes for Mario: ")
# peach <- readline("Enter votes for peach")
# bowser <- readline("Enter votes for Bowser")
# # Type Conversion in R programming language
# mario <- as.integer(mario)
# peach <- as.integer(peach) 
# bowser <- as.integer(bowser)

# total <- mario + peach + bowser

# print(paste("Total votes", total))


# file.create("count.R")
mario <- as.integer(readline("Enter votes for Mario: "))
peach <- as.integer(readline("Enter votes for peach"))
bowser <- as.integer(readline("Enter votes for Bowser"))

total <- sum(mario,peach,bowser)

print(paste("Total votes", total))

Enter votes for Mario:  100
Enter votes for peach 50
Enter votes for Bowser 200

[1] "Total votes 350"

In [ ]:
?as.integer

In [5]:
ls()

[1] "bowser" "mario"  "peach"  "total"

In [6]:
rm(list = ls())

In [13]:
# # reading files in R
# votes <- read.table("votes.csv", 
#                   sep =",", 
#                   header=TRUE)
# View(votes)

# reading files in R
votes <- read.csv("votes.csv")
View(votes)

Warning message in read.table("votes.csv", sep = ",", header = TRUE):
“incomplete final line found by readTableHeader on 'votes.csv'”

  candidate poll mail
1 Mario     37    63
2 Peach     43   107
3 Bowser    84    36

In [14]:
votes[, 3] # display the information of the 3rd column

[1]  63 107  36

In [16]:
# display specific information on a row peach's mail
votes[2,3]

[1] 107

In [17]:
votes$total <- votes$poll + votes$mail

In [20]:
write.csv(votes, "total.csv", row.names=FALSE)

In [21]:
View(read.csv("total.csv"))

  candidate poll mail total
1 Mario     37    63  100
2 Peach     43   107  150
3 Bowser    84    36  120